### ISSUE TITLE
Install the latest/greatest when building the docker image

### ISSUE THREAD

**Issue by cgiroua** [open-horizon/anax#1000]
In the Dockerfile for the anax-in-a-container build, please add an apt upgrade to grab the latest packages, this ensures we have the newest security fixes at build-time.

 So `RUN apt-get update && apt-get upgrade -y && apt-get install ...` to the following line:
https://github.com/open-horizon/anax/blob/master/anax-in-container/Dockerfile.amd64#L10

**Comment by dabooz** [comment]
This was done under another issue in commit 1be9606
