### ISSUE TITLE
Add /etc/default/horizon to list of config files hzn searches

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1002]
See related issue https://github.com/open-horizon/anax/issues/970

Currently `hzn` searches:
1. `horizon/hzn.json`
1. `~/.hzn/hzn.json`
1. `/etc/horizon/hzn.json`

I'd like it to search:
1. `horizon/hzn.json`
1. `~/.hzn/hzn.json`
1. `/etc/default/horizon`
1. `/etc/horizon/hzn.json`

This is because this will tend to keep `hzn` and the horizon agent pointed at the same exchange.

Where does `hzn` asking the running agent for the exchange url fall into the list above?

**Comment by MaxMcAdam** [comment]
Verified in 2.23.10
