### ISSUE TITLE
`hzn exchange business removepolicy` should support input for both businessPolicyName and org/businessPolicyName

### ISSUE THREAD

**Issue by LiilyZhang** [open-horizon/anax#1018]
Remove business policy only support passing in businessPolicyName `hzn exchange business removepolicy <businessPolicyName>` now. We need to change the command so it will also support `hzn exchange business removepolicy <org>/<businessPolicyName>`

**Comment by MaxMcAdam** [comment]
Confirmed in version 2.23.10
