### ISSUE TITLE
'hzn dev service start' builtin properties errors on mac

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1031]
Service still runs, but these errors will be disconcerting to a user:

```
hzn dev service start -S
Service project /Users/bp/examples/edge/services/helloworld/horizon verified.
Service project /Users/bp/examples/edge/services/helloworld/horizon verified.
ERROR: logging before flag.Parse: W0617 15:50:51.658871    2233 builtin_properties.go:35] Failed to get cpu count for the local node. Does not support mac os for getting cpu count.
ERROR: logging before flag.Parse: W0617 15:50:51.658942    2233 builtin_properties.go:41] Failed to get memory info for the local node. Does not support mac os for getting memory info.
Start service: service(s) ibm.helloworld with instance id prefix bdfef5f865f21e4fcea26ee0a05e873b5b5e7a0a8e9259399139ab8c60708ac3
Running service.
```

**Comment by LiilyZhang** [comment]
Verified on 2.23.13 in containter running on mac:

Didn't see builtin properties errors for both cases:

1. test with mqtt service:
![Screen Shot 2019-07-25 at 11.47.19.png](https://images.zenhubusercontent.com/5cab63df6e5dd53fc8a26b5a/8873e878-886e-4a67-82ae-34e935d9bbd8)

2. test with helloworld service:![Screen Shot 2019-07-25 at 11.48.05.png](https://images.zenhubusercontent.com/5cab63df6e5dd53fc8a26b5a/20f9da38-361f-4505-9ac8-42620a567e52)
