### ISSUE TITLE
Run agbot in e2edev as non-root user

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1033]
The agbot in e2edev currently runs as root. It should be able to run as non-root. I did some manual experiments to get it working. The purpose of this issue is to include these changes into e2edev permanently:
1. create a non-root user: adduser agbotuser --disabled-password --gecos "agbot user,1,2,3"
2. in the agbot config file, change "PolicyPath": "/home/agbotuser/policy.d/" - precreate this directory with the right permissions before starting the agbot
3. in the agbot config file, change "APIListen": "0.0.0.0:8082", the port has to be above the root only range
4. change the docker compose config for the agbot container to map agbot port 8082 to external port 81.
5. export HZN_VAR_BASE=/home/agbotuser/.colonus before starting the agbot, precreate this directory
6. start the agbot with an updated log file location: >/home/agbotuser/agbot.log, e.g.
su - agbotuser -c "export HZN_VAR_BASE=/home/agbotuser && /usr/local/bin/anax -v=5 -alsologtostderr=true -config /etc/agbot/agbot.config >/home/agbotuser/agbot.log 2>&1 &"

**Comment by MaxMcAdam** [comment]
Verified
