### ISSUE TITLE
'hzn dev service start' fails when it requires a service with '[0.0.0,INFINITY)'

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1041]
See how the cpu2msghub service requires the cpu and gps services: https://github.com/open-horizon/examples/blob/113cd44738c5b2df9e1a1afcfad4713d3d56303a/edge/msghub/cpu2msghub/horizon/service.definition.json#L11 . It uses a version range of `[0.0.0,INFINITY)`. This results in the exchange api call at the bottom of this output:
```
Bruces-MacBook-Pro cpu2msghub$ hzn dev service start -Sv
[verbose] Reading configuration file: /usr/local/etc/horizon/hzn.json
[verbose] Config file does not exist: /Users/bp/.hzn/hzn.json.
[verbose] Reading configuration file: /Users/bp/examples/edge/msghub/cpu2msghub/horizon/hzn.json
[verbose] Reading Horizon metadata from /Users/bp/examples/edge/msghub/cpu2msghub/horizon
[verbose] Reading Horizon metadata from /Users/bp/examples/edge/msghub/cpu2msghub/horizon
[verbose] The exchange url: https://major-peacock-icp-cluster.edge-fabric.com/ie-exchange/v1
[verbose] GET https://major-peacock-icp-cluster.edge-fabric.com/ie-exchange/v1/orgs/IBM/services?url=ibm.cpu&version=[0.0.0,INFINITY)&arch=amd64
[verbose] HTTP code: 404
Error: bad HTTP code 404 from GET https://major-peacock-icp-cluster.edge-fabric.com/ie-exchange/v1/orgs/IBM/services?url=ibm.cpu&version=[0.0.0,INFINITY)&arch=amd64, output: {"services":{},"lastIndex":0}
```

Which doesn't find any services, because that api (and most exchange api's) doesn't support a range being passed in. Eventually the exchange should support ranges, but for now can you handle it at the `hzn` level by:  omit the version (all the time, because it is always a range even if it looks like 1.2.3) and filter the results to find the highest version that satisfies the range.

**Comment by MaxMcAdam** [comment]
Verified in version 2.23.10
