### ISSUE TITLE
hzn exchange service listpolicy shows unicode characters in output

### ISSUE THREAD

**Issue by LiilyZhang** [open-horizon/anax#1075]
`hzn exchange service listpolicy` shows unicode inside "Constraints" section, need to fix that. This issue is similar to issue #982. This is found in icp-staging, hzn version: `2.23.11`
Current: 
![Screen Shot 2019-06-26 at 14.29.28.png](https://images.zenhubusercontent.com/5cab63df6e5dd53fc8a26b5a/7dc1ce7c-05ec-4937-9371-a06813d2fd1e)
where constrains looks like:
```
"constraints": [
    "icp == true AND temperature \u003e 70"
  ]
```

Should be:
```
"constraints": [
    "icp == true AND temperature > 70"
  ]
```

**Comment by jiportilla** [comment]
FYI , tested similar function in business policy and it works as intended

"constraints": [
      "openhorizon.arch == amd64",
      "say-hello == true",
      "icp == true AND temperature > 70"
    ],

**Comment by MaxMcAdam** [comment]
Verified in version 2.23.13
