### ISSUE TITLE
`hzn exchange node` cli should verify the user input before saving it

### ISSUE THREAD

**Issue by LiilyZhang** [open-horizon/anax#1081]
`hzn exchange node update` command should should verify the user input if has user input in the given json. Validation include:
- [x] should verify that the service exists 
- [x] the variables are defined in the service (only check the highest version), Otherwise, return a warning message, eg: `variable1 is not defined in service <service1>`
- [x] the values have correct type (check against highest version of that service. Return error if type is not correct)

when a node is using policy
- [x] the input json must set values for non-default variables in the referenced service definition. We don't know which business policy will be used to deploy the service to this node.
- [x] it is ok to set an empty userinput for a service if that service has no non-default variables.

when node has a pattern associated with it, also check service given in userinput.json is one of the: 
- [x] the service defined in top level services 
- [x] dependent services (recursively check) defined in the pattern (service defined in pattern will have the same required services for all versions, so you can only grab the first version and check its dependent service)
  - when check dependent service, it considered false if versionRange of the dependent service doesn't have intersection with versionRange of service from user input
- [x] otherwise return an error because the service referenced in the input is not part of the pattern.
- [x] it is ok to set an empty userinput for a service if that service's non-default variables are set in the pattern.

when node has a pattern associated with it, for all services (from top to down) defined in that pattern
- [x] the userinputs need to be set in given userinput.json if no default value given in service userinput or no value is set in the service's userinput of the pattern definition.

This issue is related to #1074. Check PR for 1074 if needed

**Comment by linggao** [comment]
Testing:
When I input wrong version, wrong name, wrong type for the value, the code did not catch it.
