### ISSUE TITLE
hzn exchange service publish -P should work with no docker creds

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1084]
`hzn exchange service publish` has the `-P` flag to pull the docker image instead of pushing it, which is used (among other times) in the script that primes a customer's ICP exchange with the samples. But because of the auth check in `cli/cliutils/cliutils.go GetDockerAuth()` it doesn't work unless you've run `docker login`. But `docker pull` from hub.docker.com doesn't require a login, so neither should `hzn` in this case.

I included troy as an assignee so he can test it when the fix is ready.

**Comment by t-fine** [comment]
In testing using my `exchangeServicePublish.sh` script; issue #1084 correctly addressed pulling the issue instead of pushing it, and issue #1085 eliminated the needs for docker creds (I deleted my docker config file to test and Carl tested when publishing the samples to a fresh ICP instance).
