### ISSUE TITLE
Agent incorrectly logs duplicate proposal as an error

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1097]
In producer_protocol_handler, the HandleProposal method writes an error log entry if it detects a duplicate proposal message. Duplicate proposal messages are normal part of retry logic and are not errors. This event log entry could either be NOT written in this case (since the event is logged in the agent's syslog) or the event could be changed to a warning.

**Comment by jiportilla** [comment]
With: `make test "NOLOOP=1 TEST_PATTERNS=sall MULTIAGBOT=1"`

Only related log entries I found included:

/tmp/agbot.log

I1021 17:32:28.359108    1499 consumer_protocol_handler.go:137] Base Consumer Protocol Handler (Basic) sending exchange message to: userdev/an12345, message {"type":"basicagreementverificationreply","protocol":"Basic","version":1,"agreementId":"433e8999a0be5c7b77f26ae2924fb6ce5d7708caa16278dab66bbdfa43db97a6","exists":true}

...

I1021 17:41:23.697573    1499 consumer_protocol_handler.go:137] Base Consumer Protocol Handler (Basic) sending exchange message to: e2edev@somecomp.com/an12345, message {"type":"basicagreementverificationreply","protocol":"Basic","version":1,"agreementId":"424f5e63e3cd86cd6691fee51df637c25c5d56a60791a0bbf788d63cb6ccba40","exists":true}
I1021 17:43:09.781948    1499 consumer_protocol_handler.go:137] Base Consumer Protocol Handler (Basic) sending exchange message to: e2edev@somecomp.com/an12345, message {"type":"basicagreementverificationreply","protocol":"Basic","version":1,"agreementId":"c7d342aa53cfe3fd99c146398bc8530db91dde0138d7c2d9b78346bcea929003","exists":true}

**Comment by jiportilla** [comment]
https://github.com/open-horizon/anax/pull/1287

tested with: make test TEST_VARS="NOLOOP=1 MULTIAGBOT=1"
