### ISSUE TITLE
CLI messages globalized

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1106]
We are not globalizing syslog messages, only the messages that come from the CLI. If we can contain globalization of CLI verbose messages, we will do that. Finally, if we still have time, we can do the human readable part of the event log messages.

- [x] Globalize CLI messages
- [x] Globalize Verbose CLI messages
- [x] Globalize the event log records (stretch)
- [x] Display timestamps with local format (use UTC for now)
- [x] Package the files for translation
- [x] hzn pass language tag to the exchange
- [x] Ship man pages for different locales (issue 1150)
- [x] Un-package the translated files when they come back
- [ ] Test

**Comment by jiportilla** [comment]
There are some man pages, follow up with Bruce

**Comment by jiportilla** [comment]
to reach out to contact in Translation team for advice
