### ISSUE TITLE
Surface Agent discovered errors to the exchange

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1109]
Error events are already captured in the agent's local DB (i.e. the event log). Publish a subset of those event objects to the exchange (new exchange API resource under the node) on a periodic basis. The event publisher on anax needs to be smart enough to analyze the event log and only publish "current" errors. That is, not simply dump every error that ever occurred. Some errors are resolved by cancelling an agreement. Agreement cancellation loops should be detected and only the newest is surfaced.
The complexity of this WILL get out of hand. We will choose 2-5 errors to surface in order to control the complexity. Concentrate on service start/deployment errors that could result from an incorrect user action (e.g. requesting a file binding where the file/directory is root protected).

The design is dependent on a new exchange API for an errors resource underneath /nodes/<id> to hold the surfaced errors. The API may not need to support PATCH. The resource is a list of errors, the actual json objects are a black box from the exchange API's perspective.

Until the exchange API is ready, the implementation can write log messages to indicate what it would have PUT to the exchange.

- [x] Write an implementation design, choosing which errors to surface and how to detect duplicate errors.
- [x] Implement the design
- [x] Add automated e2edev testcase

**Comment by MaxMcAdam** [comment]
Design for this feature: https://ibm.ent.box.com/notes/504074261377
