### ISSUE TITLE
Allow properties to be set on nodes even when policy is not in use.

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1111]
- [x] Enable CLI and anax API for setting properties even if the node is configured to use a pattern.

**Comment by jiportilla** [comment]
pushed to 19

**Comment by jiportilla** [comment]
Two steps today, first register with a Pattern , then add properties with a node policy. New properties saved on the exchange node:

hzn exchange node listpolicy bldbzt1047.bld.dst.ibm.com

{
  "properties": [
    {
      "name": "say-hello",
      "value": true
    },
    {
      "name": "site",
      "value": "Boulder"
    },
    {
      "name": "type",
      "value": "vm"
    },
    {
      "name": "model-number",
      "value": 100
    },
    {
      "name": "openhorizon.cpu",
      "value": 1
    },
    {
      "name": "openhorizon.arch",
      "value": "amd64"
    },
    {
      "name": "openhorizon.memory",
      "value": 1993
    }
  ],
  "constraints": [
    ""
  ]
}

**Comment by linggao** [comment]
Also fixed a problem that panic in agreement verification after the agreement is canceled.

**Comment by MaxMcAdam** [comment]
Verified in 2.23.18
