### ISSUE TITLE
Address various user experience issues

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1112]
The UX reviews identified a small number of UX items for the CLI to resolve. These items are not documented as openhorizon issues, so they will have to be tracked down.

- [x] Find and discover which UX issues we should address
- [x] Implement solutions

**Comment by jiportilla** [comment]
Here are the minutes of the Design Review meeting with each corresponding issue created on zenhub, I will go through the list and see which ones are related to the CLI - - https://ibm.box.com/s/h7zbzvh0pd5j49f00rb1xruzfvcgklp3

**Comment by jiportilla** [comment]
https://github.ibm.com/Edge-Fabric/UX/issues/91  & maybe this - https://github.ibm.com/Edge-Fabric/UX/issues/71 (so far, still reviewing other UI feedback items)

**Comment by jiportilla** [comment]
here are some transactions that could take longer to complete and may need a status/progress bar or a more detailed status message:

1. For the Registration task:

Node registration with a pattern
hzn register -p major-peacock-icp-cluster/pattern-ibm.helloworld -v

1.1
Talking to the exchange:
Node major-peacock-icp-cluster/2a11fb278229740e0707f3632b550e730e507cfe does not exist in the exchange with the specified token, creating/updating it...

1.2
Initializing the Horizon node...

1.3
Changing Horizon state to configured to register this node with Horizon...




2. Unregistration

2.1
Unregistering this node, cancelling all agreements, stopping all workloads, and restarting Horizon...

2.2
Checking the node configuration state...

**Comment by jiportilla** [comment]
Recommend adding MSG to these commands:

https://ibm.box.com/s/n5ec7rwvmmqtjywzr24pvermp4099vki

**Comment by jiportilla** [comment]
After 13 attempts to fix locales/es issues, Travis build completed successfully.

Verifying agreements: agreements still present
Sleeping for 30s giving agreements time to fail before checking again
Verifying agreements: agreements still present
Node unconfig setting is 
Unconfig loop tests are disabled.
All tests SUCCESSFUL
make: Leaving directory `/home/travis/gopath/src/github.com/open-horizon/anax/test'
The command "if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then make test -C test TEST_VARS="NOLOOP=1 TEST_PATTERNS=sall APPSTORE=1"; else make test -C test TEST_VARS="NOLOOP=1 TEST_PATTERNS=sall" && make test -C test TEST_VARS="NOLOOP=1"; fi" exited with 0.
Done. Your build exited with 0.

**Comment by jiportilla** [comment]
Made changes as requested.

**Comment by jiportilla** [comment]
Verifying agreements: agreements still present
Sleeping for 30s giving agreements time to fail before checking again
Verifying agreements: agreements still present
Node unconfig setting is 
Unconfig loop tests are disabled.
All tests SUCCESSFUL
make: Leaving directory `/home/travis/gopath/src/github.com/open-horizon/anax/test'
The command "if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then make test -C test TEST_VARS="NOLOOP=1 TEST_PATTERNS=sall APPSTORE=1"; else make test -C test TEST_VARS="NOLOOP=1 TEST_PATTERNS=sall" && make test -C test TEST_VARS="NOLOOP=1"; fi" exited with 0.
