### ISSUE TITLE
Enhance hzn mms to allow object list to provide filters

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1115]
The hzn mms object list command can only filter returned objects based on object type. The filters would be in the form of a command line switch that specified:
a) one or more of the non-policy object metadata fields, destination (type, id, destination list) is at the top of the list.
b) one or more properties (and value) from the destination policy

- [x] Write a design
- [x] Implement design
   - [x] sync service
   - [x] anax hzn cli
- [x] Create automated e2edev testcase

**Comment by LiilyZhang** [comment]
Initial design: https://ibm.ent.box.com/notes/502324078697

**Comment by jiportilla** [comment]
Upcoming leave of absence
