### ISSUE TITLE
Need to sync node policy and userinput before accepting local changes

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1136]
registration right after unregistration resulted in the following error sometimes. 
````
Setting service variables...
Error: bad HTTP code 500 from POST http://localhost/service/config: Failed to add the user input to node. Cannot accept this node user input because the local node user input is out of sync with the exchange copy. Please wait a minute and try again.
````
This is because the local node syncs with the exchange policy and userinput every 15 seconds. When it it out of sync, it will not allow any modification from local api.

We need to force a sync before accepting changes and remove this error.

**Comment by MaxMcAdam** [comment]
Verified in 2.23.18
