### ISSUE TITLE
Agbot needs to monitor its public msg key in the exchange

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1146]
There is a corner case possible where a malicious admin could delete the agbot's object in the exchange, and re-add the object without the messageing key (or just wipe out the public messaging key), leaving the agbot container(s) unable to interact with any agents. As long as the agbot's config remains unchanged, it is possible for the agbot to detect that it's message key is missing by periodically checking its own object in the exchange. If the key goes missing, the agbot should restart itself. During the restart, if the config was also damaged, the agbot will not come back up. I think this is the behavior we want.

**Comment by MaxMcAdam** [comment]
Verified in e2edev
