### ISSUE TITLE
Error messages need to help the user fix the problem.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#1167]
When attempting to register a pattern, the command failed with the error message shown below.

```
hzn register -n $EXCHANGE_NODEAUTH $HZN_ORG_ID $PATTERN -f input.json
Reading input file input.json...
Warning: cli is configured with exchange url https://alpha.edge-fabric.com/v1, and the agent is configured with exchange url https://alpha.edge-fabric.com/v1/. This may cause enexpected behavior. Please update /etc/default/horizon and run 'service horizon restart'.
Node joe.pearson@us.ibm.com/joe-blue-rpi exists in the exchange
Initializing the Horizon node...
Setting service variables...
Error: {"error":"Unable to find the service definition using  joe.pearson@us.ibm.com/pattern [0.0.0,INFINITY) arm in the exchange.","input":"service"}
```

Can you guess where the error is located, only from reading that message?

Well, it turns out that Joe had an error in the `url` field in his `input.json` file. The error message given by horizon was unhelpful in figuring this out. Could you please change the error message to direct the user straight to the location of the problem? Specifically, it should say *where* there error is located. We first thought it was a pattern definition problem, then a service definition problem, and only much later did we discover the problem's location in the userinput.json file. Since horizon is reading this file when it discovers the error, that should be made clear in the output. I think the existing heading, "setting service variables" is supposed to hint that but it is completely ineffective. Perhaps it is the message 6 lines above the error that says "Reading input file input.json..." that is supposed to hint that the much later error message is related to this. These existing messages are just noise when things are working, and they are unhelpful when things go wrong. Instead of those ineffective messages, please state, "ERROR in <filenametheusersupplied>". Immediately after this error-in-file-X message, please also clarify that the `url` and/or `versionRange` field for entry #N in the `services` array refers to a service not present in the agreement.

Given messaging like what I am suggesting here, the user has a good chance of figuring out this error for themselves, instead of having to call the support line for help, which will save time and money.

**Comment by jiportilla** [comment]
tested latest changes, Ok to close ticket

Error: Error setting service variables from user input file: {"error":"Unable to find the service definition using  major-peacock-icp-cluster/bad-ivanp.ibm.helloworld [0.0.0,INFINITY) amd64 in the exchange.","input":"service"}

**Comment by MaxMcAdam** [comment]
Verified in 2.23.18
