### ISSUE TITLE
Agent never receives proposal from AgBot

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#1171]
After a relatively slow series of registering and unregistering my RPi on Alpha (while I was doing horizon service development) with everything working well, for no reason that I can see (just up-arrow then enter in a terminal window) one **successful** registration failed to form an agreement. The AgBot(s) seem to be ignoring the RPi's offer.

After more than a full day of waiting, the status on this node remains the same. It is "configured" but no AgBot has ever reached out to the node (as shown in the logs below, which are unchanged after a day of waiting). I believe this indicates a lack of synchronization between the Agent on my node and the AgBot(s) responsible for the pattern. Unfortunately I have no access to information about the AgBot state to add here. Note also that only this one registration is wedged. During this day, many other registrations have been done and the AgBots have behaved appropriately, so they are still functioning, but with respect to the agent on my node alone there is a problem.

Gayatri also reported in the user channel that she has seen this problem as well.

Details below...

```
pi@raspberrypi:~/yolo2msghub $ hzn node list
{
  "id": "00000000fbaf975a",
  "organization": "joe.pearson@us.ibm.com",
  "pattern": "joe.pearson@us.ibm.com/pattern-yolo2msghub",
  "name": "00000000fbaf975a",
  "token_last_valid_time": "2019-08-25 17:10:00 +0100 BST",
  "token_valid": true,
  "ha": false,
  "configstate": {
    "state": "configured",
    "last_update_time": "2019-08-25 17:10:07 +0100 BST"
  },
  "configuration": {
    "exchange_api": "https://alpha.edge-fabric.com/v1/",
    "exchange_version": "1.100.0",
    "required_minimum_exchange_version": "1.98.0",
    "preferred_exchange_version": "1.98.0",
    "mms_api": "https://alpha.edge-fabric.com/css",
    "architecture": "arm",
    "horizon_version": "2.23.13"
  },
  "connectivity": {
    "firmware.bluehorizon.network": true,
    "images.bluehorizon.network": true
  }
}
pi@raspberrypi:~/yolo2msghub $ hzn agreement list
[]
pi@raspberrypi:~/yolo2msghub $ hzn agreement list -r | grep terminated_description | egrep -v 'node was unconfigured|agreement bot policy changed'
pi@raspberrypi:~/yolo2msghub $ hzn eventlog list
[
  "2019-08-25 17:09:59:   Start node configuration/registration for node 00000000fbaf975a.",
  "2019-08-25 17:10:00:   Start service configuration with user input for joe.pearson@us.ibm.com/joe.yolo2msghub.",
  "2019-08-25 17:10:03:   Complete service configuration for joe.pearson@us.ibm.com/joe.yolo2msghub.",
  "2019-08-25 17:10:04:   Start policy advertising with the exchange for service joe.pearson@us.ibm.com/joe.yolo2msghub.",
  "2019-08-25 17:10:04:   Complete policy advertising with the exchange for service joe.pearson@us.ibm.com/joe.yolo2msghub.",
  "2019-08-25 17:10:06:   Start service auto configuration for joe.pearson@us.ibm.com/joe.yolo.",
  "2019-08-25 17:10:06:   Complete service auto configuration for joe.pearson@us.ibm.com/joe.yolo.",
  "2019-08-25 17:10:06:   Start service auto configuration for joe.pearson@us.ibm.com/joe.hal.",
  "2019-08-25 17:10:06:   Complete service auto configuration for joe.pearson@us.ibm.com/joe.hal.",
  "2019-08-25 17:10:06:   Start service auto configuration for joe.pearson@us.ibm.com/joe.wan.",
  "2019-08-25 17:10:07:   Complete service auto configuration for joe.pearson@us.ibm.com/joe.wan.",
  "2019-08-25 17:10:07:   Start service auto configuration for joe.pearson@us.ibm.com/joe.cpu.",
  "2019-08-25 17:10:07:   Complete service auto configuration for joe.pearson@us.ibm.com/joe.cpu.",
  "2019-08-25 17:10:07:   Start service auto configuration for joe.pearson@us.ibm.com/joe.yolo2msghub.",
  "2019-08-25 17:10:07:   Complete service auto configuration for joe.pearson@us.ibm.com/joe.yolo2msghub.",
  "2019-08-25 17:10:07:   Complete node configuration/registration for node 00000000fbaf975a.",
  "2019-08-25 17:10:07:   Start policy advertising with the exchange for service joe.pearson@us.ibm.com/joe.yolo.",
  "2019-08-25 17:10:08:   Complete policy advertising with the exchange for service joe.pearson@us.ibm.com/joe.yolo.",
  "2019-08-25 17:10:08:   Start policy advertising with the exchange for service joe.pearson@us.ibm.com/joe.hal.",
  "2019-08-25 17:10:08:   Complete policy advertising with the exchange for service joe.pearson@us.ibm.com/joe.hal.",
  "2019-08-25 17:10:09:   Start policy advertising with the exchange for service joe.pearson@us.ibm.com/joe.wan.",
  "2019-08-25 17:10:09:   Complete policy advertising with the exchange for service joe.pearson@us.ibm.com/joe.wan.",
  "2019-08-25 17:10:09:   Start policy advertising with the exchange for service joe.pearson@us.ibm.com/joe.cpu.",
  "2019-08-25 17:10:10:   Complete policy advertising with the exchange for service joe.pearson@us.ibm.com/joe.cpu."
]
pi@raspberrypi:~/yolo2msghub $ date
Sun 25 Aug 17:23:02 BST 2019
pi@raspberrypi:~/yolo2msghub $ 
```

**Comment by dabooz** [comment]
Glen, I need the agent's syslog to debug this problem. Do you have it? It's good practice to always grab the log just in case we need it.

**Comment by TheMosquito** [comment]
David (@dabooz), well, that's unfortunate. You just missed it (logrotate has wiped away the syslog from Aug 26 and before).

**Comment by TheMosquito** [comment]
@dabooz can you not debug this from the Exchange anbd AgBot logs? I mean, the AgBot failed for more than a day to notice this Agent in the Exchange. There should be some record of this in the Exchange and the AgBots.

**Comment by TheMosquito** [comment]
This same error happened again for me. Here is the syslog from this node...
[syslog.txt](https://github.com/open-horizon/anax/files/3592098/syslog.txt)

**Comment by TheMosquito** [comment]
Note that I was registering a simple helloworld pattern example this time, and that I had previously registered this exact pattern and exact input file 3 times previously and it worked. Then this 4th time, nothing happened after a successful registration (no errors). I have been waiting over 20 minutes so far and no agbot has reached out to the local agent at all.

**Comment by dabooz** [comment]
The Agbots are actually sending proposals, but the agent is unable to decrypt the proposal msg. Still investigating.

**Comment by dabooz** [comment]
There was a bug in the exchange PATCH API for patching the userinput config to the node resource, which accidentally removed the node's public key from the exchange. We could add support to monitor this key from the agent side and make sure it is always there.

**Comment by bmpotter** [comment]
The exchange bug referred to above is https://github.com/open-horizon/exchange-api/issues/213 and will be fixed by sadiyah soon.

If you do monitor the key from the agent, i assume you can do it w/o adding another repetitive exchange api call?

**Comment by dabooz** [comment]
@bmpotter  We would need a repetitive poller, OR this kind of change would need to be included in the list of node changes that we are told about within the exchange notification framework.

**Comment by TheMosquito** [comment]
This bug has occurred again:

**Comment by TheMosquito** [comment]
[syslog.rpi.zip](https://github.com/open-horizon/anax/files/3781470/syslog.rpi.zip)

**Comment by linggao** [comment]
@TheMosquito A lot of changes has made to the agbot for 4.1 release. Please retest.

**Comment by TheMosquito** [comment]
@linggao This was an intermittent issue, not easily testable. I don't think I can repeat it. Various experts have weighed-in above so it seems the issue is well understood by your colleagues. I think they will have to help you here. If not, I recommend just closing it. It's almost a year old anyway.
