### ISSUE TITLE
Errors in constraint expression token parsing, and related problems.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#1172]
The current constraint expression parsing mechanism has weaknesses, both in terms of what property relationships can be expressed, and in terms of simple syntax (even unexpected whitespace usage issues can cause parsing errors).

I believe the current parsing mechanism is implemented by the code in here:
https://github.com/open-horizon/anax/blob/master/externalpolicy/constraint_expression.go

When we have time, we should restructure this part of open-horizon to support a much more robust and much more expressive constraint expression mechanism.

The following considerations should be part of that restructuring:
1. define a constraint expression language (so users can understand the syntax). typically expression languages are defined in EBNF
2. instead of parsing by whitespace, use a tokenizer (e.g., the equivalent of lex or flex). Since the current code is written in Go, you might consider using the excellent tokenizer built into Go (see "go/token")
3. use the language definition to do the parsing, instead of a complex set of loops and if statements (e.g., by using the equivalent of yacc or bison). Since the current code is written in Go, you might consider using the excellent parser built into Go (see "go/parser")
4. arrays of expression components are a very limiting way to store an expression in the code, and this has restricted the types of expressions the current code can represent. Expressions inherently form tree structures, with nodes that may have any number of children, enabling unary, binary or other types of operators. Normally expressions are stored in an Abstract Syntax Tree (AST) data structure. If you use the Go language parser, it will construct an AST for you. Note that by using an AST you can have any set of precedence order you wish and you can easily support bracketing to force precedence changes too.

**Comment by dabooz** [comment]
item 1 (in doc),2 and 3 have been addressed. I dont think item 4 is important given there is now support for parenthetical expressions.
