### ISSUE TITLE
Penetration test finding - Cache-control not set in HTTP response headers 

### ISSUE THREAD

**Issue by ctiijima** [open-horizon/anax#1174]
The following is from the penetration test team:

**Description**
Unless directed otherwise, browsers may store a local cached copy of content received from web servers. Some browsers, including Internet Explorer, cache content accessed via HTTPS. If sensitive information in application responses is stored in the local cache, then this may be retrieved by other users who have access to the same system at a future time.

Affected URL/API(s)
https://<host>:8443/ec-exchange/v1 
https://<host>:8443/ec-css/ 
https://<host>:8443/edge

**Request/Response**
Request:
GET /ec-exchange/v1/orgs/<host>/users HTTP/1.1
Authorization: Basic cm9vdC9yb290OkpISmk4ZlkzQ1RUcGh4MlluQjNLUW0zZWFERDJibw== User-Agent: PostmanRuntime/7.15.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 36bf3250-99a4-4c28-9c18-0f096991d4d2
Host: 9.30.147.239:8443
Accept-Encoding: gzip, deflate
Connection: close
Origin: https://attacker.com

Response:
 **_HTTP/1.1 200 OK
 Date: Tue, 23 Jul 2019 09:43:50 GMT
 Content-Type: application/json;charset=utf-8
 Connection: close
 Access-Control-Allow-Origin: https://attacker.com
 Access-Control-Allow-Credentials: true
 Access-Control-Max-Age: 1800
 Access-Control-Allow-Methods: GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH
 X-Frame-Options: SAMEORIGIN
 X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Length: 1137_**
{"users":{"<host>/admin1":{"password":"$2a$10$g1pJ938cdcTdX01vmbrYn.lmqCvWpeTcIOa2.TTna5sXWCo0H 1uQy","admin":true,"email":"<redacted>","lastUpdated":"2019-07- 23T09:43:24.294Z[UTC]","updatedBy":"root/root"},"<host>/user2":{"password":"","admin":false,"email":"user2","lastUpdated":"2019-07- 18T13:21:34.798Z[UTC]","updatedBy":"<host>/user2"},"<host>/clusteradmin1":{"password":"","admin":false,"email":"clusteradmin1","lastUpdated":"2019- 07-18T05:34:09.709Z[UTC]","updatedBy":"<host>/clusteradmin1"},"<host>/admin":{"password":"","admin":false,"email":"admin","lastUpdated":"2019-07- 18T00:53:52.322Z[UTC]","updatedBy":"<host>/admin"},"<host>/user1":{"password":"","admin":false,"email":"user1","lastUpdated":"2019-07- 18T01:17:17.733Z[UTC]","updatedBy":"<host>/user1"},"<host>/testuser1":{"password":"$2a$10$bB1vSbfm1nDMf.hs4K7ygeoM9FqMMGYmXdxCxfWg45BdS odXhnQ3.","admin":true,"email":"<redacted>","lastUpdated":"2019-07- 22T11:07:41.787Z[UTC]","updatedBy":"root/root"}},"lastIndex":0}

**Risk Assessment**
Sensitive information can be retrieved at a later point from the cached information.

**Fix Recommendation**
Applications should return caching directives instructing browsers not to store local copies of any sensitive data. Often, this can be achieved by configuring the web server to prevent caching for relevant paths within the web root. Alternatively, most web development platforms allow you to control the server's caching directives from within individual scripts. Ideally, the web server should return the following HTTP headers in all responses containing sensitive content:
1-Cache-control: no-store 2-Pragma: no-cache

**Comment by bmpotter** [comment]
Opened https://github.com/open-horizon/exchange-api/issues/203 for the exchange's part of this, so removing sadiyah from this issue.
