### ISSUE TITLE
Horizon "deployment string" should support the equivalent of `docker run --entrypoint ...`

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#1195]
In general Horizon "deployment strings" should support all of the features of the `docker run` unless there is a very good reason not to do so.

When a Dockerfile uses an `ENTRYPOINT` statement, `docker run` allows you to overwrite that with the `--entrypoint` CLI argument. Horizon does not support this docker feature so the customer will have to make a custom Dockerfile to build their image manually modifying the ENTRYPOINT in the Dockerfile.

We encountered this issue working with EdgeX where they have chosen to use ENTRYPOINT statements, and we need to override one of the items in their ENTRYPOINT, but currently in Horizon we only support *appending* to an ENTRYPOINT (while supporting replacing the entire CMD entry). I believe they cannot switch to using CMD because they want their containers to also be independently usable as CLI commands as well.

**Comment by sirotsinskuy** [comment]
Working on it. @joewxboy please assign this issue to me
