### ISSUE TITLE
'hzn exchange business *' does not send root creds correctly

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1199]
The `hzn exchange business` sub-cmds are not sending root creds correctly to the exchange. I think the issue is that with non-root creds, the user usually doesn’t prepend the org to the user:pw (altho this is supposed to be supported). With the root creds, the user must prepend the org, because the root user is actually in the root org. So the user specifies it like `root/root:<pw>`. But the `hzn exchange business` cmds appear to pass it to the exchange as `<myorg>/root:<pw>`, which results in an invalid-credentials response from the exchange.

It’s not really just about root, i.e. we don’t need a special case for that. Any user creds passed to `hzn exchange` via the `-u` flag or `HZN_EXCHANGE_USER_AUTH` can optionally have the org prepended. `hzn exchange` should only prepend the org from `-o` or `HZN_ORG_ID` if the creds don't already have an org.

Also, it would be good to an e2edev test for each `hzn exchange` sub-cmd using root creds.

**Comment by MaxMcAdam** [comment]
Verified
