### ISSUE TITLE
DELETED: configureRaw value not written to to launch context when agreement is formed

### ISSUE THREAD

**Issue by michaeldye** [open-horizon/anax#120]
The launchcontext has both a structured configure message member and an unstructured one. The unstructured one is used to write the raw configure description inside the workload so it can read facts about how it was set up. It also is used to build iptables network isolation rules.

It looks like we're not writing the raw config to the launchcontext so these container features won't work (the written config file is 0-length and no one is using the network isolation feature so we're not encountering errors there).

We either need to write the configuration facts to the launch context as a byte array or rework the container code to use the structure configuration data.

**Comment by dabooz** [comment]
Is the byte array form of the configure message just a json serialized form of the structured configure message?

**Comment by dabooz** [comment]
Mike answered the question out of band. The raw byte array (before v2) contained more than the serialized form of the configure message. His recollection is that it included some info on how to setup iptable isolation rules, but a quick investigation by him did not yield a quick solution so he opened the issue to remember this problem. There is no urgent need to fix this right now.
