### ISSUE TITLE
Default option gives error for Y/N questions in hzn

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1233]
````
 hzn unregister -v
Are you sure you want to unregister this Horizon node? [y/N]:
Error: Error scanning input, error unexpected newline
````
That's with default (enter) answer.

This happens for all the hzn commands that requires Y/N answers from the user.

**Comment by jiportilla** [comment]
https://github.com/open-horizon/anax/pull/1277

**Comment by jiportilla** [comment]
hzn reg test: Done
Node unconfig setting is 
Unconfig loop tests are disabled.
All tests SUCCESSFUL
make: Leaving directory '/home/travis/gopath/src/github.com/open-horizon/anax/test'
make: Entering directory '/home/travis/gopath/src/github.com/open-horizon/anax/test'
Starting cleanup
Shutdown anax cleanly
