### ISSUE TITLE
[TVT] Translation is missing for "code" in hzn version

### ISSUE THREAD

**Issue by fionalin** [open-horizon/anax#1241]
Step to reproduce:

Open Edge node console
Input the following command, and replace your language with it:
export LANG=it
Input the following command.
hzn version -v
You can find "code" is displayed in English in the panel as the screen shot shows.

![0b474c80-d4b2-11e9-8bc0-8ed39a0b2082](https://user-images.githubusercontent.com/8230523/64899757-8f225400-d6bf-11e9-9755-5b32a19161f1.png)

**Comment by linggao** [comment]
I have put it in the PII file hzn.gotext.json. It will get into the build in next cycle.

**Comment by jiportilla** [comment]
it works in Spanish 

HZN_LANG=ES hzn version -v
[verbose] Leyendo el archivo de configuración: /etc/horizon/hzn.json
[verbose] Leyendo el archivo de configuración: /etc/default/horizon
[verbose] El archivo de configuración no existe: /home/pi/.hzn/hzn.json.
[verbose] Leyendo el archivo de configuración: /home/pi/open-horizon/examples/edge/services/holaworld/horizon/hzn.json
Versión de línea de mandatos de Horizon: 2.23.26
[verbose] GET http://localhost/status
[verbose] Código HTTP: 200
Versión de agente de Horizon: 2.23.26
