### ISSUE TITLE
False termination reason "workload terminated"

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#125]
Sometimes the anax wrongly reported that the agreement termination reason was  "workload terminated", but in fact the agreement was terminated by user.

**Comment by linggao** [comment]
This is due to the  GovernanceMaintenanceMessage thread periodically check the workloads for active agreements, it deletes those whose workloads failed.  Sometimes this threads reads the agreement info from the persistence storage just before the user cancellation info was written to the persistence storage.

**Comment by linggao** [comment]
PR: https://github.com/open-horizon/anax/pull/126

**Comment by bmpotter** [comment]
in 73/74 snap build
