### ISSUE TITLE
Use same JSON syntax for same purposes in multiple places.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#1259]
There is a significant difference in configuration variable value specifications in userinput.json files, which look like this:
```
    {
      "org": "IBM",
      "url": "ibm.helloworld",
      "versionRange": "[0.0.0,INFINITY)",
      "variables": {
        "HW_WHO": "Pattern Customer"
      }
    }
```
while in other places, like the business policy definition, we use:
```
  {
    "serviceOrgid": "IBM",
    "serviceUrl": "ibm.helloworld",
    "serviceVersionRange": "[0.0.0,INFINITY)",
    "inputs": [
      {
        "name": "HW_WHO", "value": "Policy Customer"
      }
    ]
  }
```
These different syntaxes represent exactly the same thing, but every single field is named differently between them. These differences seem unnecessary and they are very confusing for users (like me). Ideally we would always use the same JSON syntax for the same function in all parts of Horizon, and ideally the same source code module would be used in these different components to parse this same syntax block of JSON.

**Comment by dabooz** [comment]
Will address with: https://github.com/open-horizon/anax/issues/1272
