### ISSUE TITLE
'hzn exchange version' requires user creds, when the call to exchange doesn't require it

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1271]
```
ic-stg Documents $ unset HZN_EXCHANGE_USER_AUTH
ic-stg Documents $ hzn exchange version 
Error: exchange user authentication must be specified with either the -u flag or HZN_EXCHANGE_USER_AUTH
ic-stg Documents $ export HZN_EXCHANGE_USER_AUTH=foo:bar
ic-stg Documents $ hzn exchange version 
1.116.0
```

**Comment by jiportilla** [comment]
https://github.com/open-horizon/anax/pull/1279

**Comment by jiportilla** [comment]
All tests SUCCESSFUL
make: Leaving directory '/home/travis/gopath/src/github.com/open-horizon/anax/test'
The command "if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then make test -C test TEST_VARS="NOLOOP=1 TEST_PATTERNS=sall APPSTORE=1"; else make test -C test TEST_VARS="NOLOOP=1 TEST_PATTERNS=sall" && make test -C test TEST_VARS="NOLOOP=1"; fi" exited with 0.
Done. Your build exited with 0.
