### ISSUE TITLE
Sometimes 2 active agreements reported in anax api

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#128]
Happens when 1 agreement is in the process of being terminated. Is this the proper design? Should there be another state called pending-termination

**Comment by linggao** [comment]
This is because there is a gab between agreement terminated to agreement archived. In governance.cancelAgreement() the procedure is this today:
1. Set AgreementStateTerminated
2. Delete agreement from exchange
3. In a separate thread: 
    3.1 Cancel the agreement from the blockchain
    3.2 Archive the agreement.

**Comment by linggao** [comment]
@dabooz , can we move 3.2 right after 1?

**Comment by linggao** [comment]
The fix will be put in the api only so that the agreements being terminated will be reported as the archived agreements instead of active agreements. We will also describe the behavior in the anax API doc.

**Comment by linggao** [comment]
PR: https://github.com/open-horizon/anax/pull/130
