### ISSUE TITLE
Horizon Agent sometimes gets wedged in one of the two "ing" states.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#1284]
The Horizon Agent can still get wedged in either "configuring" or "unconfiguring" state even using the latest (exchange 1.116.0, agent 2.23.29) code.
For example, see these recent Slack posts:
when: Oct 14th from: @mosquito in: #edge-fabric-dev containing: "unconfiguring"
when: Oct 19th from: @yshk in #edge-fabric-users containing "unconfiguring"

**Comment by dabooz** [comment]
@TheMosquito Did you capture the data I asked for. i.e. terminal log of what you were doing and syslog from the agent?

**Comment by dabooz** [comment]
Many things have been fixed, esp when connectivity is bad.
