### ISSUE TITLE
Move the logic for generating a default device id into agent or hzn

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1285]
Move the logic for generating a default device id (if not otherwise specified) into the agent or hzn, instead of the package script that puts it in /etc/default/horizon. This will allow us or the user to more easily completely replace /etc/default/horizon with a version of it appropriate for their icp cluster, w/o having to worry about preserving the device id. Because now the /etc/default/horizon file isn't device specific, so it will be easier for our automation to put the same file on all edge nodes of a customer.

This issue is part of a larger feature:

**Comment by dabooz** [comment]
register.go line 134: https://github.com/open-horizon/anax/blob/master/cli/register/register.go#L134
is where the code should go. The field horDevice.Id will be nil if HZN_DEVICE_ID is not set in /etc/default/horizon.
