### ISSUE TITLE
Pattern registration needs to execute an early verification of the exchange URL value

### ISSUE THREAD

**Issue by jiportilla** [open-horizon/anax#1290]
hzn cli has to check for exchange url early on during Pattern registration either in the HZN_EXCHANGE_URL environment variable or in the horizon agent config files (/etc/default/horizon) so that users do not encounter an error at the end of the registration process.

**Comment by mikehyde** [comment]
Please label p1, p2, or p3.

**Comment by jiportilla** [comment]
also fixed in https://github.com/open-horizon/anax/pull/1294
