### ISSUE TITLE
Always show what config files are being used in the CLI and the HZN variables values used during any CLI process

### ISSUE THREAD

**Issue by jiportilla** [open-horizon/anax#1291]
To show users always (not just verbose) what variables are found at the hzn.json files during code execution and show the files being read.

For example during Pattern registration:

[verbose] Reading configuration file: /etc/horizon/hzn.json
[verbose] Reading configuration file: /etc/default/horizon
[verbose] Config file does not exist: /home/pi/.hzn/hzn.json.
[verbose] Reading configuration file: /home/pi/services/oiworld/horizon/hzn.json
[verbose] The exchange url: https://9.30.210.34:8443/ec-exchange/v1
[verbose] GET https://9.30.210.34:8443/ec-exchange/v1/orgs/IBM/patterns/pattern-rpi-rpi.ibm.holaworld-arm

**Comment by mikehyde** [comment]
Please label p1, p2, or p3.

**Comment by jiportilla** [comment]
design doc to be reviewed - https://ibm.box.com/s/3czqqcphsblvr3mgx7ln399veowl1f89

**Comment by jiportilla** [comment]
https://github.com/open-horizon/anax/pull/1373

**Comment by jiportilla** [comment]
https://github.com/open-horizon/anax/pull/1379

**Comment by jiportilla** [comment]
All tests SUCCESSFUL
make: Leaving directory '/home/travis/gopath/src/github.com/open-horizon/anax/test'
The command "if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then make test -C test TEST_VARS="NOLOOP=1 TEST_PATTERNS=sall APPSTORE=1"; else make test -C test TEST_VARS="NOLOOP=1 TEST_PATTERNS=sall" && make stop -C test && make test -C test TEST_VARS="NOLOOP=1"; fi" exited with 0.

**Comment by jiportilla** [comment]
updated PR - https://github.com/open-horizon/anax/pull/1396
