### ISSUE TITLE
Detect when node is registered, user changes exchange url and restarts agent

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1301]
Even tho this is an uncommon situation, since we don't even know exactly how anax will respond or how to get a user out of it, it would be best to detect this case and deal with it right away.

**Comment by linggao** [comment]
Added an eventlog in the anax initialization, if the node cannot be retrieved from the exchange, the eventlog display the error + "If the exchange url is changed, please run 'hzn unregister -D' command to clean up the local node before starting horizon service."
This way the user can run `hzn eventlog list` and know what to do.

**Comment by MaxMcAdam** [comment]
Verified in 2.26.8
