### ISSUE TITLE
Allow changes to model policy service reference

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1308]
The model object metadata contains a reference to the service that is associated with this model. Currently, that service reference cannot be changed. Allow the service reference to be changed. But, when you allow this, a second underlying problem will surface. Suppose model m1 refers to service s1, s1 is deployed to node n1, s1 polls for updated models and is given m1. Then m1 is changed to refer to service s2. m1 is removed from n1 storage in n1's agent, but s1 is never told that m1 is being deleted.
- [x] enable changes to the service reference in model metadata
- [x] fix the underlying problem of notifying previous services when the service metadata changes

**Comment by jiportilla** [comment]
additional opportunities for improvement on the pipeline...

**Comment by LiilyZhang** [comment]
Design to solve the problem:
1. For each ESS, when polling the updates from CSS, compare policy services of local object with policy services of polled object, to get the removed services.
2. Add those removed services to `RemovedDestinationPolicyServices` list. (`RemovedDestinationPolicyServices` is a new field of ESS db object introduced with PR), then update that list of the object
3. When service call ESS `GET .../objectType` API to get all objects, also check: if current service is contained in `RemovedDestinationPolicyServices` list, set `deleted` to true (but don't store it back to ESS storage), then present to use
4. When service call ESS `PUT .../deleted` to confirm deletion, remove the service from `RemovedDestinationPolicyServices` list
