### ISSUE TITLE
Make anax calling exchange APIs more robust.

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#133]
Currently anax uses default http.Client to make request to the exchange APIs. The default timeout for the http.Client is 0 which means not default. This means if it take 1 hour for the server to return the result, it will wait for an hour.  We can add timeout to the http request and add retry logic if it is returns error.

**Comment by dabooz** [comment]
There is already retry logic for all exchange calls, but you're right that we should make sure the HTTP request timeout is not infinite.

**Comment by bmpotter** [comment]
Dave says its done.

**Comment by dabooz** [comment]
All http.Client objects has a default timeout value set to 20 seconds. This done a while ago in another PR. Closing this issue.
