### ISSUE TITLE
Add micropayments back into anax

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#134]
Needs to be done by end of april

**Comment by dabooz** [comment]
First draft here: https://docs.google.com/document/d/1qFPlIdSmQ-YwPwkEoSzMnPYWOcKbMj-jDSjc5BioZKM

**Comment by dabooz** [comment]
Shipped smart contract, bootstrap, supporting tests and contract API library.
https://github.com/open-horizon/go-solidity/commit/4fb00b46317dffd8e2c6d978f505119449b77088

**Comment by dabooz** [comment]
Completed policy lib updates and data verification interval implementation. 

Going by the numbered items in the implementation details section:
1 - coded and unit tested, needs to be integrated with runtime
3 - coded, unit tested and delivered in go-solidity commit
4 - coded, unit tested, needs integration test
5 - starting implementation today
6 - coded, unit tested, and integration tested

**Comment by dabooz** [comment]
Had to add a new implementation item 8 for tracking the amount of time when data is intermittently missing from the ingest.
1. coded and integration tested
2. coded and integration tested, we decided to not create a new API and just allow the existing /agreement API to display metering information per agreement (both for active and archived agreements)
3. done as above
4. coded and integration tested
5. coded, still need to update the diagrams
6. coded and integration tested
8. coded and integration tested

**Comment by linggao** [comment]
PR: https://github.com/open-horizon/anax/pull/184
Built in snap revision 94, 95. version 2.0.6

**Comment by dabooz** [comment]
Forgot the code for #7. Submitted the PR: https://github.com/open-horizon/anax/pull/189
