### ISSUE TITLE
Agent install script old version prompt improvement

### ISSUE THREAD

**Issue by omega2733** [open-horizon/anax#1349]
Anytime you update with agent-install using an older version of the agent code you receive a prompt warning that you are about to downgrade your agent if you have not already registered the agent. However, we do not receive this notification when a pattern/policy is also specified (agent registered). We should also receive this notification/user prompt of downgrade even if the agent is registered.

**Comment by LiilyZhang** [comment]
verified on `ocp-mcm-1x3`, hzn version downgrade from 2.24.16 to 2.24.13 works
