### ISSUE TITLE
MMS object metadata should keep track of the creator/owner of an object

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1351]
When the UI provides support for the MMS, they will need to be able to display the owner (in terms of a user) of artifacts in the system. They do this today with artifacts in the Exchange. The owner is not something that the user provides, it is something that the system adds based on the authenticated identity of the user who created the artifact. For example, when a new object is added to the system, the CSS would fill in the owner field of the object metadata based on the user identity that added the object. When the user provides object metadata to the system, the owner field is irrelevant/ignored by our code. hzn mms object new should NOT contain the owner field. hzn mms object list -l would show the owner field.

**Comment by MaxMcAdam** [comment]
Verified in 2.26.8
