### ISSUE TITLE
hzn gives misleading message when exchange URL is unreachable

### ISSUE THREAD

**Issue by MegaMosquito** [open-horizon/anax#1352]
I am seeing this:
```
gdarling@ubuntu18:~$ echo $HZN_ORG_ID
icp321
gdarling@ubuntu18:~$ hzn exchange user list
Error: organization ID must be specified with either the -o flag or HZN_ORG_ID
gdarling@ubuntu18:~$ 
```
That is, an org ID was specified, but the message says otherwise.
The actual problem here was a typo in the `/etc/default/horizon` file giving a bad URL for the exchange.

**Comment by TheMosquito** [comment]
(sorry...  I created this with my non-IBM github user ID)

**Comment by dabooz** [comment]
problem not recreateable
