### ISSUE TITLE
hzn unregister hangs during network outage

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1363]
Or if HZN_EXCHANGE_URL is set incorrectly, effectively the same thing happens.

**Comment by dabooz** [comment]
When the node unregisters, if there were network connectivity problems, something like the following message is likely to be displayed:
WARNING: The node is unregistered, but an error occurred during unregistration.
The error was: Unable to delete the node from the Exchange. Please use 'hzn exchange node remove major-peacock-icp-cluster/booz.vm.test.node' to remove it. The error was: exceeded 1 retries trying to delete node for Invocation of DELETE at https://major-peacock-icp-cluster.icp:8443/ec-exchange/v1/orgs/major-peacock-icp-cluster/nodes/booz.vm.test.node with  failed invoking HTTP request, error: Delete https://major-peacock-icp-cluster.icp:8443/ec-exchange/v1/orgs/major-peacock-icp-cluster/nodes/booz.vm.test.node: dial tcp 9.30.210.35:8443: connect: connection refused, HTTP Status:

**Comment by MaxMcAdam** [comment]
verified in 2.24.16
