### ISSUE TITLE
Updates for agent-install script

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1374]
- [x] on ubuntu bionic (18.04) or later, let the `horizon` pkg prereq  cause the distro docker pkg to be installed, instead of explicitly installing via `curl -fsSL get.docker.com | sh`. This way docker can be updated using the normal `apt update`. Investigate if the recent updates in ubuntu xenial (16.04) and raspbian stretch have recent enough docker pkgs ( > 18.06.01 ).
- [x] On mac it never calls the function `install_macos()`. One of the problems this causes is the check for `jq` never happens, so the user doesn't get a clear msg.
- [x] On mac instead of just requiring `jq`, try to install it for them: if they have `brew` on their mac, then do: `brew install jq`
- [x] If the `-i` value starts with `http:` or `https:`, then use it like an apt repo. This will enable internal users to use pkg.bluehorizon.network, and also artifactory in the future once https://github.ibm.com/Edge-Fabric/edge-computing/issues/125 is implemented. And will be needed for the batch install capability: https://ibm.ent.box.com/notes/540559786985

**Comment by MaxMcAdam** [comment]
Add a flag (if it's not already there) to wait for agreement and service execution. 
Make sure this is documented.

**Comment by MaxMcAdam** [comment]
Add a flag to use a non-default name for the batch install zip file.

**Comment by LiilyZhang** [comment]
Verified on Mac OS
