### ISSUE TITLE
hzn exchange user list - Error: bad HTTP code 405

### ISSUE THREAD

**Issue by njabbouribm** [open-horizon/anax#1395]
Running hzn exchange user list without any parameters is supposed to default to your own user. The default user is obtained from user-pw which is either set using hzn exchange user-pw or has a default value of HZN_EXCHANGE_USER_AUTH.

In the example of HZN_EXCHANGE_USER_AUTH = e2edev@somecomp.com/e2edevadmin:e2edevadminpw, the default user will be set to "e2edev@somecomp.com/e2edevadmin". This will result in the following error:
> Error: bad HTTP code 405 from GET http://exchange-api:8080/v1/orgs/e2edev@somecomp.com/users/e2edev@somecomp.com/e2edevadmin, output:

The correct user to be used in this scenario should be "e2edevadmin"

**Comment by bmpotter** [comment]
Nadim, i've been using `hzn exchange user list` a lot over the last month and it has always worked for me. Is this a corner case that is failing?

**Comment by njabbouribm** [comment]
Bruce, this is the case when the username for HZN_EXCHANGE_USER_AUTH is being set to orgID/username. I am not sure if this is done often but it seems to be the case in e2edev test.
