### ISSUE TITLE
Support configurable memory and CPU limits for a service

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1419]
From Docker: https://docs.docker.com/config/containers/resource_constraints/
--cpus x.y is equivalent to HostConfig.NanoCPUs=x.y * 1000000000
The other options for limiting CPU usage are obtuse, impossible to explain.
The go-dockerclient doesnt support the NanoCPUs field (not even in the newest code). We need an update to the library before we can move forward: https://github.com/fsouza/go-dockerclient/issues/818
For memory, it's easier. It's HostConfig.Memory to set the memory limit.

**Comment by dabooz** [comment]
The issue in go-dockerclient has been fixed. We should be able to proceed with this now.

**Comment by losdevnull** [comment]
Is there a plan for this support being added?  Thanks.

**Comment by sirotsinskuy** [comment]
Working on it. @joewxboy please assign this issue to me
