### ISSUE TITLE
hzn register waits for a service in any org

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1423]
hzn register can optionally wait for a service to start before giving control back to the caller. In some contexts, it is useful to allow the serviceorg to be omitted and replaced with something like '*' for the org, meaning the service in any org. Currently the command will default to HZN_ORG_ID as the default org if not specified, so not quite sure how to fit this one in.

**Comment by linggao** [comment]
PR https://github.com/open-horizon/anax/issues/1869
