### ISSUE TITLE
[BUG][TVT][IEC41] CLI answer <Are you sure ?> is not localized> in ES

### ISSUE THREAD

**Issue by JimmyCheng-tw** [open-horizon/anax#1425]
## Issue Summary
testcase 02.010.250
1. Open Edge node console
2. Input the following command, and replace your language with it.
	export LANG=es
 	(e.g. de, fr, es, it, pt-br, ja, ko, zh, zh-tw)
3. Input the following command.

	export HORIZON_EXCHANGE_URL=https://icp-console.apps.ocp-mcm-1x3.os.fyre.ibm.com/ec-exchange/v1 HORIZON_CSS_URL=https://icp-console.apps.ocp-mcm-1x3.os.fyre.ibm.com/ec-css HORIZON_EXCHANGE_USER_AUTH=root/root:????????????????????? HZN_ORG_ID=ocp-mcm-1x3

	hzn exchange pattern remove -o IBM -u iamapikey:?????????????????????? ss

	input  y

	click Enter

4. Verify    the translation strings in red rectangle(s) in expected results

## Problem
I see answer to Are you sure question is not localized:

## Expected Result
y/N -- should it be s/N?

## Environment
* IEC41 CLI Version: 4.1 (latest)
* Edge UI: https://icp-console.apps.ocp-mcm-1x3.os.fyre.ibm.com/edge
* IP: 9.30.24.146
![443_02 010 250__ESP_y_answer](https://user-images.githubusercontent.com/60088792/72705704-211ef980-3b97-11ea-97cf-b106e3e7adab.jpg)

**Comment by linggao** [comment]
The answer y/N are used by the code,  it should not be changed.  Please do not translate it.

**Comment by JimmyCheng-tw** [comment]
@linggao I have notified to the Spanish tester. Thank you.
