### ISSUE TITLE
[BUG][TVT][IEC41] English strings are displayed in CLI (hzn --help-long) in top session

### ISSUE THREAD

**Issue by JimmyCheng-tw** [open-horizon/anax#1426]
## Issue Summary
testcase 02.010.110
1. Open Edge node console
2. Input the following command, and replace your language with it.
	export LANG=es
 	(e.g. de, fr, es, it, pt-br, ja, ko, zh, zh-tw)
3. Input the following command.
	hzn --help-long
4. Verify    the translation strings in red rectangle(s) in expected results

## Problem
English strings in <hzn --help-long> flags and commands are displayed
No PII resource ID for these string. Maybe a hard-coded string.

## Expected Result
The string should be resource out.

## PII info
Show context-sensitive help (also try --help-long and --help-man).
Flags:
Commands:
Show help.
Show the Horizon Environment Variables.

## Environment
* IEC41 CLI Version: 4.1 (latest)
* Edge UI: https://icp-console.apps.ocp-mcm-1x3.os.fyre.ibm.com/edge
* IP: 9.30.24.146
![442_02 010 100_ESP_hard-coded_strings](https://user-images.githubusercontent.com/60088792/72707484-72c98300-3b9b-11ea-8457-254687ff362e.jpg)

**Comment by linggao** [comment]
The "Show the Horizon Environment Variables" is a new string and will get into next PII. 
Others are from the underlining kingpin.v2 framework. We cannot change or translate.

**Comment by JimmyCheng-tw** [comment]
@linggao I have to convey your comments to the tester. Thank you.

**Comment by JimmyCheng-tw** [comment]
Regarding the English problem of "Show context-sensitive help (also try --help-long and --help-man).", it is still displayed in English in the final pass build.
As long as I searched in the current PII files, the corresponding PII strings could not be found.
Please check this string in PII again. Thank you. @linggao
