### ISSUE TITLE
[BUG][TVT][IEC41] English strings are displayed in CLI (hzn --help-long) in register session

### ISSUE THREAD

**Issue by JimmyCheng-tw** [open-horizon/anax#1427]
## Issue Summary
testcase 02.010.150
1. Open Edge node console
2. Input the following command, and replace your language with it.
	export LANG=es
 	(e.g. de, fr, es, it, pt-br, ja, ko, zh, zh-tw)
3. Input the following command.
	hzn --help-long
4. Verify    the translation strings in red rectangle(s) in expected results

## Problem
English strings in <hzn --help-long> in register session are displayed
No PII resource ID for these string. Maybe a hard-coded string.

## Expected Result
The string should be resource out.

## PII info
    -s, --service=SERVICE        Wait for the named service to start executing on this node.
        --serviceorg=SERVICEORG  The org of the service to wait for on this node. If omitted, the node's org is used.
    -t, --timeout=60             The number of seconds for the --service to start. The default is 60 seconds, beginning when registration is successful. Ignored if --service is not specified.

## Environment
* IEC41 CLI Version: 4.1 (latest)
* Edge UI: https://icp-console.apps.ocp-mcm-1x3.os.fyre.ibm.com/edge
* IP: 9.30.24.146
![1427_02_010_150_English_strings_PTB](https://user-images.githubusercontent.com/60088792/72708535-ecfb0700-3b9d-11ea-9175-300d730e8896.png)

**Comment by linggao** [comment]
These are new messages. We will create new PII which will include them tonight.

**Comment by JimmyCheng-tw** [comment]
I have to convey your comments to the tester. Thank you. @linggao
