### ISSUE TITLE
Honor HZN_MGMT_HUB_CERT_PATH in anax container and deployment check apis.

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1434]
Currently the anax-in-container does not honor HZN_MGMT_HUB_CERT_PATH and old HZN_ICP_CA_CERT_PATH correctly.
`hzn deploycheck` and agbot secure api do not honor HZN_MGMT_HUB_CERT_PATH and old HZN_ICP_CA_CERT_PATH

**Comment by jiportilla** [comment]
3 tests completed successfully:

1. horizon container (mac)
2. deploycheck
3. agbot secure api

1.
export HZN_ICP_CA_CERT_PATH=/tmp/ocp.crt
ivanp@horizonvm1:~$ hzn exchange user list
{
  "mycluster/admin": {
    "admin": false,
    "email": "admin",
    "lastUpdated": "2020-01-27T18:45:28.093Z[UTC]",
    "password": "********",
    "updatedBy": "mycluster/admin"
  }
}


2.
hzn deploycheck all -b ibm.holaworld
Neither node id nor node policy is specified. Getting node policy from the local node.
Neither node id nor node user input file is specified. Getting node user input from the local node.
{
  "compatible": false,
  "reason": {
    "mycluster/ibm.holaworld_1.0.1_amd64": "Policy Incompatible: Compatibility Error: Node properties do not satisfy constraint requirements. The required properties (group==9, f>2.0) were not found in the available properties openhorizon.hardwareId=1cd234bb07023c8a59c09483ce8391249c6f2f1e, openhorizon.cpu=2, openhorizon.arch=amd64, openhorizon.memory=3938, openhorizon.allowPrivileged=false"
  }
}

3.

read -d '' comp_input <<EOF
  {
    "node_id": "mycluster/vm-26.ibm.com",
    "pattern_id": "mycluster/pattern-ibm.helloworld-amd64"
  }
EOF


echo $comp_input | curl -k -sLX GET -w %{http_code} https://icp-console.apps.better-tapir.purple-chesterfield.com/ec-agbot/deploycheck/deploycompatible -u "mycluster/iamapikey:xxxxx" --data @- |jq



{
  "compatible": true,
  "reason": {
    "mycluster/linghello_0.0.2_amd64": "Compatible"
  }
}
200
