### ISSUE TITLE
Error getting service with multiple architectures from the exchange for 'hzn deploycheck'

### ISSUE THREAD

**Issue by MaxMcAdam** [open-horizon/anax#1436]
root@4b573b6b614a:/tmp/exsvc# hzn deploycheck all -b test --node-pol node.policy.json
Neither node id nor node user input file is specified. Getting node user input from the local node.
Error: Failed to get services for all archetctures for e2edev@somecomp.com/test version 0.0.1. expecting 1 service test e2edev@somecomp.com 0.0.1, got 2

To recreate: Publish a service for 2 different architectures, then create a business policy with “*” for arch. Run deploycheck on it specifying a node policy so the command can’t tell the architecture of the node.

**Comment by jiportilla** [comment]
Found no issues with multiple architecture services, verified it is working as intended:

hzn deploycheck all -b ibm.holaworld --node-pol=bp.denver.json
Neither node id nor node user input file is specified. Getting node user input from the local node.
{
  "compatible": false,
  "reason": {
    "mycluster/ibm.holaworld_1.0.1_amd64": "Policy Incompatible: Compatibility Error: Node properties do not satisfy constraint requirements. The required properties (group==9, f>2.0) were not found in the available properties site=denver",
    "mycluster/ibm.holaworld_1.0.1_arm": "Policy Incompatible: Compatibility Error: Node properties do not satisfy constraint requirements. The required properties (group==9, f>2.0) were not found in the available properties site=denver"
  }
}

ivanp@horizonvm1:~/services/holaworld$ hzn exchange service list
[
  "mycluster/ibm.holaworld_1.0.1_arm",
   ...
  "mycluster/ibm.holaworld_1.0.1_amd64",
