### ISSUE TITLE
Create OAI JSON file for agbot secure APIs

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1443]
In order to do security vulnerability scan, a JSON file that meets the OAI specification https://github.com/OAI needs to be created for the anax public APIs. 

Also change the the following APIs path
````
/policycompatible
/userinputcompatible
/deploycompatible
````
to
````
/deploycheck/policycompatible
/deploycheck/userinputcompatible
/deploycheck/deploycompatible
````

**Comment by jiportilla** [comment]
manually created for this release to meet v2.0 req.
