### ISSUE TITLE
[TVT] Use single quote for Chinese translation

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1457]
```
export LANG=zh_CN
hzn policy patch -h
...
Args:
  <patch>  新的约束或属性，其格式为“{"constraints":[<constraint list>]}”或“{"properties":[<property list>]}”
```
format of the patch should use the single quote for the outmost quotes as the original. 
Please change 
```
其格式为“{"constraints":[<constraint list>]}”或“{"properties":[<property list>]}”
```
to 
```
其格式为 '{"constraints":[<constraint list>]}' 或 '{"properties":[<property list>]}'
```

**Comment by jiportilla** [comment]
For Spanish:


HZN_LANG="es" hzn register -h----------------------------- [<pattern>]  Si el patrón es de una organización distinta que el nodo, utilice el formato 'otra_org/patrón'.    

(translated other_org/pattern only in Spanish)       

Not in other languages:
     
PT: Se o padrão for de uma organização diferente do nó, use o formato 'other_org/pattern'    
FR: Si le pattern provient d'une organisation différente de celle du noeud, utilisez le format 'other_org/pattern

**Comment by jiportilla** [comment]
'Please' was omitted from most languages in this help msg: HZN_LANG="es" hzn unregister  -h
**-D, --deep-clean**
  EN
  Please capture the logs by ...
  ES
 Capture los registros ejecutando el mandato .
 PT
 Capture os logs, executando o comando
 FR
 Capturer les journaux à l'aide de la commande
 DE
 Erfassen Sie die Protokolle durch Ausführen des Befehl

**Comment by jiportilla** [comment]
unusual spacing in **'env variables section'**
 HZN_EXCHANGE_USER_AUTH:  Valor predeterminado para el distintivo 'hzn exchange -u' o 'hzn        register -u' con el formato '[org/]user:pw'.  Tenga  en  cuenta  que  HZN_ORG_ID  se  puede
       establecer        si se omite org cuando se establece HZN_EXCHANGE_USER_AUTH.
