### ISSUE TITLE
hzn unregister loses hardwareId

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1458]
Not exactly sure where in the scenario things went wrong.
1) registered a new node (version .13), hardwareId builtin prop was set and in the exchange
2) added some custom properties with hzn policy update -f
3) hzn unregister (without -r)
4) hzn register - hardwareId property was missing
5) hzn unregister -r
6) hzn register - hardwareId property was present

**Comment by jiportilla** [comment]
hzn unregister
hzn register

hzn policy list
{
  "properties": [
    {
      "name": "site",
      "value": "denver"
    },
    {
      "name": "openhorizon.hardwareId",
      "value": "0c368b247ccf0386941efff3a90cc1ddc6e26bcc"
    },
    {
      "name": "openhorizon.cpu",
      "value": 2
    },
    {
      "name": "openhorizon.arch",
      "value": "amd64"
    },
    {
      "name": "openhorizon.memory",
      "value": 3938
    },
    {
      "name": "openhorizon.allowPrivileged",
      "value": false
    }
  ],
  "constraints": [
    ""
  ]
}
