### ISSUE TITLE
service variables typed list of string with empty value causes panic

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1463]
Jan 28 11:58:33 radish1 anax[29145]: panic: runtime error: slice bounds out of range
Jan 28 11:58:33 radish1 anax[29145]: goroutine 27 [running]:
Jan 28 11:58:33 radish1 anax[29145]: github.com/open-horizon/anax/cutil.NativeToEnvVariableMap(0xc420b9e1e0, 0xc42094b210, 0xc, 0xcd8c40, 0xc42084c620, 0x0, 0x0)
Jan 28 11:58:33 radish1 anax[29145]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/cutil/cutil.go:163 +0x6c7
Jan 28 11:58:33 radish1 anax[29145]: github.com/open-horizon/anax/policy.UpdateSettingsWithUserInputs(0xc4207d54a0, 0x1, 0x4, 0xc420b9e1e0, 0xc42094b170, 0x10, 0xc42094b151, 0x9, 0xc420b9e1e0, 0x0, ...)
Jan 28 11:58:33 radish1 anax[29145]: #011/tmp/anax-gopath/src/github.com/open-horizon/anax/policy/user_input.go:212 +0x33a
Jan 28 11:58:33 radish1 anax[29145]: github.com/open-horizon/anax/governance.(*GovernanceWorker).GetServicePreference(0xc420a370a0, 0xc42094b170, 0x10, 0xc42094b151, 0x9, 0xc4207076c0, 0xc42094b180, 0x5, 0x14005f8)

**Comment by MaxMcAdam** [comment]
Verified in 2.24.16
