### ISSUE TITLE
MMS does not remove objects when node unregisters

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1478]
- [x] MMS objects are not removed from the node during unregister
- [x] MMS object destination is not updated to remove a node when it unregisters
- [x] MMS object list displays destination status for the wrong objects

**Comment by jiportilla** [comment]
Verified it is working as intended, please remember to register your node first.

make publish-label
hzn mms object publish -m mms/label.object.json -f mms/imagenet_comp_graph_label_strings.txt
Object imagenet_comp_graph_label_strings.txt added to org mycluster in the Model Management Service
ivanp@horizonvm1:~/img-class-v1$ make list-label
hzn mms object list -t txt -i imagenet_comp_graph_label_strings.txt -d
Listing objects in org mycluster:
[
  {
    "objectID": "imagenet_comp_graph_label_strings.txt",
    "objectType": "txt",
    "destinations": [
      {
        "destinationType": "openhorizon.edgenode",
        "destinationID": "mm.test.1",
        "status": "delivering",
        "message": ""
      },
      {
        "destinationType": "openhorizon.edgenode",
        "destinationID": "lubuntuVM-13.boulder.ibm.com",
        "status": "delivering",
        "message": ""
      },
      {
        "destinationType": "openhorizon.edgenode",
        "destinationID": "bruce-dev1.fyre.ibm.com",
        "status": "delivered",
        "message": ""
      },
      {
        "destinationType": "openhorizon.edgenode",
        "destinationID": "vm-26.ibm.com",
        "status": "delivering",
        "message": ""
      }
    ],
    "objectStatus": "ready"
  }
]
ivanp@horizonvm1:~/img-class-v1$ make list-label
hzn mms object list -t txt -i imagenet_comp_graph_label_strings.txt -d
Listing objects in org mycluster:
[
  {
    "objectID": "imagenet_comp_graph_label_strings.txt",
    "objectType": "txt",
    "destinations": [
      {
        "destinationType": "openhorizon.edgenode",
        "destinationID": "lubuntuVM-13.boulder.ibm.com",
        "status": "pending",
        "message": ""
      },
      {
        "destinationType": "openhorizon.edgenode",
        "destinationID": "bruce-dev1.fyre.ibm.com",
        "status": "pending",
        "message": ""
      },
      {
        "destinationType": "openhorizon.edgenode",
        "destinationID": "vm-26.ibm.com",
        "status": "delivered",
        "message": ""
      }
    ],
    "objectStatus": "ready"
  }
]
ivanp@horizonvm1:~/img-class-v1$ sudo ./ls.sh
/var/horizon/ess-store/sync/local:
total 12
drwxr-x--- 2 root root 4096 Feb  5 16:43 .
drwxr-x--- 4 root root 4096 Feb  5 16:40 ..
-rw------- 1 root root   19 Feb  5 16:43 mycluster-txt-imagenet_comp_graph_label_strings.txt

ivanp@horizonvm1:~/img-class-v1$ make delete-label
hzn mms object delete --type=txt --id=imagenet_comp_graph_label_strings.txt
Object imagenet_comp_graph_label_strings.txt deleted from org mycluster in the Model Management Service
ivanp@horizonvm1:~/img-class-v1$ make list-label
hzn mms object list -t txt -i imagenet_comp_graph_label_strings.txt -d
Listing objects in org mycluster:
[
  {
    "objectID": "imagenet_comp_graph_label_strings.txt",
    "objectType": "txt",
    "destinations": [
      {
        "destinationType": "openhorizon.edgenode",
        "destinationID": "lubuntuVM-13.boulder.ibm.com",
        "status": "deleted",
        "message": ""
      },
      {
        "destinationType": "openhorizon.edgenode",
        "destinationID": "bruce-dev1.fyre.ibm.com",
        "status": "pending",
        "message": ""
      },
      {
        "destinationType": "openhorizon.edgenode",
        "destinationID": "vm-26.ibm.com",
        "status": "deleted",
        "message": ""
      }
    ],
    "objectStatus": "objdeleted"
  }
]


ivanp@horizonvm1:~/img-class-v1$ sudo ./ls.sh
/var/horizon/ess-store/sync/local:
total 8
drwxr-x--- 2 root root 4096 Feb  5 16:44 .
drwxr-x--- 4 root root 4096 Feb  5 16:40 ..
