### ISSUE TITLE
More strict checking/validation of userinput compatibility

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1494]
- [x] Currently the the userinput compatibility check only checks if the userinput satisfies the requirements of the top level services and dependent services. It does not, however, point out the redundant service userinput and wrong service specifications.  (Ling)
- [x] The `hzn exchange node update` uses  compcheck.UserInputCompatible to check the input file in the pattern case. It does not check the input file for policy case and for the unregistered case.  Please also add node type checking to make sure the service type consists with the node type.(Lily) (opened a new issue for this one: 1797)

**Comment by linggao** [comment]
@LiilyZhang  for part 2, please move your original code back and use exchange.ServiceDefResolver() go get the service definitions for the top level and dependent services.

**Comment by LiilyZhang** [comment]
REMINDER: add node type and service type check
