### ISSUE TITLE
support hzn service log when using hzn dev to test services

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1498]
The impact of this is that in all of our examples that show the user how to create edge services we have to have instructions like step 2.5 of [Package an existing docker container as an edge service](https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.0/devices/developing/quickstart_example.html):

5. View the service container log:

On **Linux**:
```
sudo tail -f /var/log/syslog | grep myservice[[]
```

On **macOS**:
```
sudo docker logs -f $(sudo docker ps -q --filter name=myservice)
```

**Comment by sirotsinskuy** [comment]
@joewxboy Working on this
