### ISSUE TITLE
Agent-install.sh user experience improvements

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1502]
I will refine this list over the next couple of weeks, just want to get them all captured:

- [x] In `agent-install/agent-install.sh` around line 542, on mac it creates `~/.hzn/hzn.json` with essentially the same info as `/etc/default/horizon`. This is unnecessary and can lead to confusion if they change 1 of those files, but are unaware of the other.
- [x] In usage description of `-l`, include: what each number means (0: silent, 1: critical, 2: error, 3: warning, 4: info, 5: debug), and what the default is (3: warning). I think you should add a level for verbose between info and debug (debug sounds like it is for developers).
- [ ] With flag `-l 4` (info) there is too much output: we shouldn't see stdout of commands, and i don't think set -x should be used for as many cmds as it is now. There should be only about a dozen lines of output, 1 for each major step being done (and of course stderr of cmds in case anything goes wrong).
- [x] move `agent-install.crt` to someplace more persistent, like under /etc/horizon (so users don't delete all of the files `agent-install.sh` left in their current dir, thinking they are not needed any more)
- [x] use whatever `apt-get install` flag necessary to avoid this prompt: `Do you want to overwrite the current node configuration?[y/N]:`  When the user gets that question, they don't have a lot of context to know what is really being asked. Plus, i think this is referring to `/etc/default/horizon` and `agent-install.sh` is very soon going to overwrite that configuration anyway
- [x] when rerunning `agent-install.sh` with the same install pkgs, it shouldn't install them, unless a force flag is specified to `agent-install.sh`
- [ ] need to support updating install pkgs w/o changing registration state (i.e. if it was unregistered, leave it that way, if registered with a pattern, leave it that way, etc.)
- [ ] put sourcing of autocomplete file in `.bash_profile` on mac (OS X doesn't read `.bashrc`). This may have been done in 1Q
- [ ] when `agent-install.sh` is run via `sudo` (which is typically needed to run docker cmds, etc), it creates some files under the user's home dir that are owned by root, which is then a problem for the user later on. The script should check if its sudo identity is different from its non-sudo identity and `chown` any files it creates.
- [ ] ensure the script exits with a non-zero exit code for all error cases
- [x] `./agent-install.sh -h` should exit with exit code of 0 (if the usage is shown as a result of invalid args, then the exit code should be 1)
- [ ] in error msg "Failed to find node id in mapping file node-id-mapping.csv with bruce-dev1.fyre.ibm.com or 10.21.9.68..." it should say what hostname/ip it was trying to match
- [x] getting node IP addresses with `hostname -I` doesn't work on mac
- [ ] handle the case in which `agent-install.cfg` is the only thing that is new, such that the only thing that needs doing is to update `/etc/default/horizon` and restart anax. (This will be the case in 2Q if the route to the cluster ingress changes.)
- [x] add the `-z` flag to the usage msg
- [x] change all occurrences of `set +x` to `{ set +x; } 2>/dev/null` so it doesn't get printed
- [x] the script prompts the user in 5 places. There needs to be a flag and env var that can disable this, and instead take the default answer for each prompt automatically. (Scripts should always have this.) This is needed for bulk install, SDO, and anyone that wants to write a script on top of `agent-install.sh`
- [x] I see `grep: ": No such file or directory` in the output when run on linux. Also, several of the grep's have variable values piped into it. These should be replaced with bash pattern matching. See the **If statements** section of [Writing Well-Structured Bash Scripts](https://ibm.ent.box.com/notes/640766459871).
- [x] In the output it looks like it runs `apt update` **before** it adds the apt repo, so it has to run `apt update` again after that. That cmd is time consuming, so should only be done once.
- [ ] All of the functions should set the relevant numbered args (e.g. `$1`) to local varaibles like: `local fileName="$1"` . This makes the code much easier to read.

**Comment by MaxMcAdam** [comment]
- [ ] Compare the devices os, version, and architecture to ensure they are a supported combination

**Comment by varatep** [comment]
A few things came up in my testing:
- sent PR in that enables `raspbian buster` https://github.com/open-horizon/examples/pull/282
- `sudo chown -R $(whoami) /root` needed on the RPI before I can `pscp` the agent tarball
  - should update docs
- `cd /root` needed at the beginning of the `pssh` command (see snippet 1)
  - should update docs
- `sudo -s` needed for running `agent-install.sh` in the `pssh` command (see snippet 1)
  - should update docs
- should include documentation example for using node policy and installing without pattern (see snippet 2)

### Snippet 1
```
pssh -h nodes.hosts -t 0 "bash -c \"cd /root && tar -zxf $AGENT_TAR_FILE agent-install.sh && sudo -s ./agent-install.sh -i . -u $HZN_EXCHANGE_USER_AUTH -p IBM/pattern-ibm.helloworld -w ibm.helloworld -o IBM -z $AGENT_TAR_FILE 2>&1 >/tmp/agent-install.log \" "
```

### Snippet 2
```
echo '{
  "properties": [
    {
      "name": "owner",
      "value": "varatep"
    },
    {
      "name": "batch",
      "value": "1"
    }
  ],
  "constraints": [
    "owner == varatep"
  ]
}'>node-policy.json

pscp -h nodes.hosts node-policy.json /root/

pssh -h nodes.hosts -t 0 "bash -c \"cd /root && tar -zxf $AGENT_TAR_FILE agent-install.sh && sudo -s ./agent-install.sh -i . -u $HZN_EXCHANGE_USER_AUTH -n node-policy.json -z $AGENT_TAR_FILE 2>&1 >/tmp/agent-install.log \"
```

**Comment by bmpotter** [comment]
Varatep's comments above have been implemented in PR https://github.ibm.com/Edge-Fabric/docs/pull/319

**Comment by t-fine** [comment]
Shake: While working on the hello world example on my mac, the mounted folder shared by docker was owned by root which required me to chown the folder manually to make thing work. The error msg occurred in step 4 of [Install the Horizon agent on your edge device and register it with the hello world example](https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.0/devices/installing/registration.html), I think when `agent-install.sh` starts the anax container.

This was the command i used to fix it was:
```
sudo chown -R Abhishek.Preman1@ibm.com /private/var/tmp/horizon
```

BP: on our macs troy and i both have /private/var/tmp/horizon owned by our id, but we are not sure if we manually did that or not. Could be a difference in macOS version. To be safe, `agent-install.sh` should change the owner of this dir like shake did above.

**Comment by t-fine** [comment]
https://github.com/t-fine/anax/tree/updates-1-agent-install/agent-install
