### ISSUE TITLE
Add workload deployment option to bind mount /dev

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#152]
By default a docker container gets a snapshot of the /dev files at startup. This means that the gps container won't see the new /dev file of a gps sensor that is plugged in after the container has started. The work around is to start the container with the equivalent of the `-v /dev:/dev` flag. See this discussion: https://github.com/docker/docker/issues/15270 .

The new gps firmware container code already has code to find the new gps sensor /dev file if it appears after the container started. So it should work in that case as soon as anax implements the above change.

**Comment by michaeldye** [comment]
Does this open a security risk? I don't know how docker segments a container's dev from the host (besides making a copy), but bind mounting it into the container may be a problem. Can you get read-only access to just a part of /dev bind mounted in?

**Comment by bmpotter** [comment]
Good questions. I don't know of a way to give access to just some of the /dev entries. We can't bind mount individual /dev files, because the whole point of this is for the gps container to access a /dev file that isn't there at the beginning. Currently the gps container (and all other firmware containers) are running in `--privileged` mode, which means giving them access to all of /dev isn't any additional exposure. Eventually, maybe we should be using `--cap-add` or `--cap-drop` to get more granular about the firmware's access, but i don't see anything in the linux capabilities (https://linux.die.net/man/7/capabilities) that would give access to some /dev files and not others.

What is the use case/requirement for this feature? (Recognizing a gps sensor that is plugged in after the gps container has been started.)

**Comment by bmpotter** [comment]
BTW, currently the reg UI says "Note: You needn't have a GPS device at this time to opt-in; if you attach a device at a later time the system will make use of it." We should probably remove that text until we resolve all of the questions above.
