### ISSUE TITLE
run hzn deploycheck if services dont start during registration.

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1521]
When hzn register is told to wait for a service to start, if the service doesnt start at all, we tell the user to run hzn deploycheck all so that they might find the reason why the service doesnt start. If the register was for a pattern, we could run the command for them and display the results. If the register is using policy, then we can tell them to run the command pointing to the deployment policy that they think should have caused the deployment to occur.

**Comment by IntelliJIN** [comment]
WIP

**Comment by MaxMcAdam** [comment]
Verified in 2.27.0-110
