### ISSUE TITLE
check css status when started by hzn dev service start

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1532]
After 'hzn dev service start -m <obj>' starts the CSS, call the CSS status API to verify that it is working correctly. We might have to retry the /status call a few times if the CSS is slow to initialize. If the CSS is not working correctly after about 10 seconds, tell the user to remove the css image and try 'hzn dev service start' again.

If we have time, when the CSS status is bad, we can remove the image ourselves and then pull it again.

This situation was encountered when the user had an old CSS docker image in their local repository. The old CSS docker image started, but when the hzn CLI tried to load the object from the -m parameter into the CSS, the CSS API always replied with an EOF, and then the entire 'hzn dev service start' command failed. This change would have identified the problem. Even though the CLI code pulls the CSS docker image, docker doesnt always realize that an image with the same tag (latest in this case) has changed, or not. Since we can't fix docker, we can at least check the status of the CSS before trying to use it.

**Comment by jiportilla** [comment]
tested with this example:  https://github.com/jiportilla/img-MMS  as follows:

1. Started dev service with: `hzn dev service start -m horizon/service.definition.json -t model -v`
2. Stopped and rm css container `openhorizon/amd64_edge-sync-service:latest`
3. Pulled an older version of CSS with `docker pull openhorizon/amd64_cloud-sync-service:1.0.0`
4. Started css v1.0.0 with ```docker run --name=openhorizon.hzn-dev.css-api --hostname=5a4533dbd6d9 --env="NODE_TYPE=CSS" --env="UNSECURE_LISTENING_PORT=8580" --env="COMMUNICATION_PROTOCOL=http" --env="LOG_LEVEL=TRACE" --env="LOG_ROOT_PATH=/tmp/" --env="LOG_TRACE_DESTINATION=stdout" --env="TRACE_LEVEL=TRACE" --env="TRACE_ROOT_PATH=/tmp/" --env="STORAGE_PROVIDER=bolt" --env="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -p 0.0.0.0:8580:8580  --restart=always --label openhorizon.hzn-dev.css-api="" --detach=true openhorizon/amd64_edge-sync-service:1.0.0 /edge-sync-service/edge-sync-service```
5. Published a model update with:  `hzn mms object publish -m mms/object.json -f mms/index.js`
6. Observed published status with `hzn mms object list -t model -i index.js -d` as follows: `Listing objects in org mycluster:
[
  {
    "objectID": "index.js",
    "objectType": "model",
    "objectStatus": "ready"
  }
]
`
7. Tested delete model update with: `hzn mms object delete -t model --id index.js`
8. Observed deleted status with `hzn mms object list -t model -i index.js -d` as follows: `Listing objects in org mycluster:
[
  {
    "objectID": "index.js",
    "objectType": "model",
    "objectStatus": "objdeleted"
  }
]`
9. Stopped test with `hzn dev service stop`

working as designed.
