### ISSUE TITLE
Empty /etc/default/horizon and remove bluehorizon pkg

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1556]
- [ ] eliminate the `bluehorizon` pkg. It appears that the only things it adds are: /etc/horizon/anax.json (should be moved to the horizon pkg), /etc/horizon/trust/horizon.pem (not needed anymore), /etc/horizon/trust/mtn-publicKey.pem (not needed because we put these in the exchange with each sample service).
- [ ] have the horizon pkg ship an "empty" version of /etc/default/horizon (with just the variable names with "=" but no value), so it is self-documenting what can be put in there. Having it "empty" (instead of with the alpha values) will also result in a more clear error msg to the user if they forget to populate this file with values that point to their cluster.

Note: these related items are already completed:
-  The logic for generating a default device id (if not specified in `hzn register`) has been moved into the agent, instead of having a package script put it in /etc/default/horizon (anax team, [issue anax 1285](https://github.com/open-horizon/anax/issues/1285) )
- The `edgeDeviceFiles.sh` script (run by the admin as part of the "Gather" section of the infrastructure install) creates an `agent-install.cfg` file specific to the customer's cluster that can be downloaded to each edge node, and then is used by `agent-install.sh` to create the proper `/etc/default/horizon`

There is a peer issue open for the devops team: https://github.ibm.com/Edge-Fabric/edge-computing/issues/126

**Comment by bmpotter** [comment]
I completed this in this PR: https://github.com/open-horizon/anax/pull/1915
