### ISSUE TITLE
When anax restarts, cleanup auto-restarted workload containers that shouldn't be there

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#157]

**Comment by dabooz** [comment]
Look into cleaning up exited containers, if possible.

**Comment by dabooz** [comment]
1) Investigate BC event reads to make sure they go back far enough in time on a restart.
2) Verify agreements in the exchange for device and for agbot as compared to anax DB.
3) Delegate container sync up to container workers and report back with an event. Block anax sync up until that async container check is done.

**Comment by linggao** [comment]
In snap revision 83 (armhf) and 84 (x86)
