### ISSUE TITLE
hzn gives incorrect advice on macos

### ISSUE THREAD

**Issue by MegaMosquito** [open-horizon/anax#1611]
When there is an agent problem on macos, you will see this message:

glendarling@mbp AgentInstall % hzn -v version
[verbose] Reading configuration file: /usr/local/etc/horizon/hzn.json
[verbose] Config file does not exist: /etc/default/horizon.
[verbose] Config file does not exist: /Users/glendarling/.hzn/hzn.json.
[verbose] No project level configuration file found.
Horizon CLI version: 2.24.18
[verbose] HTTP request timeout set to 0 seconds
[verbose] GET http://localhost:8081/status
[verbose] Can't connect to the Horizon REST API to run GET http://localhost:8081/status. Run 'systemctl status horizon' to check if the Horizon agent is running. Or set HORIZON_URL to connect to another local port that is connected to a remote Horizon agent via a ssh tunnel. Specific error is: Get http://localhost:8081/status: dial tcp [::1]:8081: connect: connection refused
Horizon Agent version: failed to get.
glendarling@mbp AgentInstall %

But of course, `systemctl status horizon` is not possible in macos.

**Comment by IntelliJIN** [comment]
@joewxboy please assign this issue to me.

**Comment by IntelliJIN** [comment]
PR: https://github.com/open-horizon/anax/pull/2186
