### ISSUE TITLE
Write doc on how to install the agent into an edge cluster

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1617]
With the script in hand, what are the steps to install the agent.
This is the input for KC 4.1

**Comment by LiilyZhang** [comment]
Draft: https://ibm.ent.box.com/notes/655853828044

**Comment by LiilyZhang** [comment]
KC 4.1:
1. https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.1/devices/developing/preparing_edge_cluster.html
2. https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.1/devices/developing/importing_clusters.html
