### ISSUE TITLE
'hzn exchange service publish' doesn't store the public signing key by default

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1623]
This was tested on mac, with a build of `hzn` from source on 3/25/20, and the `latest` anax container at that time.

Synopsis of problem: `hzn exchange service publish ...` doesn't store the public signing key in the exchange unless `-K` is explicitly specified.

Here's the test:

```
$ make publish-service-overwrite
hzn exchange service publish -O -P -f horizon/service.definition.json
Checking private key file format ... 
Verifying public key file ... 
Signing service...
Pulling openhorizon/bp.helloworld_amd64:1.0.0...
1.0.0: Pulling from openhorizon/bp.helloworld_amd64
Digest: sha256:f1c8eb54b3f099604ee4840ad1c0041efaebe8896a296af5e4522743367de13c
Status: Image is up to date for openhorizon/bp.helloworld_amd64:1.0.0
Using 'openhorizon/bp.helloworld_amd64@sha256:f1c8eb54b3f099604ee4840ad1c0041efaebe8896a296af5e4522743367de13c' in 'deployment' field instead of 'openhorizon/bp.helloworld_amd64:1.0.0'
Updating bp.helloworld_1.0.0_amd64 in the exchange...
$ hzn exchange service listkey bp.helloworld_1.0.0_amd64
Error: keys not found
$ echo $HZN_PUBLIC_KEY_FILE $HZN_PRIVATE_KEY_FILE
$ ls ~/.hzn/keys/service.public.pem
/Users/bp/.hzn/keys/service.public.pem
$ hzn exchange service publish -O -P -f horizon/service.definition.json -K ~/.hzn/keys/service.public.pem
Checking private key file format ... 
Verifying public key file ... 
Signing service...
Pulling openhorizon/bp.helloworld_amd64:1.0.0...
1.0.0: Pulling from openhorizon/bp.helloworld_amd64
Digest: sha256:f1c8eb54b3f099604ee4840ad1c0041efaebe8896a296af5e4522743367de13c
Status: Image is up to date for openhorizon/bp.helloworld_amd64:1.0.0
Using 'openhorizon/bp.helloworld_amd64@sha256:f1c8eb54b3f099604ee4840ad1c0041efaebe8896a296af5e4522743367de13c' in 'deployment' field instead of 'openhorizon/bp.helloworld_amd64:1.0.0'
Updating bp.helloworld_1.0.0_amd64 in the exchange...
Storing service.public.pem with the service in the exchange...
```

**Comment by dabooz** [comment]
@bmpotter just to be clear, the CLI should reject the command if -k is specified but -K isnt specified? Also, in your first case, you allowed the private key to default to the hzn default key location, so would you have expected the public key to be published from that default location also, without -K?

**Comment by bmpotter** [comment]
@dabooz  the original idea of the key defaults was to not make the user have to think about it in normal cases. If they have created a key pair in the default location, we should always use both of them.

But i think your specific questions are about trying to avoid letting the user use mismatched private and public keys (i.e. from different key pairs)? I have mixed feelings about that. I see it would be helpful, but we can't be sure it is a mismatched pair just because they are coming from different sources. And it seems like it would result in confusing rules.

I vote for the way the behavior has been in the past: if it finds a private key in any of the places (flag, env var, default loc) it uses it to sign the service. And if it finds a public key in any of the places (flag, env var, default loc) it will store it in the exchange.

**Comment by linggao** [comment]
The logic is: 
For private key: if it finds a private key in any of the places (flag, env var, default loc) it uses it to sign the service.
For public key: And if it finds a public key in any of the places (flag, env var, default loc) it will store it in the exchange.
Special case: if the private key is explicitly specified by -k and public key is NOT specified with -K, do not store the public key. 
This was the original design. I fixed a bug in it.

**Comment by LiilyZhang** [comment]
Verified on rested-squid cluster with agent 2.26.5. closed
