### ISSUE TITLE
Anax agent doesn't destroy workload after receiving a cancel under heavy load

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#1655]
I have a scenario where I have 10k agents with a policy and then I delete the policy on the hub expecting that all agent agreements will be canceled.  What I see is that some agents will continue to run the workload and not destroy it. Looking at the agent logs, they receive the cancel message but then have trouble communicating back to the hub (due to 502 errors) and the workload continues to run. The agents need to be able to process the cancel message and destroy the workload

**Comment by dlarson04** [comment]
Agent logs added.  The cancel messages were received about April 13 around 11:16 but the workloads were still running hours later

[edge-scale-test-rtp-4-host-86.fyre.ibm.com_horizon5.zip](https://github.com/open-horizon/anax/files/4469531/edge-scale-test-rtp-4-host-86.fyre.ibm.com_horizon5.zip)
[edge-scale-test-rtp-4-host-84.fyre.ibm.com_horizon9.zip](https://github.com/open-horizon/anax/files/4469537/edge-scale-test-rtp-4-host-84.fyre.ibm.com_horizon9.zip)

**Comment by dabooz** [comment]
@dlarson04 Are you sure this isnt a dup of #1641 ? I am seeing EOF errors at the time the agent was trying to handle the cancel, which it should have retried but didnt because of 1641.

**Comment by dlarson04** [comment]
Even after the retry logic is fixed, what if there is still connectivity problems from the agent to the hub and all the retries fail... doesn't there need to be some mechanism for the agent to eventually recover and destroy the workload? Even if it was the agent waits a very long time and retry again or maybe the agbot has to resend the cancel the message  it it doesn't get a message from the agent.  
I think there should be some way for the system to eventually cleanup/recover and not get stuck in an indeterminate state

**Comment by dabooz** [comment]
ah ok, I misunderstood the reason for opening the issue. Yeah, I think we could make the tear down more forgiving of errors.

**Comment by dabooz** [comment]
Turns out that all interactions with the exchange in the agreement cancellation code path already have logic to requeue the cancel command (so that it will be retried) if there is an error, except for the one spot exposed by this test. Fixed it.
