### ISSUE TITLE
Use the namespace to create the k8s artifacts if provided

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1658]
- [x] If a k8s namespace object is present in the operator yaml archive, create (dont fail if already present) during install and delete the namespace during uninstall
- [x] If a namespace is ONLY (there is no yaml namespace object) specified in the operator deployment, try to create it (dont fail on error) on install and DO NOT delete it on uninstall.

**Comment by MaxMcAdam** [comment]
Verified
