### ISSUE TITLE
Reduce duplicated in Makefile

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1662]
In the Makefile, anax-image, agbot-image, anax-k8s-image and fss-image have a lot of duplicates.
Same with promote-anax, promote-agbot etc.

**Comment by xauthulei** [comment]
@linggao , I suggest the we could leave this duplicates in a shell script, how about this ,Thanks

**Comment by linggao** [comment]
@xauthulei yes, I agree.  We can have then calling shell scripts with different parameters.

**Comment by xauthulei** [comment]
@linggao ,Thanks for the confirmation. I will work on this , Thanks

**Comment by xauthulei** [comment]
@linggao I have committed a PR #2639 , would u please help review when you are free, Thanks
