### ISSUE TITLE
Add label and description to node and service policy

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1667]
It would be helpful to be able to annotate the node and service policies with label and description in order to allow a user to more effectively communicate their purpose.

Also, `hzn exchange service listpolicy <service-policy>` should also display the `lastUpdated` field. (It doesn't right now.)

After this is implemented, the samples in open-horizon/examples should be updated to set these values.

This issue depends on https://github.com/open-horizon/exchange-api/issues/435 (which is now complete)

**Comment by IntelliJIN** [comment]
@joewxboy please assign this issue to me.

**Comment by bmpotter** [comment]
The exchange updates you need for this issue are complete. See https://github.com/open-horizon/exchange-api/issues/435#issuecomment-770001093 .

**Comment by dabooz** [comment]
@IntelliJIN This issue is now unblocked. Are you able to proceed with this issue?
