### ISSUE TITLE
Horizon agent never gets agreement after node policy update

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#1672]
Scenario:

Agent has node policy that matches 3 business policies and gets an agreement for all 3.
Update the node policy but still match the constraints for all 3 business policies.
Intermittently, agent will end up with less than 3 agreements. It will never get additional proposals.

Expected behavior:
Since agent matches all 3 business policies, the agent should always end up with 3 agreements

I will attach logs but here is what I think is the sequence of events that lead to the agent not getting 3 agreements. In the attached logs, only 1 agreement was reached

Policy Name: ocp-mcm-1x3/PerfHznModel200Policy
```
"2020-04-20 08:37:26:   Node received Proposal message using agreement 9a31cf257f74a628e88b7112f421889d2e8221bf36f94e5466bbf280e38afd73 for service IBM/ibm.helloworld from the agbot IBM/ocp-mcm-1x3-agbot.",
"2020-04-20 08:37:38:   Node received Proposal message using agreement 013612c06719597d01f89ccd3870fe7cd51a08f14f2d9dfa44583dce0bfe012f for service IBM/ibm.helloworld from the agbot IBM/ocp-mcm-1x3-agbot.",
"2020-04-20 08:37:39:   Agreement 9a31cf257f74a628e88b7112f421889d2e8221bf36f94e5466bbf280e38afd73 already exists, ignoring proposal: ibm.helloworld",
```

Policy Name: ocp-mcm-1x3/PerfHznModel300Policy
```
"2020-04-20 08:37:29:   Node received Proposal message using agreement 2697c32596d247a0ecb2d381d23bf7b169b7c9f56d56de2978cd72188f0ea08b for service IBM/ibm.helloworld from the agbot IBM/ocp-mcm-1x3-agbot.",
"2020-04-20 08:37:40:   Node received Proposal message using agreement b4e71ead6ec041398eb3fb1d37044e9fecea98f5238d8c3de7748a825917db6c for service IBM/ibm.helloworld from the agbot IBM/ocp-mcm-1x3-agbot.",
"2020-04-20 08:37:41:   Agreement 2697c32596d247a0ecb2d381d23bf7b169b7c9f56d56de2978cd72188f0ea08b already exists, ignoring proposal: ibm.helloworld",
```

Policy Name: ocp-mcm-1x3/PerfHznModel100Policy
```
 "2020-04-20 08:37:42:   Node received Proposal message using agreement ad1afb3a97259c90eead2fccafc335a9fa811948f0aa3d4376166f172920f68a for service IBM/ibm.helloworld from the agbot IBM/ocp-mcm-1x3-agbot.",
```

Agreements Reached
```
  "2020-04-20 08:37:51:   Agreement reached for service ibm.helloworld. The agreement id is 2697c32596d247a0ecb2d381d23bf7b169b7c9f56d56de2978cd72188f0ea08b.",
  "2020-04-20 08:37:57:   Agreement reached for service ibm.helloworld. The agreement id is 9a31cf257f74a628e88b7112f421889d2e8221bf36f94e5466bbf280e38afd73.",
  "2020-04-20 08:38:01:   Agreement reached for service ibm.helloworld. The agreement id is ad1afb3a97259c90eead2fccafc335a9fa811948f0aa3d4376166f172920f68a.",
```

Node policy changed
```
  "2020-04-20 08:38:54:   New node policy: [map[name:horizon_model_200 value:5,500] map[name:horizon_model_300 value:5,500]]",
```

Sending Cancel messages
```
I0420 12:38:55.074003      82 producer_protocol_handler.go:108] Base Producer Protocol Handler (Basic): Sending exchange message to: IBM/ocp-mcm-1x3-agbot, message {"type":"cancel","protocol":"Basic","version":1,"agreementId":"2697c32596d247a0ecb2d381d23bf7b169b7c9f56d56de2978cd72188f0ea08b","reason":101}

I0420 12:38:55.465286      82 producer_protocol_handler.go:108] Base Producer Protocol Handler (Basic): Sending exchange message to: IBM/ocp-mcm-1x3-agbot, message {"type":"cancel","protocol":"Basic","version":1,"agreementId":"9a31cf257f74a628e88b7112f421889d2e8221bf36f94e5466bbf280e38afd73","reason":101}

I0420 12:38:55.952231      82 producer_protocol_handler.go:108] Base Producer Protocol Handler (Basic): Sending exchange message to: IBM/ocp-mcm-1x3-agbot, message {"type":"cancel","protocol":"Basic","version":1,"agreementId":"ad1afb3a97259c90eead2fccafc335a9fa811948f0aa3d4376166f172920f68a","reason":101}
```

New Agreement For Policy Name: ocp-mcm-1x3/PerfHznModel100Policy
```
  "2020-04-20 08:39:08:   Node received Proposal message using agreement 08c6b61c56e6734cb35997785783d05a20a92633251ab3e8f49b6a7cd9f71a3e for service IBM/ibm.helloworld from the agbot IBM/ocp-mcm-1x3-agbot.",
  "2020-04-20 08:39:41:   Agreement reached for service ibm.helloworld. The agreement id is 08c6b61c56e6734cb35997785783d05a20a92633251ab3e8f49b6a7cd9f71a3e.",
```

But no new agreements for PerfHznModel200Policy or PerfHznModel300Policy are received. I am thinking that the reason is because the agbot still has outstanding agreements for those policies that were ignored that have not timeout out yet 

```
I0420 12:39:53.994154      82 worker.go:585] MessageDispatcher: Handling Message (*events.ExchangeDeviceMessage): Event: RECEIVED_EXCHANGE_DEV_MSG, AgbotId: IBM/ocp-mcm-1x3-agbot, ProtocolMessage: {"type":"cancel","protocol":"Basic","version":1,"agreementId":"b4e71ead6ec041398eb3fb1d37044e9fecea98f5238d8c3de7748a825917db6c","reason":201}, Time: 1587386393

I0420 12:39:54.194863      82 worker.go:585] MessageDispatcher: Handling Message (*events.ExchangeDeviceMessage): Event: RECEIVED_EXCHANGE_DEV_MSG, AgbotId: IBM/ocp-mcm-1x3-agbot, ProtocolMessage: {"type":"cancel","protocol":"Basic","version":1,"agreementId":"013612c06719597d01f89ccd3870fe7cd51a08f14f2d9dfa44583dce0bfe012f","reason":201}, Time: 1587386393
```

The agbots should eventually realize that the agent doesn't have agreements for matching policies and issue new proposals.

**Comment by dlarson04** [comment]
[anax-logs-issue-1672.zip](https://github.com/open-horizon/anax/files/4510199/anax-logs-issue-1672.zip)

**Comment by dlarson04** [comment]
I should point out that this issue was seen under light load - just 1 agent was registering

**Comment by dabooz** [comment]
https://github.com/open-horizon/exchange-api/issues/345 is reproduce-able with a single node and a single agreement. If the node ever reaches a point where there are zero agreements on the node, policy searches come back empty when nodes should be returned.

**Comment by dlarson04** [comment]
Times are shown in EDT

Scenario:
On May 04 (around 07:55:xx) 50 agents registered with a policy that matches PerfHznModel100Policy

Action:
Around 08:05:xx agents updated node policy with additional properties
"2020-05-04 08:05:32:   New node policy: [map[name:horizon_model_200 value:2,000] map[name:horizon_model_300 value:2,000]]"



Expectation:
All 50 agents would have 3 agreements for a total of 150 agreements but only see the following in hzn exchange status even after 2 hours

{
  "dbSchemaVersion": 35,
  "msg": "Exchange server operating normally",
  "numberOfAgbotAgreements": 4224,
  "numberOfAgbotMsgs": 0,
  "numberOfAgbots": 1,
  "numberOfNodeAgreements": 82,
  "numberOfNodeMsgs": 0,
  "numberOfNodes": 50,
  "numberOfUsers": 2
}

Looking at the agreements on the agents, I see

Agreements matching PerfHznModel200Policy :  37
Agreements matching PerfHznModel300Policy :  33
Agreements matching PerfHznModel100Policy :  12



Sample agreements on agents
edge-scale-test12_horizon0 has agreements from all 3 policies. Same for edge-scale-test13_horizon0, edge-scale-test14_horizon0, edge-scale-test15_horizon0, edge-scale-test16_horizon0, edge-scale-test17_horizon0, edge-scale-test18_horizon0

edge-scale-test19_horizon0 has agreements from PerfHznModel300Policy and PerfHznModel100Policy

edge-scale-test30_horizon0 has agreement from PerfHznModel300 only


[edge-logs-may04.zip](https://github.com/open-horizon/anax/files/4575194/edge-logs-may04.zip)

**Comment by LiilyZhang** [comment]
Closed. Dup as #1698
