### ISSUE TITLE
Status indicator for MMS publish command

### ISSUE THREAD

**Issue by jiportilla** [open-horizon/anax#1674]
When using hzn mms object publish command, we encountered network latency issues at different locations when transferring a 500 MB model. For example: it took from 1 minute on a cloud VM to 20 minutes on local VM at a developer home location (all with similar upload speeds 4-6 Mbs).

It will be very helpful if we can show an status indicator of this network transfer operation so that end-users can tell how long it will take to transfer larger model files.

(some examples at https://github.com/sbwhitecap/tqdm )

**Comment by sirotsinskuy** [comment]
@joewxboy Working on it.
@jiportilla @linggao Do we need some time prediction for the uploading? Or showing progress in % would be enough?

**Comment by jiportilla** [comment]
IMHO, just showing progress would be enough, sometimes we do not know if the upload step was interrupted due to network latency issues. Thank you.
