### ISSUE TITLE
Unable to advertise policies with exchange, i/o timeout

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#169]
Flashbot test node2.9879 , the sdr agreement did not get creted. There were three calls to register the services with the exchange.  The first time was location, the second time was location + netspeed and the third time was location + netspeed + sdr. The third one failed with timeout error.  There was retry logic in the code, but this error was not tpErr, so it did not get chance to retry.  
```
agreement.go:254 AgreementWorker unable to advertise policies with exchange, error: Invocation of PUT at https://exchange.bluehorizon.network/api/v1/devices/000000004d230fbc with { ....} failed invoking HTTP request, error: Put https://exchange.bluehorizon.network/api/v1/devices/000000004d230fbc: dial tcp 169.55.61.216:443: i/o timeout

```

**Comment by linggao** [comment]
The call was made at 18:07:08, the error log was at 18:07:38.

**Comment by dabooz** [comment]
While investigating the defect, several things were discovered:
1) Transport timeouts are not handled as retryable errors anywhere in anax, but they should be retryable.
2) HTTP client timeouts are not used, which means no timeout. That's not what we want, so an anax wide default was established and baked into all uses of the go http client. This is what most of the changes are for.
3) Retryable HTTP errors are not consistently logged as Warnings, some were Info messages. They were all changed to Warning messages.

**Comment by linggao** [comment]
Built into snap 108 (arm) and 109 (x86) version 2.0.11
