### ISSUE TITLE
Unregister edge cluster agent returns DockerEndpoint error

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1697]
microk8s.kubectl exec agent-8cdb5ddb7-mx4rn -it -n openhorizon-agent -- /usr/bin/hzn unregister -fr
Unregistering this node, cancelling all agreements, stopping all workloads, and restarting Horizon...
Waiting for Horizon node unregister to complete: No Timeout specified ...
Waiting for Horizon node unregister to complete: No Timeout specified ...
WARNING: The node is unregistered, but an error occurred during unregistration.
The error was: GovernanceWorker: Docker client cannot be initialized. Please make sure DockerEndpoint is set in the configuration file.

**Comment by MaxMcAdam** [comment]
Verified in e2edev
