### ISSUE TITLE
Prevent hzn user from accidentally creating deployment policy with no constraints

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1700]
Because they could easily cause a service to be deployed to 1000's of edge nodes w/o realizing it.

- [x] add a flag to `hzn exchange deployment addpolicy` that they need to use if they want to create a deployment policy with no constraints
- [x] Have `hzn exchange deployment addpolicy` without the flag above check the constraints and display error msg if there are no constraints and tell them they must use the flag above if they really want to do this
- [x] Change `hzn exchange deployment new` to create a constraint like `"myproperty == myvalue"`

**Comment by MaxMcAdam** [comment]
Verified in 2.26.8
