### ISSUE TITLE
Have nonexistent policy property match "myprop != myvalue"

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1701]
If a deployment policy has a constraint like `"myprop != myvalue"`, i think that should match a node whose policy doesn't set the property `myprop` at all. Because the constraint is true, `myprop` does not equal `myvalue`.

But this is not how it works today.

**Comment by dabooz** [comment]
I disagree, but since this is a p3 we dont have to decide it in this release.

**Comment by bmpotter** [comment]
Yep, we can talk about it later. One alternate idea to make it more explicit: add an operator or keyword such that the user can write a constraint that is true when the node doesn't have that property. For example: `myprop is undefined`.

That way they could write a constraint like this to get the behavior i'm looking for: `myprop != myvalue OR myprop is undefined` . A little more work for the user, but more explicit/clear about the meaning/behavior.
