### ISSUE TITLE
Add a way to override the blockchain name in the exchange that is used

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#172]
CMTN_BLOCKCHAIN is the setting inside anax that controls what exchange resource name under /bctypes/ethereum/blockchains is used to load the geth container (defaults to `bluehorizon`). We need a way to set that from outside anax, the same way the exchange url can be overridden by putting it in horizon/config/horizon_exchange_url in the boot partition.

Also, for completeness, please make update_horizon look in /var/horizon/config for that file too.

**Comment by linggao** [comment]
PR: https://github.com/open-horizon/bluehorizon-snap/pull/40

**Comment by linggao** [comment]
Built in snap revision 85 (armhf) and 86 (x86).  version 2.0.3
