### ISSUE TITLE
GVT [IEC41] - Hardcode string displays in CLI (hzn exchange service publish -h)

### ISSUE THREAD

**Issue by helloyangyxq** [open-horizon/anax#1748]
testcase 02.020.020
**Environment:**
hzn version: 2.26.3

**ISSUE Summary**    
    Open Edge node console
    Input the following command, and replace your language with it.
    export LANG=es
    (e.g. de, fr, es, it, pt-br, ja, ko, zh, zh-tw)
    Input the following command.
    hzn exchange service publish -h
    
**Problem**
English strings in <-h> flags and commands are displayed
No PII resource ID for these string. Maybe a hard-coded string.

**Screenshot**
![image](https://user-images.githubusercontent.com/65275431/81781028-13b4c300-952a-11ea-81c9-449d7d1b40b9.png)

**Comment by linggao** [comment]
The line with "-h --help" is from the kingpin frame work that hzn depends on. It cannot be translated.

**Comment by helloyangyxq** [comment]
Thanks for explanation, close it now.
