### ISSUE TITLE
Agbot DB workload_usages_ row deletion cause postgres logs to fill

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1751]
...when there arent any rows in the table.

< 2020-05-12 23:59:59.985 UTC > ERROR:  relation "workload_usages_" does not exist at character 13
< 2020-05-12 23:59:59.985 UTC > STATEMENT:  DELETE FROM "workload_usages_" WHERE device_id = $1 AND policy_name = $2;

**Comment by dlarson04** [comment]
Verified that these log messages are not seen in the agbot postgres logs after 2.26.6
