### ISSUE TITLE
GVT [IEC41] - Hardcode error string(hzn exchange deployment updatepolicy)

### ISSUE THREAD

**Issue by helloyangyxq** [open-horizon/anax#1764]
testcase 02.040.040
Environment:
hzn version: 2.26.3

ISSUE Summary
Open Edge node console
Input the following command, and replace your language with it.
export LANG=es
(e.g. de, fr, es, it, pt-br, ja, ko, zh, zh-tw)
Input the following command:
hzn exchange deployment updatepolicy --json-file=service_cluster.json arendelle/ibm.helloworld_1.0.0

Problem
The error message maybe a hard-coded string, please double check

Screenshot:
![image](https://user-images.githubusercontent.com/65275431/82001752-7e7f0f00-968e-11ea-8752-d0f1e8448741.png)

**Comment by linggao** [comment]
This error is from the GO framework. We cannot translate it.
