### ISSUE TITLE
Agent-created node policy properties should explicitly state their units.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#1777]
Any agent-created properties that have unit quantifiers should explicitly specify them. `open-horizon.memory` for example is in megabytes, but the field name is ambiguous about that. So when I see `open-horizon.memory=200` how would I know that means 200MB. One of the edge machines I work on has 200GB RAM, and another has 128GB RAM so it does not seem intuitively obvious that 200 means 200MB. Could we make it `open-horizon.memory.mb=200` perhaps? You could keep the old one as well for backward compatibility.

**Comment by gripson** [comment]
@TheMosquito , @dabooz  could you please assign this issue to me?
