### ISSUE TITLE
[BUG] agent-install.sh does not check for docker pre-requisite

### ISSUE THREAD

**Issue by omega2733** [open-horizon/anax#1780]
Summary: We do not check for the docker pre-requisite when installing for a device type of cluster, thus can cause the script to fail when docker is called but not installed during edge cluster agent install. We should have a pre-requisite check for this as we have pre-requisite checks for kubectl, export of variables, configuration files etc necessary to run the tool so we do not run into an unexpected failure.

Update: docker re-requisite check should also added for cluster agent install

This also further is exacerbated by issue [1779](https://github.com/open-horizon/anax/issues/1779) if hit by a user.

**Comment by omega2733** [comment]
Just for clarity, this works perfectly fine for agent devices (nodes). This is only an issue for device types of "cluster"

**Comment by omega2733** [comment]
I believe that Troy's PR https://github.com/open-horizon/anax/pull/1793 - which fixes the function install_linux is only called by install_${OS}. This isn't called in the install_cluster() function, I'm not sure if we wish to re-use the install_linux function or another function for cluster install pre-reqs.

**Comment by LiilyZhang** [comment]
Verified with latest agent-install.sh from master
