### ISSUE TITLE
[TVT][EAM41]Bad layout in command 'hzn exchange node listerrors -h'

### ISSUE THREAD

**Issue by helloyangyxq** [open-horizon/anax#1782]
testcase 02.010.010

    Open Edge node console
    Input the following command, and replace your language with it.
    export LANG=es
    (e.g. de, fr, es, it, pt-br, ja, ko, zh, zh-tw)
    Input the following command.
    hzn exchange node listerrors -h
    Verify the translation strings in red rectangle(s) in expected results

Problem:
Bad layout, the strings are not alignment correctly in JPN

Screenshot:
![image](https://user-images.githubusercontent.com/65275431/82421140-30657380-9ab3-11ea-9f17-3db5327269de.png)

**Comment by linggao** [comment]
It is because of the wrapping of a long sentence. It works for languages like en, br, fr, it, de, but does not work for zh, ja, ko. This from the framework. We cannot do anything about it.
