### ISSUE TITLE
Other Docker Registries not currently supported through agent-install.sh script 

### ISSUE THREAD

**Issue by JShelf** [open-horizon/anax#1784]
[This Line](https://github.com/open-horizon/anax/blob/master/agent-install/agent-install.sh#L1465) in the agent-install script removes support other registries as the login defaults to the base dockerhub and fails if the login info is some other registry, such as openshift. 

There should likely be some default parameter for the dockerhub and the line should be something like 
```echo "$EDGE_CLUSTER_REGISTRY_TOKEN" | docker login -u $EDGE_CLUSTER_REGISTRY_USERNAME --password-stdin $IMAGE_ON_EDGE_CLUSTER_REGISTRY```

**Comment by LiilyZhang** [comment]
Bruce is able to install agent with microk8s image registry. Closed
