### ISSUE TITLE
geth does not work when time is not synced.

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#180]
If the system time for a rpi is different from the real time (ntp server time), geth could not peer and did not work.  Here is one example:
The daemon.log usually starts with `March 22` dates and then switch to the real dates in the middle. (I have not found out a pattern yet comparing different daemon logs). But for all the daemon.log I have seen, anax and geth started after the date got changed to real date. However for today's flashbot error node node1.1705, the anax and geth started on the `March 22` dates instead of real `April 18` dates.  geth downloaded all the blocks and then post a message like this:
```
Mar 22 20:40:25 horizon-000000006606d73d workload-bluehorizontest_geth[1292]: GETH: geth_process: I0322 20:40:25.221617 miner/worker.go:430] We are too far in the future. Waiting for 636h56m9s
```
It then went into loops doing nothing. It still did nothing after the date switched to `April 18`. The peer count was 0.
According to @datajerk blockchain will not work if date is off by too much. ethereum will not peer if date is wrong, we need a way to query ntp to verify that date has been updated.  the problem with these sbcs is no RTC.

**Comment by bmpotter** [comment]
Issue moved to [open-horizon/ubuntu-classic-image #17](https://github.com/open-horizon/ubuntu-classic-image/issues/17) via [**ZenHub**](https://www.zenhub.com/)
