### ISSUE TITLE
Multiple agbots cause model routing failures

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1823]
This problem was introduced in the Jan 2020 change to ./agreementbot/policy.go in issue #1308.

Multiple agbots step on each others handling of model policy changes, occasionally causing models to be removed from nodes. Externally, the symptom is that when a model is added to the system, it is delivered to some of the eligible nodes, but not all. Most of the time, it will be delivered to all nodes, but the behavior is random. I hit it once in 10 times or so.

To test this, make sure you are testing in an environment with multiple agbots.
- hzn mms object new > model.json
- update the model.json to refer to a service that you have running on at least a handful of nodes. You do not need to add any properties or constraints, just the service reference is enough.
- hzn mms object publish -m model.json -f <some file - any file>
- hzn mms object list -t <model type you put into model.json> -d
- was the object delivered to all nodes?
- hzn mms object delete -i <model id from model.json> -t < model type from model.json>
- you might have to issue the delete twice if the model objects are not actually read in by the service you specified in model.json.
- repeat the above starting with step 2 - you can add more than 1 service ref, you can specify constraints and remove them. The hzn mms object list -t <type> -d should always be accurate (depending of course on the change you made)

**Comment by LiilyZhang** [comment]
verified by Jon
