### ISSUE TITLE
Eliminate frequent meaningless error msgs in syslog

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#183]
These 2 error msgs are frequent and syslog treats them as errors so they are displayed with a bright red background:

```
Apr 20 06:53:25 mnode2-2 dockerd[28745]: time="2017-04-20T06:53:25.192301000Z" level=error msg="Handler for GET /containers/3d7bc7d710db2a78336c3c115eb78afbd3f54b25fd54ebec09167d6f5f1b3da7/json returned error: No such container: 3d7bc7d710db2a78336c3c115eb78afbd3f54b25fd54ebec09167d6f5f1b3da7"

Apr 20 06:53:28 mnode2-2 snap[112999]: 2017/04/20 06:53:28 14a47108d2bcc3bfd2f6c1eec16074f4aa9833be: all trackers failed
```

They should be eliminated, or at least made informational and without words like "error" and "failed". Even if they aren't coming from anax proper. For example, can the docker msg be avoided by checking to see if the container is there before trying to delete it?

**Comment by michaeldye** [comment]
The only part of this that is relevant to anax is standard golang logger messages from libraries (like this one about torrent trackers). We don't use the standard lib's logger but libs we use do; unfortunately, this logger doesn't have the granular control we get from our preferred logger, glog. But I think I have a mechanism for selectively disabling it in code:

```
// optionally silence native log package messages (like from libs)
  logNative := os.Getenv("LOG_NATIVE")
  if logNative == "" {
    log.SetOutput(ioutil.Discard)
  } else {
    glog.Infof("golang native logging not silenced")
  }
```

I haven't tested this, but it may be worth pursuing.

**Comment by bmpotter** [comment]
On the 1st msg (docker container not found) who is the instigator that results in that msg? I assumed it was anax requesting a removal of a docker container when it was already gone. Is it something else instead?

**Comment by bmpotter** [comment]
We are attacking this 1 at a time
