### ISSUE TITLE
agent-install fails if no cert file is present

### ISSUE THREAD

**Issue by cgiroua** [open-horizon/anax#1832]
If an installation was run in the same location previously, the `agent-install.crt` file is moved out of the current location.

On a subsequent run it will fail to move the cert (because it's no longer there):
```
+ sudo mv agent-install.crt /etc/horizon/agent-install.crt
mv: cannot stat 'agent-install.crt': No such file or directory
```

We should do a check to see if it's there, if so move it and if not just continue on.  If it's never there in the first place (and never moved) it will likely fail later on ... but I think that's OK.

**Comment by linggao** [comment]
@cgiroua if the cert file does not exist, continue without the cert? Set the cert file name to empty?
