### ISSUE TITLE
Deleting the last deployment policy causes the agbot to not pickup a new one

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1833]
New policies being ignored is due to several problems that can occur when cleaning up a deleted deployment policy. The agbot keeps a cache of deployment policies. When the last policy in an org is deleted, the org needs to remain in the cache so that new policies can be added to the org. Also, when the last policy is deleted, it needs to be removed from the cache (like all the others), so that if it is re-added (but is exactly the same as it was when it was deleted), the cache will detect that it is new.

A regression test of this fix would include add/update/delete deployment policies along with verification that agreements are being formed when the policies allow it.

**Comment by dlarson04** [comment]
Verified in agbot build 2.26.12
