### ISSUE TITLE
[BUG] agent-install.sh calls a deprecated apt package for docker when installing docker

### ISSUE THREAD

**Issue by omega2733** [open-horizon/anax#1834]
Summary:
When running agent-install.sh and docker is not installed, agent-install.sh attempts to install it for you. When doing so it attempts to run `apt install -y docker-ce docker-ce-cli containerd.io` . These packages as either "not available" or "not found" and appear to be deprecated.

This causes agent-install.sh to fail to run and requires a user to manually install docker.

This issue was found on Ubuntu 18.04 and Ubuntu 16.04

Workaround:
I used a workaround which is **not** recommended by manually installing with `apt install -y docker.io`. This is not recommended because docker.io refers to an old docker installation and installation method (probably will be deprecated in future).

Solutions:
Two different solutions exist in terms of time commitment:

Short-term: Remove the installation for docker on linux and only check to see if docker is installed. If it's not installed have the customer manually install it (this presents automated install issues however). **Or** Have the customer configure the apt repositories from the below recommendation manually.

Optimal: Fix the installation process to set up the repository to point to the proper locations to pull the package using apt (steps 1-3 in the docs below). We would still use the same apt install command, but are currently missing the steps today to setup the repository that apt pulls from.

Link to supported docker installation methods: https://docs.docker.com/engine/install
Ubuntu Install: https://docs.docker.com/engine/install/ubuntu/

Logs:
`root@agent-install-docker-test1:~# apt install -y docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Unable to locate package docker-ce-cli
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
root@agent-install-docker-test1:~# apt install -y containerd.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'`

**Comment by bmpotter** [comment]
Jon,

I'm confused by your description above. According to the ubuntu docker install instructions you linked to above, the `apt install ...` cmd the script is already using is the correct one. The only thing missing is adding the correct apt repo via:

```
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
```

**Comment by t-fine** [comment]
^^ these two lines are what I was planning to add, though I may just have to include a couple checks to figure out if it's ubuntu, Debian or raspbian since all those installs use the same `install_linux( )` function

**Comment by linggao** [comment]
The fix for this release it to prompt the user that docker is not installed, ask them to install it. Then exit. This is what the edge cluster path is doing currently.

Troy's PR: https://github.com/open-horizon/anax/pull/1836

**Comment by bmpotter** [comment]
Ling,

You don't actually mean "prompt", right? Just give an error msg that docker isn't installed and they should install it and try again. Then exit.

**Comment by linggao** [comment]
Right, just give an error and ask them to install docker and try agent-install again.
