### ISSUE TITLE
Modify agbot /status route to avoid Exchange API call to get version

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#1840]
Liveness and readiness probes call the agbot /status api which then calls the exchange api to get the exchange version. If the exchange is under heavy load this might cause the agbot pods to get killed if the liveness probes fail. 

Avoiding this call into the exchange would prevent the agbot from incorrectly restarting

**Comment by linggao** [comment]
Since issue #1873 will cache the exchange version, getting the exchange version will not hit the exchange if the version stays the same. We will move this issue to Review/QA pipeline.

**Comment by MaxMcAdam** [comment]
Verified in scale testing
