### ISSUE TITLE
hzn exchange version -v fails with a "No such host message"

### ISSUE THREAD

**Issue by bfawcett** [open-horizon/anax#1842]
I recently attempted to switch my macbook from a device on one 4.0 EAM to another 4.0 EAM instance.

But I get the following error:

**_hzn exchange version -v_**
[verbose] Reading configuration file: /usr/local/etc/horizon/hzn.json
[verbose] Reading configuration file: /etc/default/horizon
[verbose] Reading configuration file: /Users/bfawcett/.hzn/hzn.json
[verbose] No project level configuration file found.
[verbose] The exchange url: https://icp-console.apps.streams-ocp-43-1.os.fyre.ibm.com/ec-exchange/v1
[verbose] GET https://icp-console.apps.streams-ocp-43-1.os.fyre.ibm.com/ec-exchange/v1/admin/version
[verbose] HTTP request timeout set to 30 seconds

**_Error: Can’t connect to the Horizon Exchange REST API to run GET https://icp-console.apps.streams-ocp-43-1.os.fyre.ibm.com/ec-exchange/v1/admin/version. Maybe HZN_EXCHANGE_URL is set incorrectly? Or unset HZN_EXCHANGE_URL to use the Exchange that the Horizon Agent is configured for. Specific error is: Get https://icp-console.apps.streams-ocp-43-1.os.fyre.ibm.com/ec-exchange/v1/admin/version: dial tcp: lookup icp-console.apps.streams-ocp-43-1.os.fyre.ibm.com on 192.168.1.1:53: no such host_**

The unknown host (icp-console.apps.streams-ocp-43-1.os.fyre.ibm.com) is pingable, and running the curl equivalent of the hzn exchange version command also works.

```
ping icp-console.apps.streams-ocp-43-1.os.fyre.ibm.com                              
PING icp-console.apps.streams-ocp-43-1.os.fyre.ibm.com (9.30.117.219): 56 data bytes
64 bytes from 9.30.117.219: icmp_seq=0 ttl=52 time=120.307 ms
```

```
curl -sS -k -u icp-1/$HZN_EXCHANGE_USER_AUTH https://icp-console.apps.streams-ocp-43-1.os.fyre.ibm.com/ec-exchange/v1/admin/version            
2.12.3
```

also, running hzn in the container also works.
```
docker exec -it horizon1 hzn exchange version -o nbg                                            
2.12.3
```

As a work-around for the problem, the following mapping was added to the /etc/hosts
9.30.117.219 icp-console.apps.streams-ocp-43-1.os.fyre.ibm.com

**Comment by linggao** [comment]
Adding the ip in /etc/hosts is needed.
