### ISSUE TITLE
hzn deploycheck on an edge cluster doesn't pick up that it is a cluster by default

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#1844]
Running deploycheck on a cluster but not specifying the node doesn't pick up the fact that it is a cluster. 
```
[agentuser@agent-5cb99897bb-xckh9 ~]$ hzn deploycheck policy -b "mycluster/ibm.operator_1.0.0" -u "${HZN_EXCHANGE_USER_AUTH}"
Neither node id nor node policy is specified. Getting node policy from the local node.
Error: The input node type 'device' does not match the node type 'cluster' from the node mycluster/qa-test-cluster3.
```

specifying the `-t cluster` option is needed to make this work.

Other commands like `hzn register` automatically pick up the fact that it is a cluster and not a device.

**Comment by sirotsinskuy** [comment]
Working on it. @joewxboy please assign this issue to me
