### ISSUE TITLE
Intermittent OOM with 1000's of business policies

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#1849]
I think I found the cause of the OOM in the agbot with 1000's of policies.
This is the last thing in the log
```
Jun 4 12:42:55 ibm-edge-agbot-666cf46796-sm9b4 ibm-edge-agbot info I0604 16:42:55.252654       8 policy.go:199] Exchange RPC getting business policy for mycluster 
```
but I actually think it might be the call to rpclogString or Sprintf that is causing the OOM
```
glog.V(3).Infof(rpclogString(fmt.Sprintf("found business policy for %v, %v", org, pols)))
```
 especially if multiple agbot threads are building this big string concurrently.
glog actually truncates long strings and you see

```
 (cut off, too long...)
```
at the end of long strings but we are building the long string.
I think it could occur about >  2000 policies and it is intermittent

Might need to check the length of the map prior to printing out the log message or maybe only print out the length of the map in the log message.

Might need to think about how to request all the business policies from the Exchange when there are 10k or 20k policies or higher

Steps to reproduce
- Have 80 or so churner agents that register, get agreements, and then unregister
- After each iteration add 250 more policies
- repeat

After the OOM, the agents continued to get agreements so things didn't implode after the agbot restart

**Comment by dlarson04** [comment]
`func GetPatterns` in rpc/pattern.go has the same type of log message so that should be changed too if the log message is what causes the OOM.

**Comment by linggao** [comment]
Feature 1864 will handle it.

**Comment by linggao** [comment]
I will change the it to display the policy only when there is 1 policy in the response. If the length is greater than 1, it will only display the length of the map.  Will do the same for GetPattern().
The question is how are we sure the OOM is from the log?

**Comment by dlarson04** [comment]
As I mentioned, the last thing I see in the log is 
```
Jun 4 12:42:55 ibm-edge-agbot-666cf46796-sm9b4 ibm-edge-agbot info I0604 16:42:55.252654       8 policy.go:199] Exchange RPC getting business policy for mycluster 
```
When I get a new build I can repeat the steps I used above to verify the OOM doesn't happen
