### ISSUE TITLE
horizon-container stop could not delete socat that was brought up by root during the agent-install

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1851]
Install horizon 2.26.11 on mac using agent-install script. (sudo was used to run agent-install.sh). 
Agreements formed and services are running.
Then run `horizon-container stop` and saw the following error:
````
# horizon-container stop
Unregistering the node, then stopping/removing the horizon container (this may take a minute)...
horizon1
horizon1
horizon1_var
horizon1_etc
Killing socat PIDs: 26092...
/usr/local/bin/horizon-container: line 91: kill: (26092) - Operation not permitted
Error: exit code 1 from: kill socat
````
This error does not affect the function, it just say that the socat could not be killed. The socat will be reused next time user run `horizon-container start`.

This error is because that the socat was brought up by root during the agent install. A non root user cannot kill it.

**Comment by sirotsinskuy** [comment]
@joewxboy Working on it

**Comment by sirotsinskuy** [comment]
I checked this and the issue seems to be fixed by https://github.com/open-horizon/anax/commit/ce02b82ae7b99c609944f4c584fac444ef7e7dbf#diff-d0a30491b014375ddd302ac5aea356ceR91-R96 lines. 
It calls the `kill` command with `sudo` if killing of socat was unsuccessful.
