### ISSUE TITLE
Change edgeNodeFiles.sh to read in tar file of only the deb pkgs

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1853]
In 4.0, `edgeNodeFiles.sh` read the PPA tar file (via the `-p` flag, or default) and pulled the pkgs of the correct arch/distro from a directory in there. In `4.1` within the PPA tar file there will be a tar file called `horizon-edge-packages-4.1.0.tar.gz` that will container the deb pkgs. (The `horizon-edge-packages-4.1.0.tar.gz` will have a directory within it called `horizon-edge-packages-4.1.0`). So the work items are:

- [x] Update the usage explaining the `-p` flag
- [x] Change the default value of `PACKAGE_NAME` to `horizon-edge-packages-4.1.0`
- [x] Change the tar extract lines to look like: `tar --strip-components 5 -zxvf $PACKAGE_NAME $PACKAGE_NAME/linux/raspbian/stretch/armhf` (Note the strip-components value is 1 less)
- [x] Update the "Gather ..." KC doc for using `edgeNodeFiles.sh`

**Comment by t-fine** [comment]
on this page... rename the section following section (devices -> **nodes**)
https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.1/hub/offline_installation.html#prereq_horizon

Gather the necessary information and files for edge nodes
---------------------------------------------------

change:
"Several files will be needed to install the IBM Edge Application Manager agent on your edge devices and register them with IBM Edge Application Manager. This section will guide you through gathering those files into a tar file, which can then be used on each of your edge devices."

to:
"Several files will be needed to install the IBM Edge Application Manager agent on your edge nodes and register them with IBM Edge Application Manager. This section will guide you through gathering those files into a tar file, which can then be used on each of your edge nodes."


change:
"It is assumed that you have already installed the cloudctl and kubectl commands, and extracted ibm-edge-computing-4.1.0-x86_64.tar.gz from the installation content, as described earlier in this page."

to: 
"It is assumed that you have already installed the **cloudctl** and **kubectl** commands, and are still in the **ibm-edge-computing-4.1.0-x86_64** directory as described earlier in this page. This script will look for the required deb packages in the **horizon-edge-packages-4.1.0.tar.gz** file."

-----------------------

the command in **step 2** should be change to:
```
curl -O https://raw.githubusercontent.com/open-horizon/anax/v4.1/agent-install/edgeNodeFiles.sh
chmod +x edgeNodeFiles.sh
```

-------------------------------

update **step 3** to the following:

3. Run the edgeNodeFiles.sh script to gather the necessary files:
```
./edgeNodeFiles.sh <edge-node-type> -t
```

-----------------------

under **step 3** in the **Command arguments** section:

update **Supported values** to the following:
Supported values: **32-bit-ARM** , **64-bit-ARM**, **x86_64-Linux**, **macOS**, or **x86_64-Cluster**

add the following flag descriptions:

**-p**: the horizon deb package bundle name. Default is **horizon-edge-packages-4.1.0**, which means it will look for **horizon-edge-packages-4.1.0.tar.gz** and expects a standardized directory structure of **horizon-edge-packages-4.1.0/<PLATFORM>/<OS>/<DISTRO>/<ARCH>**

**-s**: storage class used on the edge cluster. Default is **gp2**. Only applies for node type **x86_64-Cluster**.

**-I**: docker tag (version) of agent image to deploy to edge cluster. Only applies for node type **x86_64-Cluster**.

**-o**: the exchange org id that should be used on the edge node. Currently on used for node type x86_64-Cluster.

**-m**: the edge cluster namespace that the agent will be installed into. Default is **openhorizon-agent.** Only applies for node type openhorizon-agent.

------------------------

update step 4 to the following:
4. The command in the previous step will create a file called **agentInstallFiles-<edge-node-type>.tar.gz**. If you have additional types of edge nodes (different architectures or if it for a cluster), repeat the previous step for each type.

**Comment by Rene-Ch1** [comment]
Doc update was made and approved.
