### ISSUE TITLE
Pre-signed services can't be published

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1858]
Pre-signed services already have the `deployment` and/or `clusterDeployment` fields flattened into an escaped json string, and `deploymentSignature` and/or `clusterDeploymentSignature` already filled in.

In `cli/exchange/service.go` function `SignDeployment()` deals with pre-signed services correctly. But then around line 250 in `SignAndPublish()` it tries to read the deployment field to get the list of images to remind the user to upload them. This section needs to be skipped if this is a pre-signed service. It is valid to skip it in that case, because it is valid to assume that if the service was already signed, the image was uploaded at that time.

Also, add at least 1 e2edev test for a pre-signed device service and 1 test for a pre-signed cluster service, so this doesn't get broken in the future.

This support is needed for the [loadResources utility](https://github.com/open-horizon/examples/blob/master/tools/loadResources)

**Comment by lichristina118** [comment]
Please assign this to me.

**Comment by lichristina118** [comment]
I tested a service with presigned deployments and it works for me. 
````
{
  "userdev/mytest2_1.0.0_amd64": {
    "owner": "userdev/userdevadmin",
    "label": "Netspeed for x86_64",
    "description": "Netspeed service",
    "documentation": "",
    "public": true,
    "url": "mytest2",
    "version": "1.0.0",
    "arch": "amd64",
    "sharable": "multiple",
    "matchHardware": {},
    "requiredServices": [],
    "userInput": [],
    "deployment": "{\"services\":{\"netspeed\":{\"image\":\"openhorizon/amd64_cpu:1.2.2\"}}}",
    "deploymentSignature": "MjEZ7X2kSw77t2qIiemGTSJlMJUSgMxBsooj5Z5R9iPCfgPQtlCuS8syO+BonL1bArNgrqSRYrZ3BPn2q9amkO4XLC9U7KIlW0orRiDyGtLB8OOmH/s8RdznbxzArg8EKTOZdPf4FSII28tYph9eEbcU7EtJmxjp0ePf2fwJwV8ghDwW365Dizw5IagxT6FytMVrsya6UyclEcl296xZuL2uKgsavAsAaKYZ5Q8PcqvwUXcJ1YfpvlR26bEhnwWXQDVMkHdVxRNmgZo7vCyOU67u17YbVDNkurYz8l7K30JE8Aml6AB7z7IHcJDm5vZaMcEvgtkfKZ4RL4HhCURpwGEqaRH1mb22ErNihiZgQJzLiWPuKcrA9kZm0mdZKoTtlajW5kAeFpZt2ySEVxei8PHTsfU5rrnhvbO6noGZLD0CPjRVHkisusIFyFI3ur/yDqGns05dCgckjAjOSamJ157Ps9XME8CLSBSQAdYKcE1P+OAeqZWEFlf3l75GRvPbxIgaHcIbnWfOc1TCDYLjgWLKNVavZIjutrerDgEvlBEtXj/jLPhVjtqoOwrh2xagtlDCqimC6KxBRA477UIDzDHZQcss8H6LLBc9qJOfcjxCLc+Mh6/18SMvK17qTVTSfnrJzO8lW+hLwk2/65D1DUDOMVAYFLidAAPhLojsms0=",
    "clusterDeployment": "{\"operatorYamlArchive\":\"H4sIAPWCxl4AA+1Z3W/bNhDPc/4KIn0IMMySZflj0JuXZluxtjGcoHsMaIm2uVKiRlLu3GH/+47U...",
    "clusterDeploymentSignature": "uN3kJ6nJVu2DXljw67KG9oKjElmfJlqxq/ogONsa1mKIP8iajfccpVnNjUk+8hV5svjWCjw0RrdPMQ3yGZj0cmO7SU1ETEvzM/x2gX+wNjuXCmXmtP6TqGPQTIUzggVygeLxDHBghw6MU8zHTjxn31JlZWWa9HZg5nfFQd4j0ygkCQCqI7MHxjSm/c9xA4zwpIywJnB8Xy6o3XmBorkbHGxH0Ez0d2yKfjjyWXqHxSq77rFr5fpZbdSBx9dafLpk6p1voVgF+F+PoeMUFzsKJNZY9R49XPoN+9dH3737lcxnQY6FQ9jo5Jijp1AYV4xjLUQy9s0n3NxnlzaxpqAyZWbj9aSYNjmjcQ2t893+H7VQLEr5SCNWfzb9jg+8NMybw0ma0Slxhl/kZlJDfRdTvG933kcgh3kaoI3OCDoaGEaAph+kLaHosROs3A3ahnCwX1ZkBR3rgqy3C4syLCxTvjW0TFVFiAQKyL7evNAFfVmrDKi0/OVOB01UvfjfHVet8ZHzSWL0YZTxuyiGViZb+ZmmImdv4WSrsfzi8+NQUSXip26eKFdmeT1h2/c91OOpS4Fg/7JmuJ7fg1qx4Wjxs9bDp2rv8PmvKU5dWSLDfhntvh7LIeAjzA73/uutRwbByGo0SENQ7chdt+7MJBR7omD5obP102ue3JTGFKR1qZE=",
    "lastUpdated": "2020-06-09T14:31:54.575Z[UTC]"
  }
}
````

**Comment by bmpotter** [comment]
By pre-signed, i really meant a service that has already been published to a different org. In those cases the `deployment` field usually looks like this:

```
"deployment": "{\"services\":{\"ibm.helloworld\":{\"image\":\"openhorizon/ibm.helloworld_amd64@sha256:22385b100ee71e746a04205beb022c0c51ff29aa1d7d846840c6a2b2c30483cf\"}}}"
```

So try listing a service from the IBM org, removing the `owner` and `lastUpdated` fields, and publishing it to another org.

For reference, this is what [loadResources](https://github.com/open-horizon/examples/blob/master/tools/loadResources) does, and what i need to have work. Thx.
