### ISSUE TITLE
"hzn service log" does not accept fully-qualified service name

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#1860]
Fully-qualified service names include the org ID.
For example,
`hzn service log orgid/servicename`
will error with:
`Error: Service orgid/servicename is not running on the node.`
while just using servicename without the org ID works:
`hzn service log servicename`

**Comment by lichristina118** [comment]
Please assign to me.

**Comment by lichristina118** [comment]
PR https://github.com/open-horizon/anax/pull/1872

**Comment by edeediong** [comment]
@TheMosquito don't you think this issue should be closed since @lichristina118 finished it off on #1872

**Comment by TheMosquito** [comment]
@edeediong That's a question for the development team. I just reported the bug. :-)
