### ISSUE TITLE
Agbot reduce the number of calls to the exchange

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1873]
Reduce the number of calls to the exchange. Investigate the agbot log to find multiple calls to the exchange for the same thing and start caching that thing. Start with the protocol worker threads and especially the InitiateNewAgreement function in agreementbot_worker.go. Service Defs is a great example, service policy, node, node policy, maybe more. I want it implemented so that calls to the functions in the exchange package, e.g. ./exchange/service.go: GetService() will start using the cache and callers of those functions are unchanged.

**Comment by MaxMcAdam** [comment]
- [ ] Create cache and functions to get/put/delete
    
- [ ] Cache service definitions and get service defs from cache 

- [ ] Handle changes to service defs

- [ ] Cache exchange nodes and get exchange nodes from cache

- [ ] Handle changes to exchange nodes

- [ ] Unit test all added code

- [ ] Cache exch version

- [ ] Timeout exch version cache

**Comment by MaxMcAdam** [comment]
Scale test results from Doug 
"29 business policies and registered 75 agents… then modified the business policy so that all agents had to renegotiate"
agbot v2.26.12 - 127,000 calls from agbot
your version - 56,000 calls from agbot

**Comment by MaxMcAdam** [comment]
- [ ] cache node policies

- [ ] handle node policy changes

- [ ] cache service policies

- [ ] handle service policy changes

**Comment by MaxMcAdam** [comment]
Verified in scale testing
