### ISSUE TITLE
Re-design sync service ACL module and apply the new authentication in anax

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1882]
Ensure ACLs can be configured to allow nodes and users to access(read-only/write) only certain objects in the CSS

This issue includes changes in sync service and anax:

1. Sync service (step 1):
- [x] Will need to modify the current design of ACL module, so that each username will also have the type (node/user) and role(aclWriter/aclReader) assoiciated with it. Database changes affect both mongo and boltdb.
    - [x] mongo
    - [x] boltdb
- [x] Object ACL: Retrieve and update objects will based on the role defined in ACL. 
- [x] Destination ACL: will only use leverate ACL type and username. ACL role is not applicable 
- [x] Add security/authentication support for exchange node authentication
- [x] ACL APIs needs to be revisited.
- [x] CSS/ESS communicaton module needs to be updated since the change of ACL entry 
- [x] unit-test

2. Anax (step 2):
- [x] enable to use exchange nodeId/nodeToken in hzn authenticator (The related issue to populate CSS with agent pkgs and config files: https://github.ibm.com/Edge-Fabric/edge-computing/issues/125)
- [x] change to use exchange user auth instead of grant all user to sync service `admin` access in hzn authenticator
- [x] add test in e2edev

3. Docs
https://ibm.ent.box.com/notes/711442189679

**Comment by LiilyZhang** [comment]
Updates on requirements:
Some of the objects need to be retrievable by all users in any org, which is public object. To enable this, a new boolean field `Public` will be introduced to object metadata. Sync service also need to consider this in security class.

- [ ] add `Public` field to object metadata
- [ ] update the `security.go` to allow user with different org
- [ ] update APIs to user new security function. Filter results based on the `Public` field (if the returned results is list of objects)
- [ ] tests (sync service/anax)
