### ISSUE TITLE
docker network bridge not needed if "network:host" is set on the service

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#1892]
According to https://github.com/open-horizon/anax/blob/master/doc/deployment_string.md

the variable

```network: "host" - start the container with host network mode. When network is set to host, the service can only be deployed to nodes with property openhorizon.allowPrivileged set to true.```

enables the workload to run with the docker run param `--net=host` option. 

I noticed, though, that when I create a container manually with 
`docker run --net=host -d --name my-helloworld2  openhorizon/ibm.helloworld_amd64:1.0.0` myself, there is not a docker network bridge created but when I deploy a service that has `network:host` set, a network bridge is still created. In both the manual test and the IEAM service, neither container got an IPv4 address which is correct. 

It seems that the creation of the docker bridge is not necessary in the case where the service is going to run with `network:host`

**Comment by sirotsinskuy** [comment]
@joewxboy Working on it
