### ISSUE TITLE
Agreement created and terminated continuously if openhorizon.allowPrivileged changed to  "true" in UI

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#1901]
User reported this in edge users slack channel and I was able to recreate it on my ubuntu environment.  The agent is the one that continuously terminates the agreement

Search agent log for agreement 63d2141b294d8c15c5b24fd61258074b1e07c2ec725d64af88b131c80e2a9451

[ubuntu-16-horizon0_agent.log](https://github.com/open-horizon/anax/files/4897184/ubuntu-16-horizon0_agent.log)
[ibm-edge-logs-jul09.zip](https://github.com/open-horizon/anax/files/4897192/ibm-edge-logs-jul09.zip)

To fix:
- [ ] UI will make sure that the openhorizon.allowPrivileged will be passed as boolean
- [x] anax will verify the build-in property values in the node policy when syncing with the exchange. It will replace the built-in properties that has the wrong types with the default values in general. But it will take the string value and convert it into the correct type if the value can be converted. For example, change "true" or "false" into a boolean.

**Comment by dlarson04** [comment]
When I updated this property from the node with `hzn exchange node updatepolicy --json-file file $node 

I lost the property (horizon_model_100) I initially registered with... I went from

```
{
  "properties": [
    {
      "name": "horizon_model_100",
      "value": 2000
    },
    {
      "name": "openhorizon.hardwareId",
      "value": "fdaf85b3a739b806c5d1c4fe32744fdfe526115e"
    },
    {
      "name": "openhorizon.cpu",
      "value": 1
    },
    {
      "name": "openhorizon.arch",
      "value": "amd64"
    },
    {
      "name": "openhorizon.memory",
      "value": 3951
    },
    {
      "name": "openhorizon.allowPrivileged",
      "value": false
    }
  ]
}
```

to 
```
{
  "properties": [
    {
      "name": "openhorizon.allowPrivileged",
      "value": true
    },
    {
      "name": "openhorizon.hardwareId",
      "value": "fdaf85b3a739b806c5d1c4fe32744fdfe526115e"
    },
    {
      "name": "openhorizon.cpu",
      "value": 1
    },
    {
      "name": "openhorizon.arch",
      "value": "amd64"
    },
    {
      "name": "openhorizon.memory",
      "value": 3951
    }
  ]
}
```

when my update json file looked like:
```
{
   "properties": [
     { "name": "openhorizon.allowPrivileged", "value": true}
  ]
}
```

so with this new node policy, I won't get a new agreement but the old agreement was canceled
```
root@ubuntu-16-vis-larsond:~# hzn eventlog list
[
  "2020-07-09 11:09:34:   Start node configuration/registration for node ubuntu-16-vis-larsond_horizon0.",
  "2020-07-09 11:09:34:   Complete node configuration/registration for node ubuntu-16-vis-larsond_horizon0.",
  "2020-07-09 11:09:56:   Node received Proposal message using agreement 3206f550542eb5ffe28a8fa752d012598cf95f477548bc6a37b0187be0bf6e69 for service dominion/perfhznmodel100.helloworld from the agbot IBM/dominion-agbot.",
  "2020-07-09 11:09:56:   Node received Proposal message using agreement 729a08a710ea0d93476a24c36d67e3f208cfafed4fa8541e9c423c83502d9b1a for service dominion/perfhznmodel100.helloworld from the agbot IBM/dominion-agbot.",
  "2020-07-09 11:09:57:   Agreement 3206f550542eb5ffe28a8fa752d012598cf95f477548bc6a37b0187be0bf6e69 already exists, ignoring proposal: perfhznmodel100.helloworld",
  "2020-07-09 11:10:06:   Agreement reached for service perfhznmodel100.helloworld. The agreement id is 3206f550542eb5ffe28a8fa752d012598cf95f477548bc6a37b0187be0bf6e69.",
  "2020-07-09 11:10:07:   Start dependent services for dominion/perfhznmodel100.helloworld.",
  "2020-07-09 11:10:07:   Start workload service for dominion/perfhznmodel100.helloworld.",
  "2020-07-09 11:10:07:   Image loaded for dominion/perfhznmodel100.helloworld.",
  "2020-07-09 11:10:08:   Workload service containers for dominion/perfhznmodel100.helloworld are up and running.",
  "2020-07-09 11:20:39:   Node policy updated with the Exchange copy: map[properties:[map[name:openhorizon.allowPrivileged value:true] map[name:openhorizon.hardwareId value:fdaf85b3a739b806c5d1c4fe32744fdfe526115e] map[value:1 name:openhorizon.cpu] map[name:openhorizon.arch value:amd64] map[value:3,951 name:openhorizon.memory]]]",
  "2020-07-09 11:20:39:   Start terminating agreement for perfhznmodel100.helloworld. Termination reason: node policy changed",
  "2020-07-09 11:20:40:   Complete terminating agreement for perfhznmodel100.helloworld. Termination reason: node policy changed",
  "2020-07-09 11:20:40:   Workload destroyed for perfhznmodel100.helloworld"
]
```

**Comment by linggao** [comment]
@dlarson04 the update file is not right. It should contain all the old and new attributes and constraints. The `hzn policy update -f <input file>` command is actually a 'replace' command. It will replace the node policy with the one from the input file.

**Comment by dlarson04** [comment]
Ling is correct... user error on my part.

I tried the `hzn policy update` command and did not hit the same issue with continuously canceling agreements.

Also, I did `hzn -v policy patch '{"properties": [ { "name": "openhorizon.allowPrivileged", "value": true} ] }'` and that did not cause the issue either

**Comment by linggao** [comment]
I got it reproduced.  The problem is that the UI sets openhorizon.allowPrivileged to string  "true" instead of boolean true , UI needs distinguish from string, number and boolean for a property attribute in a policy.

**Comment by linggao** [comment]
UI has not fixed the problem yet.
