### ISSUE TITLE
Test anax on Ubuntu 20.04

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1902]

**Comment by dcmartin** [comment]
I have installed Ubuntu20 on a VirtualBox VM with 8 GB RAM and 4 vCPU and built anax and run the following test:

**Comment by dcmartin** [comment]
Working on Ubuntu20 according to test suite

**Comment by linggao** [comment]
I reopened it because it is a reminder for me to add the test case to out test plan.
