### ISSUE TITLE
hzn mms object download does not handle existing file correctly

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1903]
When i tried to download an mms file when the file name already existed, i got:

```
$ hzn mms object download -t stuff -i mms-file -f mms-file.downloaded
Error: Failed to create file: 
```

At the very least the error msg should say the file already exists (and give the file name in the msg). But it would also be good to provide an overwrite flag that would enable it to replace the file. (Don't add a prompt.)

**Comment by MaxMcAdam** [comment]
Verified in 2.27.0-110
