### ISSUE TITLE
help for hzn dev commands is ... lacking

### ISSUE THREAD

**Issue by RobHigh** [open-horizon/anax#1904]
We really need better documentation and help on the hzn dev commands. At the least we need description for what each of the commands do. 

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/26487355/87234668-47349200-c3a1-11ea-905a-ca925da55382.png">

**Comment by RobHigh** [comment]
I found more details in the help-long option, but still ... a phrase for each command at the non-long level might be helpful

**Comment by dabooz** [comment]
Did you try hzn dev service --help or hzn dev service new --help? The help is contextual and the CLI framework we are using doesnt display help for subcommands when displaying help for the parent command.

**Comment by rajpratyush** [comment]
@dabooz is this issue still open for work??
