### ISSUE TITLE
Deprecate 'hzn policy patch' and 'hzn exchange node updatepolicy' commands

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1907]
The `hzn policy patch` and the `hzn exchange node updatepolicy` commands update the current node policy. They take one attribute ("properties" or "constraints") as input. If the input contains both attributes an error will be given. This causes a lot of confusion to the users.  These two commands will be deprecated. The user should use `hzn policy update` or `hzn exchange node addpolicy` commands when updating the node policy as a whole.

**Comment by MaxMcAdam** [comment]
Verified in 2.27.0-110
