### ISSUE TITLE
Check on /etc/default/horizon env variables values during 4.0 to 4.1 upgrade agent install on edge node

### ISSUE THREAD

**Issue by jiportilla** [open-horizon/anax#1919]
While helping a seller install 4.1 agent, he had an older 4.0 agent installed on his device.

The environment variables in `/etc/default/horizon` in 4.0 were 
```
HZN_EXCHANGE_URL=<console_url>/ec-exchange/v1
HZN_FSS_CSSURL=<console_url>/ec-css
```
in 4.1 those values changed to
```
HZN_EXCHANGE_URL=<console_url>/edge-exchange/v1
HZN_FSS_CSSURL=<console_url>/edge-css/
```
He did an upgrade using the agent install script. But the above env did not change in /etc/default/horizon. Please make sure that these new values are set in /etc/default/horizon.

**Comment by jiportilla** [comment]
per Ashok & Steve they both used the agentInstall.sh to upgrade to 4.1

**Comment by bmpotter** [comment]
The plan is to have `agent-install.sh` handle this properly as part of the work in https://github.com/open-horizon/anax/issues/1694

**Comment by bmpotter** [comment]
This case has been handled in `agent-install.sh` in #1694 . They just have to use the most recent version of `agent-install.sh`.
