### ISSUE TITLE
Document Policy Properties

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/anax#1929]
Beginning with the built-in properties, document from code what the policy file properties are, their potential values, and what they mean.  Add an md file to `./anax/doc/` named `policy.md` to document the built-ins. In the code they are in `./externalpolicy/builtin_properties.go`

**Comment by sirotsinskuy** [comment]
@joewxboy Working on it

**Comment by joewxboy** [comment]
We're actively migrating .md docs from ./anax/doc to ./anax/docs so go ahead and create the doc in the `docs` folder.

**Comment by joewxboy** [comment]
See also: https://github.com/open-horizon/open-horizon.github.io/issues/27
