### ISSUE TITLE
Container architecture specifications

### ISSUE THREAD

**Issue by dcmartin** [open-horizon/anax#1947]
What do we have in mind to address the architecture specifications of the services that are deployed by the agent?  For example, the `aarch64` value (from `uname -m`) for nVidia Jetson Nano is not the same as the `arm64` designation used by the agent; similarly, for the RaspberryPi there are both `armv6l` and `armv7l` values for various models, but only `arm` for the agent.  Perhaps some clarity with respect to these values would be of general utility.

**Comment by linggao** [comment]
In the anax config file, there is a section called `ArchSynonyms` that address this issue. 
````
    "ArchSynonyms": {
        "x86_64": "amd64",
        "armhf": "arm",
        "aarch64": "arm64"
    }
````
You can add `"aarch64": "amd64"` in both agbot and edge node anax configuration,  anax will treat `aarch64` node as `amd64` node.

**Comment by dcmartin** [comment]
How do synonyms apply to differing architecture?  That may be a solution for the same architecture with a different name, but not for different architectures, eg armv6l

**Comment by dcmartin** [comment]
Wht is the explicit list of architectures as defined in GOLANG?  The https://github.com/open-horizon/anax/blob/master/doc/service_def.md document only refers to a very long GOLANG document and does not explicitly list, including if there are distinctions for armv6, armv7, and armv8
