### ISSUE TITLE
Document metering smart contract so micropayments can be queried from the BC

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#196]
Assume they will be using the ethereum rpc.

**Comment by dabooz** [comment]
First Draft of document is here:
https://docs.google.com/document/d/1Z6AzXDLIFmwL-IP-EJTymiLGaKqLHItBGAJJSXslpeU/

**Comment by dabooz** [comment]
Delivered a pdf of the doc to Cameron Hunt at Sofwerx.
