### ISSUE TITLE
Can not make test under /anax/test/ folder on aarch64 platform (OS: CentOS 8.0-1905, aarch64)

### ISSUE THREAD

**Issue by hcliu0608** [open-horizon/anax#1960]
Hi Support, 

In anax/test folder would like to make test command but hang in the following message output

Bootstrapping the exchange
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.39
 Go version:        go1.13.10
 Git commit:        48a6621
 Built:             Mon Jun 22 15:46:22 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:23 2019
  OS/Arch:          linux/arm64
  Experimental:     false
Drop and recreate the exchange DB.

And we added some debug messages in anax/test/gov/ init_exchange.sh:39

 DBTOK=$(curl -sLX GET -u "root/root:${EXCH_ROOTPW}" "${EXCH_URL}/admin/dropdb/token" | jq -r '.token')
+++ echo "DBTOK="+${DBTOK}+"=END"+".EXCH_ROEXCH_RO="+${EXCH_ROOTPW}+"=END"+"EXCH_URL="+${EXCH_URL}+"=END"

and found the log likes this:
DBTOK=++=END+.EXCH_ROEXCH_RO=+Horizon-Rul3s+=END+EXCH_URL=+http://exchange-api:8080/v1+=END

maybe start exchange-api fail, so we make command docker ps -a and found these images exit.

openhorizon/amd64_cloud-sync-service          testing             bded38911df8        3 months ago        313MB
openhorizon/amd64_exchange-api                2.23.0              6fe7c5434c0c        3 months ago

#docker ps -a
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS                      PORTS                                                                    NAMES
17a21d9d7da2        openhorizon/e2edev-agbot:latest                "/bin/bash"              41 minutes ago      Up 41 minutes               127.0.0.1:8082-8085->8082-8085/tcp, 127.0.0.1:8510-8511->8510-8511/tcp   agbot
df3f4d63a555        openhorizon/amd64_cloud-sync-service:testing   "/usr/edge-sync-serv…"   44 minutes ago      Exited (1) 44 minutes ago                                                                            css-api
f6cb06f9bab8        mongo:4.0.6                                    "docker-entrypoint.s…"   44 minutes ago      Up 44 minutes               127.0.0.1:27017->27017/tcp                                               css-db
9d2479709691        openhorizon/amd64_exchange-api:2.23.0          "/bin/sh -c '/usr/bi…"   44 minutes ago      Exited (1) 44 minutes ago                                                                            exchange-api
bd6d839792e4        postgres:9                                     "docker-entrypoint.s…"   44 minutes ago      Up 44 minutes               5432/tcp                                                                 exchange-db
2c40f0022670        registry                                       "/entrypoint.sh /etc…"   44 minutes ago      Up 44 minutes               127.0.0.1:443->443/tcp, 5000/tcp                                         e2edevregistry
66ef47e10fb0        3ebfe6803190                                   "/bin/sh -c 'microdn…"   18 hours ago        Exited (1) 18 hours ago                                                                              elated_napier

Is it means that can not run on my platform?

OS: CentOS 8.0-1905, aarch64 
# uname -rm
4.19.81 aarch64

# cat /proc/meminfo
MemTotal:       11977484 kB
MemFree:         6628532 kB
MemAvailable:   10544688 kB

# docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:06 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:23 2019
  OS/Arch:          linux/arm64
  Experimental:     false

**Comment by dabooz** [comment]
The problem is that the management hub is not supported on any arch other than amd64, and there are currently no plans to change this. The embedded test environment (e2edev) is only supported on amd64. If you are trying to test a non-amd64 agent, then you should (a) find an amd64 linux machine and (b) use this process to start up the management hub: https://github.com/open-horizon/devops/blob/master/mgmt-hub/README.md
