### ISSUE TITLE
cluster agent failed to start the service pods if the operator is created with helm type

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1963]
The operator was created using 
````
operator-sdk new app-operator --type=helm \
  --api-version=app.example.com/v1alpha1 \  
  --kind=AppService \
  --helm-chart=myrepo/app 
````
The agent was able to create all the objects except the custom resource.
The agent's kube_operator worker cmd process hung while waiting for the customer resource to be created, because it was continually failing.
The operator pod was started but the service pods failed to start, because the operator was not fully initialized when the CR failed to be created.

The root cause is that the operator-sdk doesn't generate the spec.version field in the CRD yaml file. That field is optional, and the agent should compensate for this missing field. The versions list is present and can be used to figure out the correct version of the CR, allowing the CR to be successfully created.

**Comment by MaxMcAdam** [comment]
Verified in 2.27.0-123
