### ISSUE TITLE
hzn service log could not display with not existing path: /var/log/syslog

### ISSUE THREAD

**Issue by georgelee-foxconn** [open-horizon/anax#1967]
I had tried to install rpm of horizon and horizon client, and do register to management hub with sample hellowolrd service.
I would like to use the command to check whether the service is running or not. Here is the command and the response error:

Request: 
hzn service log -f ibm.helloworld

Response: 
Displaying log messages for service ibm.helloworld with service id 124b8714b56510d80f94aa5cbacbd1a2a0f2cfa0163a086df1d4771a02ad6a3e.
Use ctrl-C to terminate this command.
Error: /var/log/syslog could not be opened or does not exist: open /var/log/syslog: no such file or directory

1 I've tried in two different edge environments, x86 RHEL and arm64 CentOS.,both have the same response.
   And both environments do not have the path: /var/log/syslog
2. horizon-cli is built-up by project: anax/pkg/rpm.
3. ibm.helloworld is running and confirmed by command: docker ps

**Comment by georgelee-foxconn** [comment]
From the message in following link: https://github.com/open-horizon/anax/tree/master/pkg/rpm

The hzn service log command does not work correctly, so view the edge service output like this:
tail -f /var/log/messages | grep ibm.helloworld

It could be worked to check the status from /var/log/messages

**Comment by losdevnull** [comment]
So when agent launchs docker containers it always specifies `syslog` as docker log driver type.  However different linux dist has different default log file path for syslog.
We could enhance `hzn service log` to recoginize different linux dist and refer to the correct syslog file for container logs.
