### ISSUE TITLE
Migrate documentation from /doc to /docs

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/anax#1970]
In support of Documentation issue https://github.com/open-horizon/open-horizon.github.io/issues/29 we will:

1. Turn on github-pages for the anax repo ✅ 
2. Move .md files from /doc to /docs ✅ 
3. Add supporting _folders to anax repo under /docs to match site look-and-feel
4. Document steps needed to make that transformation and maintain going forward
5. Train developers on maintaining going forward

**Comment by dabooz** [comment]
Closing this issue as complete. The OH Documentation workgroup will own documentation tasks and strategy for OH doc updates from now on.
