### ISSUE TITLE
The `hzn version` command communicates with the exchange (it shouldn't).

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#1972]
The purpose of the `hzn version` CLI command is to determine the local agent version and the CLI version. Surprisingly this command also currently communicates with the exchange. This command should run purely locally (as I believe it used to be) -- i.e., interacting with the local agent but not with the exchange. This is especially important when there problems communicating with the exchange.

For example, recently after a new `agent-install.sh` for a 4.1 exchange instance on a very fast 96 CPU x86 server `hzn version` took over 2 minutes to return:

```
zen@zen:~$ time hzn version
Horizon CLI version: 2.26.12
Horizon Agent version: 2.26.12
real    2m4.521s
user    0m0.965s
sys     0m0.547s
zen@zen:~$ 
```

The purely local operation should take only seconds to run.

**Comment by linggao** [comment]
@dlarson04 yes, it calls /status under the cover to get the agent version. But the /status api returns a bunch of things including the exchange api. We may need a separate agent api just for the agent version.
