### ISSUE TITLE
Unicode Support inconsistent among different commands

### ISSUE THREAD

**Issue by jhespeter** [open-horizon/anax#1996]
**Describe the bug**
**hzn exchange org** commands could support Unicode successfully.
It could handle Unicode name Org create, list, update, and remove.
However, if we create a Unicode Org, then we won’t be able to register any node to it, because the node registration will be failed by Unicode Org name.

**To Reproduce**
1. Create a unicode name Org by command - hzn exchange org create -d "some unicode word" "unicode org name"
(Ex: hzn exchange org create -d "啊☆" "㐁ᠠﭖ")
2. Register any device node to the unicode Org by command - hzn register "the unicode org name" 
(Ex:  hzn register "㐁ᠠﭖ")
3. Observe the Failure & Error message displayed

**Expected behavior**
If Unicode is decided to be not supported, we should have clear error messages (and provide the allowed char set) for all commands/UIs when user trying to input an Unicode name & make sure the operation is not taking effect.
On the other hand, If Unicode should be supported, we should have all functions support Unicode. 
Or at least, clearly hint users about the functions that don’t support Unicode & make sure the Unicode supported parts won’t disable the not supported parts. 
(Ex: A Unicode name Org should also be able to get non-Unicode nodes registered. Assuming node registration won’t support Unicode name, but Org does.)

**Screenshots**
<img width="1258" alt="register node to Unicode Org" src="https://user-images.githubusercontent.com/5623182/91579212-dc094400-e97d-11ea-8a00-c4ee73398782.png">

**Build Level**
Horizon: 2.27.0-81
amd64_agbot:2.27.0-59.202008251412.ade4eb9d
amd64_cloud-sync-service:1.4.0-52.202008190414.7d45c489
amd64_exchange-api:2.38.0-82.202008190416.5ab01d6

**Comment by MaxMcAdam** [comment]
Verified in 2.27.0-110

**Comment by cdyq** [comment]
1.Can successfully register node with basic unicode 
![image](https://user-images.githubusercontent.com/25783969/96069661-4005ae80-0ed1-11eb-98f2-694eed8064bc.png)
![image](https://user-images.githubusercontent.com/25783969/96070053-041f1900-0ed2-11eb-9907-a807c6a54453.png)
2.Register node with a special unicode will failed. (eg:  hzn register -n abcＡＢＣ一丁七ÇàâｱｲｳДфэأبتثअइउ€¥)
@linggao 
2 points need you check when register node failed
i: The error message is not readable(Error initializing the node: {"error":"Value violates regex illegal char match: [^-*+()?\u0026! _\\w\\d.@,:/\\\\\\pL\\pN]","input":"device.id"}), maybe the error message could be displayed as something like "A-Za-Z0-9 is only allowed"
![image](https://user-images.githubusercontent.com/25783969/96071400-a5a76a00-0ed4-11eb-89bb-33ce50d1ee8b.png)

ii: Register node with special character failed and return to un-register status, but the node still display in ui page.
The node should be removed from ui when the node is unregister
![image](https://user-images.githubusercontent.com/25783969/96071556-fb7c1200-0ed4-11eb-9aa5-9fdf549294a1.png)

**Comment by cdyq** [comment]
@linggao 
1. failed to register node with some special characters. (eg: ☆ # )
2. failed to register node when the string contains space (eg: hzn register -n 에지 노드 추가 )

**Comment by linggao** [comment]
@cdyq thanks for the feedback. Anax does not support special character and strings with space for resource IDs.
