### ISSUE TITLE
agbot did not detect policy change after the workload priority was re-arranged.

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#202]
Changing the priority value for the workload in the agbot policy file and restart anax, the agbot did not detect the policy change.

**Comment by linggao** [comment]
Make sure to update the testcases

**Comment by dabooz** [comment]
Ling, I needed to fix this while testing issue164, so i have a fix for it in the PR that I am about to submit to you. Hopefully you havent started on it yet.

**Comment by linggao** [comment]
Built in revision 102 (arm) and 103 (x86), version 2.0.9.
