### ISSUE TITLE
'hzn dev service verify' failed to verify netspeed service

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2035]
To recreate it:
1. Create a project:
 `hzn dev service new -i myrepo/mytest_image -s mytest`, 
2. Run `hzn dev dependency fetch --url https://bluehorizon.network/services/netspeed -o IBM`
3. Run `hzn dev service verify`
You will get the following error 
````
Error: 'service verify' project does not validate. dependency IBM_bluehorizon.network-services-network2_1.5.0.service.definition.json did not validate, error: /usr/ling/hzn_dev/ling_newui/horizon/dependencies/IBM_bluehorizon.network-services-network2_1.5.0.service.definition.json: deployment configuration, deployment config map[] is not supported
````

This error does not happen if you have fetched the "weather" service.

**Comment by sirotsinskuy** [comment]
@joewxboy working on it
