### ISSUE TITLE
Agent-install.sh edge cluster fixes/improvements

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2040]
This issue records the `#lily:` comments in `agent-install.sh`. They all pertain to the edge cluster case:

- [x] Don't make the user input `IMAGE_ON_EDGE_CLUSTER_REGISTRY`. Instead, query the edge cluster to figure out what it should be:
    - OCP: `<registry-host>/<agent-project>/amd64_anax_k8s`
    - microk8s: `localhost:32000/<agent-namespace>/amd64_anax_k8s`
    - k3s: `<docker-registry-service-endpoint>/openhorizon-agent/agent_amd64`
- [x] Replace all of the hardcoded sleeps with `wait_for()`
- [x] In `update_deployment()` if they are prompted but choose not to force delete the agent pod, what happens if the script continues?
- [x] The edge node id can be specified several different ways: `-d node-id`, `NODE_ID`, `HZN_DEVICE_ID`, or the first part of `-a node-auth` or `HZN_EXCHANGE_NODE_AUTH`. Need to try to reduce this list. Let's discuss it.
   - Modify `agent-install.sh`: accept `HZN_NODE_ID` as another way to input node id. Deprecate `NODE_ID`. Still set `HZN_DEVICE_ID` in `/etc/horizon/default` (change need to made for this issue)
   - Modify agent and hzn: also accept `HZN_NODE_ID` (future issue)
   - Modify agent-install.sh: set `HZN_NODE_ID` in `/etc/horizon/default` (future issue)

**Comment by LiilyZhang** [comment]
verified
