### ISSUE TITLE
Stop retry and retry duration processing when a workload upgrade is successful

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#205]
When a workload successfully sends data, the retry and retry duration policy (i.e. the rollback feature) will be turned off so that future failures in the infrastructure will not cause the workload to rollback. When a workload comes up and successfully sends data, the agbot keeps the device at that workload priority from here on out.

**Comment by linggao** [comment]
Built in revision 106 (arm) and 107 (x86), version 2.0.10.
