### ISSUE TITLE
Add an API to the agbot to force a workload upgrade on a specific device

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#206]
If a device upgrade does not work for some reason and the device stabilizes on a lower priority workload, this agbot API can be used to force the device to retry the upgrade processing. Think of this like an agbot policy change that is directed to 1 specific device. It would enable an admin to retry an upgrade without affecting all the other devices that successfully upgraded.

**Comment by dabooz** [comment]
The PR for this issue does the following things:
1) Add an agbot API to force a device to attempt a workload upgrade. This API would be used in cases where an upgrade was attempted across all devices but some were unsuccessful. After fixing the problem, devices which still need to be upgraded can be forced to attempt the upgrade to catch them up with the previously upgraded devices
2) Add an agbot API to return all the workload usage information for each device so that one can see which devices are running which workloads.
3) Fixed a problem found during testing where an agreement cancellation was written to the blockchain before the agreement itself was written, causing the device to miss the cancel. The cancel came from the agbot interestingly (the same agbot that was writing the agreement).

**Comment by linggao** [comment]
built in snap 114 (arm) and 115 (x86) version 2.0.13.

**Comment by linggao** [comment]
Testing #1.  Both of the following worked. 
```
curl -s -X POST -H "Content-Type: application/json" -d '{"device":"12345678"}' http://localhost/policy/netspeed%20amd64/upgrade
```

 ``` curl  -X POST -H "Content-Type: application/json" -d '{"device":"vs4.ling.com", "agreementId":"ba5303bec729b40eac74c823e0e1a14eada07d7060b251927e82d4061cddf400"}' http://localhost:8046/policy/netspeedha%20amd64/upgrade
```
agreementId is optional.

**Comment by linggao** [comment]
Testing #2. 
```# curl -s http://localhost:8046/agreement |jq '.agreements.active[].current_agreement_id'
"578a4966fa4185a0a68da6e58fbed62c9b1e3432a47e597b4f864d10583f47c6"
"da2db1aa48ba7572378e677c0918cc7d9a0692d5a18dd4dd85182d55b13ca3b4"
#curl -s http://localhost:8046/workloadusage  |jq '.[].current_agreement_id'
"da2db1aa48ba7572378e677c0918cc7d9a0692d5a18dd4dd85182d55b13ca3b4"
```
 /agreement returned 2 items, /workloadusage only returned 1 item. This is because that location is not using more than 1 workload priority. This is the limitation for this api for now.
