### ISSUE TITLE
Installation via script fails due to missing package/download

### ISSUE THREAD

**Issue by markusvankempen** [open-horizon/anax#2064]
Script
https://open-horizon.github.io/quick-start
curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh | bash

gave me an error due to missing zip files.

Error: http code 404 from: downloading https://github.com/open-horizon/anax/releases/latest/download/ubuntu.bionic.amd64.assets.tar.gz, stdout: Not Found

had to change to older release 
OH_ANAX_RELEASES=${OH_ANAX_RELEASES:-https://github.com/open-horizon/anax/releases/download/v2.26.12/}

**Comment by bmpotter** [comment]
Yes, the naming convention for anax releases changed. Fixed by https://github.com/open-horizon/devops/pull/17 which has been merged.

**Comment by markusvankempen** [comment]
Worked Fine - when in execute on a different box ...thank you
