### ISSUE TITLE
Pull the Sync Service updates for 'ACL cleanup for Delete Org API'

### ISSUE THREAD

**Issue by LiilyZhang** [open-horizon/anax#2065]
`DELETE /api/v1/organizations/{orgID}` api cleanup data for destination/notification/objects/files, but doesn't cleanup data for ACL under `{orgID}`. 

Actual changes will be implemented in https://github.com/open-horizon/edge-sync-service/issues/48

**Comment by sirotsinskuy** [comment]
Working on it. @joewxboy please assign this issue to me
