### ISSUE TITLE
anax org creation and deletion needs to call sync service organizations API

### ISSUE THREAD

**Issue by LiilyZhang** [open-horizon/anax#2066]
This issue needs discussion to finalize the detail  
- [x] anax org creation needs to call `PUT /api/v1/organizations/{orgID}`
~- [ ] anax org update needs to call `PUT /api/v1/organizations/{orgID}`~
- [x] anax org delete needs to call `DELETE  /api/v1/organizations/{orgID}`
- [x] e2edev update

**Comment by sirotsinskuy** [comment]
@LiilyZhang does this still need discussion? I could work on this if there are final decision(s)/details

**Comment by LiilyZhang** [comment]
@sirotsinskuy we need more discussion about the details of this issue
