### ISSUE TITLE
device failed to get upgraded after the policy file change the second time

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#207]
There were 2 devices in a ha pair and both had netspeed 2.4 as workload.
On the agbot side, added a new workload netspeed 2.5 in the policy file with an intentional error in the torrent url.  Restarted anax.
Saw device1 tried upgrade and failed and rolled back to netspeed 2.5.  Device2 stayed at netspeed 2.4 because device rolled back to this level.
On the agbot side, fixed the torrent url in the policy file and restarted anax.
Saw device1 upgraded to netspeed 2.5.  However device2 stayed at netspeed 2.4 which is a not right.

**Comment by dabooz** [comment]
I tried this scenario today while testing the PR for issue 164 and was unable to recreate it. Do you have logs from your failure?

**Comment by linggao** [comment]
@dabooz sorry I do not have the logs saved.
