### ISSUE TITLE
Every hzn flag that is a file name should support stdin

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2077]
For example, the `-m` flag of `hzn mms object publish` command should support setting it to stdin, but doesn't:

```
$ echo '{"objectID": "horizon-agent-rpm-x86_64.tar.gz", "objectType": "agent_files", "destinationOrgID": "IBM", "public": true}' | hzn mms -o IBM object publish -f $HOME/Downloads/agent-install2/upload/horizon-agent-rpm-x86_64.tar.gz -m-
Error: unable to read definition file -: stat -: no such file or directory
```

(This particular flag is especially important to support stdin, because the metadata file is a throw away file, only needed for input for the command. When scripting, it is a pain to create the file and then have to make sure it gets cleaned up after the command, even if an error occurs.)

**Comment by sirotsinskuy** [comment]
Working on it. @joewxboy please assign this to me

**Comment by bmpotter** [comment]
@sirotsinskuy thanks. Be aware the many of the flags already do support stdin as an option when the filename given is `-` . So you can use the same functions they do

**Comment by sirotsinskuy** [comment]
@bmpotter thanks, I've noticed that. Maybe you have some observations, which other commands are not supporting the stdin, but should?
