### ISSUE TITLE
 'hzn exchange org delete' should delete it from agbot served org list

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2081]
`hzn exchange org create` now creates the org. It then searches the all the orgs and finds the first agbot and add this org to the served list. If the agbot name is given, it uses the given agbot instead. By served list, it has two parts: served pattern list and served deployment policy list. You can get these list from the following comments:
````
hzn exchange agbot listpattern <agbot>
hzn excjhange agbot listdeploymentpol <agbot>
````
Each has 3 parts:  pattern or policy org, pattern name or policy name (usually it is *), node org. 
It mean that the node from the node org will be served by this agbot with these patterns or policies. Without doing so the nodes will not get agreements from the patterns or policies from this agbot. Please note that for the policy case, the node org and the policy org are always the same. 

So for `hzn exchange or delete`,  the served org should be deleted from the agbot. The agbot can be searched the same way or getting from the -a flag  as in the `create` case. Please refer to the following commands to see how the served orgs are deleted. 
````
hzn exchange agbot removepattern <agbot>
hzn excjhange agbot removedeploymentpol <agbot>
````

**Comment by sirotsinskuy** [comment]
Working on it, @joewxboy please assign this issue to me
