### ISSUE TITLE
Hardcode string display when using command hzn register -h

### ISSUE THREAD

**Issue by cdyq** [open-horizon/anax#2083]
Describe the bug
Hardcode string display when using command hzn register -h

To Reproduce
hzn register -h

Expected result
The string should be externalized & get translated
Screenshots
![hardcode](https://user-images.githubusercontent.com/25783969/93748317-9e20d800-fc2a-11ea-8c57-e1258d320227.png)

Build Level
Horizon: horizon-cli_2.27.0-108_amd64.deb

**Comment by MaxMcAdam** [comment]
Verified in 2.27.0-123

**Comment by cdyq** [comment]
Working fine on latest version: horizon_2.27.0-141_amd64.deb
![image](https://user-images.githubusercontent.com/25783969/95533846-ddb33680-0a16-11eb-8092-b9accdae3316.png)
