### ISSUE TITLE
Anax breaks docker logging.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#2097]
Anax breaks docker logging. At first glance it looks like the docker daemon config on the host causes this problem, because the error from docker logs says “configured logging driver does not support reading”. But that is not what this message is trying to convey. I know the local docker daemon is actually configured properly for reading since other manually started containers work correctly with `docker logs`.

The problem is that anax is explicitly forcing the logging driver to be `syslog` on containers it starts! We need to stop forcing syslog to enable our users to debug their containers using **whatever default logging driver they have configured for their docker daemon**. That is, we should not override what the user has configured on their host. Then they will be able tto use `docker logs` as always to debug ttheir containers and not have to sift through the vast noise in syslog.

Anax-started containers show this in docker inspect:
      "LogConfig": {
        "Type": "syslog",
        "Config": {
          "tag": "workload-1ba58bacf60096bf525da3c7b61866bfd249e48d4328e965fb8ef64a0105aa9c_rsp-controller-event"
        }
      }

I think ideally we should expose this docker run argument as an option in our deployment string (i.e., --log-driver) so the user can direct the logs for a specific container to a specific logging endpoint. But the default should be to use what the user has configured for their docker daemon and not force syslog.

**Comment by sirotsinskuy** [comment]
Working on it. @joewxboy please assign this issue to me

**Comment by joewxboy** [comment]
@sirotsinskuy could you please coordinate with @linggao since she also assigned the issue to herself?
