### ISSUE TITLE
hzn mms object publish of large tar.gz file times out

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2102]
When publishing a file like `amd64_anax.tar.gz` or `amd64_anax_k8s.tar.gz`, the cmd `hzn mms object publish ...` says that it is 100% uploaded, but then hangs, and then times out. The object meta data gets in the DB, but the file size of the object itself is 0. Exporting `HZN_HTTP_TIMEOUT` to a longer time doesn't help.

**Comment by LiilyZhang** [comment]
More information and observations:
CSS deployed on stg:
- Succeed to upload text file (.txt) in different sizes (95M, 105M, 150M, 170M, 180M) via hzn mms CLI and cURL command.
- Succeed to upload some tarball files (.tar.gz). See same result from hzn mms CLI and cURL command
```
68MB -> ok
99MB -> ok
150.53MB -> ok
168.48MB -> timeout 
381MB -> timeout
```

CSS in e2edev
- Succeed to upload all above files, without seeing any timeout

**Comment by LiilyZhang** [comment]
It works for rested-squid cluster (common service 2.7.2) but not work for rok-stg (common service 3.5.x). Open an issue in common service github: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/41486

**Comment by LiilyZhang** [comment]
As discussed in scrum, this is not anax issue. Will keep track of the common service issue posted above. Closed.
