### ISSUE TITLE
metering "missed_time" not updated on device side

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#211]
I am running the agbot api and found "data_verification_missed_count" is non-zero. However, on the device side the "metering_notification.missed_time" is always 0.

**Comment by dabooz** [comment]
ok, the problem @linggao found is due to the fact that "check_rate" is not specified in the data verification section of the policy file. There should be a system default when this value is not specified, but there isn't. That's the problem.

**Comment by linggao** [comment]
Built in revision 104 (arm) and 105 (x86), version 2.0.9.
