### ISSUE TITLE
Agent failed to restart after systemd crash

### ISSUE THREAD

**Issue by MaxMcAdam** [open-horizon/anax#2123]
Sep 29 13:45:19 ubuntu anax[98999]: E0929 13:45:19.281510  98999 resource_manager.go:149] Resource Manager: ESS Start error: Failed to setup Unix Socket listening. Error: listen unix /var/run/horizon/essapi.sock: bind: no such file or directory

This is on ubuntu 20.04, the systemd crash is unrelated

**Comment by sudo-panda** [comment]
@MaxMcAdam I am getting the exact error when trying to start horizon.service. Is there something I can do to fix it? I am running Ubuntu 18.04 on a VM and afaik there has been no systemd crash.

**Comment by FrancescoBaroneItaly** [comment]
Something was happened at your linux system, simply check under /var/run if horizon folder exists, if not, create /var/run/horizon with root auth and restart horizon service. Bye!
