### ISSUE TITLE
constraint parsing failed when the closing round bracket has a space before it

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2130]
Here is a node policy file:
````
{
    "properties": [
        {
            "name": "prop1",
            "value": "value1"
        }
    ],
    "constraints": [ "(group == blue) AND ( goodnode == true )" ]
}
````
The command "hzn policy update -f <policy_file>" failed with the following error
````
Error: Incorrect policy format in file horizon/service.policy.json: constraint language [(group == blue) AND ( goodnode== true )] is not supported.  Error finding a control operator in (group == blue) AND ( goodnode== true ). Error was: <source>:1:1: no match found for  
````
Removing the space before the last closing round bracket fixed the problem. 

Another problem: 'hzn deploycheck' failed when the open round bracket has a space after it in the node policy file.

**Comment by gripson** [comment]
I am going to work on it. Could you please assign this issue to me?
