### ISSUE TITLE
Node policy with constraints which include '>' is converted in CLI, prevents agreements from succeeding.

### ISSUE THREAD

**Issue by tbsloan** [open-horizon/anax#2136]
User defines a node policy file as follows: 
{
    "properties": [
        {
            "name": "has-temperature-sensor",
            "value": true
        }
    ],
    "constraints": [
        "coc-approved == true AND security-level >= 3"
    ]
}

When viewed from the CLI, the > symbol is being converted as follows: 

{
  "properties": [
    {
      "name": "has-temperature-sensor",
      "value": true
    }
  ],
  "constraints": [
    "coc-approved == true AND security-level \u003e= 3"
  ]
}
Notice the conversion of the greater than symbol.  When this happens the services do not get deployed properly

**Comment by linggao** [comment]
I tested with the latest code. The `>` or `<` signs are displayed as unicode in `hzn exchange node listpolicy` command. However, it does not affect the agreements.
