### ISSUE TITLE
Inaccurate help on the org create command

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#2146]
The following is the help for `hzn exchange org create --help`

Says:
```
usage: hzn exchange org create --description=DESCRIPTION [<flags>] <org>


      --max-nodes=MAX-NODES      The maximum number of nodes this organization is allowed to have. The default is 0 which means no limit
```

But I got 

root@ubuntu-16-vis-larsond:/usr/horizon# hzn -v exchange org create --description="Test ORG for 5 min heartbeat" --heartbeatmin=20 --heartbeatmax=300 --max-nodes=50000 "HeartBeat-5Min-Org2"

[verbose] HTTP code: 400
Error: bad HTTP code 400 from POST https://cp-console.apps.dominion.rtp.raleigh.ibm.com/edge-exchange/v1/orgs/HeartBeat-5Min-Org2: invalid-input, Org specific limits cannot be over the global exchange limit. Org limit: 50,000; Exchange Limit: 45,000

so I think the help should say something like:
```
The default is 0 which means it will allow up to maximum number of nodes allowed on the system. The value cannot exceed the Exchange global limit. 

 - or - 

The default is 0 which means no organization limit. The value cannot exceed the Exchange global limit. 
```

Additionally, there are some places in this help that has `exchange` lower case and some `Exchange` upper case. I think it should be upper cased.

**Comment by Anukriti2512** [comment]
Hello, I would like to take up this issue. Could you please assign this to me @linggao ? Thank you
