### ISSUE TITLE
A user input with empty name will cause a cluster agreement to fail

### ISSUE THREAD

**Issue by MaxMcAdam** [open-horizon/anax#2161]
`E1008 23:17:19.017659    1210 kubeworker.go:95] Kubernetes Worker: failed to process kube package after agreement negotiation: Error: failed to create config map for dcb0c603c3f233e9cf1c8e058448fe375e6eca1c8f965de07ad213908bf32da4: ConfigMap "hzn-env-vars-dcb0c603c3f233e9cf1c8e058448fe375e6eca1c8f965de07ad213908bf32da4" is invalid: data[]: Invalid value: "": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')`

**Comment by linggao** [comment]
verified/
