### ISSUE TITLE
Node registration with special unicode character needs more cleanup

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2169]
Anax support unicode. But it does not support special characters like symbols. Register a node with special unicode characters like:
````
 hzn register -n abcＡＢＣ一丁七ÇàâｱｲｳДфэأبتثअइउ€¥
````
1. The error message is not readable(Error initializing the node: {"error":"Value violates regex illegal char match: [^-*+()?\u0026! _\w\d.@,:/\\\pL\pN]","input":"device.id"}), maybe the error message could be displayed as something like "A-Za-Z0-9 is only allowed"

2.  Register node with special character failed and return to un-register status, but the node still display in ui page. The undo process should remove the node if it is created by this command.

**Comment by sirotsinskuy** [comment]
Working on it. @joewxboy please assign this issue to me
