### ISSUE TITLE
Have 'hzn deploycheck' default --node-type to the node's type

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2184]
I got this error when running it on an edge cluster:

```
$ hzn deploycheck all -b policy-ibm.operator_1.0.0 -o mycluster -u $HZN_EXCHANGE_USER_AUTH
Neither node id nor node policy is specified. Getting node policy from the local node.
Neither node id nor node user input file is specified. Getting node user input from the local node.
Error: The input node type 'device' does not match the node type 'cluster' from the node mycluster/bp-edge-cluster-5.
command terminated with exit code 7
```

If the code knows what node type i should have specified, then it should just default to that, instead of the default always being `device`. The `-t` or `--node-type` flag is not actually supported at the `hzn deploycheck` sub-cmd level, so the default i'm referring to should be supported in all of these sub-cmds:

- hzn deploycheck all
- hzn deploycheck policy
- hzn deploycheck userinput

**Comment by sirotsinskuy** [comment]
Working on it
