### ISSUE TITLE
'edgeNodeFiles.sh -f <dir>' does not work

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2187]
It puts the gathered files in the current directory instead of the one specified.

The fix is that all 3 lines:

```
if [[ -n $DIR ]]; then pushd; fi
```

need to be changed to this:

```
if [[ -n $DIR ]]; then pushd $DIR; fi
```

Until this is fixed a work around is to run it like this:

```
(cd <dir> && edgeNodeFiles.sh ... )
```

**Comment by xauthulei** [comment]
@bmpotter , Is that OK to let me fix this ? Thanks

**Comment by bmpotter** [comment]
@xauthulei Yes, thank you!
