### ISSUE TITLE
support docker login credentials in the OS keyring

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#2188]
The support is needed in at least 2 places, maybe more:

- hzn exchange service publish
- anax runtime when attempting to download containers from private registries

**Comment by sirotsinskuy** [comment]
Working on it. @joewxboy please assign this issue to me

**Comment by johnwalicki** [comment]
I've done some OS keyring integration on Linux/Mac.  Let me read through this ticket.

**Comment by johnwalicki** [comment]
A quick scan of the source tree shows that this feature would be integrated into
anax/cli/cliutils/cliutils.go
possibly also anax/cli/exchange/service.go

**Comment by johnwalicki** [comment]
There are a bunch of Go keyring libraries.  Don't know if we have a preference?  What are other Edge projects using to for OS keyring credentials?

**Comment by bmpotter** [comment]
@johnwalicki  There is not any other open-horizon code using OS keyring credentials. This will be the first, so any tips/help you can provide is appreciated. Any opinion on the best Go keyring package?

**Comment by sirotsinskuy** [comment]
@johnwalicki @bmpotter There is a PR submitted for this issue https://github.com/open-horizon/anax/pull/2214
It allows to use creds from Linux/Mac keyrings, created by "docker login"
