### ISSUE TITLE
Remove '{a1, a2}' from installation scripts

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2190]
In rpm installation script, https://github.com/open-horizon/anax/blob/master/pkg/rpm/horizon/horizon.spec, the following code generates a directory `{bin, samples}` 
````
mkdir -p $RPM_BUILD_ROOT/usr/horizon/{bin,samples} 
````
We need to change all the places in the install scripts where `{a1, a2}` are used. So above can be changed to 
````
mkdir -p $RPM_BUILD_ROOT/usr/horizon/bin
mkdir -p $RPM_BUILD_ROOT/usr/horizon/samples
````

**Comment by bmpotter** [comment]
@LiilyZhang You can verify this by running `agent-install.sh` on a red hat machine to install the horizon rpms. Then run `ls /usr/horizon/` and you should **not** see in curly braces in the directory names.

**Comment by LiilyZhang** [comment]
Verified on rpm. No curly braces in the the `/usr/horizon/` directory
