### ISSUE TITLE
AgentAutoUpgrade: Improve support for running the anax container on linux edge node

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2217]
Today, you can manually make this work, but it is too many error prone steps and requires too much understanding of how the pieces fit together. This will enable using the agent on more edge node platforms.

- [x] Update `agent-install` to support using the anax container on linux (similar to how it supports it on mac today):
  - [x] New flag and/or env var to indicate they want to use the anax container (instead of the `horizon` package)
  - [x] Install `horizon-cli` (which contains `horizon-container`)
  - [x] Set up `/etc/default/horizon` and `/etc/horizon/agent-install.crt` because `horizon-container start` mounts/uses these.
  - [x] Support running multiple instances of anax container on the same edge node host (like the mac case does)
  - [x] Change `hzn version | grep "^Horizon CLI"` to `LANG=en_US hzn version | grep "^Horizon CLI"`
- [x] Modify the `hzn` command to automatically figure out that it should connect to anax in the container not on the host. Provide an env var to force this in the case when anax is running on both.
- [ ] Update documentation to describe using this

**Comment by johnwalicki** [comment]
It would be helpful to describe this technique in the documentation.
