### ISSUE TITLE
Unable to manipulate IPTables rules in container post-creation step

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#2219]
On a Linux node whose open horizon agent is deployed **in a container**, we were trying to register with just the IBM helloworld pattern. We see the agreement being created, accepted, finalized, and then immediately the service is terminated due to the error below. And then it cycles.
And here is the output we see:
"2020-12-07 16:02:36:  Image loaded for biz/sg.edge.example.visual.mms.",
 "2020-12-07 16:02:37:  Error starting containers: Unable to manipulate IPTables rules in container post-creation step: Error: running [/usr/sbin/iptables -t filter -N OPENHORIZON-ANAX-ISOLATION --wait]: exit status 4: iptables v1.8.4 (nf_tables): CHAIN_ADD failed (No such file or directory): chain INPUT\n",
If you wish to reproduce this, or get hands on with the agent, Ryan has an HP MP9 machine in the Berkeley Garage Lab which is one of the two places we have seen this issue. You can get remote access to this machine by asking Ryan.
Another user reported this in the Slack edge-users channel as well. I was told that he solved this problem for his demo by building a custom agent binary that did not do this iptables manipulation.

**Comment by dlarson04** [comment]
A similar error was reported by a user running WLS2 under Windows 10. Ideally the solution/work-around would work in both environments.

**Comment by LiilyZhang** [comment]
Verified
