### ISSUE TITLE
Horizon service failed to start on RHEL 8.3 - tied to ESS Start error

### ISSUE THREAD

**Issue by jarcher** [open-horizon/anax#2223]
Failed to start Service for Horizon control system.
--
CODE_FILE | ../src/core/job.c
CODE_FUNC | job_log_done_status_message
CODE_LINE | 933
INVOCATION_ID | a6a325e4df3d4f6e8cdbb10ab881d522
JOB_RESULT | failed
JOB_TYPE | start
MESSAGE_ID | be02cf6855d2428ba40df7e9d022f03d
PRIORITY | 3
SYSLOG_FACILITY | 3
SYSLOG_IDENTIFIER | systemd
UNIT | horizon.service
_BOOT_ID | df268b81b9d7410999cf2522a69d182b
_CAP_EFFECTIVE | 3fffffffff
_CMDLINE | /usr/lib/systemd/systemd --switched-root --system --deserialize 18
_COMM | systemd
_EXE | /usr/lib/systemd/systemd
_GID | 0
_HOSTNAME | founders.oakridge
_MACHINE_ID | edd566dec18944fcb6c3818ce269d1dd
_PID | 1
_SOURCE_REALTIME_TIMESTAMP | 1608052155835550
_SYSTEMD_CGROUP | /init.scope
_SYSTEMD_SLICE | -.slice
_SYSTEMD_UNIT | init.scope
_TRANSPORT | journal
_UID | 0
__CURSOR | s=391267577cd3496da5522847f3fdd2b7;i=91e;b=df268b81b9d7410999cf2522a69d182b;m=11f5754;t=5b683d1876500;x=df06dced5b09465a
__MONOTONIC_TIMESTAMP | 18831188
__REALTIME_TIMESTAMP | 1608052155835648

tied it back to this

E1215 11:09:15.731446    3382 resource_manager.go:149] Resource Manager: ESS Start error: Failed to setup Unix Socket listening. Error: listen unix /var/run/horizon/essapi.sock: bind: no such file or directory
--
PRIORITY | 6
SYSLOG_FACILITY | 3
SYSLOG_IDENTIFIER | anax
_BOOT_ID | df268b81b9d7410999cf2522a69d182b
_CAP_EFFECTIVE | 3fffffffff
_CMDLINE | /usr/horizon/bin/anax -v 3 -logtostderr -config /etc/horizon/anax.json
_COMM | anax
_EXE | /usr/horizon/bin/anax
_GID | 0
_HOSTNAME | founders.oakridge
_MACHINE_ID | edd566dec18944fcb6c3818ce269d1dd
_PID | 3382
_STREAM_ID | 6fa3cd765e264f64a4e7cfdb9bddad17
_SYSTEMD_CGROUP | /system.slice/horizon.service
_SYSTEMD_INVOCATION_ID | a6a325e4df3d4f6e8cdbb10ab881d522
_SYSTEMD_SLICE | system.slice
_SYSTEMD_UNIT | horizon.service
_TRANSPORT | stdout
_UID | 0
__CURSOR | s=391267577cd3496da5522847f3fdd2b7;i=914;b=df268b81b9d7410999cf2522a69d182b;m=11dc053;t=5b683d185cdff;x=2c14d233b3eb42c0
__MONOTONIC_TIMESTAMP | 18726995
__REALTIME_TIMESTAMP | 1608052155731455

Could start the service on system restart, was able to restart manually

**Comment by linggao** [comment]
It could very much be that directory `/var/run/horizon` does not exist. We have fixed this error in anax to create this directory if it does not exist.
