### ISSUE TITLE
Under heavy load, same agbot can process same message multiple times

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#2230]
What I see under heavy load is that the same agbot can process the same message multiple times. This will work but the agbot will do a lot of work decrypting the message and putting a duplicate entry on its work queue.  

If the agbot gets the messages in order, can the agbot keep a variable around with the last msgid it processed so it can skip over it on next pass if the message is still there… similar to the way it keeps the changeid?  

This section of the log shows it for 1 agbot. This example reads the message twice but I have seen it where the same message can be read 4 or 5 times.

```
Jan 6 12:23:06 ibm-edge-agbot-7b44857df-d2q6r ibm-edge-agbot info I0106 17:23:06.411225       9 agreementbot.go:596] AgreementBotWorker reading message 2253508 from the exchange
Jan 6 12:23:06 ibm-edge-agbot-7b44857df-d2q6r ibm-edge-agbot info I0106 17:23:06.427055       9 prioritized_workqueue.go:196] Prioritized Work Queue: queueing inbound high: WorkType: AGREEMENT_VERIFY, Verify: {Type: basicagreementverification, Protocol: Basic, Version: 1, AgreementId: 1d8abf35678eaa8ad252e55ffcb92c3911d6ec60f307cc5515cd4bc52bc0697a}, MsgEndpoint: , SenderId: ieam-roks-scale/edge-scale-test170_x1_horizon22, SenderPubKey: set, MessageId: 2253508
Jan 6 12:23:38 ibm-edge-agbot-7b44857df-d2q6r ibm-edge-agbot info I0106 17:23:38.206885       9 basic_agreement_worker.go:148] BasicAgreementWorker (360dd257-ebb7-4a5b-90fd-948a12fa16b5): received work: WorkType: AGREEMENT_VERIFY, Verify: {Type: basicagreementverification, Protocol: Basic, Version: 1, AgreementId: 1d8abf35678eaa8ad252e55ffcb92c3911d6ec60f307cc5515cd4bc52bc0697a}, MsgEndpoint: , SenderId: ieam-roks-scale/edge-scale-test170_x1_horizon22, SenderPubKey: set, MessageId: 2253508
Jan 6 12:23:44 ibm-edge-agbot-7b44857df-d2q6r ibm-edge-agbot info I0106 17:23:44.784758       9 agreementbot.go:596] AgreementBotWorker reading message 2253508 from the exchange
Jan 6 12:23:44 ibm-edge-agbot-7b44857df-d2q6r ibm-edge-agbot info I0106 17:23:44.798963       9 prioritized_workqueue.go:196] Prioritized Work Queue: queueing inbound high: WorkType: AGREEMENT_VERIFY, Verify: {Type: basicagreementverification, Protocol: Basic, Version: 1, AgreementId: 1d8abf35678eaa8ad252e55ffcb92c3911d6ec60f307cc5515cd4bc52bc0697a}, MsgEndpoint: , SenderId: ieam-roks-scale/edge-scale-test170_x1_horizon22, SenderPubKey: set, MessageId: 2253508
Jan 6 12:23:50 ibm-edge-agbot-7b44857df-d2q6r ibm-edge-agbot info I0106 17:23:50.804852       9 agreementbot.go:835] Deleted exchange message 2253508
Jan 6 12:24:35 ibm-edge-agbot-7b44857df-d2q6r ibm-edge-agbot info I0106 17:24:35.508995       9 basic_agreement_worker.go:148] BasicAgreementWorker (63bb60c1-73b8-4092-b7b8-c826eb127d29): received work: WorkType: AGREEMENT_VERIFY, Verify: {Type: basicagreementverification, Protocol: Basic, Version: 1, AgreementId: 1d8abf35678eaa8ad252e55ffcb92c3911d6ec60f307cc5515cd4bc52bc0697a}, MsgEndpoint: , SenderId: ieam-roks-scale/edge-scale-test170_x1_horizon22, SenderPubKey: set, MessageId: 2253508
Jan 6 12:24:41 ibm-edge-agbot-7b44857df-d2q6r ibm-edge-agbot info I0106 17:24:41.624972       9 agreementbot.go:835] Deleted exchange message 2253508```

**Comment by dlarson04** [comment]
Another scenario that would be avoided by keeping track of the last processed msgid is one where an agent is sending a protocol message for an agreement, but neither agbot has that agreement. This could happen in a system recovery scenario. In this case, the message will get processed over and over again by both agbots because it won't get deleted.

**Comment by dlarson04** [comment]
I was playing around with this... I think this would be a huge boost for the agbot since I think it processes the same message multiple times when under heavy load. However, I am seeing that the GET call to /agbots/agbot/msgs sometimes doesn't return a message that it should... cause unknown at this point. The messages are in order but there are gaps sometimes and then the next read, it returns the missing messages.  This means that setting the lastRead variable to the last read msgid would intermittently miss some messages.

I wrote a small tool that calls GET to /agbots/agbot/msgs every 8 seconds and prints out the msgid and updates the lastReadMsgId to the last read and prints out the msgid and checks to see if all the messages are in sequential order. On the next pass, if there is a msgId < lastReadMsgId, I print out that message id saying it has already been read.  Here is an example of what I see on a call that returns ~292 messages. (Some msgid's skipped for brevity)

```
Messages read: 4835795,4835796,...,4836071,4836072,** Out of Order **,4836077,** Out of Order **,4836079
```
My tool prints `Out of Order` if some messages are not in sequential order so in this case 4836073 to 4836076 are not returned by the exchange in this call to GET /msgs. However, on my next pass through, I see the following print statements
```
Already read msg 4836073
Already read msg 4836074
Already read msg 4836075
Already read msg 4836076
```
so this tells me  on the next pass, these messages were returned.

Sometimes, some messages may not be in sequential order since one of the agbots could have processed the message and deleted it, but in this case, the message was not deleted by an agbot since on the next read it was returned. 

I suspect this only happens when the exchange has to return large numbers of messages but not sure yet. I did look at the exchange code and the messages are sorted in the Scala code outside of the DB. Not sure if doing the sorting inside the DB would be better.

**Comment by bmpotter** [comment]
Exchange issue https://github.com/open-horizon/exchange-api/issues/440 may at least partially resolve this issue.

**Comment by dabooz** [comment]
As part of this issue we need to address how the agbot consumes and processes messages that come in from agents:
1) throttle the consumption of messages to prevent duplicate message processing
2) increase the agbot worker default pool side to 30, to increase the throughput of message processing
