### ISSUE TITLE
e2edev improvements: use all-in-1 env, etc

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2232]
- [x] rebase on all-in-one management hub
- [x] add all-in-one cert to e2edev
- [x] pass config files to all-in-one containers
- [x] remove msg-hub related code.

**Comment by linggao** [comment]
For the `rebase on all-in-one management hub` part, the process is the following from the Makefile:
1. build anax binary, amd64_agbot and amd64_anax_k8s  docker images
2. create `hzn_horizonnet` docker network
3. start all-in-one management hub with given agbot image name, exchange root and hubadmin admin passwords etc. It will start agbot, css, exchange etc on the `hzn_horizonnet` network.
4. start `e2edevtest` container on `hzn_horizonnet` network.
5. docker exec  to run `init_exchange.sh` in `e2edevtest` container to add orgs/users/services/patterns/policies to the exchange
6. docker exec to run `run_kube.sh` to start a cluster agent
7. docker exec to run `gov_combined.sh` to run all the test cases.

**Comment by dabooz** [comment]
@linggao The above process is driven from the same make commands with the same variables as what used to work? e.g. make test TEST_VARS="NOLOOP=1 NONS=1 ..." etc?

**Comment by linggao** [comment]
> @linggao The above process is driven from the same make commands with the same variables as what used to work? e.g. make test TEST_VARS="NOLOOP=1 NONS=1 ..." etc?

Yes, the same process.
