### ISSUE TITLE
Agbot failed to give new proposals due to old node cache

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2235]
When a node is registered with a pattern, then unregister it and register it with a policy very fast, new agreements take hours to come.
I debugged the agent and the agbots.The agbot did picked up the node at the time of new registration, but it failed to make agreement because of node policy does not match. I think this is the timing issue between the thread for node search and changes_worker.
````
11:11:27: changes_worker looking for changes starting from ID 621425
11:11:27: node policy put in to the exchange
11:11:30: node is done registration/publicKey set to exchange node
11:11:30: agbot picked up node and could not make agreement because node policy not match
11:11:37: changes_worker looking for changes starting from ID 621425
11:11:47: changes_worker looking for changes starting from ID 621430
````
Node policy cache in agbot got updated AFTER agbot did the policy check

**Comment by LiilyZhang** [comment]
Verified
