### ISSUE TITLE
Agbot cancels finalized agreement due to agreement timeout because it is looking at stale data

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#2238]
See the attached log for agreement 9edcc6c322737428d208beb6a8ca781b7ba0427d7060eacfe366ad145f299ca3

You can see that at time `16:35:24.498134`, the agbot gets the `reply` message and sets `AgreementFinalizedTime` and writes it to the DB

However, the agreementbot/governance code is working on an old copy of the agreement and at `16:35:27.848016`, it doesn't think the `AgreementFinalizedTime` is set so it cancels the agreement.  

[ibm-edge-agbot-6974499dbb-v2mm7.log](https://github.com/open-horizon/anax/files/5815816/ibm-edge-agbot-6974499dbb-v2mm7.log)

(Note: I added some debug statements to the code so some of the log messages are additions by me)

On the agent side, he sees this:
```
  "2021-01-14 11:29:37:   Node received Proposal message using agreement 9edcc6c322737428d208beb6a8ca781b7ba0427d7060eacfe366ad145f299ca3 for service ieam-roks-scale/quay-perfhznmodel100.helloworld from the agbot IBM/agbot.",
  "2021-01-14 11:29:57:   Agreement reached for service quay-perfhznmodel100.helloworld. The agreement id is 9edcc6c322737428d208beb6a8ca781b7ba0427d7060eacfe366ad145f299ca3.",
  "2021-01-14 11:29:57:   Start dependent services for ieam-roks-scale/quay-perfhznmodel100.helloworld.",
  "2021-01-14 11:29:57:   Start workload service for ieam-roks-scale/quay-perfhznmodel100.helloworld.",
  "2021-01-14 11:29:58:   Image loaded for ieam-roks-scale/quay-perfhznmodel100.helloworld.",
  "2021-01-14 11:30:10:   Workload service containers for ieam-roks-scale/quay-perfhznmodel100.helloworld are up and running.",
  "2021-01-14 11:36:03:   Node received Cancel message for ieam-roks-scale/quay-perfhznmodel100.helloworld from agbot IBM/agbot.",
  "2021-01-14 11:36:04:   Complete terminating agreement for quay-perfhznmodel100.helloworld. Termination reason: unknown reason code, device might be downlevel",
  ```

I am not clear on the filter that is used `notYetFinalFilter()` and why it wouldn't also check for `AgreementFinalizedTime != 0`

Another aspect of this issue that made it hard to figure out is that when this occurs, the reason code gets set to `TERM_REASON_NOT_FINALIZED_TIMEOUT` 
but in agreementbot/basic_protocol_handler.go, that case is commented out so the code gets set to  999.  This translated into the agreement (and to the agent) as 
`TerminatedDescription: unknown reason code, device might be downlevel`.

**Comment by linggao** [comment]
It looks like a timing issue between different threads for large loads.

**Comment by dlarson04** [comment]
Two possible solutions I thought of for your consideration
- If looking at an agreement and  `ag.AgreementFinalizedTime == 0` and this condition is true
```
if ag.AgreementCreationTime+w.BaseWorker.Manager.Config.AgreementBot.AgreementTimeoutS < now {
// Start timing out the agreement
w.TerminateAgreement(&ag, protocolHandler.GetTerminationCode(TERM_REASON_NOT_FINALIZED_TIMEOUT))
}
```
before terminating the agreement, read this one agreement out of the DB and see  `AgreementFinalizedTime` is still 0. 
There still might a timing issue on different threads but the window would be much narrower.

- create a new field on the agreement like "next_cycle_terminate_agreement_if_not_finalized". If the timeout has occurred, 
set this field on this agreement. Then on the next cycle through the agreements, if this field is set and `AgreementFinalizedTime` is still 0, then go ahead and cancel the agreement.

**Comment by dlarson04** [comment]
For more information.... 
The comment in governance.go says

```
// Find all agreements that are in progress. They might be waiting for a reply or not yet finalized on blockchain.
if agreements, err := w.db.FindAgreements([]persistence.AFilter{notYetFinalFilter(), persistence.UnarchivedAFilter()}, agp); err == nil {
```

but that is not what is happening... I have 10k agreements and this code is continuously looks at all agreements (well after they are all finalized) (5100 on one agbot and 4900 on the other). If this code is only supposed to look at agreements still in process, perhaps the `notYetFinalFilter(),` needs to check for `AgreementFinalizedTime != 0`

This isn't causing a problem except making the agbot do more work than needed

**Comment by dlarson04** [comment]
I don't see this being a big issue.. Closing
