### ISSUE TITLE
x509: certificate signed by unknown authority - Error raised on MacOs to access IEAM4.2 Hub

### ISSUE THREAD

**Issue by olympien13** [open-horizon/anax#2239]
Hi,
 I am facing a technical issue while installing an IEAM4.2 agent on a Mac0s on one of my colleague in my team. I tried several stuff to try to solve it but now I am struck and need your support/ideas/suggestions to try to solve it.
The error is : “x509: certificate signed by unknown authority”.
Here is the list of commands that shows the error. I checked the “agent-install.crt” location and validity.

** $> hzn exchange version**
Error: Can't connect to the Horizon Exchange REST API to run GET https://cp-console.apps.tnc-env2-rhocp.nca.ihost.com/edge-exchange/v1/admin/version. Maybe HZN_EXCHANGE_URL is set incorrectly? Or unset HZN_EXCHANGE_URL to use the Exchange that the Horizon Agent is configured for. Specific error is: Get "https://cp-console.apps.tnc-env2-rhocp.nca.ihost.com/edge-exchange/v1/admin/version": x509: certificate signed by unknown authority

** $> hzn register -p IBM/pattern-ibm.helloworld**
Horizon Exchange base URL: https://cp-console.apps.tnc-env2-rhocp.nca.ihost.com/edge-exchange/v1
Using node ID 'MacBookPro-Clemence.local' from the Horizon agent
Generated random node token
Error: Can't connect to the Horizon Exchange REST API to run GET https://cp-console.apps.tnc-env2-rhocp.nca.ihost.com/edge-exchange/v1/orgs/cp4mfg-sandbox/nodes/MacBookPro-Clemence.local. Maybe HZN_EXCHANGE_URL is set incorrectly? Or unset HZN_EXCHANGE_URL to use the Exchange that the Horizon Agent is configured for. Specific error is: Get "https://cp-console.apps.tnc-env2-rhocp.nca.ihost.com/edge-exchange/v1/orgs/cp4mfg-sandbox/nodes/MacBookPro-Clemence.local": x509: certificate signed by unknown authority

** $> hzn env**
Horizon Agent HZN Environment Variables are:
HZN_ORG_ID: cp4mfg-sandbox
HZN_EXCHANGE_USER_AUTH: iamapikey:******
HZN_EXCHANGE_URL: https://cp-console.apps.tnc-env2-rhocp.nca.ihost.com/edge-exchange/v1
HZN_FSS_CSSURL: https://cp-console.apps.tnc-env2-rhocp.nca.ihost.com/edge-css

** $> cat /etc/default/horizon**
HZN_EXCHANGE_URL=https://cp-console.apps.tnc-env2-rhocp.nca.ihost.com/edge-exchange/v1
HZN_FSS_CSSURL=https://cp-console.apps.tnc-env2-rhocp.nca.ihost.com/edge-css/
HZN_DEVICE_ID=MacBookPro-XXXXXXX.local
# HZN_MGMT_HUB_CERT_PATH=/etc/default/agent-install.crt
HZN_MGMT_HUB_CERT_PATH=/Users/lebrun/Downloads/agent-install.crt

When accessing directly the IEAM Hub point without checking the SSL certificate using the curl command it works as shown below:
** $> curl https://cp-console.apps.tnc-env2-rhocp.nca.ihost.com/edge-exchange/v1/admin/status --insecure**
{"code":"invalid-credentials","msg":"invalid credentials"

Command to use install the IEAM agent:
**sudo -E -s ./agent-install.sh -p IBM/pattern-ibm.helloworld -w '*' -T 120**

**Comment by bmpotter** [comment]
On macOs the `agent-install.sh` script tells the OS to trust the cert (in addition to putting it in /etc/default/horizon). See https://github.com/open-horizon/anax/blob/afda149c139b0853387b6b3f003c44ed68bf1569/agent-install/agent-install.sh#L979 . See if that solves your colleague’s problem

**Comment by bmpotter** [comment]
@olympien13 Can you respond to my comment above? I don't know why you are hitting this problem, and i can't reproduce it. Thx

**Comment by olympien13** [comment]
forget about this pb. She never contacted me again for that issue. You can close it.
Thanks Bruce
