### ISSUE TITLE
Make reg_all work for raspbian image

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#224]
From @is8ac:  I flashed an RPI 2 with `horizon-raspbian-pi2-2017-05-07_2212.img` and set to staging as described in https://repo.hovitos.engineering/MTN/mtn/wikis/horizon_v2_on_rpi
However both with an existing user, and with a new user, it fails to create user.

**Comment by linggao** [comment]
from the output, it looks like the variable EXCH is not generated.  There is no snap on the reapbian image. anax is installed on it as horizon and bluehorizon packages.

**Comment by bmpotter** [comment]
Works well for me.
