### ISSUE TITLE
Clean up non-UBI anax Dockerfiles

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2256]
- [ ] Remove `anax-in-container/Dockerfile_agbot.amd64` (No need for a non-UBI container, like alpine, for the agbot container in the mgmt hub.)
- [ ] Remove `anax-in-container/Dockerfile.amd64` because that name is misleading (makes it seem like that's the default dockerfile), and because its implementation is very different from the ubi dockerfiles (the former installs the horizon pkgs, the latter just copies the necessary binaries and files into the image)
- [ ] Create a new file called `anax-in-container/Dockerfile.alpine.amd64` that is based on alpine, but the rest of the dockerfile is similar to `anax-in-container/Dockerfile.ubi.amd64`

**Comment by imskr** [comment]
Can I work on this? Please assign me :)

**Comment by linggao** [comment]
@imskr it is assigned to you. Thanks.

**Comment by sudo-panda** [comment]
@imskr are you still working on this?

**Comment by imskr** [comment]
Yes, I will make the PR by EOD @sudo-panda
