### ISSUE TITLE
Miscellaneous agent-install.sh fixes

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2259]
- [x] Relax check "Can not specify both -c (AGENT_CERT_FILE) and -i (INPUT_FILE_PATH)" (for both sdo case and regular users)
- [x] Address error case:
    - cp: cannot stat 'agent-install.crt': No such file or directory
    - 2020-11-12 08:11:53 ERROR: exit code 1 from: moving cert file to /etc/horizon/agent-install.crt
- [x] Fix sanjeev's rpi problem (see edge-dev channel): add-apt-repository: command not found
    - add software-properties-common to: runCmdQuietly apt-get install -yqf curl jq
- [x] Make `agent-install.sh` not affected by external USE_EDGE_CLUSTER_REGISTRY env var

**Comment by jacob-rogers** [comment]
@bmpotter Trying to work now with external registry, does the 4th subtask
> Make agent-install.sh not affected by external USE_EDGE_CLUSTER_REGISTRY env var

mean that it won't be able to connect to any other registry except edge cluster registry ?
This error made me confused:
`"Agent install on edge cluster requires using an edge cluster registry"`

**Comment by bmpotter** [comment]
@jacob-rogers Correct, but there are more changes necessary to `agent-install.sh` to support an external registry than just being able to set `USE_EDGE_CLUSTER_REGISTRY='false'`. That is why i'm disabling the input of the variable for now. If someone has the time to add full support for an external registry, then the variable can be re-enable at that time. (The should work with @LiilyZhang  .)

**Comment by LiilyZhang** [comment]
Verified bullet 1,2,4

**Comment by MaxMcAdam** [comment]
Verified bullet 3
