### ISSUE TITLE
Make MicroserviceDefinition and MicroserviceInstance consistent for all cases

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2267]
MicroserviceDefinition and MicroserviceInstance were created to track the dependent services, their containers and upgrade state. It was created back then with and old agreement protocol. Since the introduction of the patterns and policies, node status and service stop/resume etc, the use of these 2 objects is  no longer consistent which may cause problems. 
This is what we is like today:
````
curl http://localhost:8510/service |jq '.definitions.active[] | {"ref_url", "organization", "microservicedef_id"}'
curl http://localhost:8510/service |jq '.instances.active[] | {"ref_url", "organization", "microservicedef_id", "associated_agreements"}'
````
For the pattern case, all services for the pattern (top and dependent) have defs. For the policy case, all the dependent services for agreements have defs. In addition, if a service is in the userinput file, the def will be created for this service. 
As to the instances, all the services that are in agreements have instances. This includes top and dependent services, even the ones with empty deployment like network, network2.  For the instance of a dependent services, the MicroserviceDefId is not empty, it points to the id of the def.  For instance of a top level service, the MicroserviceDefId is empty even there is def defined. This is true for both pattern and policy cases.

*Please note that the output from the `/service` API used by the two commands above does not reflect what's in the db tables. For the microservice instances the api adds the top level services on fly from the agreements on the agreement table.
The questions are:
1. Do we need need MicroserviceDefinition for top level services? 
2. Do we still need to create MicroserviceDefinition for any services from the user input for the policy case? NO
3. How MicroserviceDefinition are used in the node status? (use agreements for top level services, use MicroserviceDefiniton/MicroserviceInstance for dependent services.)
4. How MicroserviceDefinition are used in the service retry? (Retry is for dependent services only)
5. How MicroserviceDefinition and MicroserviceInstance are used for dependent service upgrade? (Loop through MicroserviceDefinitions)
6. How MicroserviceDefinition and MicroserviceInstance are used for service stop and resume? (use registeredServices in node)
7. How MicroserviceDefinition and MicroserviceInstance are used for the Edge Cluster case?

This issue was changed from a feature to a bug because the hzn service log command depends on the anax /service API to return the same services in the active instances list and the active definitions list. This is one of the side effects of the problems that need to be addressed in this issue.

Implentation:
 - [x] create an interface for Microservice Instance. The implementation of this interface is EstablishedAgreeement and MicroserviceInstance.
- [x] create top level MicroserviceDefintion objects for all the case. 
- [x] update the /service api with the new MicroserviceInstInterface
- [x] update the node status report code to use the new MicroserviceInstInterface code. No more differences between top level and dependent services.
- [x] clean up the dependent MicroserviceDefinition if no instances referencing it
- [x] multi-version support for MicroserviceDefintion
- [x] add --version for hzn service log command.
- [x] update hzn service list command to get service date from /service API instead of /service/config API.
- [x] add version for service configstate cli and api. (need exchange to add the version in node's registeredServices.  https://github.com/open-horizon/exchange-api/issues/518)
- [x] update and test the service configstat changes (suspending and resuming)

**Comment by dlarson04** [comment]
Updating per request from Ling

When using a pattern deployment with just a top level service, if an updated service is added to the exchange, I see the following eventlog messages in the agent

```  
"2021-02-15 08:10:52:   Workload service containers for testOrg/quay-perfhznmodel100.helloworld are up and running."
  "2021-02-15 08:21:51:   Start upgrading service testOrg/quay-perfhznmodel100.helloworld from version 1.0.1 to version 1.0.2."
  "2021-02-15 08:21:51:   Complete upgrading service testOrg/quay-perfhznmodel100.helloworld from version 1.0.1 to version 1.0.2.",
  "2021-02-15 08:21:51:   Start policy advertising with the Exchange for service testOrg/quay-perfhznmodel100.helloworld.",
  "2021-02-15 08:21:51:   Complete policy advertising with the Exchange for service testOrg/quay-perfhznmodel100.helloworld."
```

but the agent didn't actually upgrade the service... I see the following in the agent logs

```
Feb 15 08:21:51 plasmas1 anax[16208]: I0215 08:21:51.338830   16208 microservice.go:265] Remove policy for testOrg/quay-perfhznmodel100.helloworld version 1.0.1, key 14
Feb 15 08:21:51 plasmas1 anax[16208]: E0215 08:21:51.338977   16208 microservice.go:396] GovernanceWorker: Failed to remove service policy for service def testOrg/quay-perfhznmodel100.helloworld version 1.0.1. Failed to rename the policy file /etc/horizon/policy.d/testOrg/quay-perfhznmodel100.helloworld.policy to /etc/horizon/policy.d/testOrg/quay-perfhznmodel100.helloworld.policy.14, error rename /etc/horizon/policy.d/testOrg/quay-perfhznmodel100.helloworld.policy /etc/horizon/policy.d/testOrg/quay-perfhznmodel100.helloworld.policy.14: no such file or directory
Feb 15 08:21:51 plasmas1 anax[16208]: I0215 08:21:51.339163   16208 microservices.go:508] Succeeded updating service definition record to Owner: testOrg/admin, Label: perfhznmodel100.helloworld for amd64 from Quay.io, Description: A super-simple sample Horizon service from Quay.io, SpecRef: quay-perfhznmodel100.helloworld, Org: testOrg, Version: 1.0.2, Arch: amd64, Archived: false, Name: _testOrg_0.0.0-INFINITY, RequestedArch: amd64, UpgradeVersionRange: [0.0.0,INFINITY), AutoUpgrade: true, ActiveUpgrade: false, UpgradeStartTime: 1613395311, UpgradeMsUnregisteredTime: 0, UpgradeAgreementsClearedTime: 1613395311, UpgradeExecutionStartTime: 0, UpgradeMsReregisteredTime: 0, UpgradeFailedTime: 1613395311, UngradeFailureReason: 200, UngradeFailureDescription: Service un-registration on exchange failed, UpgradeNewMsId: , MetadataHash: [12 110 34 14 209 184 127 185 159 168 56 4 193 130 28 240 62 229 145 8 133 15 45 96 106 235 2 87 105 32 110 101]
Feb 15 08:21:51 plasmas1 anax[16208]: I0215 08:21:51.343368   16208 microservice.go:295] Generate policy for the given service testOrg/quay-perfhznmodel100.helloworld version 1.0.2 key 15
```

If the agent should not upgrade this top level service, the eventlog messages should not appear

**Comment by Isabel-Gan** [comment]
To help answer question 3:

In `governance/status.go`, `ReportDeviceStatus()` compares the currently running services against the status of the node stored in the local database. The code tries to persist suspended services by carrying over the running services in the local database to the new updated status it writes to the exchange. However, in the local database, it seems that `MicroserviceDefinitions` are not updated correctly on policy and pattern changes. After agreement termination, the database still shows active `MicroserviceDefinitions`, so these terminated services are shown on `liststatus` when they should not be.

This leads to issue #2559, since the status function depends on the microservice status stored in the local database, which is incorrect, `liststatus` will show services that should have been terminated on the node. Once this issue is fixed and `MicroserviceDefinitions` are updated correctly, #2559 should be fixed.
