### ISSUE TITLE
Create ESS API socket listener path if it does not exist

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2275]
The problem occurs when the node got rebooted and anax failed to restart with the following error:
````
Jan 31 22:43:39 bp21 anax[8420]: I0131 22:43:39.301716    8420 authenticate.go:24] ESS: Authenticator Starting
Jan 31 22:43:39 bp21 anax[8420]: E0131 22:43:39.309832    8420 resource_manager.go:149] Resource Manager: ESS Start error: Failed to setup Unix Socket listening. Error: listen unix /var/run/horizon/essapi.sock: bind: no such file or directory
````
This is because the ESS socket file is located at `/var/run/horizon/essapi.sock`.  However everything under `var/run` got wiped out during reboot. 
After the discussion with a group of developers, we found there are other problems for ESS API socket mapping. The following is a list of to do's. 
- [x] Create the base directory for essapi.sock at anax start up. This can be the anax startup script or anax itself. ( _Added creation of the path in anax before starting ESS_)
- [x] Test reboot and reregister case for native agent
- [x] Test reboot and agent container restart for the anax in container case. (_Tested on Mac, socat does not survive reboot_)
- [x] Test multiple agent container case

**Comment by linggao** [comment]
- For the anax-in-container case on Mac: Nothing to do. This is how it is working today: The base dir for essapi.sock is `/private/var/tmp/horizon/horizon1/fss-domain-socket`, it is mounted to both agent container and the service container. It is created by `horizon-container` and `anax.service` puts it to the anax.json for ess config. No socat needed for this.
- For the anax-in-container case on Linux: Nothing to do. This is how it is working today: The base dir for essapi.sock is `/var/tmp/horizon/horizon1/fss-domain-socket`, it is mounted to both agent container and the service container. It is created by `horizon-container` and `anax.service` puts it to the anax.json for ess config.

**Comment by MaxMcAdam** [comment]
Verified in 2.28.0-326
