### ISSUE TITLE
Agent-install.sh: Accept `HZN_NODE_ID` in `/etc/default/horizon`

### ISSUE THREAD

**Issue by LiilyZhang** [open-horizon/anax#2284]
`Agent-install.sh` should support `HZN_NODE_ID` in addition to `HZN_DEVICE_ID` in `/etc/default/horizon`. This should be done in a backward compatible way. I.e. whether an edge node is using `HZN_DEVICE_ID` or `HZN_NODE_ID` it should work. Do this by changing `agent-install.sh` to write both variables in `/etc/default/horizon` when creating it. And when reading it or checking it, look for both variables. If both are set, prefer `HZN_NODE_ID` because that’s what we want to use going forward, since it makes sense on both edge devices and edge clusters.

**Comment by Isabel-Gan** [comment]
Hello! Worked on this
