### ISSUE TITLE
Agreement-less service that is also a dependency is terminated when parent is suspended.

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#2291]
To recreate:
1) run the e2edev pattern tests: make test TEST_VARS="NOLOOP=1 NOKUBE=1 TEST_PATTERNS=sall"
2) suspend the location workload: hzn service configstate suspend e2edev@somecomp.com https://bluehorizon.network/services/location

Observe:
The location service is stopped, this is correct. The locgps service is also stopped, this is incorrect because the service is agreement-less. The cpu service (dependent of locgps) is not stopped, because it is still needed as a dependency of one of the other workloads that is running, so this is correct.

Please note that https://github.com/open-horizon/anax/blob/master/test/gov/verify_agreements.sh will have to be updated when this issue is fixed, in order to pass the e2edev 'make test TEST_VARS="NOLOOP=1 TEST_PATTERNS=sall' test. When issue #2095 is integrated, this testcase was changed because the fix for 2095 exposes this problem and creates an extra network. The verify script was updated to allow the tests to pass until this issue could be fixed.

**Comment by sudo-panda** [comment]
I was trying to reproduce the issue but on running `hzn service configstate suspend e2edev@somecomp.com https://bluehorizon.network/services/location` I get the error:
```
Error: bad HTTP code 400 from POST http://localhost:8510/service/configstate: {"error":"No changes made. The service e2edev@somecomp.com/https://bluehorizon.network/services/location does not exist or is not a registered service in the exchange for node node1.","input":"url, org"}
```
I am unsure how to proceed could you give some pointers?
