### ISSUE TITLE
hzn subcommands aliases / shortnames

### ISSUE THREAD

**Issue by jacob-rogers** [open-horizon/anax#2298]
Sometimes it's quite difficult to regularly repeat some hzn commands, especially in a new environment, where are no scripts prepared for efficient usage.
But there are a lot of good examples of improving user experience by using built-in aliases for subcommands/objects/resources. For example, `kubectl` tool helps a lot with natively support of these variants: 
```sh
kubectl get services
kubectl get svc
kubectl get pods
kubectl get po
kubectl get nodes
kubectl get no
# ...
# namespaces = ns
# persistentvolumeclaims = pvc
#
# full list of short names you can see using `kubectl api-resources` command
```

And sometimes it disappointing me when calling smth like:
```sh
hzn exchange deployment updatepolicy ...
```
And in this case, performing the same API behavior, is it really useful to apply this as an option?
```sh
hzn exchange dp u
# or
hzn exchange dp upd
```

Deployment policies API is only as an example here. There are some even more lengthy commands in hzn.

What do you think?

**Comment by dabooz** [comment]
These kinds of shortcuts are helpful. Some of the nouns in the existing hzn CLI are long. While we do provide command autocompletion when the CLI is installed from a release, it is not always available, especially if you are working on anax in development.

**Comment by bmpotter** [comment]
Autocompletion is available even when you build `hzn` from source. I use it constantly.
