### ISSUE TITLE
Unable to pull openhorizon/e2edev-agbot

### ISSUE THREAD

**Issue by codejaeger** [open-horizon/anax#2305]
I am trying to run the e2edev tests using the steps outlined in [/test/README.md](https://github.com/open-horizon/anax/blob/master/test/README.md).
I built anax from the Makefile at root and ran the checks to verify the installation. Then I proceeded to try out e2edev. I started with the lightweight tests:
`make test TEST_VARS="NOLOOP=1 NOCANCEL=1 NOHZNREG=1 ... "`
But this is the error that I get every time :-
```
Handling agbot
Unable to find image 'openhorizon/e2edev-agbot:latest' locally
docker: Error response from daemon: pull access denied for openhorizon/e2edev-agbot, repository does 
not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Failure to ensure agbot is running or to start it
Makefile:92: recipe for target 'run-agbot' failed
make: *** [run-agbot] Error 2
```
I double checked my commands and looked for the image in the docker hub [registry](https://hub.docker.com/u/openhorizon). Could not find it there either. Am I doing something wrong over here?
I am on Ubuntu 18.04 VM and arch=amd_64. Thanks for your help.

**Comment by linggao** [comment]
@codejaeger Please run `make` under `anax/test` directory first and then run `make test TEST_VARS="NOLOOP=1 NOCANCEL=1 NOHZNREG=1 ... " on the same directory.

**Comment by codejaeger** [comment]
Thanks @linggao it worked. I totally missed the last step to build the image using the Makefile. Sorry for the trouble and thanks for the help! You may close this issue.
