### ISSUE TITLE
Failed to register any device node to the unicode Org and the org function is not working fine in ui after use hzn create a unicode Org

### ISSUE THREAD

**Issue by cdyq** [open-horizon/anax#2332]
**Describe the bug**
issue1. Failed to register any device node to the unicode Org
issue2. the org function(create/delete/display) is not working fine in ui after use hzn create a unicode Org

**To Reproduce for issue1**
Steps to reproduce the issue1:
1. Create a unicode name Org by command - hzn exchange org create -d "some unicode word" "unicode org name"
 (Ex: hzn exchange org create -d "啊☆" "㐁ᠠﭖ")
2. Register any device node to the unicode Org by command - hzn register "the unicode org name"
 (Ex: hzn register "㐁ᠠﭖ")
3. Observe the Failure & Error message displayed

**Expected behavior**
If Unicode is decided to be not supported, we should have clear error messages (and provide the allowed char set) for all commands/UIs when user trying to input an Unicode name & make sure the operation is not taking effect.
On the other hand, If Unicode should be supported, we should have all functions support Unicode.
Or at least, clearly hint users about the functions that don’t support Unicode & make sure the Unicode supported parts won’t disable the not supported parts.
(Ex: A Unicode name Org should also be able to get non-Unicode nodes registered. Assuming node registration won’t support Unicode name, but Org does.)
**Screenshot for issue1**
![image](https://user-images.githubusercontent.com/25783969/109099995-f9697000-775e-11eb-99b5-da9e475be947.png)

**To Reproduce for issue2**
Steps to reproduce the issue2:
1. Create a unicode name Org by command - hzn exchange org create -d "some unicode word" "unicode org name"
 (Ex: hzn exchange org create -d "啊☆" "㐁ᠠﭖ")
2. Login to the organization administration console with hub admin role((https://cp-console.apps.stockholm.rtp.raleigh.ibm.com/edge)     testldap/1234)
3. Check the new created unicode org whether display in ui
4. Delete a org
5. Check the deleted org

**Expected behavior**
Step3: new created unicode org should display in ui
Step5: Deleted org should remove from ui
**Actual result**
Step3: new created unicode org not display in ui
Step5: Deleted org still display in ui not removed
BTW: If i removed the created unicode org use hzn the org function in ui will working fine.
**Screenshot for issue2:**
![image](https://user-images.githubusercontent.com/25783969/109100662-50237980-7760-11eb-9cf5-302929d93ec9.png)
step3:
![image](https://user-images.githubusercontent.com/25783969/109100689-59ace180-7760-11eb-9476-8665b4f61bed.png)
step5:
![image](https://user-images.githubusercontent.com/25783969/109100728-63364980-7760-11eb-8216-8f7be0cc8a11.png)

**ENV**
horizon-cli_2.28.0-285_amd64.deb
#image_agbot: amd64_agbot:2.28.0-289
#image_exchange: amd64_exchange-api:2.62.0-289
#image_css: amd64_cloud-sync-service:1.5.1-289
#image_sdo: sdo-owner-services:1.9.2-201
#image_ui: edge-ui-amd64:1.4.0-323

**Comment by linggao** [comment]
@cdyq I have not problem register a node in a org with unicode.
1.  hzn exchange org create -d "啊☆" "㐁ᠠﭖ"
2. hzn exchange agbot addpattern IBM/agbot IBM '*' "㐁ᠠﭖ"
3. hzn register -p IBM/pattern-ibm.helloworld -o "㐁ᠠﭖ" -n 我的節點
They all ran successfully.

**Comment by linggao** [comment]
@cdyq Could you please verify it with latest build?

**Comment by cdyq** [comment]
issue1: can register node with unicode org but the node not display in ui
![image](https://user-images.githubusercontent.com/25783969/131784628-554a42a2-9b50-47c6-8697-525241efcbe0.png)

issu2: still can reproduced,  new created unicode org not display in ui
![image](https://user-images.githubusercontent.com/25783969/131777735-58ced64b-c0e6-4aed-a05d-d6e57687a4cd.png)
