### ISSUE TITLE
"docker run --device ..." arguments  are not fully supported currently

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#2333]
Docker run's "--device" syntax is "<hostpath>[:<containerpath>][:<accessmode>]" so it accepts things like this:
"/dev/foo:/dev/foo:rwm"
"/dev/foo:/dev/foo"
"/dev/foo"
As equivalent. That is, the access mode argument is ":rwm" (read, write, mknod) when not explicitly specified. And the container path for the device will be the same as the host path when not specified.

Currently ["/dev/foo"] is not allowed in our service definitions (but ["/dev/foo:/dev/foo"] does and this can be used as a workaround until this issue is fixed).

**Comment by shubhank-saxena** [comment]
Hello @linggao @TheMosquito . I would love to take this issue up if that's okay!

**Comment by rajpratyush** [comment]
@linggao is this issue still open ??

**Comment by linggao** [comment]
@rajpratyush it is being worked on by @shubhank-saxena.

**Comment by rajpratyush** [comment]
@linggao I was going through the PR that he pushed there was a line of code which I think is wrong or mistyped . Can we discuss about it?

**Comment by linggao** [comment]
@rajpratyush yes. If you could comment in the PR, that will be great. If not, please put your comment here.
