### ISSUE TITLE
hzn unregister kills dev containers unexpectedly

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2343]
1. Use `hzn dev` command to create a service, then publish the service and the pattern defined under the horizon directory
2. hzn register -p <above_pattern>
3. hzn dev service start -S
4. docker ps
You will see 2 service containers are running. One from # 2, one is from # 3.
5. hzn unregister
The service container for # 2 is supposed to be removed only. But both of them are removed.

Implementation hint:  The service container that is brought up by # 3 has the following label when you inspect the service using `docker inspect`: `"openhorizon.anax.dev_service": "true"`.

**Comment by sirotsinskuy** [comment]
I can take it. @joewxboy please assign this issue to me

**Comment by joewxboy** [comment]
@sirotsinskuy You got it!
