### ISSUE TITLE
'hzn dev service log' -s flag is documented incorrectly in the help

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2344]
On the hzn dev service log command, the help for the -s flag says that it is used to specify the name (URL) of the service whose logs should be displayed. This is incorrect, the -s flag is used when the service being tested has more than 1 container in the service definition. The service's deployment config has a services section which defines each container that is part of the overall service definition. It's one of these service names that can be passed on the -s flag. A service definition has at least one container within the deployment config, so the -s flag can be omitted, and the single container in the service definition will be used. This is all working correctly in the code. The help is incorrect.

There are other problems in this area of the CLI that could also be addressed by this issue. The hzn dev service log is inconsistent with hzn service log and with other CLI commands in a few ways:
1) hzn service log has a positional argument for specifying the service URL, but hzn dev service log does not. Adding this to hzn dev service log will be done as a feature in https://github.com/open-horizon/anax/issues/2393
2) the -s flag on hzn dev service log is inconsistent with the use of -s in other parts of the CLI. Deprecate the -s flag (by adding this deprecation statement to the help) and introduce a flag called -c to replace it. The -c flag is used to select a container within a service def, whose logs are displayed.
3) add the -c flag to the hzn service log command, which will be used to indicate the same thing as on the hzn dev service logs command. The current code randomly returns the logs from 1 of the containers in the service def, that's no good.

**Comment by codejaeger** [comment]
@linggao Can I work on this issue?

**Comment by linggao** [comment]
Issue https://github.com/open-horizon/anax/issues/2393 handles the part that adds a positional parameter <service> for  `hzn dev service log`  command.
