### ISSUE TITLE
Suspended service tests in e2edev cause subsequent tests to timeout

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#2353]
When the agbot tries to make an agreement with a node but the node has a suspended service, the agbot declines to make the agreement, and instead defers the agreement for future consideration. When the deferred agreement request is retried, an agreement could have been previously made, so before retrying the agbot needs to verify that the target node is not already in an agreement. Otherwise, the agbot ends up sending a proposal which will be ignored, but which will prevent additional agreements from being made (if the node's existing agreement was subsequently cancelled) until the extra agreement times out.

Unfortunately, during debug of this problem we discovered that the underlying service resume function is just broken, so this issue will fix the requeue problem but will also disable the suspend/resume tests in e2edev. Issue #2355 will address the underlying functional problem and will re-enable these tests.

**Comment by linggao** [comment]
PR https://github.com/open-horizon/anax/pull/2356
