### ISSUE TITLE
agbot to use /changes API  handle service configstate changes

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2355]
Currently agbot handles service suspension through holding the agreement making process back. It is very inefficient and cause problems. It will change to use the /changes API to detect the service configstate changes so that once the service is resumed, it will start a new search. For service suspension, it will just terminate any agreement making process.
However, when the service configstate is updated through the service_configstate resource,  the lastUpdated field for the node resource is not updated so that agbot cannot detect the service configstate change through the node resource. The exchange [issue 476](https://github.com/open-horizon/exchange-api/issues/476) will fix this issue. 

This issue should also re-enable the suspend resume tests in e2edev.

**Comment by MaxMcAdam** [comment]
Verified
