### ISSUE TITLE
The registration status is not translated for 'hzn register'

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2377]
Run `LANG=zh_CN hzn register -p IBM/ibm.hello-mms -s "*"`,  you will see some texts are in English like:
```
正在等待以下服务启动（至多 60 秒）：
	IBM/ibm.hello-mms
您正在监视的服务的状态：
	IBM/ibm.hello-mms 	Waiting: no agreements formed yet
您正在监视的服务的状态：
	IBM/ibm.hello-mms 	Waiting: agreement is formed
您正在监视的服务的状态：
	IBM/ibm.hello-mms 	Waiting: agreement is accepted
您正在监视的服务的状态：
	IBM/ibm.hello-mms 	Waiting: service is created
您正在监视的服务的状态：
	IBM/ibm.hello-mms 	Waiting: execution is started
	anaxsquad2/lingTop 	Waiting: service is created
您正在监视的服务的状态：
	IBM/ibm.hello-mms 	Waiting: execution is started
	anaxsquad2/lingTop 	Waiting: execution is started
您正在监视的服务的状态：
	IBM/ibm.hello-mms 	Waiting: execution is started
您正在监视的服务的状态：
	IBM/ibm.hello-mms 	Success
```

To fix, use `msgPrinter.Sprintf` for these strings. https://github.com/open-horizon/anax/blob/master/cli/register/servicewait.go#L59-L65.
To build the language into the executable, under anax directory, 
 ````
 make i18n
 make
 ````
 Then run the hzn command from cli/hzn. Like: `LANG=fr cli/hzn register... `

**Comment by losdevnull** [comment]
I will work on this... taking it as an opportunity to re-setup my local dev/test environment : )

**Comment by losdevnull** [comment]
@linggao, once I have the change, would we have to wait for translation files to be update before I could actually test this?  Do you have any suggestion on how to locally mock test this?  One way I could think of is to manually update messages.gotext.json locally and build hzn binary out of it.  Please advice if you think there would be a better way.   Thanks much in advance.

**Comment by linggao** [comment]
@losdevnull yes. the translation will have to wait for the the next cycle. However, you can manually change one of the messages.gotext.json files under cli/locales directory. And do `make i18n-catalog` and test with your translation.
