### ISSUE TITLE
New respbian image does work on staging if the config files contain ^M

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#239]
Flashed the SD card with the 05-25/05-28 pi3/pi2 raspbian image. Added /Volumes/BOOT/horizon-cfg/etc/horizon/anax.json and /Volumes/BOOT/horizon-cfg/etc/default/horizon-env
 using Window's emacs or Notepad.  Power on the device. anax failed to start because it had panic due to CMTN_DEVICE_ID not found.  This is because the files added above contain a ^M character at the end of each line.

**Comment by linggao** [comment]
Suggest to auto-remove all the ^M from the files when copying anax.json and horizon-env from /boot/horizon-cfg/ to /etc on the device.
```
tr -d '\15\32' < winfile.txt > unixfile.txt
```

**Comment by bmpotter** [comment]
fixed
