### ISSUE TITLE
Ensure hzn dev leverages the hosts docker authentication

### ISSUE THREAD

**Issue by cgiroua** [open-horizon/anax#2392]
`hzn dev` has the option to define the following to variables to pull the ESS image from an alternate source:
`HZN_DEV_FSS_IMAGE_REPO`
`HZN_DEV_FSS_IMAGE_TAG`

Defining those two variables correctly targets the alternate image location, however `hzn dev service start` seems to ignore the hosts docker auth. Despite doing a `docker login` the following error is seen:
```
unknown: Authentication is required. Set environment variable HZN_DEV_FSS_IMAGE_TAG to use a different image tag.. Set environment variable HZN_DEV_FSS_IMAGE_TAG to use a different image tag.
```

**Comment by sirotsinskuy** [comment]
I can take it @joewxboy
