### ISSUE TITLE
hzn dev service log should have an argument for the URL of the service to display

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#2393]
In order for the hzn dev service log command to be consistent with hzn service log, the former should support a positional argument that allows the user to specify the service URL to identify which service's logs are displayed.

By default, hzn dev service log displays the logs of the service in the current project (directory). With this new feature, the specified URL could be the service in the current directory or a dependency. Any other service URL will result in an error message from the command. To implement this new feature, the hzn dev service log code will have to navigate the current project's dependencies directory in the filesystem in order to find the service defs of valid dependencies and check them against the input URL. If the URL is a valid dependency, the service defs in the dependencies directory will provide the container info needed to find the right container and display the logs.

**Comment by Isabel-Gan** [comment]
Hello! Working on this
