### ISSUE TITLE
Expose BC container status via anax api

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#242]
This is primarily so the dashboard can show status of geth, especially right after registration, when the device owner is waiting for the BC to sync.

**Comment by dabooz** [comment]
There is already a status API in ANAX: /status that returns a JSON struct with info on the current blockchain(s) in use.  Issue 218 changed the output of this API to turn it into an array. Once you are on that level, the array could be empty or could have more than 1 entry in it. The output structure is docmented in the ANAX API doc: https://github.com/open-horizon/anax/blob/master/doc/api.md
When the doc gets updated, the output of the API will be shown as an array.
