### ISSUE TITLE
More work on node's service configstate changes

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2420]
- [ ] Agent does not respond when the service config state changes on the exchange.
- [ ] Handle the case when the service configstate is changed by both local user and exchange admin at the same time. The exchange is the master

**Comment by sirotsinskuy** [comment]
Working on it, @linggao

**Comment by linggao** [comment]
I will close this issue because the service config state change already uses the exchange as the base. No need to store a local cache.
