### ISSUE TITLE
Support the docker run `--ipc` feature (for kernel IPC namespaces)

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#2423]
For `docker run --ipc ...` usage details, search for "ipc" in the docker run documentation: [https://docs.docker.com/engine/reference/run/](https://docs.docker.com/engine/reference/run/)

Here's an excerpt:
>IPC (POSIX/SysV IPC) namespace provides separation of named shared memory segments, semaphores and message queues.
> Shared memory segments are used to accelerate inter-process communication at memory speed, rather than through pipes or through the network stack. Shared memory is commonly used by databases and custom-built (typically C/OpenMPI, C++/using boost libraries) high performance applications for scientific computing and financial services industries.

**Comment by dlarson04** [comment]
closing... Added support in

https://github.com/open-horizon/anax/issues/3912
