### ISSUE TITLE
Couldn't install agent script on centos-7

### ISSUE THREAD

**Issue by sanathukumar14** [open-horizon/anax#2440]
Hello @bmpotter,
I have done below steps and got some error
export SUPPORTED_REDHAT_VERSION_APPEND=7
Error:
 Problem: conflicting requests
  - nothing provides redhat-release >= 8 needed by epel-release-8-10.el8.noarch
[root@sanath agent-install]#

**Comment by bmpotter** [comment]
Requesting that you change your local copy of agent-install.sh to use https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm instead of https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm and let me know if the rest of it works
