### ISSUE TITLE
mms and service name with underscore fails

### ISSUE THREAD

**Issue by SanjeevKGupta** [open-horizon/anax#2446]
When an object is published in MMS and object meta file has service_name_with_underscore as part of deployment policy,  the object is not delivered to qualifying nodes. None of the current set of `hzn mms` commands provide any clue to this naming syntax issue. 

Service-name with _underscore_ works while using service publishing and node registration etc. Issue arrises when MMS is trying to use that service_name and MMS fails to deliver the object.  

**Workaround:** do not use _underscore_ in service name.

A fix or an early error should be provided so that service_name is corrected as user is developing the service and application.

**Comment by dlarson04** [comment]
MMS also fails if the org name has an _ in it.... We should fix the logic in the MMS handling or fail the service and org create if they have these characters.

**Comment by linggao** [comment]
````Sep 3 12:50:04 ibm-edge-agbot-659d4558b9-tfvsp ibm-edge-agbot error panic: runtime error: index out of range [1] with length 1
Sep 3 12:50:04 ibm-edge-agbot-659d4558b9-tfvsp ibm-edge-agbot goroutine 525 [running]:
Sep 3 12:50:04 ibm-edge-agbot-659d4558b9-tfvsp ibm-edge-agbot github.com/open-horizon/anax/agreementbot.findCompatibleService(0xc004386930, 0x26, 0xc001ba0a10, 0xc000331ef0, 0x24, 0xc00044f950, 0xc006bf65fa, 0x5, 0xc006bf66b0)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/policy.go:385 +0x9ab
Sep 3 12:50:04 ibm-edge-agbot-659d4558b9-tfvsp ibm-edge-agbot github.com/open-horizon/anax/agreementbot.(*BaseAgreementWorker).findCompatibleServices(0xc000695380, 0xc001ba0e10, 0xc001ba0a10, 0xc000331ef0, 0x24, 0xc00044f950, 0x0)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/policy.go:
Sep 3 12:50:04 ibm-edge-agbot-659d4558b9-tfvsp ibm-edge-agbot 358 +0xa8
Sep 3 12:50:04 ibm-edge-agbot-659d4558b9-tfvsp ibm-edge-agbot github.com/open-horizon/anax/agreementbot.(*BaseAgreementWorker).HandleMMSObjectPolicy(0xc000695380, 0x1f98900, 0xc00029b9e0, 0xc00216a600, 0xc000331ef0, 0x24)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/policy.go:260 +0xb41
Sep 3 12:50:04 ibm-edge-agbot-659d4558b9-tfvsp ibm-edge-agbot github.com/open-horizon/anax/agreementbot.(*BasicAgreementWorker).start(0xc0003a3420, 0xc000694b40, 0xc00044f3b0)
        /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/basic_agreement_worker.go:355 +0x1cf2
Sep 3 12:50:04 ibm-edge-agbot-659d4558b9-tfvsp ibm-edge-agbot created by github.com/open-horizon/anax/agreementbot.(*BasicProtocolHandler).Initialize

Sep 3 12:50:04 ibm-edge-agbot-659d4558b9-tfvsp ibm-edge-agbot /tmp/anax-gopath/src/github.com/open-horizon/anax/agreementbot/basic_protocol_handler.go:72 +0x2d0
````

**Comment by playground** [comment]
For some reason we are not able to drill down on MMS services for more details in the U.  It would just keep spinning.  This is the error it's throwing in UI {"errors":[{"code":500,"msg":"Invalid Version: .0."}],"data":{"service":null}}.
@Sanjeev pointed out there is an open ticket on issue  "_" in the service name.  Not sure if this is related.  
![image](https://user-images.githubusercontent.com/243495/140173344-9c2bcaeb-9ad7-485d-9ee3-72dca44d174a.png)
![image](https://user-images.githubusercontent.com/243495/140173455-206d82cf-e9e4-49aa-9ad8-19dfe4731d88.png)

**Comment by dlarson04** [comment]
opened https://github.ibm.com/Edge-Fabric/edge-fabric-mgmt-ui/issues/1747

to address Jeff's issue
