### ISSUE TITLE
Agbot API to support lifecycle operations on secrets

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#2463]
Add a new resource called /org/<org>/secrets/<vault-secret-name>
GET returns a JSON encoded object indicating the existence or non-existence of the named secret.
200: Secret exists
{
  "exists":<boolean>
}
401: invalid user creds
403: user not in the org specified on the API path
404: Secret does not exist
503: There is no vault component in the management hub. The caller should retry this API call a small number of times with a short delay between calls to ensure that the vault is really not there.

POST/PUT creates or updates a secret. If the secret already exists, it is updated.
Body:
{
  "name":"some/secret/name",
  "secret":"base64 encoded secret bytes"
}
201: created/updated
401: invalid user creds
403: user not in the org specified on the API path
503: here is no vault component in the management hub. The caller should retry this API call a small number of times with a short delay between calls to ensure that the vault is really not there.

DELETE removes a secret.

204: no content, secret is deleted
401: invalid user creds
403: user not in the org specified on the API path
404: secret not found
503: here is no vault component in the management hub. The caller should retry this API call a small number of times with a short delay between calls to ensure that the vault is really not there.

**Comment by codejaeger** [comment]
@dabooz should the status code 503 also be returned when the agbot config does not contain a vault URL. In that case the subsequent message seems irrelevant. So, would it be better of we return a 404 in case of unconfigured vault url.
Also since the user credentials belong to the agbot to authenticate to the vault, where is the org specific information (that the user belongs to this org) is going to come from. I am a bit confused if this will be available from the exchange or the vault itself.

**Comment by dabooz** [comment]
@codejaeger
1) http status code 503 means service unavailable, it is a temporary condition but there is no standard meaning for temporary, could be seconds could be much longer. Since the caller needs to respond differently when a secret is not there 404 vs the vault not being there, having a distinct status code helps the caller.
2) The agbot will sometimes use the callers credentials (called impersonation) when accessing the vault, sometimes its own. A fully formed userid in OH is org/user, and is always carried this way internally.  That is, when a user calls an OH API, the userid in the basic auth header is ALWAYS org/user. Nothing else is supported. This is true for exchange API and for agbot APIs.
