### ISSUE TITLE
Agent add /secret et. al. APIs, document APIs

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2473]
Updated secrets are transported to the appropriate node via the agreement protocol and made available to services via a new REST API hosted by the agent. The REST API allows the service implementation to query for new secrets and to receive them when it is ready to do so.

- [x] REST API
    - GET /secrets
    - GET /secrets/<secret-name>
    - POST /secrets/<secret-name>?received=true
- [x] adding `secret_status` table to store the status
- [x] API check `secret_status` and `secrets` table to determine if a secret has update
- [x] hzn dev support
- [x] swagger

**Comment by Isabel-Gan** [comment]
Hello! Working on this
