### ISSUE TITLE
Change 'hzn register -m <name>' to set the name in the exchange node resource, even if it already exists

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2480]
When SDO registers an edge device, it uses the `-m` flag to try to set the node name to the hostname (different from the node id, which is the sdo UUID of this device). For example, here’s an edge device sdo recently registered in roks-stg:

```
hzn register -m 'bruce-dev31' -o 'mycluster'  -n '4c8a8002-d176-4b19-aaf2-5f01ddfdc156:ef192241ea38af727fd793ddea00fe124b3b02b4d95d'
```

But when i look at in the exchange, the name field is the same as the node id:

```
$ hzn exchange node list 4c8a8002-d176-4b19-aaf2-5f01ddfdc156
{
  "mycluster/4c8a8002-d176-4b19-aaf2-5f01ddfdc156": {
    "token": "********",
    "name": "4c8a8002-d176-4b19-aaf2-5f01ddfdc156",
    "owner": "mycluster/bp",
    "nodeType": "device",
    "pattern": "",
    "registeredServices": [],
    "msgEndPoint": "",
    "softwareVersions": {},
    "lastHeartbeat": "2021-04-22T15:11:47.436287Z[UTC]",
    "publicKey": "",
    "arch": "amd64",
    "userInput": [],
    "heartbeatIntervals": {
      "minInterval": 0,
      "maxInterval": 0,
      "intervalAdjustment": 0
    },
    "lastUpdated": "2021-04-22T15:11:47.436287Z[UTC]"
  }
}
```

Before registration, during voucher import, sdo does pre-create the node in the exchange with the `name` field set to the UUID (because at that point we aren’t on the edge device, so don’t know its hostname). It appears that the `hzn register -m <name>` flag doesn’t take effect if the node already exists in the exchange.

@linggao confirmed this and will change the behavior of `hzn register -m <name>` to set the name in the exchange node resource, even if it already exists.

**Comment by linggao** [comment]
Implementation hint: add a PATCH after this line for the node name if the name does not match. 
https://github.com/open-horizon/anax/blob/master/cli/register/register.go#L224
Just like the token update code.

**Comment by sirotsinskuy** [comment]
@joewxboy I could take this
