### ISSUE TITLE
Allow node removal even when node is registered.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#2482]
When you `hzn exchange node remove ...` a node that is registered, the CLI asks:

```
Are you sure you want to remove node myorg/667d377d-ba1a-4c7b-a1b1-e3291a273e83 from the Horizon Exchange (should not be done while an edge node is registered with this node id)? [y/N]: y
```

The exchange (and/or anax) should internally, quietly, unregister it for the user. Obviously they want to get rid of this node so they no longer want it to be registered. The “are you sure” prompt is good but it should instead tell the user something like it will be unregistered (if registered) and permanently removed from the exchange.

Bruce added:
@mosquito well,  of course the exchange can reach into the edge node to tell the agent to unregister. But the agent could detect that its resource in the exchange is gone and unregister itself (maybe it already does, i don’t know). Open an issue in the anax repo and assign it to @linggao

**Comment by Polber** [comment]
I can work on this

**Comment by MaxMcAdam** [comment]
Verified in 2.29.0-542
