### ISSUE TITLE
Horizon agent can use up all open files if IEAM hub in bad state

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#2517]
I problem occurred on an IEAM Hub where the hub returned 503 Service Unavailable

```
May 14 15:44:53 ieam-camera-1 anax[2271]: W0514 15:44:53.710019    2271 
changes.go:269] Exchange RPC Invocation of POST 
at https://cp-console.ieam42-edge-8e873dd4c685acf6fd2f13f4cdfb05bb-0000.us-south.containers.appdomain.cloud/edge-exchange/v1/orgs/demo/changes 
with  failed invoking HTTP request, error: <nil>, HTTP Status: 503 Service Unavailable
```

The next day problem on the hub still existed and this led to the following error on the horizon agent

```
May 15 08:20:36 ieam-camera-1 anax[2271]: E0515 08:20:36.746736    2271 
changes.go:266] Exchange RPC Invocation of POST 
at https://cp-console.ieam42-edge-8e873dd4c685acf6fd2f13f4cdfb05bb-0000.us-south.containers.appdomain.cloud/edge-exchange/v1/orgs/demo/changes with {"changeId":3612943,"maxRecords":1000} 
failed invoking HTTP request, error: 
Post "https://cp-console.ieam42-edge-8e873dd4c685acf6fd2f13f4cdfb05bb-0000.us-south.containers.appdomain.cloud/edge-exchange/v1/orgs/demo/changes": 
dial tcp: lookup cp-console.ieam42-edge-8e873dd4c685acf6fd2f13f4cdfb05bb-0000.us-south.containers.appdomain.cloud on 10.11.96.22:53: dial udp 10.11.96.22:53: socket: too many open files
```

lsof showed a 11k  of TCP files owned by the anax agent

```
anax       2271                  root    8u     sock                0,9       0t0     174835 protocol: TCP
anax       2271                  root    9u     sock                0,9       0t0     174078 protocol: TCP
anax       2271                  root   10u     sock                0,9       0t0     173796 protocol: TCP
anax       2271                  root   11u     sock                0,9       0t0     173849 protocol: TCP
```

The theory is that since the Hub was returning a 503 Service Unavailable  that the HTTP response body wasn't being closed by the horizon agent.  @linggao  found the following article

http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#close_http_resp_body

The horizon agent had to be restarted to clear the condition

**Comment by linggao** [comment]
Yes, this[ link](http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#close_http_resp_body) talks about in some error situation the response body is not nil. The code should close the response body for this case too. 
So for `exchange/rpc.go` line 1019 should be moved to right after line 1009, it should look like this:
````
httpResp, err := httpClient.Do(req)
if httpResp != nil && httpResp.Body !=  nil {
    defer httpResp.Body.Close()
}
```` 
There are other places in anax and hzn  that also need to be fixed. Please search for `close()`.

**Comment by dlarson04** [comment]
I think I have been able to reproduce this problem.. I can build your changes and see if it resolves the issue

**Comment by dlarson04** [comment]
Verified this issue with
Horizon CLI version: 2.29.0-442
Horizon Agent version: 2.29.0-442

that picked up a new ESS build
