### ISSUE TITLE
typo in "an agent in a container" document

### ISSUE THREAD

**Issue by yshk** [open-horizon/anax#2520]
In anax/docs/agent_container_manual_deploy.md
https://github.com/open-horizon/anax/blob/master/docs/agent_container_manual_deploy.md
There is trivial typo below.
"hzn register -policy node_pol.json"  --> "hzn register --policy node_pol.json" (not "-" but "--")

**Comment by lhazuca** [comment]
Hi, I would like to fix this. Can you assing me this one?

**Comment by lhazuca** [comment]
Hi, I would like to fix this. Can you assing it to me?

**Comment by linggao** [comment]
@hdiedrich please create a pull request for your fix. thanks.

**Comment by linggao** [comment]
@lhazuca please create a pull request for your fix.
