### ISSUE TITLE
Agbot /health API report it's connection with the vault

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2533]
The agbot's non-remotable API /health  to report it's connection with the vault. A new field will be added to the HealthTimestamps struct to indicate the last time the agbot successfully invoked the Vault API:
"lastVaultInteraction":<linux-epoch-timestamp>

For implementation, here is the health API. https://github.com/open-horizon/anax/blob/master/agreementbot/api.go#L334

**Comment by codejaeger** [comment]
@dabooz @linggao the non-remotable API does not have a handle on the secret implementation (if at all) being used. How will this endpoint be supported? Will this information be stored in the Agbot database?

**Comment by dabooz** [comment]
@codejaeger Look at line 169 in main.go where the secrets manager is passed into the secure API worker. There is also a worker for the insecure API, so you will have to pass the secrets manager into that worker in a similar way and save a reference to the secrets manager in the api worker.
