### ISSUE TITLE
API error (500): error while creating mount source path operation not permitted

### ISSUE THREAD

**Issue by playground** [open-horizon/anax#2536]
Running 
Macs OS Big Sur V11.4
Horizon CLI version: 2.28.0-338
Horizon Agent version: 2.28.0-338

(base) jeff:cpcli/ $ echo $USER                                                                                                              
jeff
(base) jeff:cpcli/ $ login_user=$(logname 2>/dev/null || echo $SUDO_USER)                                                                    
(base) jeff:cpcli/ $ echo $login_user                                                                                                        
root
(base) jeff:ieam/ $ logname                                                                                                          
root
(base) jeff:ieam/ $ echo $SUDO_USER                                                                                                

Have given Docker Full Disk Access

  "2021-05-28 09:00:05:   Start node configuration/registration for node jeffs-mbp.",
  "2021-05-28 09:00:07:   Start service auto configuration for IBM/ibm.helloworld.",
  "2021-05-28 09:00:07:   Complete service auto configuration for IBM/ibm.helloworld.",
  "2021-05-28 09:00:07:   Complete node configuration/registration for node jeffs-mbp.",
  "2021-05-28 09:00:07:   Start policy advertising with the Exchange for service IBM/ibm.helloworld.",
  "2021-05-28 09:00:07:   Complete policy advertising with the Exchange for service IBM/ibm.helloworld.",
  "2021-05-28 09:00:48:   Node received Proposal message using agreement 812e6c1d0c20d6dfc660ac8d2ee41096a3c7ff1f9fb316eb67ebb88a16f4cbe8 for service IBM/ibm.helloworld from the agbot IBM/agbot.",
  "2021-05-28 09:01:00:   Agreement reached for service ibm.helloworld. The agreement id is 812e6c1d0c20d6dfc660ac8d2ee41096a3c7ff1f9fb316eb67ebb88a16f4cbe8.",
  "2021-05-28 09:01:00:   Start dependent services for IBM/ibm.helloworld.",
  "2021-05-28 09:01:00:   Start workload service for IBM/ibm.helloworld.",
  "2021-05-28 09:01:00:   Image loaded for IBM/ibm.helloworld.",
  "2021-05-28 09:01:07:   Error starting containers: API error (500): error while creating mount source path '/private/var/tmp/horizon/horizon1/ess-auth/812e6c1d0c20d6dfc660ac8d2ee41096a3c7ff1f9fb316eb67ebb88a16f4cbe8': mkdir /private/var/tmp/horizon/horizon1/ess-auth/812e6c1d0c20d6dfc660ac8d2ee41096a3c7ff1f9fb316eb67ebb88a16f4cbe8: operation not permitted",
  "2021-05-28 09:01:08:   Start terminating agreement for ibm.helloworld. Termination reason: service terminated",
  "2021-05-28 09:01:08:   Complete terminating agreement for ibm.helloworld. Termination reason: service terminated",
  "2021-05-28 09:01:08:   Workload destroyed for ibm.helloworld",
  "2021-05-28 09:01:08:   Error handling ReplyAck message. Unable to retrieve single agreement 812e6c1d0c20d6dfc660ac8d2ee41096a3c7ff1f9fb316eb67ebb88a16f4cbe8 from database for ReplyAck message.",
  "2021-05-28 09:01:49:   Node received Proposal message using agreement 7c08d6573d6900758ae48488f4b27b011f4d357f0290166396e4f35cccfa4cd3 for service IBM/ibm.helloworld from the agbot IBM/agbot.",
  "2021-05-28 09:02:00:   Agreement reached for service ibm.helloworld. The agreement id is 7c08d6573d6900758ae48488f4b27b011f4d357f0290166396e4f35cccfa4cd3.",
  "2021-05-28 09:02:00:   Start dependent services for IBM/ibm.helloworld.",
  "2021-05-28 09:02:00:   Start workload service for IBM/ibm.helloworld.",
  "2021-05-28 09:02:01:   Image loaded for IBM/ibm.helloworld.",
  "2021-05-28 09:02:08:   Error starting containers: API error (500): error while creating mount source path '/private/var/tmp/horizon/horizon1/ess-auth/7c08d6573d6900758ae48488f4b27b011f4d357f0290166396e4f35cccfa4cd3': mkdir /private/var/tmp/horizon/horizon1/ess-auth/7c08d6573d6900758ae48488f4b27b011f4d357f0290166396e4f35cccfa4cd3: operation not permitted",
  "2021-05-28 09:02:08:   Start terminating agreement for ibm.helloworld. Termination reason: service terminated",
  "2021-05-28 09:02:08:   Complete terminating agreement for ibm.helloworld. Termination reason: service terminated",
  "2021-05-28 09:02:08:   Workload destroyed for ibm.helloworld",
  "2021-05-28 09:02:08:   Error handling ReplyAck message. Unable to retrieve single agreement 7c08d6573d6900758ae48488f4b27b011f4d357f0290166396e4f35cccfa4cd3 from database for ReplyAck message.",
  "2021-05-28 09:02:49:   Node received Proposal message using agreement f9b12fcb9d40b40cb3baf8f87e789bb8d7b25105d7df2db85de26e212c73a985 for service IBM/ibm.helloworld from the agbot IBM/agbot.",
  "2021-05-28 09:03:01:   Agreement reached for service ibm.helloworld. The agreement id is f9b12fcb9d40b40cb3baf8f87e789bb8d7b25105d7df2db85de26e212c73a985.",
  "2021-05-28 09:03:01:   Start dependent services for IBM/ibm.helloworld.",
  "2021-05-28 09:03:01:   Start workload service for IBM/ibm.helloworld.",
  "2021-05-28 09:03:01:   Image loaded for IBM/ibm.helloworld.",
  "2021-05-28 09:03:08:   Error starting containers: API error (500): error while creating mount source path '/private/var/tmp/horizon/horizon1/ess-auth/f9b12fcb9d40b40cb3baf8f87e789bb8d7b25105d7df2db85de26e212c73a985': mkdir /private/var/tmp/horizon/horizon1/ess-auth/f9b12fcb9d40b40cb3baf8f87e789bb8d7b25105d7df2db85de26e212c73a985: operation not permitted",
  "2021-05-28 09:03:08:   Start terminating agreement for ibm.helloworld. Termination reason: service terminated",
  "2021-05-28 09:03:08:   Complete terminating agreement for ibm.helloworld. Termination reason: service terminated",
  "2021-05-28 09:03:09:   Workload destroyed for ibm.helloworld",
  "2021-05-28 09:03:09:   Error handling ReplyAck message. Unable to retrieve single agreement f9b12fcb9d40b40cb3baf8f87e789bb8d7b25105d7df2db85de26e212c73a985 from database for ReplyAck message.",
  "2021-05-28 09:03:10:   Node received Proposal message using agreement ff0a625f905472cac7c2fe77fa1e82d9aa9395ec23f7b35f1b17c94321bce09f for service IBM/ibm.helloworld from the agbot IBM/agbot.",
  "2021-05-28 09:03:21:   Agreement reached for service ibm.helloworld. The agreement id is ff0a625f905472cac7c2fe77fa1e82d9aa9395ec23f7b35f1b17c94321bce09f.",
  "2021-05-28 09:03:21:   Start dependent services for IBM/ibm.helloworld.",
  "2021-05-28 09:03:21:   Start workload service for IBM/ibm.helloworld.",
  "2021-05-28 09:03:21:   Image loaded for IBM/ibm.helloworld.",
  "2021-05-28 09:05:28:   Start node unregistration.",
  "2021-05-28 09:10:23:   Start node unregistration.",
  "2021-05-28 09:10:23:   Error unregistering the node. The node must be in 'configured' or 'configuring' state in order to unconfigure it.",
  "2021-05-28 09:13:54:   Start terminating agreement for ibm.helloworld. Termination reason: service start timeout",
  "2021-05-28 09:13:54:   Complete terminating agreement for ibm.helloworld. Termination reason: service start timeout",
  "2021-05-28 09:13:55:   Workload destroyed for ibm.helloworld",
  "2021-05-28 09:14:36:   Start node unregistration.",
  "2021-05-28 09:14:36:   Error unregistering the node. The node must be in 'configured' or 'configuring' state in order to unconfigure it.",
  "2021-05-28 09:14:55:   Start node unregistration.",
  "2021-05-28 09:14:55:   Error unregistering the node. The node must be in 'configured' or 'configuring' state in order to unconfigure it.",
  "2021-05-28 09:15:23:   Start node unregistration.",
  "2021-05-28 09:15:23:   Error unregistering the node. The node must be in 'configured' or 'configuring' state in order to unconfigure it.",
  "2021-05-28 09:19:52:   Start node unregistration.",
  "2021-05-28 09:19:52:   Error unregistering the node. The node must be in 'configured' or 'configuring' state in order to unconfigure it.",
  "2021-05-28 09:19:59:   Start node unregistration.",
  "2021-05-28 09:19:59:   Error unregistering the node. The node must be in 'configured' or 'configuring' state in order to unconfigure it.",
  "2021-05-28 14:47:02:   Start upgrading service IBM/ibm.helloworld from version 1.0.0 to version 1.0.0.",
  "2021-05-28 14:47:03:   Complete upgrading service IBM/ibm.helloworld from version 1.0.0 to version 1.0.0.",
  "2021-05-28 14:47:03:   Start policy advertising with the Exchange for service IBM/ibm.helloworld.",
  "2021-05-28 14:47:03:   Complete policy advertising with the Exchange for service IBM/ibm.helloworld."

**Comment by linggao** [comment]
In most cases on Mac, $USER and `logname` should be the same. When the use uses `sudo`, the $USER will be root and the $SUDO_USER will be the user login name. In `horizon-container` command, it changes the owner for `/private/var/tmp/horizon/horizon1` and its subdirectories to the user login name in order for the service container to access the ess auth etc. 
But the case for this PR, the `logname` is root which is different. The shell is zsh instead bash.
