### ISSUE TITLE
Add MS deployment and mgmt to anax

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#257]
Anax needs to handle MS deployment info separately from workload deployment info. The MS deployment info can include 0, 1, or multiple containers. (E.g.gNetspeed has no MS container, PWS has 2: culex and fwweather.)

**Comment by dabooz** [comment]
The implementation design of this issue can be found here underneath the section for issue 257: https://docs.google.com/document/d/1jr8X0x6k_ahRvt4gOWQss73ba26-npkl3aGlQj87T7A/edit#heading=h.ckvsqm9pz7lr

**Comment by linggao** [comment]
PR: https://github.com/open-horizon/anax/pull/300
