### ISSUE TITLE
Add new workload definition support to agbot

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#258]
The agbot needs to get the workload info from a combination of the policy file and the referenced workload definitions in the exchange.

**Comment by linggao** [comment]
Built in deb 2.3.0

**Comment by dabooz** [comment]
The implementation design notes for this issue can be found underneath the section for issue 258, here: https://docs.google.com/document/d/1jr8X0x6k_ahRvt4gOWQss73ba26-npkl3aGlQj87T7A/edit#heading=h.ckvsqm9pz7lr
