### ISSUE TITLE
Create sample service that uses secrets manager

### ISSUE THREAD

**Issue by LiilyZhang** [open-horizon/anax#2592]
Create a "HelloSecrets" as example service to demonstrate how service use secrets manager

Example service will be added to /examples repo:
Related issue: https://github.com/open-horizon/examples/issues/442

**Comment by Isabel-Gan** [comment]
Hello! I can work on this

**Comment by Isabel-Gan** [comment]
Waiting on PR #2585 to be able to test the new service with the API
