### ISSUE TITLE
The user private secrets are not working correctly in agbot API

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2600]
The user private secrets are not working correctly in the secure_api and therefore it is affecting the CLI.
`hzn secretsmanager secret list user/userdevadmin` came back with exists:false
The URL `org/userdev/secrets/user` should have returned a 400...bad request. the URL `org/userdev/secrets/user/userdevadmin` should return a 404 or 200 with a list.

**Comment by Isabel-Gan** [comment]
Hello! I can work on this
