### ISSUE TITLE
Optimization: Make sure all deployment policies are searched before deployment policies searched again

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#2609]

**Comment by dabooz** [comment]
@dlarson04 Did a number of scaling tests on this code to ensure that:

It doesn't affect small scale/demo environments. Agreements are still completed fairly quickly.
While some scale scenarios perform slower (i.e. some nodes take longer to get into agreement) than they used to, the overall experience of how quickly agreements can be completed is more balanced than it was before resulting is better overall response times to get into an agreement.
New nodes being targetted by new policies that arrive in the system during heavy agreement creation are not lost.
