### ISSUE TITLE
Add lines and variables to all-in-1 template files so e2edev can use them directly

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2637]
- [x] (Bruce) So e2edev doesn't need its own copy of these template files (which causes problems when there are updates to all-in-1), add lines and variables to all-in-1 template files so e2edev can use them directly. Also made these unrelated enhancements along the way:
  - [x] Enable sdo variables `EXCHANGE_INTERNAL_RETRIES` and `EXCHANGE_INTERNAL_INTERVAL` to be overridden
  - [x] Move unregistration earlier, so it is not affected by the mgmt hub components being changed
  - [x] Add a skip registration flag
  - [x] Change all uses of `hzn voucher ...` to `hzn sdo voucher ...`
  - [x] Modify test-sdo.sh to work on external nodes
- [x] (Ling) Modify e2edev to set the correct variables and use the `css-tmpl.conf` and `agbot-tmpl.json` files from all-in-1.

These were the differences:

```
 $ grep -v -E '^#' test/docker/fs/etc/edge-sync-service/css-tmpl.conf | grep -v -E '^$' | diff - ~/devops/mgmt-hub/css-tmpl.conf
2a3
> UnsecureListeningPort 8080
4,5d4
< UnsecureListeningPort 8880
< CommunicationProtocol HTTP
8,11c7,9
< PersistenceRootPath /tmp/persist
< LogLevel TRACE
< LogRootPath /tmp
< LogTraceDestination stdout,glog
---
> CommunicationProtocol HTTP
> LogLevel INFO
> LogTraceDestination stdout
13d10
< TraceRootPath /tmp/trace
15d11
< MongoAuthDbName d_edge
```

```
$ diff test/docker/fs/etc/agbot/agbot-tmpl.json ~/devops/mgmt-hub/agbot-tmpl.json 
17c17
<         "AgreementTimeoutS": 300,
---
>         "AgreementTimeoutS": 360,
23,24c23,24
<         "NewContractIntervalS": 10,
<         "ProcessGovernanceIntervalS": 10,
---
>         "NewContractIntervalS": 5,
>         "ProcessGovernanceIntervalS": 5,
26c26
<         "ExchangeURL": "http://exchange-api:8080/v1",
---
>         "ExchangeURL": "${HZN_TRANSPORT}://exchange-api:8080/v1",
30c30
<         "ExchangeHeartbeat": 10,
---
>         "ExchangeHeartbeat": 5,
37c37
<         "CheckUpdatedPolicyS": 15,
---
>         "CheckUpdatedPolicyS": 7,
44,49c44
<         "AgreementBatchSize": 1300,
<         "RetryLookBackWindow": 900,
<         "MMSGarbageCollectionInterval": 20,
<         "Vault": {
<             "VaultURL": "${HZN_VAULT_URL}"
<         }
---
>         "AgreementBatchSize": 1300
```

**Note:** `Partitions` and `ExchangeVersionCheckIntervalM` are not used by the agbot, so they have been removed.

**Comment by linggao** [comment]
I am waiting on https://github.com/open-horizon/devops/pull/85
