### ISSUE TITLE
Policy mismatch error

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#270]
I installed snap revision 125 on the device which has multi-bc stage2 support while the staging agbots were  on snap revision 123. Could not make agreement because of the following error.
```
Jun 28 13:06:02 vs3 snap[14117]: E0628 13:06:02.187582   14153 protocol.go:314] AbstractProtocol (Citizen Scientist): Protocol Citizen Scientist decide on proposal received error, producer policy from proposal is not one of our current policies, rejecting proposal: Policy matching Name: Policy for sdr Version: 2.0
...
Jun 28 13:06:02 vs3 snap[14117]: ], error is AgreementProtocol [Agreement Protocol name: Citizen Scientist, Blockchains:BC Name: bluehorizon, BC Type: ethereum,] mismatch with [Agreement Protocol name: Citizen Scientist, Blockchains:]
Jun 28 13:06:02 vs3 snap[14117]: I0628 13:06:02.187692   14153 policy_manager.go:298] Policy Manager: Agreement tracking map[Policy for location:Count: 0  Policy for netspeed:Count: 0  Policy for sdr:Count: 0 ]
Jun 28 13:06:02 vs3 snap[14117]: E0628 13:06:02.187725   14153 producer_protocol_handler.go:136] Base Producer Protocol Handler (Citizen Scientist): respond to proposal with error: Protocol Citizen Scientist decide on proposal received error, producer policy from proposal is not one of our current policies, rejecting proposal: Policy matching Name: Policy for sdr Version: 2.0

```

**Comment by linggao** [comment]
The other way works.  The agbot has snap revision 125 (latest), the device has 123.  I tried the following cases on the agbot policy files and both had agreement finalized.
```  
"agreementProtocols": [
    {
      "name": "Citizen Scientist"
    }
  ],
```
and
``` 
 "agreementProtocols": [
    {
      "name": "Citizen Scientist",
            "blockchains": [
                {
                    "type": "ethereum",
                    "name": "bluehorizon"
                }
            ]
    }
  ],
```

**Comment by dabooz** [comment]
The problem is that the agbot didnt put the correct device policy into the proposal. Instead of putting in the device's original policy, it JSON marshalled a policy (based on the agbot's old policy schema) into the proposal which will drop any fields added to the policy schema in the stage 2 code. Thinking about the fix now.

**Comment by linggao** [comment]
Built in snap revision 126 (arm) and 127 (x86), version 2.0.17.

**Comment by linggao** [comment]
Tested with snap 127 (2.0.17) on the device and snap 123 (2.0.15) on the agbot, got the same error.

**Comment by linggao** [comment]
Need to put the snap on the agbot in order to make it work.
So the workaround is to install the snap on the agbot first.
