### ISSUE TITLE
Clean up configuration files; distinguish b/n envvars and file configuration

### ISSUE THREAD

**Issue by michaeldye** [open-horizon/anax#273]
There is a lot of duplication between anax "edge" and "agbot" configuration in `anax.json`. There is also configuration as envvars in `/etc/default/horizon` (when using the `deb` packaging). We should clean up duplication in the config file and define config that should be envvars vs. in config files. There isn't an agreed upon standard in the world for this, but I think these guidelines are a good start for our project:

- use envvars for values that meet any of these criteria: 1) ones that shouldn't ever be checked into a repo; 2) ones that aren't be changeable without restarting the Anax process; 3) ones that are specific to a system
- use json config files in `/etc/horizon/` (either `anax.json` now or others in the future) for: 1) config that can have values change during execution of the process and the process will adopt them during exec; 2) config that users shouldn't have to tweak but might want to (like timeouts)

@linggao is interested, specifically, in making some of the destination URLs like `ExchangeURL` into envvars.

**Comment by linggao** [comment]
I reason I am asking moving `ExcchangeURL` into envvars file is because in order to make anax run against staging I have to change the CMTN_DIRECTORY_VERSION in the environment file and the ExchangeUrl in anax.json file.

**Comment by michaeldye** [comment]
Also, we need to modify the code to not use `SNAP_COMMON` so we can get rid of the envvar for it. If it makes sense to make a `HORIZON_DATA_ROOT` envvar or something that is the root of a filesystem tree to an assumed structure for the db, policy files, etc. we can do that. The place this stuff lives on the linux fs is `/var/horizon`; `/usr/horizon` is for content that is treated like code (the anax binary itself, helper scripts, and contracts)

**Comment by bmpotter** [comment]
Mike,

According to your definitions in the description of this issue about what belongs in env vars and what belongs in the config files, it sounds to me like the exchange url really belongs as an env var. Do you agree?
