### ISSUE TITLE
Single anax config file that is reread on registration

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2756]
The anax config file situation should be cleaned up. There are currently 2 different config files, and they aren't both read (or reread) at all of the right times. There are several improvements that are all related:

- [ ] Use a config file framework that handles multiple config files in precedent order and produces consolidated internal map that honors that precedence. Use this capability to bundle a complete `anax.json` file that contains default values for every config parameter. This then enables the user to specify a minimal `/etc/horizon/anax.json` that contains only the config parameters he/she wants to override (like exchange url, etc.)
- [ ] With the bullet above supported, start phasing out `/etc/default/horizon` so there is only 1 kind of config file for anax.
- [ ] Have the agent reread `/etc/horizon/anax.json` on registration, so changes to mgmt hub values like exchange url or the cert are picked up.

**Comment by LiilyZhang** [comment]
No longer needed
