### ISSUE TITLE
Hardcode issue on command "hzn secretsmanager secret read"

### ISSUE THREAD

**Issue by cdyq** [open-horizon/anax#2770]
**Describe the bug**
Hardcode issue on command "hzn secretsmanager secret read"

**To Reproduce**
Steps to reproduce the issue:
Use hzn secretsmanager command read a non-exist secret (eg: hzn secretsmanager secret read 1234)

**Expected behavior**
All strings should be translated
eg:
![image](https://user-images.githubusercontent.com/25783969/129859452-5a2fdc9d-d8dc-49e2-877e-401988c9f94c.png)

**Actual result**
The string display as english
![image](https://user-images.githubusercontent.com/25783969/129859588-c4c803e4-45b6-4f7a-acfe-dff902fc9b9e.png)

**ENV**
horizon_2.29.0-552_amd64.deb
horizon-cli_2.29.0-552_amd64.deb

**Comment by linggao** [comment]
@bencourliss this is because the agbot image does not have the translated messages. Please make sure run `make i18n-catalog` to create the message catalogs before building anax.

**Comment by cdyq** [comment]
Working fine on latest env
horizon_2.29.0-585_amd64.deb
horizon-cli_2.29.0-585_amd64.deb
![image](https://user-images.githubusercontent.com/25783969/131859451-0ef041b4-f037-4f64-8c20-237376b8e0bc.png)
