### ISSUE TITLE
non-root user cannot list a specific org level secret

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2774]

**Comment by linggao** [comment]
depends on https://github.com/open-horizon/vault-exchange-auth/issues/25

**Comment by linggao** [comment]
https://github.com/open-horizon/vault-exchange-auth/issues/25 fixed the case where the user credential does not use `iamapikey`.  The `iamapikey` case still does not work.

**Comment by dabooz** [comment]
Created https://github.com/open-horizon/vault-exchange-auth/issues/27 to enable ACL recreation on login in the vault auth plugin.
