### ISSUE TITLE
Hardcode issue on command "hzn sdo key create"

### ISSUE THREAD

**Issue by cdyq** [open-horizon/anax#2804]
**Describe the bug**
Hardcode issue on command "hzn sdo key create"

**To Reproduce**
Steps to reproduce the issue:
Use hzn sdo key create command to create a key with existing name (eg: hzn sdo key create key.json)

**Expected behavior**
All strings should be translated
eg:
![image](https://user-images.githubusercontent.com/25783969/131101804-fcebf761-3d4d-48ff-91c0-c38ec21d2466.png)

**Actual result**
The string display as english
![image](https://user-images.githubusercontent.com/25783969/131101698-a2f1d01e-fc8d-4299-abee-93482b6712c7.png)

**HZN**
horizon_2.29.0-572_amd64.deb
horizon-cli_2.29.0-572_amd64.deb

**Images**
#image_agbot: amd64_agbot:2.29.0-572
#image_exchange: amd64_exchange-api:2.85.0-510
#image_css: amd64_cloud-sync-service:1.6.6-572
#image_sdo: sdo-owner-services:1.11.11-420
#image_ui: edge-ui-amd64:1.5.0-554
#image_vault: amd64_vault:1.0.0-147
#image_kubectl: amd64_edge-sidecar:4.3.0-46

#image_ess: amd64_edge-sync-service:1.6.6-572
#image_anax_k8s: amd64_anax_k8s:2.29.0-572
#image_anax: amd64_anax:2.29.0-572

**Comment by cdyq** [comment]
Use the same command can't verify this defect as the English string is updated, please see the screenshot.
![image](https://user-images.githubusercontent.com/25783969/131769528-14634aec-d3c6-423e-85fc-db4722a6de9d.png)

**Comment by linggao** [comment]
The last PR changed the text. We need to get it into the translation cycle for next release.

**Comment by linggao** [comment]
I will close this issue because it is not hard coded. It just missed the translation.
