### ISSUE TITLE
"hzn service log" command slow to provide output

### ISSUE THREAD

**Issue by omega2733** [open-horizon/anax#2826]
Version: 2.29.0-586

Issue:

When running `hzn service log <container>` we no longer produce any results on RHEL 8.x with the latest image, it just hangs with zero return. But we can run docker logs <container> and produce output to prove the service is running and as a workaround.

[ppc64-service-log-issue.txt](https://github.com/open-horizon/anax/files/7106371/ppc64-service-log-issue.txt)

OS: RHEL 8.2/8.3/8.4 impacted.

**Comment by omega2733** [comment]
Did some more testing, this impacts RHEL 8.1/8.2/8.3/8.4 on any architecture. This works fine on Ubuntu distros etc., appears to only be impacting RHEL.

**Comment by Polber** [comment]
After more testing, it was determined that the output does eventually stream, but it takes much longer than it used to. This has been switched to a performance issue.
