### ISSUE TITLE
Remove CS Protocol version 1 code, whisper and snap references

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#284]
Code was added to maintain compatibility between old and new devices and agbots. Old means a version of Horizon that is running at a code level pre issue 233, where Citizen Scientist protocol version 2 was added. The code would be greatly simplified if only version 2 were supported.

For removing whisper references:
- remove deprecated fields in the agreement protocol message structs
- remove comments about field msgEndPoint in node and agbot exchange resource being the whisper id
- remove/change any other references to whisper or variable names called whisper

And run lint and conform to results.

**Comment by bmpotter** [comment]
done
