### ISSUE TITLE
Modify anax docs index.md to show index of docs

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/anax#2867]
Remove the current contents of /docs/index.md and replace with a hyperlinked list of the documents in /docs showing their title and short description.

**Comment by joewxboy** [comment]
Mention @joewxboy and @Rene-Ch1 when you are ready to submit a PR.

**Comment by Abhijay007** [comment]
@joewxboy I want to work on this if it is available, and can please Provide more detail about it : )

**Comment by joewxboy** [comment]
Hmm, it looks like it was completed back in October last year.  I guess they forgot to link the issue to the PR.
