### ISSUE TITLE
Change OpenHorizon references in docs to Open Horizon

### ISSUE THREAD

**Issue by benzim** [open-horizon/anax#2927]
Several of the documentation files refer to Open Horizon as `OpenHorizon`. These should be changed to `Open Horizon`.

**Comment by anhuong** [comment]
Hello, I am new to this project and to open source contributing but I would like to pick up this issue!

**Comment by joewxboy** [comment]
Sorry, @anhuong I just saw your comment.  Are you still interested?

**Comment by johnwalicki** [comment]
From the top of the docs directory, `find . -name "*.md" | xargs grep -i OpenHorizon`

If you ignore the cases where the literal `openhorizon` is correct, there are **zero** cases where `OpenHorizon` appears.

I think this ticket can be closed.

**Comment by johnwalicki** [comment]
At best, there is one file where the literal `Open Horizon` could be replaced with the keyword `{{site.data.keyword.edge_notm}}`

See ./getting_started/developer_learning_path.md
```
a. Get an idea of what Open Horizon is all about
```

**Comment by benzim** [comment]
Yeah, I fixed this issue in those PR: https://github.com/open-horizon/anax/pull/2928. I forgot to close the issue.

**Comment by joewxboy** [comment]
Thanks, closing.
