### ISSUE TITLE
MMS CLI should be usable within a container deployed to k8s

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#2952]
The hzn mms CLI commands are kicked out of ./cli/hzn.go when run inside a container that is deployed within k8s. While it is true that the MMS is not supported in edge cluster service deployment usecases yet, that does not need to prevent the use of hzn mms commands within k8s. The fix is simple, just remove the check in ./cli/hzn.go that disables the hzn mms commands.

A good example of using the hzn mms CLI within a k8s hosted container is kubeflow, which is used to enable CI/CD pipelines for AI/ML model creation. When the pipeline has a newly trained model, it should be able to use the MMS CLI to upload the model to the management hub for deployment to edge devices.

**Comment by LiilyZhang** [comment]
verified
