### ISSUE TITLE
agbot not give new agreement after device got deleted from the exchange

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#299]
1. start anax and register for an agreement that uses property and counterpartyproperty attributes to points to one agbot.
2. got an agreement from that agbot
3. restart anax, delete the device from the exchange and re-register the device with the same device id, register for an agreement for the same service.
4. the device does not get new agreement for about 30 minutes.

**Comment by dabooz** [comment]
This is a 2 year old issue. The closest I can get to recreate this (something like step 3) with current code is to get a device registered and running workloads, and then:
sudo apt-get purge --auto-remove bluehorizon.

Everything gets cleaned up on the device. I was able to re-install the deb packages, and register the device again using policy. The agbot sent agreement proposals as expected. The originally reported problem appears to be gone.

However, I did notice a small thing at the end of the apt-get purge output:
dpkg: warning: while removing horizon, directory '/var/run/horizon' not empty so not removed
This error message is pointing out that /var/run/horizon/essapi.sock has not been cleaned up by the horizon.postrm script that runs when the horizon package is uninstalled.

This is something we can fix in the deb packager: https://github.com/open-horizon/horizon-deb-packager/issues/260
