### ISSUE TITLE
Add the "anaxcopydocs" GHA 

### ISSUE THREAD

**Issue by Sukriti-sood** [open-horizon/anax#3044]
Adding the __anaxcopydocs__ GHA and configure it to copy the docs folder content to  `open-horizon.github.io/docs/anax`

I would like work to on this..

**Comment by joewxboy** [comment]
Thanks, @Sukriti-sood 

* Let's rename the GHA to just "Copy Docs" if spaces are allowed, or "CopyDocs" if not.
* Let's run the GHA automatically every time there's a merge containing files in `/docs` if possible, otherwise on every merge.

**Comment by joewxboy** [comment]
@dabooz FYI ... this is the last task we needed to perform that will merge the anax developer docs with the main documentation web site.

**Comment by joewxboy** [comment]
@Sukriti-sood and @Rene-Ch1 Once this is complete and merged, let's evaluate how to best link to the anax docs on the main documentation web site.

**Comment by Sukriti-sood** [comment]
Thanks @joewxboy for assigning me, i will open pr soon.

**Comment by joewxboy** [comment]
GHA is implemented.  Closing this issue.

**Comment by johnwalicki** [comment]
I don't yet see a docs/anax folder in the 
https://github.com/open-horizon/open-horizon.github.io/tree/master/docs
How does the GHA get kicked off the first time?

**Comment by Sukriti-sood** [comment]
we need to make some changes in docs foldrr of anax repo, I will create pr
for same.
