### ISSUE TITLE
Anax arm64 Docker image is showing linux/amd64 platform

### ISSUE THREAD

**Issue by bencourliss** [open-horizon/anax#3063]
**Describe the bug**
The anax Docker images that are created when the ARCHITECTURE is set to arm64 do not appear to be actual arm64 images. Doing a docker image inspect on the supposed arm64 image shows `"Architecture": "amd64"`

**Expected behavior**
The arm64_anax and arm64_anax_k8s images should show `"Architecture": "arm64"` when doing a docker image inspect.

**Comment by johnwalicki** [comment]
podman has different multi arch build parameters.
This is good. In the future,  we might use podman in the build pipeline.
