### ISSUE TITLE
Add pattern support to agbot and anax

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#308]
https://drive.google.com/open?id=1SsryW0_3FaO29hdINoqr9R85DQ_7PvdGylISOgeDeYA

**Comment by dabooz** [comment]
Notes:

1. This code REQUIRES exchange v1.33.
2. Old style policy files are not supported. Either use the new split microservice based policy files or use patterns.
3. agbot policy files MUST be placed in a subdirectory named the same as the org that the agbot is serving. The subdirectory goes under the configured PolicyPath directory.
4. Blockchain agreements and HA nodes have NOT been tested with this code. That will come later.
5. To serve a pattern based workload, the agbot MUST have the org and pattern configured to it in the exchange.
