### ISSUE TITLE
Add service update policy choices

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#311]
- policy choice for when to update workloads and required services: immediately, at next agreement negotiation, specified time, never, etc.
- and add back in the agbot spacing out the updates of different edge nodes (today this spacing out of updates only applies to HA groups)
- when a pattern or policy is updated to deploy a new version of the service, this change is detected and the nodes are immediately updated to the new versions. It doesnt work this way if a new version of a required service is deployed. In the case of a new required service, the default behavior is to do nothing.

**Comment by dabooz** [comment]
design document start:https://docs.google.com/document/d/1ZkMS0Q__ZgbqZrHv5PBc_FmjoyLFDUF7zUEPo08TP2I
