### ISSUE TITLE
MMS fails to find service if it contains an underscore

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#3155]
### Describe the bug.

Issue https://github.com/open-horizon/anax/issues/2446 was supposed to address the case where MMS would send models to the agent if the service name contained underscores. That change works if the agent is registered when the model is updated. However, it did not address the case where the model exists a new agent is registered with that service.

Need to fix that path too

### Describe the steps to reproduce the behavior.

Publish a MMS with a destination policy of a service containing an underscore
Register a new agent so that that service with an underscore is running

Problem: Agent will not receive model file

### Expected behavior.

Agent should receive model file

### Operating Environment

Ubuntu 20.04

**Comment by LiilyZhang** [comment]
verified
