### ISSUE TITLE
Bug:  nmp and node pattern matching failed for hzn commands

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#3202]
### Describe the bug.

When the nmp contains pattern names that does not proceed with orgs, the following checking failed.
hzn exchange node mgmt list <node_name>
hzn exchange nmp list --nodes <nmp_name>
hzn exchange nmp add -f <nmp_file> <nmp_name> --appliesTo

### Operating Environment

ALL

**Comment by LiilyZhang** [comment]
verified
