### ISSUE TITLE
AgentAutoUpgrade: API and CLI to force an agent to reevaluate a NMP

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#3284]
When an agent upgrade is failed, provide a way to force the agent to reevaluate its NMPs so that the failed NMPs can be retried. 
- [x] agent API
- [x] hzn command to call the agent API
- [x] hzn exchange API to do it remotely

The design: 
- agent api: `/nodemanagement/reset[/{orgname}/{nmpname}]` -- set the status to 'waiting'.
- local (`hzn nmstatus reset [{nmpname}]`) -- call the agent API to turn the status to 'waiting'.
- remote (`hzn exchange node mgmt reset {nodename} [-p {nmpname]]`) -- set the nmp status for the node in the exchange to 'reset', the agent gets the change through the `/changes API`, it then turns the status to `waiting`.

**Comment by dlarson04** [comment]
In my opinion, ideally, the retry logic would happen automatically driven by something on the agent  and not requiring a user to issue any hzn command. Lilly mentioned a resend action within CSS that does this for MMS downloads
