### ISSUE TITLE
Agbot optionally cancel agreement if agreement in exchange disappears

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#330]
- Or it could check the node's agreement status in the exchange.
- Or if the node heartbeat in the exchange is very stale
- Also provide an anax api to cancel/unregister a microservice or pattern (remove fields in exchange so agbots won't find it, then explicitly cancel the agreements with the agbot) - moved to issue #369 .

This can be used as an alternative to data verification, or in addition to it.

**Comment by dabooz** [comment]
Issue #369 was opened to address the 3rd bullet in the description. This issue will only address the 1st 2 bullets.

**Comment by dabooz** [comment]
Design: https://docs.google.com/document/d/1iZ7Mfl6FwDrAb72yQpy44tlM0-i5uBJ8XXOquGrJ6Ms

**Comment by dabooz** [comment]
The PR for this issue also add tests for the node side API and fixes a problem where the configstate API doesnt verify (during the transition to configured) that workloadconfig exists for workloads in the node's pattern that need to be configured.

**Comment by dabooz** [comment]
The fix for this issue required exchange version 1.39.
