### ISSUE TITLE
hzn exchange users list should show lastActiveAt timestamp

### ISSUE THREAD

**Issue by SanjeevKGupta** [open-horizon/anax#3317]
### Is your feature request related to a problem? Please describe.

This is a small enhancement to the existing hzn exchange users list command .

### Describe the solution you'd like.

 Last time a user accessed the system across any org. Usually one user is in one org but it's possible that the same user can be in multiple orgs. Since it's about active user, latest activity coming from any org makes the user active. 

### Describe alternatives you've considered

may be process nodes registered by that user and use the latest **lastHeartbeat** of hzn exchange node list as a proxy by the user's edge-agent. 

### Additional context.

This is to remove/flag/clean inactive users and their nodes.

**Comment by LiilyZhang** [comment]
@SanjeevKGupta Can you open the issue on exchange board? Thanks!

**Comment by SanjeevKGupta** [comment]
Opened a new issue in exchange https://github.com/open-horizon/exchange-api/issues/636

**Comment by SanjeevKGupta** [comment]
Closing here.
