### ISSUE TITLE
suggest config and cert version be indicated on initial agent install

### ISSUE THREAD

**Issue by kmbarton423** [open-horizon/anax#3336]
Working with IEAM (build 908) testing auto upgrade functionality.
Noticed that the version following for a cert upgrade is properly indicated for the node:

hzn ex node list <node>
    "softwareVersions": {
      "certificate": "1.0.1",
      "config": "",
      "horizon": "2.30.0-908"
    },

I believe this behavior is true for a config upgrade as well.
But when you do a fresh install of the agent, the certificate and config versions are not indicated.
Would be helpful to have this information.

**Comment by kmbarton423** [comment]
recent observation:

after initial agent install, allowDowngrade=false is not honored for the first config and cert upgrade attempts
   scenario i ran was initial install with version 1.0.0 of both the config and cert
   nmp manifest was for version 0.x.x of the config and cert with allowDowngrade=false
   was surprise when the downgrade actually occurred

after the config and cert have been upgraded once, allowDowngrade=false is properly determining whether or not the upgrade should occur

**Comment by LiilyZhang** [comment]
To do list:
- [ ] `agent-install.sh` will need to inject version in config file and cert file
- [ ] download worker will need to inject version in config file and cert file (cover for both device and cluster cases)
- [ ] agent needs to read in cert version from certificate and update agent local db
- [ ] register will need to update versions in agent local db

**Comment by kmbarton423** [comment]
Confirmed fix good
