### ISSUE TITLE
Bug: On podman, agent in container stays in initiated state after upgrade 

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#3356]
### Describe the bug.

Run agent install on a RHEL8.6 or RHEL9 with podman.
Provision the anax in container using the --container flag
Go through the steps to upgrade the software from say 916 to 918

The agent gets upgrade successfully but the nmp status (and the agent eventlog never move out of `initiated`

on agent
```
[root@rhel9-edge1 tmp]# hzn version
Horizon CLI version: 2.30.0-918
Horizon Agent version: 2.30.0-918

From hzn eventlog list

  "2022-06-30 07:21:50:   New node management policy status created for policy dal-org/Upgrade918NMP.",
  "2022-06-30 07:21:53:   Node management status for dal-org/Upgrade918NMP changed to download started.",
  "2022-06-30 07:21:58:   Node management status for dal-org/Upgrade918NMP changed to downloaded.",
  "2022-06-30 07:25:03:   Node management status for dal-org/Upgrade918NMP changed to initiated."
```

```
hzn exchange nmp status dal-org/Upgrade918NMP
{
  "dal-org/rhel9-edge1.fyre.ibm.com_horizon1": "initiated",
  "dal-org/serer1.fyre.ibm.com_horizon1": "successful"
}
```

Doing the same scenario on a Ubuntu with docker (the serer1 node), the NMP status moves to `successful`

Note: Issue https://github.com/open-horizon/anax/issues/3298 was created to get the podman container to upgrade at all

### Describe the steps to reproduce the behavior.

See steps above

### Expected behavior.

Like on docker anax in container, the NMP status should move to `successful` after the upgrade

### Operating Environment

RHEL

**Comment by dlarson04** [comment]
[podman-and-docker-logs-issue-3356.tar.gz](https://github.com/open-horizon/anax/files/9020992/podman-and-docker-logs-issue-3356.tar.gz)

**Comment by linggao** [comment]
The following command got stuck in RHEL with podman and docker emulator.
````
cmd="agent-install.sh ..."
eval "$(${cmd} \
        2> >(Err_msg=$(cat); typeset -p Err_msg) \
        > >(Std_msg=$(cat); typeset -p Std_msg); \
        RC=$?; typeset -p RC)"
 ````
 It stuck at `docker run` command. 
 It works on all other platforms.
 
 The fix will be changing the way the agent-install.sh runs in agent-auto-upgrade.sh

**Comment by dlarson04** [comment]
verified in the 924 build
