### ISSUE TITLE
Bug: anax starts podman service containers without network services

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/anax#3401]
### Describe the bug.

The agent will start service containers on edge devices running Podman 4.x (I tried on Podman 4.0.1 / 4.0.2 / 4.0.3 / 4.1.1 )
I have configured it to use netavark and `podman network ls` shows podman bridge (not cni)

However these service containers cannot be reached from the network. Nor can dependent services talk to each other.

I see this incorrect behavior on both Fedora 36 (amd64) laptop and Fedora 36 (arm64) Raspberry Pi.

The agent will form an agreement and run the same service container workload on a Raspberry Pi arm64, Jetson Nano - (via Docker)

I can start the container manually on my Fedora 36 / podman systems (amd64 / arm64) and both can open a URL / port <http://localhost:1880>   So podman natively starts the container / networking just fine.  However the anax agent with podman does not.

I captured the `podman container inspect` output on one of the Fedora systems.  That allows a direct comparsion of native podman running the container vs how anax starts the container.

### Describe the steps to reproduce the behavior.

On a RHEL / Fedora / Podman system.
```
git clone git@github.com:open-horizon-services/service-node-red-hello-world.git
cd service-node-red-hello-world
make build
make run
make browse   (this will open a browser to the Node-RED editor)
make stop
make publish
echo Wait for the anax agent to form an agreement and start the container
make browse
```
The `make browse` will not load http://127.0.0.1:1880

### Operating Environment

RHEL / Fedora36 podman 4.x

**Comment by johnwalicki** [comment]
Just to be clear.  Anax starts the container and it runs fine.  The container just not reachable from the network.

Natively running `podman run -it -p 1880:1880 docker.io/walicki/service-node-red-hello-world_arm64:1.0.0` works fine and is reachable.

**Comment by dlarson04** [comment]
@johnwalicki   Was looking at this issue... Not sure what is going on yet, but if you change your service.definition.json to eliminate
```
"HostIP":"0.0.0.0"
```
it works for me on RHEL8.6. The interesting thing is that without HostIP specified, it still binds to 0.0.0.0 but now it works.
Not sure what is different

**Comment by johnwalicki** [comment]
@dlarson04 - Thanks for the investigation.
Indeed, I did notice the HostIP in my `podman container inspect`  diff between the anax-started container and the manually-started container.

I've verified that removing the "HostIP":"0.0.0.0" from the service.definition.json and republishing the service does allow anax to start the container and the network is available.

Snip of `podman container inspect abcdef` before:
```
			"Ports": {
				"1880/tcp": [
					{
						"HostIp": "0.0.0.0",
						"HostPort": "1880"
					}
				],
				"8080/tcp": null
			},
```
and after
```
			"Ports": {
				"1880/tcp": [
					{
						"HostIp": "",
						"HostPort": "1880"
					}
				],
				"8080/tcp": null
			},
```

**Comment by johnwalicki** [comment]
I don't understand enough about podman / netavark to determine if this is a bug in their implementation.

I've pushed a fix to my Open Horizon Services repos:
- https://github.com/open-horizon-services/service-node-red-hello-world/commit/705b11b2d0dfe87f13a4532f2c0e86cd294d7cb3
- https://github.com/open-horizon-services/service-node-red-object-detection/commit/fd61d9865e6d0323d7a5722d5daa12c44d04c976

**Comment by johnwalicki** [comment]
Closing issue with this workaround. I suspect that we will be back to this podman problem in future service definitions.
