### ISSUE TITLE
Bug: Edge cluster service didn't start if variables do not have default values

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#3407]
### Describe the bug.

Customer created a service using operatorsdk for helm charts. In the templates files, there were some variables that did not have default values. 

The customer could successfully create the operator and the service using `kubectl apply` commands but when he tried to deploy the service using IEAM, the operator started but the application itself did not start. 

I think Max said the variables ended up with nil values instead of empty strings. This prevented the service from starting

IEAM should be able to still start a service since `kubectl apply` commands could work

### Operating Environment

k3s cluster

**Comment by johnwalicki** [comment]
While you are improving the getK8sObjectFromYaml  function in client.go, see #3363 which is also related.
