### ISSUE TITLE
Feature Request: arm64 anax-in-container support / testing

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/anax#3441]
### Is your feature request related to a problem? Please describe.

The CI/CD pipeline builds arm64 anax-in-container for 2.30.x versions
We see them here:

- https://hub.docker.com/r/openhorizon/arm64_anax/tags

It doesn't build arm64 anax-in-container containers for 2.29.x

The IBM product release bundles should add these components when it supports 2.30.x

### Describe the solution you'd like.

`agent-install.sh --container` on arm64 should be supported / tested in the release bundles for the IBM product.

### Additional context.

This is mostly a @bencourliss and @dlarson04 request, potentially in support of the IBM product build process.

**Comment by dlarson04** [comment]
This has been implemented in https://github.com/open-horizon/anax/issues/3450

Closing
