### ISSUE TITLE
Bug: Need to support CRD-less kube operators for edge clusters

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#3445]
### Describe the bug.

It is possible to build a kube operator that has no CRDs. The agent's kube worker doesn't support this. Here is an example: https://github.com/skupperproject/skupper-operator/blob/main/bundle/manifests/1.0.0/skupper-operator.v1.0.0.clusterserviceversion.yaml

The ClusterServiceVersion yaml seems to describe all the aspects of operator.yaml, role bindings, etc, but all in a single file.

I know that ClusterServiceVersion is a newer concept in kube, but I haven't experimented with the operator SDK to see if it  enables the user to easily build this kind of operator. The skupper operator above might be an example of a hand built operator that we need to support, that's why I'm opening an issue that is separate from #3363 .

### Describe the steps to reproduce the behavior.

Try to deploy the skupper operator as a service, it will fail.

### Expected behavior.

Successful installation of the operator.

### Operating Environment

edge clusters

**Comment by SanjeevKGupta** [comment]
Updated the latest example link. The one referenced by David Booz above is non-existent now. https://github.com/skupperproject/skupper-operator/blob/main/bundle/manifests/1.1.1/skupper-operator.v1.1.1.clusterserviceversion.yaml
