### ISSUE TITLE
Bug: pollInterval is too long when there is a node policy change

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/anax#3473]
### Describe the bug.

A user runs `hzn policy update --input-file=/tmp/changes.json` to change the node policy.
Any new agreement / service container start is delayed for a really long time (70 seconds).

There is a UPDATE_TYPE_ALERT section in `changes/changes_worker.go` which updates the polling interval to (min + max)/ POLL_INTERVAL_ALERT_LEVEL
By default, this will be (20+120)/2 = 70.  Essentially for 70 seconds the edge node does nothing even though it has pending node policy or userinput changes.

Suggested fix would be to modify POLL_INTERVAL_ALERT_LEVEL from `2` to `4`

That will decrease the delay to 35 seconds.

### Describe the steps to reproduce the behavior.

`hzn policy update --input-file=/tmp/changes.json`

Watch the logs. The agent does a PUT to the exchange
```
I0923 19:53:01.206644      22 worker.go:585] MessageDispatcher: Handling Message (*events.NodePolicyMessage): event: UPDATE_POLICY
I0923 19:53:01.206762      22 worker.go:593] MessageDispatcher: Success handling message: propagated event to all workers
I0923 19:53:01.206809      22 worker.go:296] CommandDispatcher: Agreement received command (*agreement.NodePolicyChangedCommand): {event: UPDATE_POLICY}
I0923 19:53:01.206894      22 worker.go:296] CommandDispatcher: Governance received command (*governance.NodePolicyChangedCommand): {event: UPDATE_POLICY}
I0923 19:53:01.206908      22 worker.go:310] CommandDispatcher: Agreement handled command (*agreement.NodePolicyChangedCommand)
I0923 19:53:01.206929      22 worker.go:296] CommandDispatcher: ExchangeChanges received command (*changes.UpdateIntervalCommand): UpdateIntervalCommand: UpdateType: ALERT
I0923 19:53:01.206947      22 changes_worker.go:453] Exchange Changes Worker: Setting poll interval to alert level 70, max interval is 120, increment is 20.
I0923 19:53:01.206957      22 worker.go:310] CommandDispatcher: ExchangeChanges handled command (*changes.UpdateIntervalCommand)
I0923 19:53:01.206966      22 worker.go:338] CommandDispatcher: Agreement command processor blocking for commands
I0923 19:53:01.206976      22 worker.go:348] CommandDispatcher: ExchangeChanges command processor non-blocking for commands
I0923 19:53:01.207894      22 worker.go:310] CommandDispatcher: Governance handled command (*governance.NodePolicyChangedCommand)
```
Nothing meaningful happens in the log for 70 seconds, then:
```
I0923 19:54:11.207456      22 changes_worker.go:255] Exchange Changes Worker: looking for changes starting from ID 21402156
I0923 19:54:11.207536      22 changes.go:248] Exchange RPC getting 1000 changes since change ID 21402156 in orgs []
I0923 19:54:11.207601      22 rpc.go:984] Exchange RPC Invoking exchange POST at https://mgmt-hub-url/edge-exchange/v1/orgs/myorg/changes with {21402156 1000 []}
I0923 19:54:11.220034      22 governance.go:1400] GovernanceWorker: GovernanceWorker dispatching no work handler.
I0923 19:54:11.220088      22 governance.go:400] GovernanceWorker: governing pending agreements
I0923 19:54:11.221058      22 worker.go:348] CommandDispatcher: Governance command processor non-blocking for commands
I0923 19:54:11.464437      22 changes.go:286] Exchange RPC found 2 changes since ID 21402156 with latest change ID 21402179 in orgs []
```

### Operating Environment

Linux

**Comment by dlarson04** [comment]
I don't think I would change the POLL_INTERVAL_ALERT_LEVEL value because that is used in other situations and may have more consequences for large scale environments where thousands of agents could be impacted by a change on the exchange. I would vote for just setting the updateType to UPDATE_TYPE_RESET  in this case of executing the node policy update command to improve behavior for this one situation... that would be a more isolated change... since a user is on the device to execute this command, the user would see a more immediate effect

**Comment by johnwalicki** [comment]
I only see one use of `POLL_INTERVAL_ALERT_LEVEL` in the anax source tree, and only in change_worker.go :
https://github.com/open-horizon/anax/blob/af6f2d9b1251cc24f7c165af504c88e97ce8a34b/changes/changes_worker.go#L458

I think its safe, but definitely welcome a review of the change_worker.go functions. Today was my first look at that section of the code. I, too, considered changing the behavior from `UPDATE_TYPE_ALERT` to `UPDATE_TYPE_RESET` 

Net : it works out to `20` or `35` seconds of delay.

**Comment by dlarson04** [comment]
keep in mind too that the 70 seconds is worst case.... after it has backed off past 70 seconds... if you do an hzn register and then followed by hzn policy update in the next minute, the agreement will happen quickly ... additionally, for demo purposes (of if you do this alot) you can change the pollMaxInterval at the org level or for an individual node.

**Comment by dlarson04** [comment]
Another way to improve this scenario about changing policies is by  changing this line to UPDATE_TYPE_RESET instead of ALERT

https://github.com/open-horizon/anax/blob/master/changes/changes_worker.go#L157

I think this would have less ramifications than changing the POLL_INTERVAL_ALERT_LEVEL since other situations use the  UPDATE_TYPE_ALERT level. I think this  would be a better change

**Comment by johnwalicki** [comment]
Yes, changing that line achieves the same goal (pollInterval will be set to 20)
I've pushed another commit to the #3474  PR branch.
