### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by marhabac33** [open-horizon/anax#3496]
Link in the `About` section of [anax repo](https://github.com/open-horizon/anax) is broken.

Currently link is https://open-horizon.github.io/anax/

It should be 

https://open-horizon.github.io/docs/anax/docs/

**Comment by johnwalicki** [comment]
@marhabac33 I've assigned this issue to you.
If you could submit a PR, that would be fantastic.  Remember to follow the contribution guidelines of the Anax team.
They have a format for the commit messages.

**Comment by marhabac33** [comment]
@johnwalicki incorrect link is in the `About` section of the repo. I believe someone with the admin access need to update it. (hope opening an issue was the right thing to do)

<img width="1477" alt="Screen Shot 2022-10-13 at 8 41 24 PM" src="https://user-images.githubusercontent.com/8888996/195736988-ab4cd893-a2ea-4815-bec8-60857640ade1.png">

**Comment by johnwalicki** [comment]
I corrected the Anax github repo About to point to the Docs at https://open-horizon.github.io/docs/anax/docs/

**Comment by johnwalicki** [comment]
Thanks for the report and pointing out where the link was broken.  Sharp eye to detail ! Closing ticket.
