### ISSUE TITLE
Documentation: docs/index.md should include a Node Management section

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/anax#3508]
### What is the current documentation state?

The monthly Orphan Pages GHA report ran over in the open-horizon.github.io repo.
The results are posted in https://github.com/open-horizon/open-horizon.github.io/issues/321

It found 5 pages in the anax/docs tree that are not linked to by any other page.  No one would know to navigate to them.

We should improve the anax docs by adding a section to the index.md
https://github.com/open-horizon/anax/blob/master/docs/index.md
that introduces the Node Management features.

**Comment by dipesh-rawat** [comment]
@johnwalicki I'm interested to make the required changes for this. Could you please assign this issue to me?

**Comment by johnwalicki** [comment]
@dlarson04 and I will huddle on this documentation topic and figure out what to write.

**Comment by johnwalicki** [comment]
Fixed by #3615
