### ISSUE TITLE
Feature Request: FDO support

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#3522]
- [x] hzn voucher command
- [x] set HZN_FDO_URL in config files.
- [x] agent-install.sh
- [x] edgeNodeFiles.sh
- [x] Build FDO image and set it up in the management hub (Lorenzo, Ben)
- [x] documentation (Lorenzo)

**Comment by johnwalicki** [comment]
@lorenzoking  You might want to look at the PR that @linggao created - https://github.com/open-horizon/anax/pull/3548

**Comment by lorenzoking** [comment]
Thank you! I took a look and left a comment! @johnwalicki
