### ISSUE TITLE
Architecture : Add support to MacOS M1 arm64 arch

### ISSUE THREAD

**Issue by playground** [open-horizon/anax#3539]
### Open a issue in the Anax repo to update the agent-install.sh with the new microprocessor architecture.

https://github.com/open-horizon/anax/issues/3538

### Open a issue in the Anax repo to update the Makefiles with the new microprocessor architecture.

https://github.com/open-horizon/anax/issues/3538

### Open a issue in the Anax repo to add the agent binaries to [edgeNodeFIles.sh](https://github.com/open-horizon/anax/blob/master/agent-install/edgeNodeFiles.sh) so they publish to CSS

https://github.com/open-horizon/anax/issues/3538

### Open a issue in the Anax repo to update the Dockerfiles to build on the new microprocessor architecture.

https://github.com/open-horizon/anax/issues/3538

### Open a issue in the Anax repo to add the build pipelines so it arrives in [GitHub Releases](https://github.com/open-horizon/anax/releases)

https://github.com/open-horizon/anax/issues/3538

### Open a issue in the Documentation repo to update the docs for this new microprocessor architecture.

https://github.com/open-horizon/anax/issues/3538

### New microprocessor architecture Support Checklist

- [X] Update the agent-install.sh
- [X] Update the Makefiles
- [X] Update the agent binaries
- [X] Update the Dockerfiles
- [X] Update the build pipelines
- [X] Validate Examples on this new microprocessor architecture
- [X] Documentation updates to support this new microprocessor architecture
- [X] Test / Validate and modify existing tests for the anax binary on this microprocessor architecture

**Comment by johnwalicki** [comment]
This issue is completed.
