### ISSUE TITLE
Streamline anax api's for pattern registration

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#355]
The goal is for anax to use the info that are already in the exchange microservice/workload/pattern definitions, and to reduce the number of steps for some who is registering a node via the api for a pattern. My suggestions:

1. As far as the node entry in the exchange, the only requirement is that it exists (so the creds work). Anax should take care of deleting all previous agreements and overwriting the registration with the pattern name, etc. (It is anax that really knows what needs to be done here, so reg_all or other clients shouldn't be doing it.)
1. The `workload_version` value in the reg_all workload json files should be a range that specifies any version, instead of an exact version. Otherwise, when the user rolls out an updated version of the workload, in addition to adding that to the exchange and updating the pattern in the exchange, they have to update the workload json files on potentially 1000's of machines.
1. I should not have to register microservices via the /service api. Anax can figure out the microservices from the pattern. The only thing i should have to do is provide variable settings like i do in /workloadconfig for any MSs that need input (a lot of them don't).
1. You should have 2 different versions of the reg_with_api wiki page: 1 for the CS case in which they register individual microservices (the page will be very similar to what reg_with_api is now), and a different page for pattern registration (which includes the changes i list above).

**Comment by dabooz** [comment]
See the design doc here:https://docs.google.com/document/d/1ZclxhHZP7BcBESGcx5oAGUxyew2aj1vZ0ffRXeX-vXQ
This issue is only intended to provide support for Phase 0 in that design.
