### ISSUE TITLE
Bug: Full range of unicode should be supported in constraint language

### ISSUE THREAD

**Issue by cdyq** [open-horizon/anax#3582]
### Describe the bug.

Only partial unicode supported in constraint language, we need to support full range of unicode in constraint language``

- Error occurs when register node with "**constraint** "contains unicode(Modèle de déploiement最終グインを有効にするＡＢＣ一丁七ÇàâｳДфэअइउ€¥)

- Error occurs when addpolicy with "**constraint** "contains unicode(Modèle de déploiement最終グインを有効にするＡＢＣ一丁七ÇàâｳДфэअइउ€¥) hzn exchange deployment addpolicy

### Describe the steps to reproduce the behavior.

1. Prepare a node.json file with unicode(eg:Modèle de déploiement最終グインを有効にするＡＢＣ一丁七ÇàâｳДфэअइउ€¥) in "**properties**" and "**constraints**" section
2. Register node with prepared node.json file (hzn register --ha-group HA6 --policy node.json)

   

### Expected behavior.

The node can be registered successful

### Screenshots.

**Actual result**
Error occurs when register node with "**constraint** "contains unicode(Modèle de déploiement最終グインを有効にするＡＢＣ一丁七ÇàâｳДфэअइउ€¥)
Same issue occurs when addpolicy with "**constraint** "contains unicode(Modèle de déploiement最終グインを有効にするＡＢＣ一丁七ÇàâｳДфэअइउ€¥) hzn exchange deployment addpolicy
![image](https://user-images.githubusercontent.com/25783969/211772149-bdec8d3c-9145-4912-a078-6dc74ccee68c.png)
![node json](https://user-images.githubusercontent.com/25783969/211772252-d0d249f6-2a1a-4314-9fe7-7e6cefd800ac.png)

### Operating Environment

CLI:2.30.0-1093

**Comment by cdyq** [comment]
BTW:  Full range of unicode for "constraint is supported in web ui

**Comment by linggao** [comment]
Added the following support in PR #3627 :

- 30A0-30FF katakana (japanese)
- FF00-FFEF Halfwidth and Fullwidth Forms
- 20A0-20CF Currency Symbols

**Comment by linggao** [comment]
The following will not be supported from above test because they are either not from the 9 supported languages or are special characters.

- Дфэ -- Cyrillic
- بتث -- Arabic
- अइउ -- Devanagari
- ㈱ -- Enclosed CJK Letters and Months
- -―～～‖∥ -- Special characters.

**Comment by cdyq** [comment]
The following will not be supported because they are either not from the 9 supported languages or are special characters.(It is function limitation. The strings are used in the logic expression and be parsed in the code.)
![image](https://user-images.githubusercontent.com/25783969/217128307-f2e19ce3-2fbf-46e8-abf2-96c2a98c6f67.png)
constraints with following strings will be supported:
马铃薯權金鑰vollständigenorganizaciónspécifiéproprietà使用しないでください서비스에organizaçãoModèlededépdéploiement最終ログインを有効にするＡＢＣ一丁七Çàâｱｲｳ€¥鯵表噂ソ十豹竹敷～兎椄＊＠＇屜丯愛金イウエオカキ
