### ISSUE TITLE
Bug: intermittently not receiving proposal for privileged service

### ISSUE THREAD

**Issue by kmbarton423** [open-horizon/anax#3589]
### Describe the bug.

Developed automation to test privileged service usage  (qa-automation/privileged-service/).
At registration, the appropriate node properties are provided to bring up the privileged service.
Intermittently, the proposal is not sent after registration therefore the service never comes up.

### Describe the steps to reproduce the behavior.

Re-running the automation over and over will eventually surface this problem.

### Expected behavior.

Expect the privileged service to come up shortly after the node registers successfully.

### Operating Environment

edge device

**Comment by playground** [comment]
I'm running into a similar issue, not sure if it is related.  I have a few nodes for testing and I was able to update the policy for each node, and the new workload would get loaded throughout my testing.  I have not touched these nodes for a few days and they all have been running for days.   Today, I try to update the policy for each node, and in the eventlog list showed some nodes did not get the "Node Policy updated..." and other nodes showed "Node Policy updated..." and workload is getting destroyed but did load in the new workload even though "hzn dploycheck" shows there is a match.

```
eventlog list
...
  "2023-01-12 20:21:43:   Workload destroyed for chunk-saved-model-service",
  "2023-01-12 20:21:44:   Workload service containers for fyre/liquid-prep-express are up and running.",
  "2023-01-13 22:05:17:   Start node unregistration.",
  "2023-01-18 14:54:48:   Node policy updated with the Exchange copy: map[constraints:[] deployment:map[properties:[map[name:mms-agent value:MMS Agent] map[name:worker-safety value:Worker Safety]] constraints:<nil>] management:map[properties:<nil> constraints:<nil>] properties:[map[name:openhorizon.allowPrivileged value:true] map[name:openhorizon.hardwareId value:dc9ccbc106da3772687ecfaeeb430fc76774f28a] map[name:openhorizon.operatingSystem value:] map[name:openhorizon.containerized value:true] map[value:2 name:openhorizon.cpu] map[name:openhorizon.arch value:amd64] map[name:openhorizon.memory value:3,931]]]",
  "2023-01-18 14:54:58:   Start terminating agreement for liquid-prep-express. Termination reason: node policy changed",
  "2023-01-18 14:54:58:   Complete terminating agreement for liquid-prep-express. Termination reason: node policy changed",
  "2023-01-18 14:54:59:   Workload destroyed for liquid-prep-express"

root@container-test41:/oh# docker ps
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS              PORTS                      NAMES
900010086ac1        playbox21/mms-agent_amd64                 "npm start"              7 days ago          Up 22 hours                                    c21cf2c542f4760a3fc1207dabf75ca3d70ad6b8855e056ca04477e285ecedf2-mms-agent
fbbf873635c7        playbox21/auto-dock-express_amd64:1.0.2   "sh /oh/input.sh"        7 days ago          Up 22 hours                                    auto-dock
f10d620a88b5        openhorizon/amd64_anax:2.30.0-952         "/root/anax.service …"   7 days ago          Up 22 hours         127.0.0.1:8081->8510/tcp   horizon1
root@container-test41:/oh# hzn deploycheck all -b policy-chunk-saved-model-service_amd64 -n fyre-216-dock
{
  "compatible": true,
  "reason": {
    "fyre/chunk-saved-model-service_1.0.0_amd64": "Compatible"
  }
}

Note:  I do notice something in the log, there is an entry of "Start node unregistration." after the last workload got loaded.  But the node is still registered and still has other services running.

**Comment by playground** [comment]
Looking at the log closely, they all somehow have an entry of "Start node unregistration." a day later and put those nodes in the reconfiguring state but still show it has an agreement.

![image](https://user-images.githubusercontent.com/243495/213286603-6d5439ea-ba58-4bf0-b76b-231be973f839.png)

![image](https://user-images.githubusercontent.com/243495/213287206-1e7ff696-614c-4e85-86bd-0a8726cec294.png)

**Comment by linggao** [comment]
@playground What is the os for your node? Is it on your MacBook?

**Comment by playground** [comment]
@linggao the nodes are on Ubuntu.  I didn't have a node running on my M1 at that time, so not sure if M1 would have the same issue.

**Comment by kmbarton423** [comment]
Confirmed fix good
