### ISSUE TITLE
Bug: Make sure MMS and secrets work for anax-in-container after the host VM reboots

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#3595]
### Describe the bug.

Run anax-in-container in a linux box
Make sure MMS and secrets work
Reboot the VM 

Currently, the anax-in-container attempts to unregister when the anax-in-container gets killed by system from here
https://github.com/open-horizon/anax/blob/master/anax-in-container/script/anax.service#L16

To prevent the unregister, we should put the `hzn unregister` in the horizon-container script to be executed when the 
`stop` command is issued

Then, need to make sure all the MMS and secrets folders exist and are usable after the reboot.. Currently I am seeing that the 
/var/tmp/horizon/horizon1/ess-store folder doesn't exist so MMS doesn't work after the reboot. 

### Operating Environment

linux

**Comment by dlarson04** [comment]
MMS and secrets work successfully after the VM reboot if we can avoid `hzn register` as part of the shutdown process. My service had an error in it that prevented MMS from working after the reboot initially

**Comment by johnwalicki** [comment]
Closed by https://github.com/open-horizon/anax/pull/3599
