### ISSUE TITLE
Bug: message at registration should include ha group name

### ISSUE THREAD

**Issue by kmbarton423** [open-horizon/anax#3618]
### Describe the bug.

Received the following message when registering a node that is already a member of an ha group:
   Node kmb-org/kha3-1 is in HA group .

Looks like the ha group name is missing.

### Describe the steps to reproduce the behavior.

Register an edge device indicating membership in an ha group (--ha-group=<hagrpName>)
Unregister the node (-f only)
Register the node without specifying --ha-group parm

### Expected behavior.

the message should provide the name of the ha group of which the node is a member

Expected something like this:
   Node kmb-org/kha3-1 is in HA group 'kmbha'.

### Operating Environment

cloud

**Comment by johnwalicki** [comment]
#3623 fixed this issue and has been merged.
@kmbarton423 can you confirm?

**Comment by kmbarton423** [comment]
@johnwalicki  confirmed fix looks good
