### ISSUE TITLE
help for unregister -D suggests an unnecessary action

### ISSUE THREAD

**Issue by kmbarton423** [open-horizon/anax#3620]
Currently, when you do an 'hzn unregister -D', your eventlog is saved to /tmp/eventlogs_bkp_*
When you look at help for unregister ... 'hzn unregister -h', you are instructed to capture the eventlog manually.
Should the help be reworded to indicate that the eventlog is backed up automatically?

attached a snapshot of the text in question
![snapshot](https://user-images.githubusercontent.com/69682345/215848922-33052b5e-26d3-40f3-89d3-07d717b5b7e0.png)

**Comment by yasirACTUALY** [comment]
can you assign this to me @joewxboy

**Comment by yasirACTUALY** [comment]
i found the line of code for it

**Comment by yasirACTUALY** [comment]
This issue has been resolved but im unable to close it @joewxboy

**Comment by johnwalicki** [comment]
Closing issue.
