### ISSUE TITLE
Documentation: anax-in-container instructions

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/anax#3636]
### What is the current documentation state?

@dlarson04  reviewed the anax-in-container manual instructions at
https://github.com/open-horizon/anax/blob/master/docs/agent_container_manual_deploy.md

Some feedback:
He had to do the following to get the horizon1 container running. Add these steps
```
export fssBasePath=/root/doug/tmp/horizon
export fssHostSharePath=${fssBasePath}/${DOCKER_NAME}

# create fss domain socket path, ess auth path and secret path
mkdir -p ${fssHostSharePath}/fss-domain-socket
mkdir -p ${fssHostSharePath}/ess-auth
mkdir -p ${fssHostSharePath}/secrets
mkdir -p ${fssHostSharePath}/nmp
```
Add the following to the docker run command
```
-e HZN_VAR_RUN_BASE=${fssHostSharePath}
```
removed this from your docker run
```
-v $DOCKER_NAME_fss:/var/tmp/horizon/$DOCKER_NAME
```
Add added this
```
-v ${fssHostSharePath}:${fssHostSharePath}
```
Not exactly sure what it does, but the horizon-container script uses `-t` but you didn't have that...

And finally, you have
```
-v /var/run/docker.sock:/var/run/docker.sock 
```
But that might not work for podman unless they set up an alias from podman.sock to /var/run/docker.sock

**Comment by johnwalicki** [comment]
At the top of this page, we should add to the doc that the recommended way to run anax-in-container  is to tell them to install the CLI and then use the `horizon-container` script.   We need instructions for that.   `horizon-container` isn't documented anywhere.  (here would be a good place as any)

**Comment by joewxboy** [comment]
> At the top of this page, we should add to the doc that the recommended way to run anax-in-container is to tell them to install the CLI and then use the `horizon-container` script. We need instructions for that. `horizon-container` isn't documented anywhere. (here would be a good place as any)

Isn't that a complexity that should be abstracted from the user by the `agent-install.sh` script?  For example, using agent-install, the default behavior would be to install the environment-specific binary package, but also include the options of installing only the CLI or installing the Agent-in-Container?

**Comment by dlarson04** [comment]
yes agent-install does have an option to install the anax-in-container... that is a good point and we could list that as an option too.. I think one problem is that I am not sure how an openhorizon user knows how to bundle and push agent artifacts into CSS in order to use agent-install.. The IEAM produce produces the required artifacts and has instructions on how to get them into CSS... Not sure what an openhorizon user would do.

**Comment by joewxboy** [comment]
> I am not sure how an openhorizon user knows how to bundle and push agent artifacts into CSS in order to use agent-install.

I'd love to learn how to do that.  My all-in-one installation at home is missing the agent packages in CSS.  I wish there were a simple way to populate the CSS from one of these existing scripts.

**Comment by johnwalicki** [comment]
> yes agent-install does have an option to install the anax-in-container... that is a good point and we could list that as an option too..

I don't see that as an agent-install.sh option.   It looks like agent-install has a MacOS only feature when installing on a Mac.
