### ISSUE TITLE
Node Config via Sync Service

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#368]
- [x] Modify a sample service to use the sync service to get a whole config file, and sense and reread the config file when it is updated (troy)
- [x] Document for customers how to do the above (glen)

Troy,

Here's what i think the mms sample should include:
- create a small config file like:
  ```
  welcome="Hello, hope you are having a good day"
  intervalSeconds=5
  ```
- include that default config file in the docker image when it's built
- `service.sh` should loop displaying the `welcome` and sleeping for `intervalSeconds`
- `service.sh` should also check inside the loop if there is an updated config file via mms. If so, it should read in the variable values so they take affect in the loop (the welcome text changes and/or the interval gets shorter/longer). When the script finds a new version of the file, also echo that fact to stdout.
- in the readme have the user do:
  - start the service with no mms file (so it uses the builtin default)
  - view the service log with `-f`
  - modify the values in the default config file and push it to css
  - see that in the service log the output changes
  - modify the file once more and push the updated file to css
  - see the changes in the service log again

This shows the user not only a practical use of mms that is easy to show and comprehend. But i think it is pretty small mental leap for the user that the file could be anything, include an ML model. (In fact we should state this at the end of the readme.) And eventually, 1 of our samples that uses an ML model should also use mms.

**Comment by dcmartin** [comment]
What is a "config file" -- I don't recognize that term for the fabric; is this term referring to a service-dependent configuration specification?  For example, the `yolo` service has a configuration defined in its userinput.json file, indicating the YOLO model to use and then downloading that model from a "well-known location" (hardcoded into Dockerfile); to "change" that configuration would include both changing environment variables defined in the userinput.json file as well as re-starting the service with those new environment variables, i.e. restarting all the containers in the service with those new environment variable values -- OR changing the service to _not_ use environment variables to convey configuration information and rather use some other mechanism, e.g. another service that would provide those values dynamically.

**Comment by dabooz** [comment]
A config file is a generic term. It is whatever config your application code needs to operate correctly. In the ML world, a model (in file form) that an inference engine uses to analyze data would be considered a config file. For a metadata driven application, a config file is the metadata that instructs the application how to behave. The purpose of the sync service in the Fabric is more like the latter of what you described. Instead of hardwiring your horizon userinputs to a specific file store, etc you deploy the model to the sync service (i.e. upload it to the CSS) and then have your app use the ESS APIs to poll for and receive the model file. It can then get updates to the model file whenever a new version is pushed to the CSS without the need to restart the inference engine container. There is a very simple example of how a service running on a node would use the ESS APIs to retrieve a config file (model file) at runtime: https://github.com/open-horizon/anax/blob/master/test/docker/fs/hzn/service/usehello/start.sh starting at line 42.
I demoed this months ago, so there should be a recording of it somewhere and there is a technical design document describing how the sync service fits into the edge fabric: https://ibm.ent.box.com/notes/380161030823

**Comment by t-fine** [comment]
Error I got on my RPi:
```
horizon@RTP-RP000-00-01:~/examples/edge/services/mms $ hzn dev service start -v
[verbose] Reading configuration file: /etc/horizon/hzn.json
[verbose] Reading configuration file: /etc/default/horizon
[verbose] Config file does not exist: /home/horizon/.hzn/hzn.json.
[verbose] Reading configuration file: /home/horizon/examples/edge/services/mms/horizon/hzn.json
[verbose] Reading Horizon metadata from /home/horizon/examples/edge/services/mms/horizon
[verbose] Converted API Attributes: [] to persistent attributes: []
Service project /home/horizon/examples/edge/services/mms/horizon verified.
[verbose] Reading Horizon metadata from /home/horizon/examples/edge/services/mms/horizon
[verbose] Reading Horizon metadata from /home/horizon/examples/edge/services/mms/horizon
[verbose] Converted API Attributes: [] to persistent attributes: []
Service project /home/horizon/examples/edge/services/mms/horizon verified.
[verbose] Reading Horizon metadata from /home/horizon/examples/edge/services/mms/horizon
[verbose] Created network hzn-dev
Error: 'service start' unable to start file sync service, unable to start CSS, error unable to pull CSS container using image openhorizon/arm_edge-sync-service:openhorizon/amd64_edge-sync-service:latest, error unable to pull CSS container using image openhorizon/arm_edge-sync-service:openhorizon/amd64_edge-sync-service:latest, error API error (400): invalid tag format. Set environment variable HZN_DEV_FSS_IMAGE_TAG to use a different image tag.. Set environment variable HZN_DEV_FSS_IMAGE_TAG to use a different image tag.
```

**Comment by t-fine** [comment]
New `helloMMS` service:

https://github.com/open-horizon/examples/tree/master/edge/services/helloMMS
