### ISSUE TITLE
Promote Doug Larson to anax MAINTAINER

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/anax#3724]
Add Doug Larson @dlarson04  to the anax MAINTAINERS.md file
Doug will be the Open Horizon Agent WG Chair.
Doug has deep expertise with Open Horizon and has led the OH QA team for many years.

**Comment by joewxboy** [comment]
@johnwalicki ✅ 
@joewxboy ✅ 

Nathan and Troy, can we get your vote?
@naphelps 
@t-fine

**Comment by naphelps** [comment]
@joewxboy I vote Yes.

**Comment by joewxboy** [comment]
@dlarson04 Would you like to do the honors and submit a PR for this change?

**Comment by dlarson04** [comment]
resolved
