### ISSUE TITLE
Bug: Unable to install arm64 or ppc64le edge cluster agent w/ agent-install.sh

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#3740]
### Describe the bug.

Other k8s edge cluster agents are available for openhorizon so agent-install.sh provide a way to support arm64 and ppc64el platforms.

I do think we should make it easier for other platforms by changing
https://github.com/open-horizon/anax/blob/master/agent-install/agent-install.sh#L29

and also not hard coding amd64
https://github.com/open-horizon/anax/blob/master/agent-install/agent-install.sh#L72-L73

### Operating Environment

Linux

**Comment by joewxboy** [comment]
@LiilyZhang are you working on this?  If not, please assign me and I'll take a shot at it.

**Comment by LiilyZhang** [comment]
@joewxboy no, I am not working on this.t Jus assign this one to you
