### ISSUE TITLE
The agbot does not auto generate policy files until the horizon service is restarted after the exchange upgrade

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#376]
exchange v1.38, anax v2.9.0
Upgrade exchange from 1.36 to 1.38
All previous pattern associations are gone for the agbots. Patterns still exist though.
Run exchange api to add the associations. 
Check the policy directory and no policies found. 
Restart horizon service.
Check the policy directory and found the policy files for the associated patterns,

From now on, the agbot can auto generate/delete the policy files.

**Comment by dabooz** [comment]
PR https://github.com/open-horizon/anax/pull/383 fixes this issue
