### ISSUE TITLE
Put signature/authentication errors in agreement termination

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#384]
When an agreement fails because anax couldn't verify the signature of a deployment string or docker image, or because authentication to the image svr failed, those errors should be put in the agreement `terminated_description` field, so the node owner can see them w/o having to dig thru the anax log.

**Comment by linggao** [comment]
Currently the agreement terminated reason from the node side are
````
                CANCEL_TORRENT_FAILURE:      "torrent failed to download",
                CANCEL_CONTAINER_FAILURE:    "workload terminated",
                CANCEL_NOT_EXECUTED_TIMEOUT: "workload start timeout",
                CANCEL_USER_REQUESTED:       "user requested",
                CANCEL_AGBOT_REQUESTED:      "agbot requested",
                CANCEL_NO_REPLY_ACK:         "agreement protocol incomplete, no reply ack received",
                CANCEL_MICROSERVICE_FAILURE: "microservice failed",
````
* docker image load error is included in the `CANCEL_CONTAINER_FAILURE`.  If we want to report this as a separate error, we can add a new category like "CANCEL_IMAGE_LOAD: "docker image load failure" 
* The torrent signature verification and torrent download errors are included in the `CANCEL_TORRENT_FAILURE`.  The errors are found in a different deb package called horizon-pkg-fetch. We do not know the error type from the api call unless we parse the error message.
* The deployment signature verification error is not reported. It is deep in the policy.HasValidSignature() which is called by policy.Is_Self_Consistent() which is called by producer.HandleProposalMessage() which is called by agreement.go when handling the exchange message. The error got logged into the log and never got float up.

**Comment by linggao** [comment]
The terminated_description for an agreement does not have detailed error. It just shows the error type.

**Comment by bmpotter** [comment]
Ling, some comments:

1. I understand about the deployment signature failure. I guess there's not much that can be done there.
1. horizon-pkg-fetch is a library call (not a cmd, right?) so you or mike could change the function to return more details about which error. But maybe the easiest thing to do is put the error msg it returns into the termination description. Specifically, we need to be able to easily tell the difference between these 3 problems (because the fix the user has to make is different in each case):
    1. anax could not authenticate to the image svr (because the user/pw supplied is wrong)
    1. downloading the image files (package parts) failed for some reason (network errors, etc.)
    1. signature verification of an image file (by all keys) failed
1. The word "torrent" should be removed from any termination descriptions and log messages. We aren't using torrent any more, so it is misleading. Use generic terms like "image file downloads".
1. Yes, docker image load error should be separated from failure to start, because again the user fix is different.
1. Also, in the anax log, please change the wording when a signature verification does not succeed, but there are more keys to try. Every horizon newbie i know has been tripped up by this, because the msg looks like a real error, when it is really just that 1 key didn't work, but the other did, which is completely expected. The msg when there are still keys left to try should be something like "image file signature not verified successfully using key <key-filename>, trying the next key..."
1 In the future keep your eye out for this situation and fix it when you encounter it: you were helping someone debug a horizon problem and the anax log showed an error msg but it wasn't as specific as it could have been. Often error msgs don't include all of the relevant variable values that help in debugging the problem. Adding a couple more variable values to existing error msgs don't significantly increase the verbosity of the log, and don't effect the performance of anax (because errors happen very infrequently), but can aid a lot in resolving a problem more quickly/easily.
