### ISSUE TITLE
Update the download woker to allow download cluster agent image with architecture s390x

### ISSUE THREAD

**Issue by LiilyZhang** [open-horizon/anax#3845]
The cluster agent package downloaded during auto-upgrade process is currently hard-coded to `amd64_anax_k8s.tar.gz` in this https://github.com/open-horizon/anax/blob/master/download/download_worker.go#L35

Need to update to support cluster agent in different arch

**Comment by dlarson04** [comment]
Verified in 2.31.0-1450
