### ISSUE TITLE
Feature Request: Update container images to latest UBI baseimage

### ISSUE THREAD

**Issue by bencourliss** [open-horizon/anax#3852]
### Is your feature request related to a problem? Please describe.

We should update all container images to UBI 9.2 to pull in security fixes and other updates. 

### Describe the solution you'd like.

Currently we are using UBI 9.1. There is a newer version, 9.2 available for all architectures (amd64, arm64, ppc64le, s390x). The Dockerfiles should change to `FROM registry.access.redhat.com/ubi9/ubi-minimal:9.2`.

**Comment by johnwalicki** [comment]
I would be willing to work on this issue.   Earlier this year, I did the initial conversion to ubi9.1 images.  Happy to continue to help Open Horizon.

**Comment by johnwalicki** [comment]
While I'm editing the Dockerfiles, I'd also like to bump up to the latest Docker Engine.  See details at
https://docs.docker.com/engine/release-notes/24.0/
```
ARG DOCKER_VER=24.0.5
```

**Comment by johnwalicki** [comment]
Actually, DOCKER_VER is not needed in the Dockerfile_agbot.ubi so I have removed that line from Dockerfile_agbot.ubi
