### ISSUE TITLE
Bug: ppc64el Docker builds are failing

### ISSUE THREAD

**Issue by bencourliss** [open-horizon/anax#3870]
### Describe the bug.

Docker build is failing

ERROR: failed to solve: registry.access.redhat.com/ubi8/ubi-minimal:9.2: registry.access.redhat.com/ubi8/ubi-minimal:9.2: not found

Apparently wrong path to the UBI9 baseimage was used.

### Operating Environment

ppc64el

**Comment by johnwalicki** [comment]
Thanks

**Comment by bencourliss** [comment]
The following other Dockerfiles need to be fixed as well: 
* `ess/image/edge-sync-service-ppc64el/Dockerfile.ubi`
* `anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.ppc64el`
* `anax-in-k8s/Dockerfile.ubi.ppc64el`
