### ISSUE TITLE
Optimize anax to not re-download containers that haven't changed

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#394]

**Comment by michaeldye** [comment]
Provided for Horizon Pkgs in https://github.com/open-horizon/horizon-pkg-fetch/commit/007e5ee0fab74c2062aad9088397d7ce21349227 (integrated into Anax around the same time). Supported for Docker image pulls in https://github.com/open-horizon/anax/commit/c4ee2b7f48dcb198f56760118756366b69687934.
