### ISSUE TITLE
anax should give error if the workload or microservice are from different arch

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#403]
This happened when someone mistakenly set arch value to "armhf" instead of "arm" on the exchange for the workload and the microservice the pattern references to.
Then he reg_all which calls:
PUT /horizondevice call succeeded without error.
PUT /horizondevice/configstat call succeeded without error.
No errors in the log file.
The auto registration of the  /horizondevice/configstat ignored the workloads and microsrvices that are do not have the same arch. But did not give any indication that it escaped the workload and microservices.

**Comment by dabooz** [comment]
Was the pattern itself inconsistent in some way?

**Comment by dabooz** [comment]
We need to do some design work before we can know how to handle this.

**Comment by dabooz** [comment]
I did one part of this already, to return an error if configstate finds no microservices in the pattern. This was done in commit https://github.com/open-horizon/anax/pull/407/commits/477b1ac43fbcbc4e23981c4316c4a69f72db8c19

**Comment by linggao** [comment]
Tested. Currently anax ignores the workloads that are from different arch. It does not check the microservice arch. Will close this one and I have opened a new one (issue 471) for the second part.
