### ISSUE TITLE
Bug: Timed Out Problem with Edge Cluster Agent Installation

### ISSUE THREAD

**Issue by szeyan543** [open-horizon/anax#4105]
### Describe the bug.

During the edge cluster installation, the agent deployment process times out after creating the necessary resources. The installation sequence proceeds as expected up to the point where it waits for the agent deployment to complete, but it fails to do so within the allocated time frame. This results in a timeout error.
```
2024-07-09 11:31:23 cronjob auto-upgrade-cronjob created
2024-07-09 11:31:24 persistentvolumeclaim/openhorizon-agent-pvc created
2024-07-09 11:31:24 persistent volume claim created
2024-07-09 11:31:25 deployment.apps/agent created
2024-07-09 11:31:25 Waiting up to 300 seconds for the agent deployment to complete...
error: timed out waiting for the condition
```

### Operating Environment

Linux

**Comment by szeyan543** [comment]
@joewxboy

**Comment by dlarson04** [comment]
responded with the following in the LFEdge messaging app


hi
 The only time I have seen this is when something goes wrong with the persistentvolumeclaims. Please issue the following commands and paste the results

```
kubectl get storageclasses
```
and
```
kubectl get persistentvolumeclaims -A
```
and
```
kubectl -n <namespace_name> get deploy/agent -o=jsonpath='{$.spec.template.spec.containers[*].image}'; echo ""
```

**Comment by szeyan543** [comment]
Hello, here are the results from the commands:
1. `root@k:~# kubectl get storageclasses`
```
NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  14h
```
2. `root@k:~# kubectl get persistentvolumeclaims -A`
```
NAMESPACE           NAME                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
default             docker-registry-pvc     Bound    pvc-f1e564ad-ee0c-49a7-b688-184a06064550   10Gi       RWO            local-path     <unset>                 14h
openhorizon-agent   openhorizon-agent-pvc   Bound    pvc-dcd879b7-8d93-4025-982e-8f8582cf6eee   10Gi       RWO            local-path     <unset>                 5m31s
```
3. `root@k:~# kubectl -n openhorizon-agent get deploy/agent -o=jsonpath='{$.spec.template.spec.containers[*].image}'; echo ""`
`10.43.195.246:5000/openhorizon-agent/amd64_anax_k8s:latest`

**Comment by dlarson04** [comment]
We debugged this and there was mismatch between HTTP and HTTPS on the k3s cluster... Fixing the cluster resolved the problem.

**Comment by dlarson04** [comment]
If I remember correctly the problem was the daemon.json did not have the insecure registry

```
cat /etc/docker/daemon.json
{
   "insecure-registries": [ "10.43.224.218:5000" ]
}
```
