### ISSUE TITLE
Add anax docker image artifact to build

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#423]
From mike: dockerized anax is about at least three things:

1. mounting the docker socket inside the container
1. faking the iptables command in-container to use the host's network namespace (and maybe mounting that namespace into the container, I can't recall, and
1. running the container in privileged mode. There are probably repos called colonus in the gitlab instance that has some of the container content in it, as well as a repo for making old images, the ones that were based on hypriot

I don't think any anax changes are required , it was mostly about getting iptables and docker commands in-container to manipulate stuff outside of the container

This might be useful for our horizon developer experience, because they could run anax in a mac docker container to easily have their mac be an edge node to develop their workload on.

**Comment by dyejon** [comment]
Is there an unstated primary use case here- something besides what's mentioned about developing workloads?  If this is for use in non-development scenarios maybe it makes sense to piggyback on the deb packaging to build the container.  Whereas if it's specifically for running anax in a container during development of anax you'd want some stuff turned inside out I'm guessing to iterate over builds- /src mounted inside one build container and binaries and config that could be mounted in a runtime container.

^^ @bmpotter @dabooz @linggao 


Also if no one objects to using host namespace for the whole container for (2) that's a pretty easy way.

**Comment by bmpotter** [comment]
Good question. Dave's e2edev environment runs anax in a container in a specialized/hacked way. Carl is trying to unravel that to run it in travis CI. Since the need to have an anax container in travis is less iterative than in dev, let's focus on that 1st (along with the user-developed workloads case). Because, yes, the anax build should be able to produce a docker image as well as deb.

About (2), yes do it the easy way, unless there is some reason that doesn't meet our requirements.
