### ISSUE TITLE
Convert anax to services (from microservices and workloads)

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#444]
Feel free to break into multiple issues.

Dependent on exchange-api issue 51

**Comment by bmpotter** [comment]
Dave is done with the main functionality. Here are the loose ends that need to be completed:

1. finish hzn dev dependency fetch for services when dependency is in the exchange, not in a local project. should (hope to) finish that today. Also test hzn dev service publish and then submit PR. - Dave
2. visual inspect of internal exchange.GetService API call to make sure there are no fixes in GetMicroservice or Getworkload that havent made it into GetService - 1 hour - Dave
3. Update examples project(s) and dev qs guide for services - couple days, the timing of when this gets done is probably important - could be done by Bruce or Ling
4. Examine Anax source log entries looking for use of work microservice that can be changed to service. When the log entry could be talking about either, the log entry will change to use the word service - 1 day - Dave or Ling
5. Test and fix pure CS use case in anax and in e2edev (convert CS policies to services). These tests/config have not been run in a long time and might have been broken by services. Workload and MSes will no longer be supported in the CS use case, only services. - couple days - Dave or Ling
6. Test HA with services including agbot policy upgrade API - 1 day plus any time to fix something that might be broken - Dave (it would be a stretch for Ling)
7. Complete the automation of hzn dev services testing, includes develop, build, deploy and test of service based "workload" - couple days - Dave
8. Remove all internal reference to WorkloadResolver, GetWorkload etc APIs in favor of using exchange Handlers to enable more unit testing of anax base code. This will also remove extraneous "non-error" error messages related to microservices not being found when services are in use - couple days - Dave or Ling
9. Test that automatic service upgrade works and fix any bugs - 1 day - Dave or Ling
10. Additional hzn dev service validation that all elements in RequiredServices array of service definition are in the project's dependencies directory. Same for userinput services array. - 1 day - Dave or Ling

**Comment by dabooz** [comment]
1. Was shipped in PR 615
2. Verified good when PR 615 is integrated.
3. Deferred to a later time when WIOTP is able to move over.
4. working on it...
