### ISSUE TITLE
cli: help text and command output need to be fixed

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#467]
`hzn register --help`  need to fix the text for -e flag. 
"  -e, --email=EMAIL            Your email address. Only needs to be specified if: the node resource
                               does not yet exist in the Horizon exchange, and the user specified in
                               the -h flag does not exist, and you specified is the 'public' org. If
                               all of these things are true we will create the user and include this
                               value as the email attribute.
"
"-h" should be changed to "-u".

`hzn register ...`
"Horizon node is registered. Workload agreement negotiation should begin shortly. Run 'hzn show agreements' to view."
Please change `hzn show agreement` to `hzn agreement list`

**Comment by bmpotter** [comment]
PR: https://github.com/open-horizon/anax/pull/468
