### ISSUE TITLE
Support signing of docker images that are stored in a docker registry

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#481]
https://docs.google.com/document/d/1Prae01IcoUFKl39HS6WB_YPL5_o5nKAEi6lH-PgNB54/edit#heading=h.fm0ql35y9v6

**Comment by linggao** [comment]
This can be achieved by setting environmental variable `DOCKER_CONTENT_TRUST=1` when pushing the image to a repository. The `docker push` command will generate the root key (for the first time), repo key on client side and store them under `~/.docker/trust/private/...` directory. It will sign the image with the keys.
When consuming the image, the image can be pulled by anyone without any credential checking. However, if the consumer wants to protect himself from malicious images, he can set  `DOCKER_CONTENT_TRUST=1`. This way only signed images can be pulled down to the node.
