### ISSUE TITLE
Add signing keys to ms/wk/pat exchange definition

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#498]
Design: https://docs.google.com/document/d/1SN6eg6i-KXySvqVLPxrfu8miLd0_TVfsXnsUug4MBJA

Provide an option for the ms/wk author to put the public key/cert used to sign the ms/wk into the ms/wk exchange definition, so any node owner can run the workload w/o having to first manually add the key/cert to all of their nodes. This is analogous to a debian repo enabling you to download the key to the debian pkgs.

Anax should get the public key/cert directly from the exchange (not the agbot), so the exchange is the only entity that needs to be trusted (and it is already trusted).

This is needed even before we support signing of docker images, because the deployment string is already signed.

- [x] hzn key list should show useful fields of the x509 certs (because it is important to know them in the next bullet)
- [x] add signing keys or certs to ms/wk exch definition. (Did not do this next part, because i wasn't sure we wanted to be this prescriptive/restrictive: The x509 certs input to the exchange should be bounded by org (like other exchange activities). The exchange should reject import of certs if the subject org (Organization Name (O), ASN id 2.5.4.10) doesn't match the org for the user uploading the key)
- [x] `hzn exchange microservice|workload publish` should take an optional flag of the public key and add the key/cert to the definition
- [x] anax needs to get the key/cert from the exchange (not the agbot), if it's there
- [x] Anax config should have an option added, something like "TrustCertUpdatesFromOrg" (defaulted to true) that, if true, will permit Anax to fetch and trust certs from the Exchange for organizations already trusted regardless of the CN. If false, Anax will not import certs into its trust store automatically

**Comment by linggao** [comment]
Can the signing key attached to one pattern/workload/microservice be used for other workloads or should it be used just for that pattern/workload/microservice ?

**Comment by bmpotter** [comment]
In answer to your question above, the signing key from any pattern/workload/microservice should be loaded into anax's list of keys and then used to check the signature of anything.

**Comment by bmpotter** [comment]
I've finished the exchange and hzn parts of this, so i'm assigning it just to you ling for the anax part.
