### ISSUE TITLE
syslog and deamon log get too large on rpi

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#504]
On my rpi3 with horizon installed, the syslog and the daemon.log kept growing. We need to set up log rotation for arm.

**Comment by michaeldye** [comment]
Looks like the newest base pi image doesn't any longer have the group expected by the logrotate.conf: 

```
root@mon:~# /usr/sbin/logrotate -d /etc/logrotate.conf 
reading config file /etc/logrotate.conf
compress_prog is now /bin/gzip
compress_ext was changed to .gz
uncompress_prog is now /bin/gunzip
compress_ext is now .gz
compress_options is now  --fast
error: /etc/logrotate.conf:19 unknown group 'syslog'
removing last 0 log configs
```

This issue should probably be moved to https://github.com/open-horizon/raspbian-image , the fix consists in adjusting the file https://github.com/open-horizon/raspbian-image/blob/master/sd-image/seed/fs/etc/logrotate.conf .
