### ISSUE TITLE
Anax support arch synonyms config param

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#526]
Add to anax.json something like this:

```
"ArchSynonyms": {
  "x86_64": "amd64",
  "x86": "amd64",
  "armhf": "arm",
  "aarch64": "arm64"
}

When anax is filtering out workloads that don't match the current system's arch, it should consider these synonyms too.

Check with chris, glen, and egan for more possible synonyms.

**Comment by linggao** [comment]
A few design points:
0. ArchSynonyms is a map of string in the anax.json file. The key is the synonym and the value is the $GOARCH value of the nodes which we will call it canonical value.
1. In the exchange, the reference in pattern to workload and the workload to microservice should use the exactly arch value that is defined in the referenced object. We will not use ArchSynonyms to convert it.
2. For registering a pattern on the node:  when reading a pattern, change arch to $GOARCH of the node.  save the canonical arch of the pattern somewhere for later use.
3. The user input for calling `PUT /microservice/config` and `PUT /workload/congi` can use synonym.
4. The registered the services in the exchange will use canonical arch.
5. Output (policy files) on both node and the agbot will use the synonym. But the internal presentation will use the canonical arch value.
6. The ms ref (apispec) in the agreement proposal from agbot to node will contain the canonical. arch value.
