### ISSUE TITLE
POST to /microserviceconfig/config for duplicate  specRef doesnt return JSON error document

### ISSUE THREAD

**Issue by varatep** [open-horizon/anax#541]
I'd like the APIs associated with registration to give reasons for _why_ something failed instead of just throwing `400` or `500` errors. 

An example would be trying to POST to `/microservice/config` with the same `specRef` multiple times.

Some calls I can think of from the top of my head that are related to registration (some may already give descriptive errors):

- `POST` `/node`
- `POST` `/attribute`
- `POST` `/microservice/config`
- `POST` `/workload/config`
- `PUT` `/node/configstate`

This would result in being able to debug/troubleshoot issues more easily when developing applications that use the ANAX API.

**Comment by dabooz** [comment]
The issue is the absence of the error document for this duplicate case.
