### ISSUE TITLE
After reboot, 3 of the 4 WIoTP containers do not restart.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#556]
To reproduce:
- follow the first part of the quickstart guide to bring up a node to the point where there is an initial agreement and the 4 WIoTP containers are running
- power cycle the box
- wait 5-10 minutes and check, only the WL container will be running (the 3 MS containers are not restarted)

**Comment by bmpotter** [comment]
Dup of #551, so i copied the reproduce info there
