### ISSUE TITLE
agbot failed to initialize the agreementworker when a pattern is hosted by it but pattern itself is deleted

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#559]
agbot failed to initialize the agreementworker when a pattern is hosted by it but pattern itself is deleted. 

Got the following error, but agbot exited out of the initializing instead of ignoring this pattern which it should do. 
```
E0206 16:01:37.519137      54 rpc.go:1170] Exchange RPC Unable to demarshal response <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The page was not found</p></body></html> from invocation of GET at https://exchange-api.service.iot:9475/v1/orgs/oex8kt/patterns, error: invalid character '<' looking for beginning of value
E0206 16:01:37.521003      54 agreementbot.go:1068] AgreementBotWorker unable to process patterns, error unable to get patterns for org oex8kt, error Unable to demarshal response <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The page was not found</p></body></html> from invocation of GET at https://exchange-api.service.iot:9475/v1/orgs/oex8kt/patterns, error: invalid character '<' looking for beginning of value```

And GetPattern call should return nil instead of error in this case.

**Comment by linggao** [comment]
With exchange 1.46.0 and horizon 2.16.0 and later, this issue cannot be recreated. The reason is that the exchange returns the {} instead of "404 Not found" when an org does not have any patterns. 
````
curl -sLX GET  -H "Authorization:Basic testorg/user1:user1password" "${EXCHANGEURL}/orgs/testorg/patterns" |jq '.'
{
  "patterns": {},
  "lastIndex": 0
}

````

**Comment by dabooz** [comment]
There is code in exchange/rpc.go InvokeExchaneg(...) function that explicitly checks for a 404 response from exchange GET APIs and it does assume that a 404 will have a parse-able json body. I agree it seems odd that this would be the case. I am surprised to see it coded this way (and I am the author of that function). I have to wonder if this was patched in at some point and forgotten, or worse, there is some API that has to behave this way such that anax shouldnt treat 404 as an error. Just scares me. In any case, I would change InvokeExchange to behave differently, return an error on 404.

**Comment by bmpotter** [comment]
This might just be semantics, but 404 isn't always an "error", because in some situations it is ok if no resources exist. So i would be careful of changing the code to interpret it as an error across the board. My point wasn't that 404 should be an error. My point was that there is no need to parse the body on 404, because 404 specifically means there will be no meaningful content in the body.

**Comment by linggao** [comment]
PR https://github.com/open-horizon/anax/pull/568:  This PR detects the the 404 http code in InvokeExchange and return non error (nil) with the given resp structure untouched. 404 code is not treated as an error here, but rather treated as 0 elements in the response. I have checked the every caller of "GET" and it works this way. Another way of doing this is to let InvokeExchange return a special error and let the caller decide what to do with it. The later involves more work and the caller code gets more complicated. 
```
