### ISSUE TITLE
Add error string to DeviceContainersSyncedMessage

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#561]
When the container finishes the resource sync up, it sends a DeviceContainersSyncedMessage message to the agreement worker. The agreement worker exit out if the sync up fails. However the agreement worker does not have enough information to write to the log as the reason for exiting out. A string field will be added to DeviceContainersSyncedMessage to hold the error message if the resource sync up fails.

**Comment by dabooz** [comment]
If there are errors during container sync up, those errors are written out to the log by the container worker.
