### ISSUE TITLE
Support update of pattern when new agreement service requires new dependent service

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#569]
If the node watches the pattern and registers any new microservices, this should be handled, right?

Not sure if dave will automatically support this with the services work.

Many people ask me about this, and are very confused about when a pattern update with be automatically handled by horizon, and when they need to re-register.

Make sure this support also allows agreement-less services to be upgraded if/when the pattern changes. If the pattern doesnt change, ag-less services will never be upgraded.

Part of epic https://github.ibm.com/Edge-Fabric/project-summary/issues/35

**Comment by linggao** [comment]
What if new microservice needs user input?
If user adds new workload, will we also support it?

**Comment by bmpotter** [comment]
Will still won't support a pattern update that requires additional edge node owner input (whether it is from the workload or microservice).

Yes, if a user adds a new workload to the pattern (that doesn't need input), we should support that.

**Comment by dabooz** [comment]
I think this is supported, someone needs to test it to verify
