### ISSUE TITLE
agbot did not offer agreement proposal if the version of registered ms is not the highest

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#594]
Here is the real test case:
node was had gps 2.0.10 registered, and agreement A was made with agbot.
gps 2.0.11 was added to the exchange, but it had image error.
node upgraded the ms into 2.0.11, agreement A was canceled and agreement B was made with agbot.
node canceled agreement B due to image error.
node rolled back gps 2.0.10. 
no agreement was offered by the agbot any more unless we remove 2.0.11 from the exchange.

**Comment by linggao** [comment]
booz: from the version design doc: The workload definition in the exchange contains a specific version
The reference from workload to microservice is a version range.
so the agbot does have to allow lower level microservices to be used
when matching workload requirements to node advertisement
so then why would the workload resolver be written to return only the highest version of the mses
clearly it would need to return all the ms(es) so that the caller can figure out which versions it needs
but that function seems to have always returned the highest version range...even back to early Nov last year
clearly you tested this rollback function when you first put it in
so it must have worked at one time
linggao: yes.
booz: this appears to have always been the behavior as far back as when it was introduced

**Comment by dabooz** [comment]
After investigation, this issue is now irrelevant given the introduction of services and the move away from microservices and workloads as formal concepts in the metadata.

**Comment by linggao** [comment]
This is for 'scientific citizen' protocol that we no longer support. I will close this issue.
