### ISSUE TITLE
Add telemetry to agbot

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#619]
Improve the /status/workers API to also perform a simple select against the database to ensure that the database is still active. The SELECT will be to count the number of rows in the partition table.

Things like summary of number of agreements and edge nodes being served. Number of calls (and which ones) to exchange, etc.

For the operations team to better manage the agobts, and to have info to be able to optimize calls to the exchange.

Part of https://github.ibm.com/Edge-Fabric/project-summary/issues/39

**Comment by dabooz** [comment]
We did this in https://github.com/open-horizon/anax/issues/1380
