### ISSUE TITLE
Create persistence directory for services

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#621]
Anax already creates a directory like `/tmp/anaxRO/<agreement-id>` for every service container and has docker mount it in the container as `/workload_config`. As currently implemented, it is incomplete/useless, because it is mounted RO (so the service can't put data in it), and we don't give the pattern/service author or edge node owner any way to prime it with info.

The original purpose of this was to provide a way to give a service more config than could easily be put in the deployment field or the user input variables, and eventually we should enable that. But a more immediate need is to provide a way for a service to persist some info that will survive across container restarts (either container crash, or host reboot, **not** renegotiation of agreement). We will need this soon for the core-iot service, and it is a legitimate requirement for other services too.

So the existing code should be modified in a few simple ways:
- Mount it readwrite
- On the host name it `/tmp/anaxRW/<agreement-id>`
- Inside the container, name it `/service_config`
- Make sure it is deleted when the agreement ends

**Comment by linggao** [comment]
The current persistence dir base is defined in the config file as 
```
"WorkloadROStorage": "/var/tmp/horizon/workload_ro/",
```
The persistence dir for a workload is ` base dir + agreement id`
