### ISSUE TITLE
Add config value for not cleaning up unknown containers

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#627]
When anax starts (or restarts) it has code to clean up containers that it doesnt know about. That is, if it find containers for agreements that it does not have in its DB then it gets rid of those containers. This is useful function in the most common case in which horizon and its services are the only thing running on the edge node, but there are a couple cases (at least) in which this is not desirable:

- anax is running on a large svr in which there are many other things running besides horizon and its services
- more than 1 instance of anax is running in a container

In these case, we need a param in anax.json, `Edge.Coexist: true`, that disables the above behavior (and any other things we find where anax shouldn't assume it is the sole controller of the host). The default for `Edge.Coexist` should be false, which gives today's behavior.

Please think thru what the ramifications of `Edge.Coexist: true` are (cases in which things don't get cleaned up which should), so we understand the tradeoffs we are making.

**Comment by linggao** [comment]
Added `Edge.MultipleAnaxInstances`. When it is set, the container.go will not perform cleanup process when anax starts up.
