### ISSUE TITLE
Reset docker logdriver to default if syslog driver fails

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#628]
I've been investigating running anax in a container on mac. I've hit several problems that i've been able to work around, and i think it is now very close to working: anax starts, is able to talk to the docker api, and negotiate an agreement. But when it tries to start a service container (location in this case), i get the following error:

```
Failed to set up location. Attempting to remove other resources in agreement (2ef96fa0b647a85f84cc380f44ae8066a6fb975bae79cbcadfa977ae16c25199) before returning control to caller. Error: API error (500): {"message":"failed to initialize logging driver: Unix syslog delivery error"}
```

This is because normal syslog doesn't exist on mac. I'd like an anan.json config param called `Edge.DontConfigureSyslog`, which when true you don't try to set up the docker syslog driver (so i think the container output will just go to `docker logs`).

**Comment by linggao** [comment]
The implementation did not use the config. It tests for syslog error when starting the container. It reset the log driver config to default if the syslog driver fails.
