### ISSUE TITLE
Add option to anax to delete registry token after using it

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#638]
There is a concern by jeff that the registry tokens that are stored with a service and downloaded by anax to edge nodes, could be stolen off an edge node and then that thief could access the image. To mitigate this in the short term, add a config param called `Edge.EphemeralTokens`. When this is true, anax should get the token for a service like it normally does, but **not** put it in the db or file system, only keep it in a variable. And when it is done downloading the image, then overwrite the variable (to clear the value in memory).

When another agreement is made for that service later, anax should go thru the same process again.

**Comment by dabooz** [comment]
Turns out the only thing we needed to do was clean up 2 info log writes. Both were at level 5, so they dont even come out by default.
