### ISSUE TITLE
archived agreements not sorted by the time

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#64]
The archived agreements returned by /agreeement API are not sorted by the timestamp which makes it very hard to understand what's going on if there are a lot of failure.

**Comment by linggao** [comment]
This also causes the dashbord not showing the latest canceled the agreement for each service.

**Comment by michaeldye** [comment]
This not resolved in the API, but there is a temporary UI-only fix in https://github.com/open-horizon/anax-ui/pull/3 .

**Comment by linggao** [comment]
tested.
