### ISSUE TITLE
The dashboard for the registration gui does not report all the status.

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#66]
The dashboard gui shows the agreement status from "registered" to "in agreement" as soon as the agreement is created. It does not show other status like: negotiating, downloading, running workloads.

**Comment by bmpotter** [comment]
The states shown should be consistent with this list: https://repo.hovitos.engineering/MTN/mtn/wikis/horizon_v2_on_rpi#agreement-negotiation-states-of-the-device-rpi

**Comment by michaeldye** [comment]
Fixed in PR https://github.com/open-horizon/anax-ui/pull/3.
