### ISSUE TITLE
End up with multiple top-level services running

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#679]
I've seen this several times now: i start the anax container on my mac (see the new readme for that: https://github.com/open-horizon/anax/blob/master/anax-in-container/README.md#using-the-horizon-agent-container-on-mac ) and register for the cpu2msghub service. Everything starts fine and i only have 1 cpu2msghub container as expected. But if i leave it running and come back a day or 2 later there is a 2nd (or sometimes a 3rd) cpu2msghub container is also running. See my `docker ps` from a registration i've had running for 4 days:

```
Bruces-MacBook-Pro bash$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                    NAMES
209f0d9495db        openhorizon/amd64_cpu2msghub   "/bin/sh -c /service…"   11 minutes ago      Up 11 minutes                                85814554d79f4ca427c938c73c703566b05af1381f3cb6f36115f5f1ee612c01-cpu2msghub
f6afda55d937        openhorizon/amd64_cpu2msghub   "/bin/sh -c /service…"   2 hours ago         Up 2 hours                                   c64f1d4b9d297c27a247f9da399d920578196311e7a974720d58db56be726c9f-cpu2msghub
1eddb00478bf        openhorizon/amd64_cpu2msghub   "/bin/sh -c /service…"   2 days ago          Up 2 days                                    ac4b07011e558b1a11c9d77fb80c530a9f1ab221c4175fcfe5d2ddaeced39bc1-cpu2msghub
2555f2fae751        openhorizon/amd64_gps          "/bin/sh -c /gps"        4 days ago          Up 4 days           31779/tcp                github.com-open-horizon-examples-wiki-service-gps_2.0.5_00c3e2e7-7854-401d-9ca1-b6f1c862cde0-gps
5e0870b9e00e        openhorizon/amd64_cpu          "/bin/sh -c /start.sh"   4 days ago          Up 4 days                                    github.com-open-horizon-examples-wiki-service-cpu_1.2.2_29333716-d364-4df4-abc8-b823d8bafb39-cpu
8f355cf0fd34        openhorizon/amd64_anax         "/root/anax.service …"   4 days ago          Up 4 days           127.0.0.1:8081->80/tcp   amd64_anax
```

I don't know if this is specific to the mac, or running anax in a container, or the `MultipleAnaxInstances` config value, or the new ibm cloud environment. Please see if you can recreate it, and if so debug it. Thx!

**Comment by linggao** [comment]
Tried on SL vms, works for 5 days. No problems found. 
However, on mac, the problems occurs within 48 hours. Eventually the amd64_anax container has trouble communicating with other hosts. All the curl calls gets "connecton refused" error.  The mapped the port `127.0.0.1:8081` is also not working.  I tried to add log rotate to reduce the logs, it did not work.

**Comment by linggao** [comment]
Upgrade docker version on my macbook to the following and the horizon containers has been running for 2.5 days without problem.:
````docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
````
