### ISSUE TITLE
Re-define the support matrix (what debs we build) for Distro/arch

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#682]
- [x] build armv6 (carl)
- [x] test armv6 anax on rpi-0 (glen)
- [x] test armv6 anax on armv7 rpi (glen)
- [x] change anax deb build script to build armv6 instead of armv7 (carl)
- [x] build the gps service for armv6 and test (glen)
- [x] build the gps service (via the new 2-stage build process) for all arch's and publish in exchange (glen)

The Raspberry Pi machines mentioned in the issue title cannot run the ARMv7 debian packages we build and tag with "armhf" because they have the lowly ARMv6 architecture.  We could welcome a lot more Raspberry Pi machines, especially the tiny ZeroW machine, to Horizon if we build our debian packages also for ARMv6 and tag them, just "**arm**":

```
pi@horizoncam:~ $ cat h.go
package main
import "fmt"
import "runtime"
func main() {
    fmt.Printf("%v\n", runtime.GOARCH)
}
pi@horizoncam:~ $ go build h.go 
pi@horizoncam:~ $ ./h
arm
pi@horizoncam:~ $

```

**Comment by cgiroua** [comment]
Re-define (add/remove) our support matrix, at least adding the above.

Current matrix (pulled from horizon-deb-packager, this is defined -per branch- in the .travis.yml and pkgsrc arch definitions):
`$ for i in $(cat .travis.yml | grep dist=\' | awk -F "\'" '{print $2}'); do echo -e "\n$i:"; cat pkgsrc/deb/meta/dist/$i/arch; done`

ubuntu.yakkety:
amd64 armhf ppc64el arm64

ubuntu.xenial:
amd64 armhf ppc64el arm64

debian.stretch:
amd64 armhf

debian.sid:
armhf

raspbian.jessie:
armhf

raspbian.sid:
armhf
