### ISSUE TITLE
Use docker volumes for service persistence

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#687]
- [x] Instead of anax creating a dir under `/var/tmp/horizon/service_storage/` for each service and bind mounting that into the service container, it should use docker volumes: https://docs.docker.com/storage/volumes/ .
- [x] We should also consider adding an option for a volume that is tied to a service url instead of agreement id (so even if the agreement is renegotiated the service can maintain its persistence on the node). Or maybe just make sure we allow for it in the design.
- [x] Considering adding a deployment option so the service could request additional docker volumes, in addition to the default one that is created in the 1st bullet above. Or maybe just make sure we allow for it in the design.

Part of https://github.ibm.com/Edge-Fabric/project-summary/issues/8

**Comment by linggao** [comment]
#1 When Edge.ServiceStorage is empty or not specified, a docker volume will be created for a service by default when the service container starts. This volume will be mapped as `/service_config` within the container. This volume is not persistent and will be deleted when the container is destroyed.
#2 If there are persistent data for a service, it can be saved to an another volume. You can specify the volume in the service definition. For example: 
````
    "deployment": {
	"services": {
		"cpu2msghub": {
			"image": "openhorizon/amd64_cpu2msghub:1.2.5",
			"binds": ["mytest:/persist_data:rw"]
		}
	}
    },
````
where `mytest` is the volume name and `/persist_data` is what it is mapped to within the service container. The volume will be created if it does not exist when the container is brought. The volume will not be deleted when the container is destroyed. This satisfied the 2nd and 3rd requirement. 
#3 the above uses "HostConfig.Binds" feature (`-v`) for creating containers. It uses docker default volume driver. To explore more volume drivers in the future we need add new attributes `VolumeDriver` and `Mounts` in anax `containermessage.Service` structure to explore "HostConfig.Mounts" (`--mount`) in go-dockerclient package. In docker, `-v` and `--mount` are equivalent unless you want to specify more complicated driver options.
