### ISSUE TITLE
FR: gui show all the terminated agreements.

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#71]
This is a feature request. Please provide a button on the dashboard so that it will show all the terminated agreements and their reasons when clicked.

**Comment by bmpotter** [comment]
I'm adding the "priority" label, because this will save you and the rest of us a lot of time if the users can readily see why the previous agreements failed.

**Comment by michaeldye** [comment]
Assigned to varatep to include in new dashboard design

**Comment by varatep** [comment]
@bmpotter would like this to be completed in the current iteration, before the re-design. I am proposing a caret-styled hide/show for two lists of cards: `Active Agreements` and `Inactive Agreements`.

**Comment by bmpotter** [comment]
Consolidated into https://github.com/open-horizon/anax-ui/issues/41
