### ISSUE TITLE
Remove named volumes from the node when unregistering

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#711]
Currently any named volumes specified by the user in the deployment part of the service definition are not removed by anax or docker. Anax should remove them when the edge node unregisters. Read all the comments in this issue before fixing it.

**Comment by dcmartin** [comment]
Please do not remove directories that already existed; I use the bind technique to mount CUDA libraries into the container from the host.

**Comment by dabooz** [comment]
The only thing we can do here is to remove volumes that the user specified, but which did not exist before the container was started. Docker auto creates these volumes but it does not clean them up when the container stops. We would do this removal when an agreement is cancelled. All agreements are cancelled when a node is unregistered.

**Comment by dabooz** [comment]
So let's recap. What works today:
1) anonymous docker volumes (see above) are cleaned up when agreements are cancelled and when nodes are unregistered. This anonymous usage is consistent with how horizon wants services to run on edge devices.
2) named docker volumes are created by docker (if they don't already exist) and are left on the system when the using container ends. This is consistent with docker run behavior, but inconsistent with how we want services to run on edge devices. It is preferable if services don't use named docker volumes, OR horizon takes the responsibility to clean these up.
3) a pre-created named volume is left on the system when the using container ends. This is also consistent with docker behavior, and perhaps consistent with horizon behavior. If the services running on an actively managed edge device require a persistent named volume, and the device owner is able to access the device and manage the lifecycle of a named volume, then horizon should not be deleting this volume.

**Comment by dabooz** [comment]
Solution: To solve this issue we should do the following:
a) for volume binds, if the volume does not exist at the time the container is started, horizon will create the volume and label it as owned by horizon (similar to how networks and containers are labelled).
b) when a node is unregistered (in the regular non -D unregister path), remove all volumes with the openhorizon label.
