### ISSUE TITLE
Add service upgrading and downgrading to the e2edev test

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#715]
A top service can reference number of dependent services. The following is part of a service definition. The requiredServices defines the dependent services this service references to.
````
    "requiredServices": [
      {
        "url": "ibm.cpu",
        "org": "IBM",
        "versionRange": "1.2.5",
        "arch": "amd64"
      },
     ...
   ]
````
The versionRange here means version 1.2.5 and above. 
So if a service is running on a node, and there is a new version of the dependent service is created in the exchange, the node should delete the old dependent service and start the new version of it. This is called service upgrading. It only happens when the agreement is canceled and new agreement formed.
On the other hand, if the current running dependent service has problem  and there is an older version defined in the exchange, the node will bring up the older version instead.  This is called service downgrading. 
A new script should be added under anax/test/gov directory to test these scenarios.
See https://github.com/open-horizon/anax/blob/master/test/gov/verify_surfaced_error.sh as a reference.

**Comment by sirotsinskuy** [comment]
Working on it. @joewxboy please assign this issue to me
