### ISSUE TITLE
test `make test` should recognize agbot(anax) is dead earlier

### ISSUE THREAD

**Issue by cgiroua** [open-horizon/anax#752]
Noticed this when running tests for psql SSL config change, opening to track.

When verifying agreements (or before?) there should be a check to determine if the agbot is alive.

In my tests there was a failure when connecting to the back-end DB causing the agbot's anax process to die.  The tests eventually failed when verifying agreements timed out after finding no agreements for 5 minutes.

**Comment by LiilyZhang** [comment]
Already done. Closed.
