### ISSUE TITLE
Node does not get agreement after the org is given permission to access IBM pattern on the agbot

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#756]
Node registered
But the org-specific patterns to the agbot (which allow the agbot to serve IBM patterns to new orgs) is not added.
Add org-specific patterns to the agbot
No agreement formed on the node. 
Both customers are using the rpi.

**Comment by cgiroua** [comment]
The same scenario resulted in successful agreements forming on an amd64 device.

Also, unregistering/re-registering the arm node -after- the patterns were added enabled the node to form agreements.

**Comment by linggao** [comment]
I tried on both amd64 and arm nodes, both nodes got agreements after the pattern is added back to the agbot pattern list.
