### ISSUE TITLE
Correct the documentation of the specific_ports deployment field

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#769]
The documentation at https://github.com/open-horizon/anax/blob/master/doc/deployment_string.md needs to be updated:

- [x] for the `specific_ports` field, it doesn't show the option to specify 2 ports, e.g.: `HostPort":"5555:7777/tcp` where 5555 is the host port and 7777 is the container port
- [x] the term "microservice" should be removed, and most cases of "workload" should be changed to "service"
- [x] in the "Deployment String Format" section, the json is no longer under the `workloads` field, and it no longer needs to be escaped. Similar comment in the "Deployment String Examples" section
- [x] please review the rest of the page for things that are out of date

**Comment by bmpotter** [comment]
Reopening this to fix the documentation for this option.
