### ISSUE TITLE
Improve user account management in the registration UI

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#77]
1. When using an existing username, they shouldn't be asked to fill in the email field
2. Reset Password should take them to a page in which the reset token is emailed to the user and this page waits for them to enter the token and new pw. Or if they click on the link in the email, it should take them to this page with the token already filled in.
3. There should also be a simpler option to change their pw when they know the current pw.

**Comment by TheMosquito** [comment]
Perhaps you could begin with a separate page that asks them to login with their existing username and password, but also has a button to create a new account or reset their password.

For account creation, I'd like to suggest that you link to a remote page where the user would set up their Horizon Exchange account.

In the password reset email, it says, "To change your password, copy/paste the token below into the Horizon registration UI.".  I was unable to make this work by entering the token into the password box (I just guessed that this was what was wanted). Was I doing the right thing, or was the UI broken?  I think you should be more explicit about where and how to use this in the Horizon UI.  Or, perhaps it would be better to include a link in the email, and have that link take them to a page where they can change their password (I think the latter approach would be much better).  The reset token could also be included in that link, to make it simpler for the user.  Also, the current 5-minute lifetime is far too short.  Typically these tokens often have much longer lifetimes, like 24 hours, and I think an hour or more lifetime should be a minimum.

It seems simplest from a user interface perspective that the user will be taken to a remote page to create an account (separate window or tab in their browser, keeping the login page active for later return).  Similarly, I think it is simplest for the user if they will be sent a reset email that will contain a link to take them to a remote page to reset their password.  After creating a new account, or resetting their password, they can simply go back to their RPi, which will still be sitting on the login page, and enter their username and password to continue.

Then the second page will get them to register (or re-register) their device (with no confusion about their user account).

Also, I saw something on that registration page about not being able to register a device if it has previously been registered.  May I assume that if they attempt to re-register an existing device (e.g., as they might be doing after a reflash) that the UI will simply state that it has previously been registered and ask whether they want to re-register it?  Or is re-registration not required?  Or is re-registration simply not possible?  What if someone else used to own the devcie but now it is being transferred to a new owner?  These questions should be clarified for the user.

**Comment by dabooz** [comment]
There is no registration UI any more.
