### ISSUE TITLE
hzn dev dep fetch creates circular dependencies

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#772]
When one runs `hzn dev dependency fetch -d mydir` and does not specify a dependency, it seems that this command opens up files in the directory, and reads dependency info from there, and makes the service circularly depend upon itself (David Martin ran into this with his `yolo2msghub`, see the #edge-fabric-dev channel conversation Jan 29).
This command should *require* the user to specify a dependency, whether or not they provide the optional directory of *this* service with `-d mydir`. Further, it should not ever be able to create a circular dependency. For example, if `-d mydir` is specified then it should require either the `... -d mydir -p mydeppath ...` form of the specifying the *local* dependency or the `... -d mydir -o myorg -a myarch --url mydep...` for of specifying an already published dependency.

So 2 things to fix:
1. `-d` should never create a circular dependency, and
2. it should also always require either:
 - `-p` or
 - `-o`, `--url`, and `-a`
to specify the dependency to fetch.

**Comment by linggao** [comment]
After discussion with @dcmartin , he said he no long see hzn command exhibit this again. He asked me to close this issue.
