### ISSUE TITLE
Anax needs to be more precise about which container to start or stop.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#774]
- [ ] **See comment below. Waiting to see if dcm can recreate this in the latest version of anax (because ling thinks this was fixed in a recent feature)**

David Martin experienced an issue (and was able to reproduce it a second time for me too) where anax first started the wrong container, then later stopped the wrong container. Both containers were named `cpu`, but they were published from different organizations, and they contained different code.
More specifically, David had the `IBM/cpu2msghub` pattern example running on his node when he ran `hzn dev service start` for his `dcmartin@us.ibm.com/yolo2msghub` service, which depends upon his own `cpu` implementation. Here is the line from his `requiredServices` section of his `service.json` file for `yolo2msghub`:
```
{"url":"com.github.dcmartin.open-horizon.cpu","org":"dcmartin@us.ibm.com","version":"0.0.1","arch":"amd64"}
```
Instead of starting up this dependency, anax seems to have discovered the already running `cpu` container, and assumed *incorrectly* that they were the same.  It did not start David's `cpu` container. In this case it appears that anax confused these 2 different containers:
```
github.com.open-horizon.examples.cpu_1.2.2
com.github.dcmartin.open-horizon.cpu_0.0.1
```
That is one issue, but there is another that is closely related so I am including it in here too (perhaps it could be raised as a separate issue).
David was eventually able to get both instances up and running (I think just by running his `make start`, then `make stop`, then `make start` again -- and those make commands run the corresponding `hzn dev service start` and `hzn dev service stop` commands):
```
docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                    NAMES
a7b06fe649b0        openhorizon/amd64_cpu2msghub             "/bin/sh -c /service…"   28 seconds ago      Up 26 seconds                                de1577eb4e27d9e97db96a1351cf0bde05da5f4aa5e434658ad8575ce98cae1c-cpu2msghub
92a3ff93eef8        openhorizon/amd64_cpu                    "/bin/sh -c /start.sh"   30 seconds ago      Up 28 seconds                                github.com.open-horizon.examples.cpu_1.2.2_3a99115d-467b-451a-af51-e600017beecc-cpu
ab417b5359ae        dcmartin/amd64_yolo2msghub:0.0.1         "/usr/bin/run.sh"        46 seconds ago      Up 45 seconds       0.0.0.0:8587->8587/tcp   b6c4852230aa83209975e0412b95c72ad993bc436ca4ecc75fef51f02c00ec10-yolo2msghub
6007877297e3        dcmartin/amd64_yolo                      "/usr/bin/run.sh"        48 seconds ago      Up 46 seconds                                com.github.dcmartin.open-horizon.yolo_0.0.1_08855100-1891-47a0-a20e-141264748f8d-yolo
15475cca8ef5        dcmartin/amd64_wan                       "/usr/bin/run.sh"        49 seconds ago      Up 47 seconds                                com.github.dcmartin.open-horizon.wan_0.0.1_15d52fe9-2cf5-491a-8dec-286e09a15e7c-wan
c4333109e318        dcmartin/amd64_hal                       "/usr/bin/run.sh"        50 seconds ago      Up 49 seconds                                com.github.dcmartin.open-horizon.hal_0.0.1_b3c53a61-e12e-4529-84af-05be61b91cbd-hal
40abfb2f8645        dcmartin/amd64_cpu                       "/usr/bin/run.sh"        52 seconds ago      Up 50 seconds                                com.github.dcmartin.open-horizon.cpu_0.0.1_85a9e9e1-8f9f-4a48-a6df-eef31a04351c-cpu
3ee7b20fa59f        openhorizon/amd64_gps                    "/bin/sh -c /gps"        9 minutes ago       Up 9 minutes        31779/tcp                github.com.open-horizon.examples.gps_2.0.5_d6bf353b-fcea-450d-b175-c6144880705e-gps
3944f4354ab9        cb7b3237/amd64-addon-cpu2msghub          "/init /usr/bin/run.…"   10 minutes ago      Up 10 minutes                                addon_cb7b3237_cpu2msghub
37199bdb24df        homeassistant/amd64-addon-configurator   "/run.sh"                About an hour ago   Up About an hour    0.0.0.0:3218->3218/tcp   addon_core_configurator
a2f34577ddb0        homeassistant/qemux86-64-homeassistant   "/bin/entry.sh pytho…"   About an hour ago   Up About an hour                             homeassistant
647c8d7b704d        homeassistant/amd64-hassio-supervisor    "python3 -m hassio"      45 hours ago        Up About an hour                             hassio_supervisor
```
When both services were up, as shown above, and David then ran `hzn dev service stop`, the dependencies of `yolo2msghub` were mostly stopped, but the exception was his own version of `cpu` which was not stopped. Instead, the version of `cpu` being used by the `IBM/cpu2msghub` pattern was the version that was stopped instead! Here is the command output to show that happening:
```
export HZN_EXCHANGE_URL=https://alpha.edge-fabric.com/v1/ && hzn dev service stop -d test/
Stop service: service(s) yolo2msghub with instance id prefix 5584ecb1740ff24ed1cbbf379f38e7a4e61ec343a1ef22fbe4794df0426e1570
Stop service: service(s) cpu with instance id prefix github.com.open-horizon.examples.cpu_1.2.2_d9ff746d-fce9-4828-b9b2-83237e248bed
Stop service: service(s) hal with instance id prefix com.github.dcmartin.open-horizon.hal_0.0.1_dcde2198-6911-4764-843e-2972ab21389e
Stop service: service(s) wan with instance id prefix com.github.dcmartin.open-horizon.wan_0.0.1_bbff30f5-6710-471d-8fba-1049fda37b2d
Stop service: service(s) yolo with instance id prefix com.github.dcmartin.open-horizon.yolo_0.0.1_e4d7dfbb-ecc0-41be-9692-e0592bd080d8
Stopped service.
```
Notice this incorrect detail above:
```
Stop service: service(s) cpu with instance id prefix github.com.open-horizon.examples.cpu_1.2.2_d9ff746d-fce9-4828-b9b2-83237e248bed
```
(stopping the wrong `cpu` container, which is not a dependency of `yolo2msghub`). It should have stopped `com.github.dcmartin.open-horizon.cpu_0.0.1_85a9e9e1-8f9f-4a48-a6df-eef31a04351c-cpu` instead.

**Comment by linggao** [comment]
@dcmartin Could you retest it with horizon verision 2.21.0?

**Comment by bmpotter** [comment]
No response from david martin on the request for retest, so closing it.

**Comment by MaxMcAdam** [comment]
I could not replicate this error in 2.23.10
