### ISSUE TITLE
Agbot database fail-over

### ISSUE THREAD

**Issue by cgiroua** [open-horizon/anax#779]
Currently we have one target for the `Postgresql` agbot takeover, in our 'compose' back-end use-case we are given two HAproxy targets for fail-over which I believe is occasionally causing some DB query misses.

Can we investigate the possibility of adding a second(multiple) postgresql URL's?

Separately, could we also perhaps make the config a bit more simplified by supplying the URL's in one json key/value?

From:
>"Postgresql": {
  "Host": "hostname",
  "Port": "port",
  "User": "user",
  "Password": "password",
  "DBName": "dbname"
}

To something more like:
>"Postgresql": {
  "URLCSV": "postgres://user:password@hostname:port/dbname,postgres://user:password@hostname2:port2/dbname"
}

**Comment by bmpotter** [comment]
Taken care of with the new db with single url
