### ISSUE TITLE
Stop and Start for a service for non-pattern case

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#781]
- [x] Design: https://ibm.ent.box.com/notes/394046222463
- [x] add /service/configstate anax api to handle the case when the top level service is no registered.
- [x] agbot handle suspended service for agreement proposing process 
- [x] test hzn cli for service configstate change
- [x] e2edev test cases
- [x] documentation
Part of https://github.ibm.com/Edge-Fabric/project-summary/issues/13

**Comment by dabooz** [comment]
Fixed in issue #958
