### ISSUE TITLE
Allow setting the pattern for a node in the exchange

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#783]
To enable more (optional) centralized control, allow the user to set or change the pattern field in a node object in the exchange. Have either anax or the agbot recognize that change and automatically do an unregister (if necessary) and register of this new pattern.

This should work even if it is the 1st time the node is being registered. (It should only depend on the horizon agent being installed.)

Part of https://github.ibm.com/Edge-Fabric/project-summary/issues/35

- [x] 'hzn register' handle node pattern defined on the exchange (both hzn and anax api). (ling)
- [x] anax detect pattern changes after started with a pattern.  (ling, defer see issue #1202 )
- [x] exchange reject the pattern when the node is running under the policy mode. (bp)

**Comment by dabooz** [comment]
We can support first time setting of the pattern, but we will not support changing the pattern once it is set.

**Comment by linggao** [comment]
Here is a list of scenarios:
````
1. hzn register without pattern and policy specified
   A. No pattern is defined in the node on the exchange.
      Node will use the default node policy to run in the policy mode. (Working today)
   B. Pattern is defined in the node on the exchange
      Node will use the pattern. This is the new feature we should try to support. There should be a warning message in the register CLI that registration is using a pattern because that's what was defined in the exchange.

2. hzn register with pattern
   A. No pattern is defined in the node on the exchange.
      Node will use the given pattern. (Working today)
   B. A different pattern is defined in the node on the exchange
      An error should return on register CLI.

3. hzn register with policy
   A. No pattern is defined in the node on the exchange.
      Node will use the given policy. (Working today)
   B. A pattern is defined in the node on the exchange
      Use the pattern as 1B, but save the policy.

4. Node is running with a policy, then a pattern is added to the node on the exchange
   This is an error that the exchange will have to detect.

5. Node is running with pattern, then a different pattern is added to the node on the exchange
   Auto unregister the node (the node detects this case and acts as if unregister was driven from the CLI, basically it does a shutdown), anax restarts automatically and then when anax comes back up it should detect that it's in scenario 1.B. This should be deferred given the time available.
````

**Comment by bmpotter** [comment]
For the exchange work, ling says: when node publicKey is not empty and pattern is empty, reject any new pattern

**Comment by bmpotter** [comment]
The exchange part is fixed in https://github.com/open-horizon/exchange-api/pull/208

**Comment by MaxMcAdam** [comment]
Verified in 2.23.18 anax/ 1.106.0 exchange
