### ISSUE TITLE
Better error messages when a service is not specified in the node config.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#784]
This error message needs to be improved:
```{"error":"service config for <service> <version> is missing","input":"configstate.state"}```
It does not convey the information people need to debug the issue.
I believe I have seen it arise in two cases: (1) missing service container, and (2) bad `userinput.json`. Ideally there should be different messages for each of these cases or if just one message then list these possibilities so people can debug.
For case (2) it was completely missing the config for a particular service that requires input, as opposed to an incorrect variable for a correctly named service.
We agree on Feb 13 in the dev channel that 2 separate fixes are needed for this:
1. Change the REST API error message in a manner specific to the arguments it receives (that should say something about *required stuff being missing*, and *where exactly to add that missing stuff* in the config), and
2. Change the `hzn` CLI command error message which can talk specifically about a JSON input file, so something ike this:
```{"error":"Required configuration for service <service> <version> is missing. Please add a 'url' entry in the 'services' section of the JSON input file to fix this.", ... }```

**Comment by linggao** [comment]
Where did you see the error?  Form syslog or from the output of a command? If it is the latter, which command?

**Comment by TheMosquito** [comment]
It comes from the `hzn register` CLI command. I'm not sure which REST API it comes from, but I see this REST API activity when I run a successful `hzn register`:
