### ISSUE TITLE
hzn and the exchange should be consistent and forgiving wrt to org qualifiers for resources.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#788]
hzn and exchange should accept a prepended *org* for any resource identifiers, or accept the resource name *without* a qualifying org, when the context of the org is known.
Of course, if a non-root user attempts an operation on a user, node, agbot resource in an org other than their own org, the access control code should give a 403 back saying their credentials do not grant access to that that resource.

- [ ] Modify `hzn exchange` sub-cmds `user`, `node`, `agbot` to work like the `service` and `pattern` sub-cmds work, in that if an arg is specified to indicate the target resource, that resource can optionally be prepended with the org it is in.
  - E.g. today this works: if `HZN_ORG_ID` and `HZN_EXCHANGE_USER_AUTH` are set to the `foo` org and `bar:pw` user auth in foo, then this cmd works to view a public service in the `IBM` org: `hzn exchange service list IBM/github.com.open-horizon.examples.sdr2msghub_0.0.4_amd64`
  - Note that in the cmd above, the `IBM/` at the beginning of the service name does **not** cause hzn to override the org used for credential authentication (it still uses `HZN_ORG_ID` and authenticates in the `foo` org.)
  - To put it another way, the cmd above is just syntactic sugar for the equivalent cmd `hzn exchange service list -u "$HZN_ORG_ID/$HZN_EXCHANGE_USER_AUTH" -o IBM github.com.open-horizon.examples.sdr2msghub_0.0.4_amd64`
  - Today, `hzn` also supports the syntax `hzn exchange service list IBM/` and `hzn exchange service list IBM/\*` to list all of the services in the IBM org. We should support the same with `user`, `node`, `agbot`.
  - Note that when you implement all of this for the `user`, `node`, and `agbot` sub-cmds, they will always return the error msg 403 access denied, because only root is allowed to access those resources in another org. So it probably seems strange to bother doing this. The reason is that since we allow it for services and patterns, it is normal for the user to think that we allow that syntax for the other resources too. When they try it, we should give them an error msgs that accurately reflects the problem. (Which we don't do now.)
- [ ] Modify `hzn exchange pattern publish` to accept a pattern name in the `-p` flag that has optionally has the org prepended

**Comment by dabooz** [comment]
Fixed in #1242
