### ISSUE TITLE
Reg UI: back button after external link does not come back to correct page

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#79]
On the device setup page and the service selection pages, there are many links that links to other websites. Clicking the links and then click the back button on the browser, it brings to a page which says "Your device is not configured to execute any services." and there is a button "Begin Setup".  It does not bring back to the previous page.

**Comment by linggao** [comment]
On snap version 73/74, finished the first page and it went the the second page where it asked for lat and lon. Click on latlon.net external link on second page, it went to that site, then clicked the back button from the browser, it then brought to the dashboard which says "Your device is not configured to execute any services.". There is a button under it says "Begin Setup". Clicking the button will lead to the second page.

**Comment by linggao** [comment]
The fixed is built in 73/74. the new behavior is mentioned above.

**Comment by bmpotter** [comment]
Consolidated into https://github.com/open-horizon/anax-ui/issues/41
