### ISSUE TITLE
hzn CLI should do what it can to prevent version mismatches with the Exchange.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#794]
The `hzn` CLI should do something to validate that it is current before trying to interact with the Exchange (in order to prevent problems like the one we saw today where someone was using an Edge Node with a 2-year-old version of `hzn` with the current Exchange.

Can this use the same exchange version check that anax uses?

**Comment by linggao** [comment]
@TheMosquito Adding version check can only prevent the newer hzn  detects that the exchange is in lower version than it is expected. It does not detect older hzn running with newer exchange. Anax only has preferred version and minimum version for exchange. It does not have maximum version.

**Comment by TheMosquito** [comment]
@linggao I'm not saying that old versions of hzn CLI should somehow have this problem fixed in their old code. I am saying that **going forward** the hzn CLI should first check that it is version-compatible with the other components it talks to. This is a well-known problem with well known solutions (e.g., a reliable and unchanging REST API that hzn can call to check the versions of components it wants to talk with). If our version numbering scheme correctly uses the "semver" approach then it should be possible for either party in a communication to determine whether there is a version mismatch.

**Comment by sirotsinskuy** [comment]
Working on it. @joewxboy please assign this issue to me.
