### ISSUE TITLE
hzn dev cannot start on rpi3 because there is no mongo db image for this arch (arm)

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#814]
**Note: dave is going to open a requirement issue on the CSS dev team to support a built-in db option for CSS. Then this issue will be converted to taking advantage of that in `hzn dev service start` so we won't need mongo db in that case.**

When running `hzn dev service start` on a rpi, it gives the following error 
````
Error: 'service start' unable to start file sync service, unable to start mongo DB for CSS, error unable to pull Mongo container using image mongo:4.0.6, error no matching manifest for unknown in the manifest list entries. Set environment variable HZN_DEV_FSS_MONGO_IMAGE to use a different image.
````
mongo db supports amd64, arm65 windowx etc architecture. But it does not have image for arm.
https://hub.docker.com/_/mongo

**Comment by linggao** [comment]
Will add a flag in `hzn dev service start` command to disable starting of FSS containers.

**Comment by dabooz** [comment]
Local bolt DB was delivered with #877, which eliminates this problem. Closing
