### ISSUE TITLE
Add `hzn service log ...` to show service container logs in a consistent way

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#844]
(Independent of linux/mac, and w/o the need to reconfig rsyslog.)

Currently, on linux to see a container log you must do:
```
tail -f /var/log/syslog | grep <service-name>
```
On mac, you must do:
```
docker logs -f $(docker ps -q --filter name=<service-name>)
```

I would like users to be able to do this on every platform:
```
hzn service log -f <service-name>
```

I would be best if they didn't have to specify the agreement id as part of the service name.

As a related item, because this will simplify the testing of the helloworld service, i'd like you to add a `test` target to the Makefile that `hzn dev service new ...` generates. See https://github.com/open-horizon/examples/blob/master/edge/services/helloworld/Makefile

**Comment by jiportilla** [comment]
to do Linux first ,then the Mac

**Comment by njabbouribm** [comment]
Linux Portion complete, functionality is as follows:

hzn service log - will tail syslog
hzn service log xyz - will tail syslog only printing lines containing xyz (container name, etc...)

**Comment by njabbouribm** [comment]
New functionality:
<service-name> : required
-f : optional
hzn service log -f <service-name>: tail -F feature
hzn service log <service-name>: tail feature

**Comment by njabbouribm** [comment]
https://github.com/open-horizon/examples/pull/261
