### ISSUE TITLE
Still stuck in `unconfiguring` state after `apt purge` and reinstall.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#845]
David Martin unregistered a node; it got into `unconfiguring` state; then he did `apt purge -y bluehorizon horizon horizon-cli`, which should have removed all of the Horizon state, but apparently some remained because when he re-installed, with `apt install -y bluehorizon`, and ran `hzn node list` he saw the state was still `unconfiguring`; He then purged again and rebooted, then re-installed, and then it went to state `unconfigured`.

So some state is remaining after purge, and rebooting seems to clear that state.

**Comment by dabooz** [comment]
not recreate-able any more
