### ISSUE TITLE
The `hzn dev dependency fetch' command gives unclear error "unsupported project type" in many situations.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#851]
Instead this command should clearly state what is incorrect or what is missing when it detects a problem (so the user is able to debug the issue without having to call for support).

They should not have to pass `-f horizon/userinput.json` when they want to use the normal input file? I think it is good that the `-f` option exists, so they can pass a *different* file (e.g., `-f tempinput.json`). But it seems like the tool is checking for the existence of the normal file anyway, so could it just use it without them having to specify it on the CLI? I.e., the default behavior could be to use this file if it exists and if none is passed on the CLI.

Also please update the "--help" text to reflect this.

**Comment by bmpotter** [comment]
Glen, booz says a more specific msg is display when `-v` is used. Can you look at that?

**Comment by TheMosquito** [comment]
I think the goal of this issue was 

> so the user is able to debug the issue without having to call for support 

so having a useful error message hidden in the `-v` output does not address that. (I.e., they would still have to ask for help, and then we would ask them to use `-v`, so this nonspecific error message will still cost us support resources).

**Comment by njabbouribm** [comment]
For the above issue, would it be sufficient to prompt the user to use -v if there is an error. From the comments it seams sufficient, since it appears -v has the information the client needs.

**Comment by TheMosquito** [comment]
I think the original error message a user receives when something goes wrong should state what has gone wrong and give them the information they need to correct the problem. I am not sure that even the `-v` output has this (I did not get a chance to reproduce the error to find out). Did you reproduce the problem and can share the `-v` output? Anyway, I do not think you should ask the user to run a separate command to get the information they need. The original message should just give this information to them.
 
Glen.
----- Original message -----From: njabbouribm <notifications@github.com>To: open-horizon/anax <anax@noreply.github.com>Cc: Glen Darling <glendarling@us.ibm.com>, Assign <assign@noreply.github.com>Subject: [EXTERNAL] Re: [open-horizon/anax] The `hzn dev dependency fetch' command gives unclear error "unsupported project type" in many situations. (#851)Date: Tue, May 21, 2019 2:53 PM 
For the above issue, would it be sufficient to prompt the user to use -v if there is an error. From the comments it seams sufficient, since it appears -v has the information the client needs.

**Comment by bmpotter** [comment]
Glen, under normal circumstances i agree with you completely. But right now is not normal circumstances. There are much bigger problems we are dealing with - whole features that might not make it into june.

Nadim, i suggest you do the quick fix to add to the current msg that they should use the -v flag for details, and then move this issue to the Fall release so it can be fixed the proper way then.
