### ISSUE TITLE
`hzn unregister` should be safe to run anytime, and should result in a stable state.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#854]
Running running `hzn unregister` and/or `hzn register` in quick succession or twice can apparently result in the `unconfiguring` state, which currently requires a full software purge and reinstall to fix.
These commands should be safe in the sense that running them should never break Horizon, and more than that, when it completes it should ensure that the Horizon state is stable. That is, for example, if the Edge Node is stuck in the `configuring` or `unconfiguring` state, running `hzn unregister` should correct that problem and leave the Edge Node in `unconfigured` state.

**Comment by linggao** [comment]
We have not found out the problems yet. We need add more level 3 debug code so that we know what happens to the node. We cannot reliably recreate the problem so far.

**Comment by dabooz** [comment]
Many adjustments have been made, including hzn unregister waiting for everything to finish before given control back to the user.
