### ISSUE TITLE
If 'hzn register' fails, it should automatically unregister

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#860]
As far as i know, the only thing the user can do when the node is left in the `configuring` state is `hzn unregister`, so why not do it for them?

If issue #1298 is resolved such that hzn register only gives back control when the node is either in configured or unconfigured state, then this issue is a mute point, we can just close it.

**Comment by MaxMcAdam** [comment]
Added in PR #1552
https://github.com/open-horizon/anax/pull/1552
