### ISSUE TITLE
On MacOS, the `horizon-container stop` command needs to press onward after errors.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#862]
On MacOS, if someone does something heavy-handed in `docker` (e.g., stop and remove all running containers) then Horizon can get "wedged" in "unconfiguring" state. The remedy is to run `horizon-container stop`, but if the container is not running when you run this command, then it fails part way through, and the Docker *volume* (containing the broken Horizon state) does not get removed. This leaves the machine in a state that can only be corrected by manually removing the Docker volume. So the `horizon-container stop` command should make sure to keep going and complete all cleanup operations even when the container is not running or when the volume is not present.

**Comment by bmpotter** [comment]
I've have verified that this works as requested, so you can close it.
