### ISSUE TITLE
`hzn unregister` should clean up all Horizon-started container, and networks.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#863]
Horizon often leaves running (and/or stopped) containers and docker networks behind after failures. Running `hzn unregister` should clean up all of these.

**Comment by dabooz** [comment]
This was done when the -D option was introduced in this commit: https://github.com/open-horizon/anax/tree/407f564f9d4c4e6f6c6b6dec98f82c791e45da54
