### ISSUE TITLE
Document all of the fields in service, pattern, policy, userinput, and object json files

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#882]
This should probably be an `.md` file in the anax repo, and should be written from the perspective of an `hzn` user.
- [x] Policy overview
- [x] Service definition
- [x] Node Policy
- [x] Service Policy
- [ ] Pattern
- [x] Deployment Policy
- [x] MMS Object
- [ ] UserInput (register and node update)
- [x] Properties and Constraints
- [x] Built-in properties

**Comment by joewxboy** [comment]
Here's my guess at all of the topics that need to be covered:

1. Node Policy
2. Service Policy
3. Service Deployment Pattern
4. Deployment Policy
5. Model Policy
6. Object JSON
7. UserInput sections and file
8. Properties and Constraints
9. Built-in properties
