### ISSUE TITLE
hzn sub-cmd to display services in all IBM-type orgs

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#891]
This is to fulfill our goal of having CLI support for the service catalog in the spring release.

- [x] exchange api `GET /catalog/services` to display all public services in all orgs that have `orgType: IBM`. The response schema is the same as `GET /orgs/{orgid}/services`. (bruce)
- [x] exchange api `GET /catalog/patterns` to display all public patterns in all orgs that have `orgType: IBM`. The response schema is the same as `GET /orgs/{orgid}/patterns`. (bruce)
- [x] hzn sub-cmds on top of the above api's (anax team)

For the hzn sub-cmds, i suggest short, medium, and long output levels, and that the output be sorted:
- Short: `hzn exchange catalog servicelist -s`
```
[
  "IBM/cpu_1.2.3_amd64",
  "IBM/cpu_1.2.3_arm",
  "IBM/cpu_1.2.3_arm64",
  ...
]
```
- Medium (default): `hzn exchange catalog servicelist`
```
{
  "IBM/cpu_1.2.3_amd64": {
    "description": "Provides a REST API to query the CPU percent",
    "documentation": "https://github.com/open-horizon/examples/tree/master/edge/services/cpu_percent/README.md",
  }
  ...
}
```
- Long: `hzn exchange catalog servicelist -l`
```
{
  "IBM/cpu_1.2.3_amd64": {
    "owner": "IBM/troy.fine@ibm.com",
    "label": "cpu for amd64",
    "description": "Provides a REST API to query the CPU percent",
    "public": true,
    "documentation": "https://github.com/open-horizon/examples/tree/master/edge/services/cpu_percent/README.md",
    "url": "cpu",
    "version": "1.2.3",
    "arch": "amd64",
   ...
}
```

**Comment by dabooz** [comment]
So the catalog command has 2 sub commands, servicelist and patternlist? Each of those sub-commands has 3 display options (short, medium, long). Are there any more sub-commands or flags?

**Comment by bmpotter** [comment]
Correct, `... catalog servicelist` and `... catalog patternlist`. No other sub-cmds that i know of. This is a view-only situation, modification of the "catalog" is via the existing `hzn exchange service|pattern ...` cmds.

**Comment by MaxMcAdam** [comment]
Verified in 2.23.10
