### ISSUE TITLE
Add node policy API

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#893]
This is a new API. The input body has 2 sections, properties and constraints. Constraints are encoded as predicates in text form.
- [x] create the API structure and implement the supported HTTP verbs
  - defer implementation of PATCH verb to issue #904 
- [x] create the basic library APIs for converting constraints to and from json format
- [x] create a plugin for the constraint language processor, but the full processor is implemented in another issue (https://github.com/open-horizon/anax/issues/892)
- [x] store the node policy locally in the database in its original form
- [x] hzn cli for node policy on anax (in progress)
- [x] API tests in e2edev

**Comment by MaxMcAdam** [comment]
Verified in 2.23.10
