### ISSUE TITLE
Add Service Policy to hzn dev

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#900]
- [x] Add the optional service policy file with the same format that API input (not the internal JSON format)
- [x] Set default built in properties before publishing to the exchange

(bp) I assume the above means have `hzn dev service new` create a sample service policy? (Since [#856](https://github.com/open-horizon/anax/issues/856) was closed as a dup?)

depends on #892

**Comment by MaxMcAdam** [comment]
Verified in 2.23.10
