### ISSUE TITLE
Horizon should support RAMdisks for Docker containers

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#903]
Using a RAMdisk is a common Docker container development pattern. A RAMdisk is particularly useful on computers whose primary file system is Flash, like the Raspberry Pi computers, because for a service that reads/write a lot of local data it will be much faster and not wear out the flash drive as quickly. Standard Docker support for this feature  is described here: https://docs.docker.com/storage/tmpfs/

**Comment by njabbouribm** [comment]
Will create a new Issue to add support for Mount. Currently we only support Volumes, simple Mounts (no type designation), and Tmpfs. More information on Mounts: https://docs.docker.com/storage/bind-mounts/

**Comment by njabbouribm** [comment]
Implemented support for --tmpfs
