### ISSUE TITLE
The hzn CLI seg faults when an unexpected service is available on localhost port 80.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#906]
When the hzn CLI is installed on a host where anax is not installed, but where some other service is responding on port 80, the hzn CLI consumes it's REST response and seg faults. It needs to gracefully handle this situation instead of crashing.

(This issue used to be: https://github.ibm.com/Edge-Fabric/project-mgmt/issues/149)

**Comment by MaxMcAdam** [comment]
#920
