### ISSUE TITLE
Disallow mapping onto whichever host port anax uses.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#907]
In the deployment string, if a service attempts to map onto the host port anax uses (currently port 80) this should result in an error at service publication time, because it cannot work on a host running anax.
a) This could be checked at service publish time and a warning issued, but since the agent port is configurable, final determination of conflict cannot be made until attempting to run the service on a device with the agent.
b) Changing the default port is moved to issue: https://github.com/open-horizon/anax/issues/1327

Also, I think anax services **should be moved to some other port** (say, 8080). With this change, our customers could setup a typical port 80 web page service for Edge Node owners to use (e.g., for device configuration). That is, I think the choice of port for anax is flexible and could be easily changed to, say, 8080, whereas it is likely that device manufacturers would probably have a hard requirement for their web page to be mapped to that port. E.g., a fridge manufacturer providing a web page on the fridge for their fridge owners to use.
In any case, the host port number that anax uses should be disallowed for service port mapping in the deployment string.

(Moved here from: https://github.ibm.com/Edge-Fabric/project-mgmt/issues/150)

**Comment by MaxMcAdam** [comment]
Verified warning in 2.24.16

Warning: service 'time' defined under 'deployment.services' is mapping a port {0.0.0.0 8510:6414/tcp} to the default Horizon API port 8510. This service will fail when deployed on a node which has not changed the default Horizon API port.
