### ISSUE TITLE
node unregistration failed at 'unconfiguring' state

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#915]
If there is any problems with either the userinput.json or the service or patterns published then the node goes into "configuring" state; if I unregister then it goes into `unconfiguring` and then the node needs to be purged.

**Comment by bmpotter** [comment]
A user error like missing variables in userinput.json can't leave the system in a weird state. Can you do those checks up front, before starting the configuring process?

**Comment by dabooz** [comment]
Issue https://github.com/open-horizon/anax/issues/1081 addresses all the problems here.
