### ISSUE TITLE
Anax add arch to node entry and accept name on hzn register

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#916]
- [x] Add `arch` field (as an optional field) to node resource (sadiyah)
- [x] The EF management UI would like to include the architecture as one of the attributes it shows about the nodes. But the agent doesn't yet put that info in the node resource in the exchange. Add that. (lily)
- [x] When `hzn register` is run w/o specifying the node id, the agent will use a pseudo-random value (based on serial #, mac addr, or truly random string). In this case, it is more difficult for the user to identify the node resource in the exchange later on. Add a flag to `hzn register` that allows the user to set the node name at the same time to help in this case. (lily)

**Comment by LiilyZhang** [comment]
Some suggestions from Bruce and Ling:
1. for `cli/exchange/node.NodeCreate`, if arch is “”, then do not default, just leave it empty when calling the exchange to create the node.
2. for `hzn register` (`cli/register/register.DoIt`), if the node exists already and arch is not set, set the arch with the anax’s arch.  If the arch is set and it does not match the current anax’s arch, prompt the user and exit out.
