### ISSUE TITLE
Node status API return `lastUpdated` for `containerStatus` & change `created` to `UTC` timestamp

### ISSUE THREAD

**Issue by dcmartin** [open-horizon/anax#921]
The payload returned by the node status API call includes a `created` attribute for each `containerStatus` which appears to be expressed in seconds since the epoch; however, no timezone information is provided so this value cannot be interpreted; rather the value should be a timestamp in UTC format.

In addition, each `containerStatus` should include a `lastUpdated` value, iff the existing `lastUpdated` cannot be applied to all `containerStatus` entries.

**Comment by dabooz** [comment]
The seconds since epoch is ALWAYS UTC time, it is defined that way. The rest is also working as designed.
