### ISSUE TITLE
`hzn register` should use the same criteria to determine pattern validity that the agbots use.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#933]
Otherwise users end up in a situation where the Edge Node is successfully registered without any errors, but the AgBots will never propose to them because their validation of the pattern failed. At this point the Edge Node is effectively wedged and must be unregistered before it can continue. Possibly the AgBot could tell the agent that there is a problem in this situation, instead of leaving it hanging?
This issue showed up when the pattern being registered did not have a valid version for its only top level service.

**Comment by linggao** [comment]
This is no longer a bug any more. First, 'hzn pattern publish` has verification for services listed in the patter. The pattern cannot be created if the service version does not exist. Second, even if the service got deleted after the pattern is created, the `hzn registration` checks the existence of the services.  So I will close this issue.
