### ISSUE TITLE
Scary warning messages should be reserved for situations that are actually risky.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#934]
This warning message is emitted by the `hzn` command even when the thing being warned about is not relevant:
```
 # hzn register -p "mdye@us.ibm.com/pattern-myhello"
Horizon Exchange base URL: https://alpha.edge-fabric.com/v1
Node mdye@us.ibm.com/glendarling.demo0 exists in the exchange
Initializing the Horizon node...
Warning: no input file was specified. This is only valid if none of the services need variables set (including GPS coordinates).
Changing Horizon state to configured to register this node with Horizon...
Horizon node is registered. Workload agreement negotiation should begin shortly. Run 'hzn agreement list' to view.
 # 
```
The message is ominous and suggests a problem situation.  However, in this case, the registered pattern contained only one Service, and it defined no user input:
 ```
 # hzn exchange pattern list "mdye@us.ibm.com/pattern-myhello" | grep '"service'
    "services": [
        "serviceUrl": "myhello",
        "serviceOrgid": "mdye@us.ibm.com",
        "serviceArch": "amd64",
 # hzn exchange service list  "mdye@us.ibm.com/myhello_1.0.0_amd64" | grep userInput
    "userInput": [],
 #
``` 
Warning messages like this will worry the users, so I think we should only warn the user about situations that actually represent a risk.

**Comment by dabooz** [comment]
With the ability to specify user inputs in deployment policy and patterns, the need to set userinputs on the node at registration time is greatly reduced. It is even possible now to set userinputs on the node in the exchange. I'd like to remove the ability to specify userinputs at registration time, but that's probably going to far. For now, I think we can just remove that message.

**Comment by linggao** [comment]
Changed the word "Warning" to "Note",
