### ISSUE TITLE
Modify e2edev to be able to use existing exchange, agbots, agents

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#935]
- [x] Create initial design: https://ibm.ent.box.com/notes/462136494540 (Dave)
- [x] Make the exchange URL replaceable so that an external exchange can be used (in progress) Nadim
- [x] Make the agbot replaceable - Nadim
- [x] Make CSS replaceable - Nadim

**Comment by njabbouribm** [comment]
Working on agbot, running into some issues when utilizing remote environment vs local.

**Comment by njabbouribm** [comment]
Currently working with hard coded values. Working on last step to remove hard coded values.

**Comment by njabbouribm** [comment]
Running into errors with verifying the agreements.
