### ISSUE TITLE
Add node service status to the node status

### ISSUE THREAD

**Issue by varatep** [open-horizon/anax#942]
I want to be able to show the services that are running on a node as well as their status. I also want to be able to pause and resume a service on the node. Currently, this is done via a combination of the `/nodes/id/status` Exchange API call and cross-checking the status with the service in the `registeredServices` property of the node details.

I would like the service state to be added to the `/nodes/id/status` call so that I do not have to cross-check in multiple places for the service state.

Depends on https://github.com/open-horizon/exchange-api/issues/445 , which is now complete and ready for use in `openhorizon/amd64_exchange-api:2.58.0` .

Todo: Support `configState` in both places:  in `registeredServices` attribute of `/orgs/{org}/nodes/{id}` API  as it now, and  in `services` attribute of `/orgs/{org}/nodes/{id}/status` API.
- `hzn exchange liststatus <node>` should list the configState.
- Expend the `ServiceConfigStateChangeMessage` to include the services that have been resumed. Currently it only reports the suspended services. Then the governance.go that handles this message should make call to `ReportDeviceStatus` function in governance/status.go to set the new configState. Other update of the node status in `ReportDeviceStatus` should preserve the configState.

**Comment by sirotsinskuy** [comment]
Working on it. @joewxboy please assign this issue to me.

**Comment by sirotsinskuy** [comment]
@varatep @dabooz do we need the whole `registeredServices` section to be in the node status response? Or some parts of it? 
We also have the `runningServices` section already in node status, that should remain unchanged (at least for backward-compatibility)?

**Comment by dabooz** [comment]
@sirotsinskuy We only need the config state for each service, not the entire registeredServicess object. The runningServices section is actually owned and modified by the exchange, based on what agreements it sees related to the node. The agent doesnt modify this field, it only reads it.

**Comment by bmpotter** [comment]
Related [exchange-api issue 445](https://github.com/open-horizon/exchange-api/issues/445) is now ready for use in `openhorizon/amd64_exchange-api:2.58.0`

**Comment by dabooz** [comment]
@sirotsinskuy This issue is unblocked now, are you able to proceed with this issue now?

**Comment by sirotsinskuy** [comment]
@dabooz yes, PR for this one is ready https://github.com/open-horizon/anax/pull/2312
