### ISSUE TITLE
`hzn dev service new` adds spurious userInput variable, `HW_WHO`.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#966]
```
 $ mkdir nothello
 $ cd nothello/
 $ hzn dev service new -o mdye@us.ibm.com -s nothello -V 1.0.0 -i ibmosquito/nothello --noImageGen
Created horizon metadata files in /root/nothello/horizon. Edit these files to define and configure your new service.
 $ jq .userInput horizon/service.definition.json
[
  {
    "name": "HW_WHO",
    "label": "Who to say hello to",
    "type": "string",
    "defaultValue": "World"
  }
]
 $ 
```

Note that the `userInput` entry should only be omitted when the `--noImageGen` is specified. When `--noImageGen` is **not** specified, the `service.sh` that is generated refers to this variable.

**Comment by LiilyZhang** [comment]
Verified on icp-staging, horizon version `2.23.10`:
1. No HW_WHO when specify `--noImageGen`:
![Screen Shot 2019-06-25 at 11.03.00.png](https://images.zenhubusercontent.com/5cab63df6e5dd53fc8a26b5a/36574536-0aea-497f-abab-60566381d085)

2. HW_WHO generated inside `userInput` in `service.definition.json` when `--noImageGen` is not specified
![Screen Shot 2019-06-25 at 10.57.45.png](https://images.zenhubusercontent.com/5cab63df6e5dd53fc8a26b5a/3992ec1a-4e6c-4d43-a02b-5d1839b5f1ee)
![Screen Shot 2019-06-25 at 11.02.13.png](https://images.zenhubusercontent.com/5cab63df6e5dd53fc8a26b5a/f8a0008f-04c1-4dc2-bbc1-76956f18188a)
