### ISSUE TITLE
hzn gives incorrect error message when agent exchange URL does not match user environment exchange URL.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#970]
See related issue https://github.com/open-horizon/anax/issues/1002

On a node who's agent is configured to use one exchange URL, when a different exchange URL is in the user's environment incorrect and misleading error messages are given.

For example, when the agent was configured for the production exchange, and attempt to register on the staging exchange gives this incorrect error message:

 $ hzn register -n $EXCHANGE_NODEAUTH $HZN_ORG_ID "IBM/pattern-ibm.cpu2msghub-arm" -f input.json
Reading input file input.json...
Horizon Exchange base URL: https://stg.edge-fabric.com/v1
Node mdye@us.ibm.com/glendarling.RPiZeroW does not exist in the exchange with the specified token, creating/updating it...
Initializing the Horizon node...
Error: bad HTTP code 400 from POST http://localhost/node: {"error":"pattern IBM/pattern-ibm.cpu2msghub-arm not found in exchange.","input":"device.pattern"}
 $ hzn exchange pattern list  "IBM/*"
[
  "IBM/cpu2msghub",
  "IBM/pattern-ibm.helloworld-amd64",
  "IBM/pattern-ibm.helloworld",
  "IBM/sdr2msghub",
  "IBM/pattern-ibm.cpu2msghub-arm",
  "IBM/pattern-ibm.cpu2msghub"
]
 $ hzn exchange pattern list "IBM/pattern-ibm.cpu2msghub-arm"
{
  "IBM/pattern-ibm.cpu2msghub-arm": {
    "owner": "IBM/troy.fine@ibm.com",
    "label": "Edge ibm.cpu2msghub Service Pattern for arm",
    "description": "Pattern for ibm.cpu2msghub sending cpu and gps info to the IBM Message Hub for arm",
    "public": true,
    "services": [
      {
        "serviceUrl": "ibm.cpu2msghub",
        "serviceOrgid": "IBM",
        "serviceArch": "arm",
        "serviceVersions": [
          {
            "version": "1.3.1",
            "priority": {},
            "upgradePolicy": {}
          }
        ],
        "dataVerification": {
          "metering": {}
        },
        "nodeHealth": {
          "missing_heartbeat_interval": 600,
          "check_agreement_status": 120
        }
      }
    ],
    "agreementProtocols": [
      {
        "name": "Basic"
      }
    ],
    "lastUpdated": "2019-05-30T21:31:28.809Z[UTC]"
  }
}
 $ 

That is, even though the command output says it is using the staging exchange URL, it says the pattern does not exist. However, the pattern does exist in the staging exchange so this is very confusing for users.

The hzn command should either display the exchange URL actually being used (in this case the production exchange) or better than that would be to report an error if the user environment specifies a different exchange from the one that will actually be used.

**Comment by MaxMcAdam** [comment]
This function is now issuing erroneous error messages anytime `hzn register` is run. Moving back to in progress.

**Comment by bmpotter** [comment]
Since `hzn register ...` does some of the work in the cli (e.g. creates the basic node object), and then other work in the agent, i think that command specifically should compare the exchange url that the cli and agent are using, and if they aren't the same give an error msg that explains which files it got each of them from and that for `hzn register` they must be the same.
