### ISSUE TITLE
Improve unclear error message when userinput.json references a service that is not in the registered pattern.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#971]
See the dev channel discussion below

**mosquito**   Also, @linggao I think this registration error message (including the line before it):

```
Setting service variables...
Error: {"error":"Unable to find the service definition using  IBM/github.com.open-horizon.examples.cpu2msghub [0.0.0,INFINITY) arm in the exchange.","input":"service"}
```

Is also not very helpful to users. In this case, the pattern does not refer that service at all.
Instead, it is the `userinput.json` file that references the bad Service url, not the pattern. The only hint of this is the line before that says “Setting service variables…“.  Could the error message instead state that the `userinput.json` file references a Service url that is not included in this pattern?

**linggao**   ok, thanks.

**Comment by jiportilla** [comment]
I tested this issue  and the error message was more helpful about the true issue

hzn exchange pattern publish --json-file=horizon/userinput.json
Creating userinput in the exchange...
Error: bad HTTP code 400 from POST https://major-peacock-icp-cluster.icp:8443/ec-exchange/v1/orgs/IBM/patterns/userinput: invalid-input, no versions specified for service '', '', ''

**Comment by jiportilla** [comment]
and --- Error: bad HTTP code 400 from POST https://major-peacock-icp-cluster.icp:8443/ec-exchange/v1/orgs/IBM/patterns/pattern-test.ivanp.helloworld-amd64: invalid-input, pattern 'IBM/pattern-test.ivanp.helloworld-amd64' not created: the following referenced service does not exist in the exchange: org=IBM, url=test.ivanp.helloworld, version=1.0.0, arch=amd64

**Comment by dabooz** [comment]
@TheMosquito We are having trouble recreating this problem, so we are unclear what to fix. Can you clarify the problem (or problems) further? Unfortunately it seems that time has eroded our context on this issue.

**Comment by TheMosquito** [comment]
It looks like you are trying to *hzn exchange pattern publish ...* this pattern with a bad userinput.json, but this error occurs when you *hzn register ...* an edge node w a bad userinput.json. So you need to register a valid pattern (e.g., one of the public ones) but have your registration userinput,.json file refer to a service *not included in that pattern*. Then I think you will see this message.

**Comment by MaxMcAdam** [comment]
@TheMosquito using **hzn register -p <pattern> -f <user input file>**, I didn't get the error unless the user input file specified a service that does not exist in the exchange.

**Comment by TheMosquito** [comment]
@MaxMcAdam Yes, I think that is the scenario. The error message should give the user a clue about where their error is located (in the userinput.json file). The user in this case spent a lot of time following through pattern, service, required service, etc, and verified all of that was correct then called for help. I created this issue because I think the error message should clearly tell the user that their error is in the userinput.json (I think this will help save support costs in future).
