### ISSUE TITLE
Getting cpu and memory info from syscall does not compile on Mac

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#977]
For the node built-in properties, it seems that go does not provide a way to get the cpu and memory info for Mac. For CPU, the `runtime.NumCPU()` provides the number of cpu for the current process (anax).  For the memory, I use `syscall.Sysinfo()`, but just found out that the syscall package is deprecated and it does not even compile on Mac.

**Comment by MaxMcAdam** [comment]
Verified in 2.23.8
