### ISSUE TITLE
Constraint expression should allow quoted string value even when it has no whitespace.

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#979]
hzn exchange business addpolicy returned error "is not supported" when working with a policy containing a constraint expression with property == "true". I managed to get the policy to be accepted when  I changed the expression to include whitespace in the quoted string, e.g. "true ". Quoting should be supported even when there is no whitespace in the value.

**Comment by MaxMcAdam** [comment]
Confirmed in version 2.23.10
