### ISSUE TITLE
Provide node policy author a way to get a skeletal node policy so they know what the schema is

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#980]
Add `hzn policy new` and `hzn exchange service newpolicy` command that returns a json object with all possible fields, but with empty values. See `hzn mms object new` for an example. The output of the new command should look something like this:
```
{
  "properties": [
    {
      "name": "",
      "value": nil
    }
  ],
  "constraints": [
    ""
  ]
}
```

While you are working on this one, we have the same problem with the business policy. We need `hzn exchange business new`, where the output looks like this:
```
{
  "label": "",
  "description": "",
  "service": {
    "name": "",
    "org": "put the $HZN_ORG_ID env var value in here",
    "arch": "",
    "serviceVersions": [
      { 
        "version": "",
        "priority":{}
      }
    ]
  },
  "properties": [
      {
          "name": "",
          "value": nil
      }
  ],
  "constraints": [
    ""
  ]
}
```

**Comment by MaxMcAdam** [comment]
confirmed in version 2.23.10
