### ISSUE TITLE
Short list for hzn exchange business listpolicy

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#981]
Look at the output for hzn exchange service list, by default it only shows the ids of each service returned. There is a flag to get the full service definition. The hzn exchange business listpolicy command should work the same way.

**Comment by LiilyZhang** [comment]
Verified on icp-staging, hzn version `2.23.10`:
`hzn exchange business listpolicy` only list org/business policy name
![Screen Shot 2019-06-25 at 12.06.15.png](https://images.zenhubusercontent.com/5cab63df6e5dd53fc8a26b5a/07f38fe6-fa14-48ff-8799-cd71fcf1ea72)
