### ISSUE TITLE
'-l' / '--long' flag not working for hzn exchange pattern list

### ISSUE THREAD

**Issue by RobHigh** [open-horizon/anax#986]
<img width="509" alt="Screen Shot 2019-06-06 at 8 46 15 AM" src="https://user-images.githubusercontent.com/26487355/59033817-97086780-8837-11e9-9408-0f06a7369189.png">

**Comment by LiilyZhang** [comment]
Verified on icp-staging, hzn version `2.23.10`, both `-l` and `--long` flag work
