### ISSUE TITLE
Path permissions misaligned

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/anax#989]
The `/tmp/hzndev/auth` directory is used to create directories for tracking agreements.  If the folder was created by root, then subsequently running `hzn dev service start -S` as another user will result in an error as the new folder cannot be created.  This was noticed on a Raspberry Pi running Raspbian OS and using Horizon CLI and Agent version 2.23.1

The solution to this problem is to ensure that /tmp/hzndev/auth (and possibly others) are removed by hzn dev service stop.

**Comment by sirotsinskuy** [comment]
@joewxboy Working on it
