### ISSUE TITLE
Pattern `userinput` variable value has `regexp` restriction

### ISSUE THREAD

**Issue by dcmartin** [open-horizon/anax#990]
BUG:
Providing a variable's value in a `userinput.json` file with certain characters will generate an error based on a Go regular expression check on the string; IDK which aspect of the regular expression is being matched.

REPLICATE:
Provide a BASE64 encoded string as a variable value, e.g. an SSH private key file.

**Comment by bmpotter** [comment]
David,

Please provide the specific string that is failing for you, so we can easily recreate the problem.

**Comment by MaxMcAdam** [comment]
Verified in 2.23.10
